### ISSUE TITLE
Feat: Новые антаги: Сверх-гештальт дион.

### ISSUE THREAD

**Issue by PhantornRU** [ss220-space/Paradise#100]
### Проблема

Гештальты дион по лору могут достигать размеры целых станций. Почему бы не добавить возможность получить антагов дион? Случайные игроки выбираются на роль дион и им соответственно выдаются дионы со случайными именами при раундстарте (или щитспавне), у них у всех единая цель - вырастить главный гештальт, увеличить свою численность, как у революционеров (диона может предложить дионе или нимфе присоединиться к гештальту) и создать сверх-гештальт поглотивший станцию словно культисты, также позволяя удаленно общаться друг с другом.

### Решение

Принцип режима игры за сверх-гештальт дион схож с культистами и блобом. Один из дион становится сверх-гештальтом (добровольно, но только 1 после чего эта способность пропадает у других дион, либо же дать им возможность становиться и другими статичными гештальтами, но тогда они должны убедиться что кто-то будет для них носить пищу и питать их). 

### Игра за антагов

![image](https://user-images.githubusercontent.com/41479614/125016029-fdfe4780-e0b3-11eb-8b01-83fe00434a9b.png)

**Сверх-гештальт**

Режим: Стратегия.

Игрок-гештальт становится как блоб и может перемещаться по подпольным корням и создавать новые структуры, а также пускать дальше подпольные корни, действуя более скрытно, если её так и не найдут, ведь подпольные корни можно обнаружить только открутив плитку от пола.
Этот же гештальт может свободно застраивать свое логово и делать все условия для жизни дион. Свет, древо охоты, древо жизни, вспомогательные стены, запускать корни по всей станции чтобы дионы стоя на плите с такими корнями могли обходиться без воздуха и даже ускоренно регенерировать и/или быстрее передвигаться(?).
Для того чтобы поедать биомассу, достаточно игроку-гештальту кликать по еде или полностью умершему трупу, после чего пища будет поглощаться в течении определенного количества времени, если её не потревожат. В чат же начинает писать что-то наподобии: 
_"Корни впиваются в *ОБЪЕКТ_НЕЙМ* и начинают поглощать/высасывать его"_
Мясо и растения всасываются без следа если их вовремя не убрать, если корни всосут труп, то после него остается только скелет как после позднего разложения или останки. При этом труп должен быть органический, КПБ/Плазмамены для таких целей не подходят.

**Дионы-кормильцы**

Режим: MOBA :)

Те игроки, которые не стали гештальтом или хотят в более позднем этапе присоединиться к гештальту, должны соответственно всячески способствовать разрастанию гештальта и таскать для него разнообразную пищу по возможности. Если они не смогут таскать для гештальта пищу, то гештальт не сможет разрастаться и пускать свои подпольные корни для увеличения сферы влияния и придется либо находить новых дион через ботаников, либо признать свое поражение, если у гештальта недостаточно биомассы для самостоятельного передвижения и жизни.
Выращенные нимфы (с названием аля Гештальт-Нимфа чтобы не путать) через древо жизни - автоматически становятся антагами и соответственно как и обычным дионам им нужно пить кровь и есть растительную пищу чтобы вырасти, после чего те присоединяются к основным целям.
Выращеные нимфы в ботаническом саду и другим дионам - дионы-гештальты могут предложить присоединиться к общей сети общения и антажеству как при предложении революции.
Дионы видят разрастающиеся под полами корни и знают их месторасположение.

**Рост гештальта проходит так:**

Дионы кормят гештальт биомассой.
- Растения дают малое количество биоматериала, но за счет постоянного выращивания овощей через ботаников, это компенсируется.
- Мясо дает усредненное количество биоматериала
- Труп разумного существа дает большое количество биоматериала
Для питания гештальта достаточно положить то что нужно принести в жертву на клетку с полом, под которым имеются корни, после чего данная вещь/труп поглощается гештальтом и ему передается биомасса.

**Стратегия:**

На выбор, одна из изначальных дион может стать статичным гештальтом и оставаться на месте, наблюдая за всей станцией и пуская незримые корни под полом (чем дальше корни, тем дальше видит такой главный гештальт), которые выглядят как лоза, но по функционалу являются просто плитой с текстурой корней.
На любом из тайлов под полом гештальт может потратить свои накопленные ресурсы (функционал похож на блоба) и создать определенные структуры:
- Корневая стена (хорошо горит, преграждает обзор)
- Плотная стена (слабо восприимчива к огню и взрывам соответственно)
- Шипастая стена (наносит урон в ответ если атаковать её в рукопашную)
- Тепловая стена (поглощает попадающие в неё лазеры, иксрейные лазеры, поглощает огонь и температуру в радиусе 2-х тайлов, возвращая всё к норме и не давая ей пройти дальше)
- Корневая дверь (доступ только у всей расы дион и нимф)
- Светящаяся стена (дает свет в радиусе ~8 тайтлов для дион)
- Древо Охоты (Позволяет как кузня у культистов раз в 5 минут создавать дионам новые инструменты для себя. Броню: Надеваемые шипастые корни. Оружие: Заостренные корни/Корневой меч. Щит: Плотный корневой щит)
- Древо Жизни (Позволяет создавать новую нимфу раз в 5 минут за которых могут залететь госты, таким нимфам сразу же выдаются цели гештальта)
- Куст лозы (Позволяет раз в 20 минут получить семена лозы и пустить лозу, неэффективную в главном гнезде, но эффективную для саботажа)

Нажатие левой кнопкой мыши:
- Подпольные корни (просто при нажатии кликом как блоб пускает корни под пол, позволяет дышать дионе и регенирироваться стоя на такой плите, из-за чего у дион нет нужды в личном атмосе даже если гештальт растет в космосе)
- Корневой пол (создает корневую плиту, позволяя расширяться даже в космосе)
- Надкорневое покрытие (повторное нажатие на клетку с подпольными корнями заменяет обычную плиту на более прочную корневую или создает если изначально плиты не было)
- Сдерживание корнями (если нажать левой кнопкой мыши на игрока, то через 2 секунды задержки он сильно замедлится стоя на корнях с визуальным отображением, повторное нажатие с задержкой 5 секунд если он не двигается - уронит его. Следующее нажатие с задержкой 5 секунд начнет душить его, если персонажа никто не вытащит.)

### Игра за экипаж

Игра за экипаж аналогична игре при блобе и культистах. 
Но возможно договориться (в конце поста в "Дополнительные задумки" описан данный момент)
Экипаж ищет главный гештальт после того как его спалит и пытается сжечь его всеми средствами (ведь наиболее эффективное средство здесь будет - огнемет и зажигалки с кусачками).
Дион принадлежащих гештальту они соответственно также пытаются всячески искоренить как и самих культистов.
Запрет ботаникам выращивать нимф и следить за распространением растений.
Вскрывать все полы чтобы обнаружить сеть корней и уничтожить её кусачками/сжечь.
Вызвать отряд боевых коз и ящик кос для борьбы с лозами и корнями.
Вызвать ЕРТ когда СБ самоубились об главный гештальт, шипастые стены и защищающих её дион и нимф.
Вызвать Дедов когда почти половина станции оказалась под сверх-гештальтом, и по ней бегает куча дион и нимф и взорвать станцию к чертям во славу НТ.

### Расценки

**Пища:**

Название + сколько дает | скорость всасывание
Растение +1 биомасса | 1 секунда
Мясо +2 биомасса | 1 секунда
Труп животного +5 биомассы | 10 секунд
Труп гуманоида + 8 биомассы | 30 секунд

**Строительство:**

_Примерное_
Название - цена | скорость постройки
- Подпольные корни -1 биомасса | мгновенно
- Корневой пол -1 биомасса | мгновенно
- Надкорневое покрытие -1 биомасса | мгновенно
- Корневая стена -2 биомасса | 3 секунды
- Плотная стена -5 биомасса | 15 секунд
- Шипастая стена -3 биомасса | 5 секунд
- Тепловая стена -5 биомасса | 20 секунд
- Корневая дверь -4 биомасса | 10 секунд
- Светящаяся стена -3 биомасса | 5 секунд
- Древо Охоты -10 биомасса | 60 секунд
- Древо Жизни -20 биомасса | 120 секунд
- Куст лозы -20 биомасса | 120 секунд

### Лор и неувязки

**Почему из-за такой угрозы гештальта НТ не запретило всех дион?**
НТ знает только о гештальтах в космосе и крайне не ожидало, что один из гештальтов решит разрастись прямо на их станции и поглотить его. Какая неожиданность.

**В чем отличия то от блоба и зачем нам второй блоб?**
Блоб - целиком и полностью самостоятельный антаг способный хоть с самого начала действовать в открытую и открыто конфронтовать. 
Сверх-гештальт является больше скрытным антагом требующий от дион слаженой работы для его разрастания и развития чтобы он же им потом помогал в выполнении цели по захвату станции. Сверх гештальт - это как база для антагов со своим интеллектом и сетями. Дионам предстоит сложная работа для его кормежки, и выгребания всего холодильника ботаники и поваров, ведь они способны спалиться в кратчайшие сроки, если заранее не подготовят место для разрастания сверх-гештальта с достаточным количеством еды, а СБ не придаст этому значение. Тактики и стратегии достигания величия гештальта разные. И столько же для противодействия и "палева".
В некотором роде Сверх-Гештальт на поздних этапах вполне может по опасности быть наравне со сверх блобом и культом призывающим Нар-Си, а то и Тенелингов достигших.
Сложный антаг на ранних этапах для антагов и легкий для экипажа если вовремя заметить.
Лёгкий антаг на поздних этапах для антагов и сложный для экипажа если сверх-гештальт набрал немалое количество биомассы и его постоянно подкармливают.

### Плюсы

Новый антаг, разнообразие режимов, соответствие лору с огромными гештальтами.

### Минусы

Это нужно кодить и рисовать спрайты. Спрайте я согласен нарисовать, кодинг для меня пока неизвестен.

### Разработка
Это не финальная версия идеи. Она будет дорабатываться и балансироваться в случае если она пройдет голосование.
Я самолично готов заняться своей же идеей и готов слушать все предложения и вносить соответственно в идею изменения для создания более приятного режима.

### Дополнительные задумки
Изначальные дионы могут приходить через метеоритный шторм. Т.Е. выбирается случайное место где спавнятся "дикие нимфы" которые уже могут проходить по всей станции. Или случайный ивент, или изначально на станции. И/Или.
В общем задумка в том, что это будет случайный ивент где для гостов будет предлагаться стать дикими дионами, а далее им выдаются более-менее нейтральные цели произрастать. Как они будут это делать - их дело и их стратегии. Могут агрессивно и пытаться поглотить всю станцию, а могут помогать станции и даже закрывать разгермы если договорятся, ну или дать ложную надежду что они дружелюбные, а потом резко начать поглощение станции. В общем, площадка для РП.

Новые нимфы:
Делаются яйца/опухоли, по нажатию на которых при росте они вылупляются и можно получить новую диону

**Comment by PhantornRU** [comment]
И да, для такой пьянки я готов рисовать спрайты, опыт имеется.

**Comment by PhantornRU** [comment]
1. ЗА
2. Я готов это кодить и спрайтить и считаю что лишний антаг может быть не лишним. Как вариант, данный режим можно запускать под присмотром администраторов и только администратором.

**Comment by DetectiveEnotsky** [comment]
1. **Против**
2. Начну с того, что это - второй блоб, который никому не нужен. Далее, есть куча всего, которое уже сделано, не нужно кодить и просто впилить в ротацию. И к тому же, реально, этот антаг будет слишком сложен для большинства игроков сервера(шуссоиды) и скорее всего быстро упразднится хейтом и предложками о выкидывании.
Так, что он [не нужен](https://tenor.com/view/why-disappointment-stress-depression-gif-12154856)

**Comment by Lenerald** [comment]
1. За
2. Серверу нехватает мажоров.

**Comment by AIDATA1** [comment]
За
Плюсы: Мажор, интересная механика хоть и выглядит как блобб + культист.

Минусы: Дионы. Почему? Потому за дион играет очень мало(!) игроков, когда этот режим будет выпадать, будет крайне подозрительным что вдруг резко появилось множество дион.

Возможное решение: Новоприбывшие антаги могут быть как генно-мофиципованные(или под влиянием блюспейс) дионы которые стали проникать в человеческие тела, пуская небольшую эко систему внутрь человека(чтобы скрыть своё присутствие на станции).

**Comment by PoTapkam** [comment]
1. За
2. Разнообразит гемплей, возможно люди смогут научится в РП ивенты и не будут тупо взрывать пол станции. Хотя на мой взгляд любой взрыв на станции практически спалит Гельшат, но попробовать стоит. Ивент всегда можно убрать если игрокам не понравится, считаю, что стоит попробовать.

**Comment by zombie288** [comment]
1. За
2. Давно нужно было сделать нового мажор антага, комба Блобика и Культа - отличная и небанальная идея.
Если Пупс сам все накодит - почему бы и нет.

**Comment by DayBreakerBrony** [comment]
1.за
2.сам писал похожую предлогу, оч хотелось бы увидеть.

**Comment by Artrery** [comment]
1.За
2. Разнообразие антагов всегда гуд. Да и мне нравится описанная реализация требующая кооперации. Ещё я так же заметил будущую фичу, если среди дион "антагов" есть генетик то никакие жертвы и не будут нужны, потому что они из обезьян спокойно могут настрогать сколько угодно гуманоидов, правда встаёт вопрос с доставкой, но это дело десятое.

**Comment by VictorSocks** [comment]
1. Против
2. Первое: Метахейчу Пупса
 Второе: Не понятно почему гештальт и дионы могут действовать агрессивно, дионы же по сути своей мирные хоть и не все, а в Лоре сказано: "Кажется, что они довольны тем, что живут в симбиозе с различными космическими народами" и "Дионы, как известно, в целом дружелюбны, жители лунных топиариев с радостью укроют у себя экипажи потерпевших бедствие кораблей, но они редко действуют политически.

Тем не менее, у дион есть тонкое, но значительное экономическое влияние. Они оказались бесценными для экологии космических кораблей по всей галактике, их нимфы защищают запасы гидропонной пищи от вредителей, улучшают рост других растений или даже сами могут служить источником пищи. Иногда эти нимфы могут вырасти в гештальты размером с команду и оказаться еще более полезными. Это было основным средством их недавнего распространения по Галактике.
Зачем в основном мирным дионам, которые дщё и дают только плюсы команде быть агрессивными и сжирающими станции, добавить механику роста дионы в мирного и помогающего гештальта можно, но почему обладающие обширными знаниями в области науки и истории галактики дионам жрать станцию корпорации с которыми она заключила договор не понимаю уж простите.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184348325-5335fc54-6d08-4ecb-8668-520e36ba86bf.png)
