### ISSUE TITLE
Feat: добавить возможность повесить кого-либо

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#102]
### Проблема

Добавить возможность повесить кого-либо с помощью проводов(30 штук).
Игрок с помощью мотка проводов сделает петлю(в меню крафта, где есть стяжки), после чего он тыкает петлёй на тайл на котором разместить её и всё, петля установлена. Далее нужно привести человека и держа его в третьем грабе тыкнуть по петле, начнётся процесс по итогу которого, жертва будет в петле и начнёт задыхаться. Можно вырваться из петли, если прожать resist, но при условии, что тот кто в петле не закован в стяжки или наручники.

### Решение

Надо кодить.

### Плюсы

Новые рп ситуации, а также новый способ убить

### Минусы

Надо кодить

**Comment by Honker9999999** [comment]
Идея интересная, но нужно продумать куда ты вешаешь саму петлю. Потолка же нет... 
Ну, или если без шуток - потолок скорее всего гладкий, а лампочек или люстр по идее нет. Т.е. некуда петлю привязать, так что вопрос - а как?

**Comment by botka4aet** [comment]
> Идея интересная, но нужно продумать куда ты вешаешь саму петлю. Потолка же нет...
> Ну, или если без шуток - потолок скорее всего гладкий, а лампочек или люстр по идее нет. Т.е. некуда петлю привязать, так что вопрос - а как?

Так же, как и душ - на стену

**Comment by Sykybekk** [comment]
> Идея интересная, но нужно продумать куда ты вешаешь саму петлю. Потолка же нет...
> Ну, или если без шуток - потолок скорее всего гладкий, а лампочек или люстр по идее нет. Т.е. некуда петлю привязать, так что вопрос - а

**Comment by Sykybekk** [comment]
> Идея интересная, но нужно продумать куда ты вешаешь саму петлю. Потолка же нет...
> Ну, или если без шуток - потолок скорее всего гладкий, а лампочек или люстр по идее нет. Т.е. некуда петлю привязать, так что вопрос - а как?

Есть два путя:
1)Принять условность, что можно зацепить.
2)Добавить новый крафт для металла, а именно крючок или зацеп какой-нибудь. Мы его тыкаем на тайл он ставится, якобы на потолок. Далее тыкаем по нему петлёй и она ставится уже и всё.

**Comment by PhantornRU** [comment]
Есть мясницкие крюки, чем вам не альтернатива повешению? Только нужно лобызать ножичком
