### ISSUE TITLE
Feat: добавить возможность повесить кого-либо 

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#103]
### Проблема

Добавить возможность повесить кого-либо с помощью проводов(30 штук).
Игрок с помощью мотка проводов сделает петлю(в меню крафта, где есть стяжки), после чего он тыкает петлёй на тайл на котором разместить её и всё, петля установлена. Далее нужно привести человека и держа его в третьем грабе тыкнуть по петле, начнётся процесс по итогу которого, жертва будет в петле и начнёт задыхаться. Можно вырваться из петли, если прожать resist, но при условии, что тот кто в петле не закован в стяжки или наручники.

### Решение

Кодить

### Плюсы

Новые рп ситуации, а также новый способ убить

### Минусы

Надо кодить

**Comment by Honker9999999** [comment]
Шизоид момент.

**Comment by HMBGERDO** [comment]
ну тогда возможность в наручниках самому в петлю залезать KEKW

**Comment by Sykybekk** [comment]
> Шизоид момент.

Почти... я случайно закрыл "это" и не нашёл как открыть, так что пусть будет так

**Comment by Jordanstolethepreciousslam** [comment]
У нас уже есть пластиковый пакет который можно надеть на голову связанной жертве чтобы она медленно задохнулась. Где все эти интересные ситуации? А нет их потому что убивать могут только антаги, а антаги не могут себе позволить убивать медленно.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184349190-3207d1c5-5edd-4ee7-ab70-798ddfcab920.png)
