### ISSUE TITLE
Bug: Закрытые доступом Хранилища ригов можно открыть и без доступа одной кнопкой

### ISSUE THREAD

**Issue by WonderCatDS** [ss220-space/Paradise#1032]
### Ckey

WonderCatDS

### Описание бага

Любой Secure Suit Storage Unit можно открыть не имея соответствующего доступа просто запустив процедуру дезинфекции. По её окончании юнит открывается, что позволяет забрать содержимое любому

### Шаги воспроизведения

1. Подойти к Secure SSU
2. Запустить процедуру дезинфекции
3. Дождаться её окончания
4. Profit : юнит открыт и можно забрать оттуда вещи

### Ожидаемое поведение

Есть два варианта
- После процедуры дезинфекции юнит не должен открываться сам.
- Юнит не должен начинать эту процедуру без наличия у игрока необходимого доступа.

### Дополнительная информация

Данный баг был обнаружен в ходе проверки на локальном сервере вопроса "как взломать SSU". 
Как оказалось, не так уж и сложно. 
https://youtu.be/ZjJWxdIW-EU - видео бага

### Операционная система

Windows 10

### Версия клиента

514.1584

### Название сервера

MAIN

### Примерное время и дата

10-00 18.06

**Comment by MorgoWizard** [comment]
https://github.com/ss220-space/Paradise/pull/1046
