### ISSUE TITLE
Feat: Ребаланс и починка всех существующих рас

### ISSUE THREAD

**Issue by VictorSocks** [ss220-space/Paradise#104]
### Проблема

Неиграбельность и имбалансность некоторых рас

### Решение

Провести ребалансировку всех существующих рас. Снизить(НЕ УБРАТЬ) бафы скорости у вульпотаяр, реген у дион, восприимчивость к урону у ипц и нюклеаций, пересмотреть бафы вринов и киданов и т.д. Т.к сейчас некоторые имеют явное преймущество в той же КСке над другими и это не есть хорошо и портит множество игровых ситуаций. Тот же ревенант убивающий ипц одной абилкой - плохо. Шансы должны быть у всех.

### Плюсы

Плюсы: все расы будут играбельными и иметь сбалансированные особенности.

### Минусы

Минусы: множество правок кода, все расы будут играбельными и сбалансированными.

**Comment by VasilevAY** [comment]
![Uploading image.png…]()
