### ISSUE TITLE
Feat: Унга-бунга

### ISSUE THREAD

**Issue by semoro** [ss220-space/Paradise#106]
### Проблема

Слишком умные эши в раундах без админов

### Решение

Запретить Эшам использовать вещи шахтеров, мехов и поды

### Плюсы

Меньше Унга-Бунга с образованием

### Минусы

Эша нельзя обучить пользоваться сложной техникой по РП

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184349489-b929287f-8cd4-4339-b659-d9f74c4f0b4a.png)
