### ISSUE TITLE
Feat:  Improving interaction with the IPC

### ISSUE THREAD

**Issue by Sora-Akuma** [ss220-space/Paradise#1077]
### Проблема

Невозможность нормально вернуть имя КПБ. Есть способ, но он связан с обезьянами, картами и аугментацией, которое занимает много времени. Имеется проблема с долгим изменением дизайна всех конечностей КПБ и она очень ограниченная. Невозможность напечатать отчета по серьёзности повреждений по примеру боди-сканера или Health Analyzer как в меде.

### Решение

Создание дополнительного устройства/машины для Роботехников по типу генетиков. Включающая себя функции  изменения цвета, модели отдельных частей или всего тела, с встроенной манипуляцией пластикой для возращения имени. Можно сделать чтобы в консоль вставлялась карта, а от имени карты ставилась бы и имя КПБ. Возможность полной диагностикой тела, с печатаньем результатов. 
Могу попробовать накидать эскизы устройства.

### Плюсы

1. Позволит сократить до нуля людей с ником Integrated Positronic Chassis 41811 и т.д
2. Роботехникам смогут обращаться КПБ для изменения своего дизайна или имени, больше РП взаимодействий и работы.
3. Возможность на антагонисте КПБ изменить внешность и имя.
4. Фиксирование побоев с КПБ.

### Минусы

1. Сложность кодинга и рисовки нового спрайта.
2. Не так много людей играют на КПБ
3. Придется немного переделать отдел роботехников

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
