### ISSUE TITLE
Feat: Доставка газов на танкере

### ISSUE THREAD

**Issue by semoro** [ss220-space/Paradise#108]
### Проблема

Из-за повреждений на станции могут заканчиваться различные газы

### Решение

Добавить корабль-танкер который заказывается с ЦК, с баками различных газов и системой подачи газов на станцию в атмос

### Плюсы

Возможность пополнять баки в атмосферке

### Минусы

Надо маппить

**Comment by PhantornRU** [comment]
1. За
2. 
- Можно будет восстанавливать станцию даже когда тесла взорвала атмос и вызов шаттла при разрушенном атмосе будет не обязателен.
- Можно будет строить СМ с большим количеством плазмы.

**Comment by Racer396** [comment]
1. За
2. Не только при сбежавшей тесле/синге можно восстановить атмос, но и когда какой-то гений выкручивает все помпы на максимум и при большом количестве разгерм воздух весело утекает в никуда. Ну и да, больше плазмы богу плазмы для СМ подойдет, если разочек реактор сгорел во время постройки, теперь будет откуда взять плазму на вторую попытку.

**Comment by Artrery** [comment]
1. За
2. Разрывался между ЗА и ПРОТИВ потому что с одной стороны, всё отлично, заказывают кораблик(За что правда, если через очки каргонии то это ещё геморрой привязывать это всё) он пристыковывается и перекачивает газы, всё хорошо и автоматизировано. С другой стороны намного более простой вариант просто добавить карго заказывать баллоны с газами, а инженерам надо будет самим морочиться с перекачкой баллонов в атмос(не большая морока на самом деле). И так получается с одной стороны геморрой кодера(большой) и маппера и автоматизация для и так ленивых инженеров, с другой стороны просто добавление баллонов с газами каргонцев и небольшие усилия по ручной перекачке газов инженерам/атмос техникам. В общем, если найдётся тот кто готов кодить и мапить то отлично, если нет то есть более простой и бюджетный вариант.

**Comment by semoro** [comment]
@Artrery BTW: Чтобы заправить цистерну до начального состояния нужно 600 канистр

**Comment by AttHawk** [comment]
1. За
2. Отличная фича, поможет восстановить станцию при разрушенном атмосе, вопрос только в том что это надо серьезно мапить и привязывать к очкам карго, а место для этого кораблика найти не проблема, особенно на дельте

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184349680-df2cdfd9-0bcf-4fa7-a9cd-b82df6cf79d8.png)
