### ISSUE TITLE
Feat: Job - jeweller

### ISSUE THREAD

**Issue by botka4aet** [ss220-space/Paradise#109]
### Проблема

- Приевшиеся профы.

### Решение

Добавить новую профу - Ювелир.
Создает:
- ювелирные украшения(серьги, кольца, браслеты)
- зажигалки

При отсылке с карго выдает КаргоПоинты
- с малым шансом поделка может **Выстрелить**, став хитом, выдавая увеличенную награду

### Плюсы

- Новый геймплей
- Новое место для получение карго-поинтов
- Не надо кодить(я сам все сделаю)

### Минусы

- Усложнение геймплея и кода
- Надо исправлять карту, добавляя кабинет
- Новое место, куда будут уходить ресурсы

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184349640-e31c2ce3-d745-4bb7-8fcf-4a999553732c.png)
