### ISSUE TITLE
Feat: Предложения с подкаста

### ISSUE THREAD

**Issue by Pecccok** [ss220-space/Paradise#110]
### Проблема

1. Не хватает возможности нормально узнавать мнение экипажа по различным вопросам, а также нормально взаимодействовать будучи капитаном, исключительно через рацию.
2. Нынешняя система камер хоть и получил улучшения всё ещё недостаточно удобная.
3. Педалям при щитспавне или просто при создании боргов ИИ получает доступ к его камере, хотя никак с ним не связан.

### Решение

1. Добавить рольке капитана возможность делать голосовалку либо через ПДА (её будут игнорить), либо аналог автовоута шаттла эвака на 3 часу.
2. Сделать возможность улучшения камер, чтобы была возможность просмотра как через консоль ксено или ИИшкой.
3. Сделать привязку боргов к ИИ только на том Z уровне, на котором находится сама ИИ.

### Плюсы

QOL на сервере

### Минусы

Нужно кодить

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184347908-34465a4e-f843-4f8d-97df-540bf85c6b28.png)
