### ISSUE TITLE
Feat: ЦК для смертных

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#111]
### Проблема

Часто есть раунды, где педалей просто не существует. И такое даже на мейне случается, не говоря про какой-нибудь ВЛ или эксту. По итогу и ЦК нет.
Нужно запросить новую цель? ЦК нет.
Нужно ОБР когда много гостов и куча антагов которые очень активничают? ЦК нет.
Просто хочется больше контакта ЦК со станцией? I sleep.

### Решение

Можно начать набирать особенных смертных, которые будут получать кнопки специально для ЦК. Попасть туда смогут только доверенные люди, по сути такое подобие "ивентологов" без обязанностей педалей. 
Примеры требований для попадания в таких:
  * 500-700 часов в игре живым (С редкими исключениями)
  * Иметь какую-либо до этого штуку (ветеранку, менторку, педальку и т.д.)
 

### Плюсы

На ЦК всегда будет сидеть игрок, который будет контактировать со всей остальной станцией. А значит больше разнообразия в раунд.
И цели новые будут. И ОБР. И посиделки в общем канале с ЦК. И просто разные ситуации.

### Минусы

Может быть абуз, и превышение порога кнопок (Можно исправить введением особых флагов, но код)

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184349753-4d5d0e25-a4db-4c8e-90e8-a7cf80ee1d15.png)
