### ISSUE TITLE
Bug: Невидимый стул "chair (light)"

### ISSUE THREAD

**Issue by RockNRollKnight** [ss220-space/Paradise#1113]
### Ckey

rocknrollknight

### Описание бага

Есть возможность из металла создать невидимый стул, с которым невозможно взаимодействовать
![Стул судьбы](https://user-images.githubusercontent.com/109584433/180634009-ac764b0c-8c4d-4711-be96-d75bedfc8f48.jpg)
.

### Шаги воспроизведения

Держа в руке листы металла нажать "Z" и выбрать постройку "chair (light)" после чего на вашем тайле появится невидимый стул.

### Ожидаемое поведение

Созданный стул будет видимым и с ним можно будет взаимодействовать.
Альтернативно нельзя создать именно этот предмет "chair (light)".

### Дополнительная информация

Спросил у других игроков, тоже кроме как через ПКМ по тайлу не видно ничего, воспроизведён на локалке.
![Стул судьбы2](https://user-images.githubusercontent.com/109584433/180634329-97b0f8e6-76f0-4274-b82b-ff0701a062bb.jpg)

### Операционная система

Windows 10

### Версия клиента

514.1585

### Название сервера

WL

### Примерное время и дата

24.07.2022, примерно 15.00 +-2 часа

**Comment by larentoun** [comment]
Уже решено: https://github.com/ss220-space/Paradise/pull/1111

**Comment by RockNRollKnight** [comment]
> Уже решено: #1111

Окей, странно, что я это встретил тогда, проверю в ближайшей катке, если проблем не будет - закрою (Если этот комент не закроет).
