### ISSUE TITLE
Bug: Отсутствуют свечи в коробках

### ISSUE THREAD

**Issue by MorgoWizard** [ss220-space/Paradise#112]
### Ckey

Leverkuzen

### Описание бага

Во всех коробках при раундстарте отсутствуют свечи в коробках, хотя тайл коробульки показывает, что свечки там есть.
Так же есть вероятность того, что даже в химии не сделать свечки (лично не проверял).

### Шаги воспроизведения

Найти коробку со свечами и проверить

### Ожидаемое поведение

Свечей в коробке не окажется, несмотря на то, что визуально она полная

### Операционная система

Windows 10

### Версия клиента

513.1542

### Примерное время и дата

09.07.2021 - 22:54

**Comment by semoro** [comment]
@ThaumicNik, похоже баг в маппинге дельты, не те коробки
`/obj/item/storage/fancy/candle_box` вместо
`/obj/item/storage/fancy/candle_box/full`

**Comment by MorgoWizard** [comment]
@VasilevAY, теперь коробки (как минимум на Дельте) полные
![image](https://user-images.githubusercontent.com/84981163/185740247-ede9db39-7f17-436b-b0ae-09472c2e66df.png)
