### ISSUE TITLE
Закрыть неактуальные и откровенно протухшие вопросы. 

### ISSUE THREAD

**Issue by VasilevAY** [ss220-space/Paradise#1120]
### Проблема

Раздел Issue откровенно заброшен. Предлагаю его сделать отправной точкой для инструментария

### Решение

1. Удалить все предложения до марта 2022 без разбирательств как протухшие
2. Оставшиеся предложения оценить с точки зрения актуальности
3. Закрыть неактуальные предложения
4. Возобновить работу этого раздела в рамках разработчиков, дабы у начинающих разрабов были реальные задачи, на которых они могли бы потренироваться

### Плюсы

1. Начало работы

### Минусы

1. Надо работать

**Comment by larentoun** [comment]
Идея то хорошая, но доступ есть только у Азиза, а он сейчас занят. Уже ранее предлагал это
