### ISSUE TITLE
Определение объектов, которым необходимо добавить крафт

### ISSUE THREAD

**Issue by VasilevAY** [ss220-space/Paradise#1124]
### Проблема

Сейчас есть ряд объектов, которые нельзя построить в рамках IC. Информация по объектам взята из #ex-chat ArcanumPictor#3619, спасибо
Вот сам список:
Консоли:
• holodeck control computer
![image](https://user-images.githubusercontent.com/98010665/181275185-d242e6ef-270e-43ed-a97a-3cba50f963ce.png)
• tachyon-doppler array
![image](https://user-images.githubusercontent.com/98010665/181275896-2ce4d119-5c9a-4736-8614-7652b52da348.png)
• telescreen и разновидности
![image](https://user-images.githubusercontent.com/98010665/181276059-b8aef25a-37a7-4420-8527-3f78b72938f6.png)
• managment consoles (пример - СМО)
![image](https://user-images.githubusercontent.com/98010665/181276308-c3062e3e-6f3f-4a61-a04d-ccecb87b3a0c.png)
• accounts uplink terminal
![image](https://user-images.githubusercontent.com/98010665/181276489-7f5b8b15-39c8-4e5b-9f16-e9dea2c9d55f.png)
• laptop (atmoscontrol, med_data, secure_data)
• консоли управления шаттлами (computer/shuttle/...)
![image](https://user-images.githubusercontent.com/98010665/181277823-1b6479e7-6c56-4bac-826d-5464b433980b.png)
• Все возможные button и control
![image](https://user-images.githubusercontent.com/98010665/181279111-b23f48ed-1962-49ca-81a1-abb329a9ceda.png)
• door_timer (в бриге для заключенных)
![image](https://user-images.githubusercontent.com/98010665/181279427-c4d7140b-1869-4b10-8e7c-5672504ccde9.png)
• обычные экраны состояния (AI display)
![image](https://user-images.githubusercontent.com/98010665/181279561-83ffc7a0-86ad-4a0c-9428-21a4d8978360.png)
• status_display, которой уведомляет о новых ресурсах
![image](https://user-images.githubusercontent.com/98010665/181279713-37bfc937-14c7-4928-8365-a3faa974e938.png)
• guest pass terminal
![image](https://user-images.githubusercontent.com/98010665/181279970-1abe5f66-031a-4d00-bfb4-32641e3f5e45.png)
Объекты:
• poddor, blast
![image](https://user-images.githubusercontent.com/98010665/181280871-05464ed4-fd1b-4d61-a3df-5fe7b9af6c4e.png)
• shutters
![image](https://user-images.githubusercontent.com/98010665/181280990-47608c12-8d3c-4873-b757-945cadaefab1.png)
• photocopier
![image](https://user-images.githubusercontent.com/98010665/181281126-947e59f3-99a1-4785-8e07-2034dff602ab.png)
• morgue
![image](https://user-images.githubusercontent.com/98010665/181281251-4883b8f1-423d-4d9b-998a-108d42e63782.png)
• Check-In/Out Computer
![image](https://user-images.githubusercontent.com/98010665/181281414-7fcde901-beef-46c0-81f4-1693af23f046.png)
• potted plant
![image](https://user-images.githubusercontent.com/98010665/181281512-88a4707e-d344-441e-98b6-d821e75b1a0c.png)
• bush (цветы)
![image](https://user-images.githubusercontent.com/98010665/181281621-4c36359a-fdd5-4922-83b8-019f72bc6e43.png)
• liquid cooler
![image](https://user-images.githubusercontent.com/98010665/181282176-4d3b1c6d-301c-4c46-a952-9ca069220963.png)
• freezer
![image](https://user-images.githubusercontent.com/98010665/181282335-0f23e6de-af25-4fb0-bb60-4a2affaa5a69.png)
• Nanotrasen automatic teller machine
![image](https://user-images.githubusercontent.com/98010665/181282467-9364b6f9-7f3e-4cff-a7ac-92e1bb596f64.png)
• Washing Machine
![image](https://user-images.githubusercontent.com/98010665/181282567-4670cfaa-8cec-4d1f-b0e3-4b19d1191ccf.png)
• peper spray refiller
![image](https://user-images.githubusercontent.com/98010665/181282971-0b78f019-3df4-4423-a940-d6e878a6ceaa.png)
• fuel tank
![image](https://user-images.githubusercontent.com/98010665/181283076-8ef61fa1-ee51-4291-9168-ccb0c9fed9ff.png)
• space cleaner refiller
![image](https://user-images.githubusercontent.com/98010665/181283347-4e3bd777-cf85-4f03-815c-721ddd150c42.png)
• emergency locker
![image](https://user-images.githubusercontent.com/98010665/181283730-d71ee830-65f6-47db-9d2e-0f188444f111.png)
UPD:
• safe
![image](https://user-images.githubusercontent.com/98010665/181284141-9e202cf1-dc7d-47cd-8210-1e8ed81294ab.png)
• crematorium
![image](https://user-images.githubusercontent.com/98010665/181284285-2d24c5d7-5081-4dc2-922e-c7fb1b395d64.png)
• wall recharger
![image](https://user-images.githubusercontent.com/98010665/181284854-5b6fc4aa-f38d-47f3-89e4-b8a534a3312a.png)
• suit storage unit (всех видов)
![image](https://user-images.githubusercontent.com/98010665/181284968-8751446f-3ad6-4162-ada8-e5041912f3cf.png)
• Meassaging Server
![image](https://user-images.githubusercontent.com/98010665/181285296-8a156da6-72c4-4e29-ab5a-f322db7b373b.png)
• Blackbox Recorder
![image](https://user-images.githubusercontent.com/98010665/181285432-3d6fd907-e51c-4fe4-b1eb-17db62628178.png)
• cryo_cell
![image](https://user-images.githubusercontent.com/98010665/181285554-ded3b239-4794-454f-82ce-b39d4fc4f365.png)
• Turret Control panerl
![image](https://user-images.githubusercontent.com/98010665/181285656-1656110f-f3d3-4c28-9133-55b1fb759a88.png)
• transite_tube
![image](https://user-images.githubusercontent.com/98010665/181285853-23b68ed0-7089-4462-8e17-2cc21f343149.png)
• station tube station
![image](https://user-images.githubusercontent.com/98010665/181285973-98b06918-5273-47e2-b123-a689b73becb8.png)
• surgery holosign (значок на двери в операционную)
![image](https://user-images.githubusercontent.com/98010665/181498616-590b0ca2-b10d-4ff9-909e-eba507317164.png)
• все структуры /sign/
пример:
![image](https://user-images.githubusercontent.com/98010665/181499055-a9c21ea3-0ac5-434d-b30e-8ed462dd8a74.png)
• /structure/closet/crate/can (неавтоматические мусорки)
![image](https://user-images.githubusercontent.com/98010665/181499105-99adcc12-db82-4b99-b88e-f046f1987f47.png)
• tank storage unit
![image](https://user-images.githubusercontent.com/98010665/181499410-26668970-0e25-4fdb-876d-2f27ca64cde8.png)
• pressure tank
![image](https://user-images.githubusercontent.com/98010665/181499508-f2932348-592c-49f4-8991-2e45f9614ca8.png)
Вещи:
• ArtVend
![image](https://user-images.githubusercontent.com/98010665/181499807-de56531f-268a-4581-a59a-dfa05a327d9e.png)
• Rapid-Crate-Sender
![image](https://user-images.githubusercontent.com/98010665/181499946-ec0f67f8-9e00-46f5-8e39-3d2e47768967.png)
• EFTPOS
![image](https://user-images.githubusercontent.com/98010665/181500910-280c6f5b-ddd8-4758-97e1-191104eebcb5.png)
• все holosign_creator, кроме СБ
![image](https://user-images.githubusercontent.com/98010665/181503281-92b2c058-e5f0-434c-bc8a-4591be00254c.png)
![image](https://user-images.githubusercontent.com/98010665/181514091-06b64b1a-4199-4d68-b81b-9a02969756b3.png)
• implanter (Death Alarm)
![image](https://user-images.githubusercontent.com/98010665/181503477-943eb76b-979b-4379-9b2c-8a5bbf49d3c9.png)
UPD:
• suit (см. изображение, в том числе и СБ и ХОС suit)
![image](https://user-images.githubusercontent.com/98010665/181512056-6603720e-0d60-4cde-8bf8-9382cff04272.png)
• emergency floodlight
![image](https://user-images.githubusercontent.com/98010665/181507639-414b613c-d183-4179-81f9-50c35eb92319.png)
• pod lock buster
![image](https://user-images.githubusercontent.com/98010665/181507853-4b9c48aa-a979-4249-be03-3e54d23714c3.png)
• Space pod paintkit
![image](https://user-images.githubusercontent.com/98010665/181508361-5d05df68-bb3c-44a1-80bc-6a243b46fe1d.png)
• briefcase и secure briefcase
![image](https://user-images.githubusercontent.com/98010665/181506841-ddc5e86e-0d5c-433a-9c03-973f3a4d52db.png)
UPD2:
• cell charger
![image](https://user-images.githubusercontent.com/98010665/181506963-3c3c1037-7f0b-499e-8661-27607f56a6e9.png)
• ~~Возможно, витрины как у капитана и РД~~ -крафтятся, информация Д.Арк. Собрать - возможно, разобрать - нет
• Filling cabinet
![image](https://user-images.githubusercontent.com/98010665/181507171-366febaf-b308-4b0f-a9f0-70600a0f86a7.png)
• notice board
![image](https://user-images.githubusercontent.com/98010665/181507350-4d642f8c-0b03-4b12-aa0d-7f282768549c.png)
• gravity generator
![image](https://user-images.githubusercontent.com/98010665/181508971-e83a38bd-1247-4afd-8ba0-ad3664e5d50c.png)
• gun cabinet
![image](https://user-images.githubusercontent.com/98010665/181509371-65ddf09e-23e3-4359-bf41-1b1415536bf7.png)
• YouTool
![image](https://user-images.githubusercontent.com/98010665/181515585-983d6d96-1b8a-4e26-a606-27da7bb0fc8c.png)
• Electrochromic window (затемняющие окна из бара)
![image](https://user-images.githubusercontent.com/98010665/181516825-f500bc0c-f2f6-49e2-8724-a6fa4ff36e77.png)
• Vial
![image](https://user-images.githubusercontent.com/98010665/181523530-5e60b778-7c3a-40e5-9611-8a76bf214b43.png)
• /obj/item/storage/fancy/vials (хранилище Vial)
![image](https://user-images.githubusercontent.com/98010665/181524802-2499702b-9e6a-450b-9068-cd4304f65886.png)
• precision
![image](https://user-images.githubusercontent.com/98010665/181525907-1a15647f-c97a-468d-bd08-43174e6412ae.png)
• long range fax machine
![image](https://user-images.githubusercontent.com/98010665/181528069-8b9480e7-bcc7-4198-99dc-12c0e012eaa5.png)

### Решение

1. Проверка на актуальность этого списка для мейн.серверов
2. Определение путем обсуждения с а-составом тех вещей, которые можно было бы разбирать и крафтить в рамках IC
3. Начало разработки крафта
....?

### Плюсы

Меньше вещей без возможности получить в рамках IC

### Минусы

Достаточно серьезная работа, требующая много времени

**Comment by Den109G** [comment]
Smartfridge (холодильники) можно сделать. Плату в РнД добыть, отвёрткой выбрать нужный тип.
Крио можно сделать. Плата у РнД Cryotube.
"неавтоматические мусорки" - интересно знать что это. Просто в игре можно сделать и disposals chute, и otlet и pipe bin. Вроде все мусорки.

**Comment by VasilevAY** [comment]
> 

я думаю речь про мусорку, которая стоит у столовой на кибериаде

**Comment by Morskoikot** [comment]
Под-двери - они делаются, надо Титаниумом тыкнуть по заготовке обычного Аирлока

**Comment by ItsMeJaba** [comment]
• Зарядник для батарей
• Возможно, витрины как у капитана и РД
• Filling cabinet
• notice board
• Краске можно добавить функцию покраски шкафчиков
• Генератор гравитации
• Турбина (более вопрос привязки к консоли)
• emergency floodlight?

**Comment by VasilevAY** [comment]
> 

это то, что еще нашел, что не крафтится?

**Comment by Den109G** [comment]
> я думаю речь про мусорку, которая стоит у столовой на кибериаде

Нет, там обычная мусорка. И в баре, и на кухне - обычная мусорка.
![image](https://user-images.githubusercontent.com/87372121/181231521-97689d55-18f3-4cea-811c-f5ff7b6c6f6c.png)

**Comment by VasilevAY** [comment]
> > я думаю речь про мусорку, которая стоит у столовой на кибериаде
> 
> Нет, там обычная мусорка. И в баре, и на кухне - обычная мусорка. ![image](https://user-images.githubusercontent.com/87372121/181231521-97689d55-18f3-4cea-811c-f5ff7b6c6f6c.png)

Интересно. Ну, оставим под вопросом.

**Comment by Den109G** [comment]
Вот `garbage can` у кухни - нельзя сделать

**Comment by VasilevAY** [comment]
> Вот `garbage can` у кухни - нельзя сделать

А можешь скрин сделать его?

**Comment by ItsMeJaba** [comment]
![image](https://user-images.githubusercontent.com/91949115/181233979-d6b8cf15-fe23-476e-b9d1-677b36992757.png)

**Comment by VasilevAY** [comment]
> ![image](https://user-images.githubusercontent.com/91949115/181233979-d6b8cf15-fe23-476e-b9d1-677b36992757.png)

а, @Den109G, так я про нее и говорил, что-то я не посмотреть, куда ты ПКМ. Скорее всего она и имелась в виду в том списке

**Comment by Den109G** [comment]
Ну может тогда на английском написать, чтобы было понятней?
А то уже poddoor путают с дверями на подах.

**Comment by VasilevAY** [comment]
> Ну может тогда на английском писать вещи, чтобы было понятней? А то уже poddoor путают с дверями на подах.

я немного на работе разгружусь и сделаю скрины тех вещей, которые есть в списке и назову по-английски все, как есть в коде

**Comment by Morskoikot** [comment]
> • Зарядник для батарей • Возможно, витрины как у капитана и РД • Filling cabinet • notice board • Краске можно добавить функцию покраски шкафчиков • Генератор гравитации • Турбина (более вопрос привязки к консоли) • emergency floodlight?

Витрины делаются, но витрины невозможно разобрать

**Comment by Morskoikot** [comment]
> Ну может тогда на английском писать вещи, чтобы было понятней? А то уже poddoor путают с дверями на подах.

А какие имелись ввиду?

**Comment by Morskoikot** [comment]
А, понял какие, извиняюсь

**Comment by Den109G** [comment]
> Витрины делаются, но витрины невозможно разобрать

Ну это уже проблема того, что нет разбора. Так-то крафт есть. Пепечилл

**Comment by VasilevAY** [comment]
> > Витрины делаются, но витрины невозможно разобрать
> 
> Ну это уже проблема того, что нет разбора. Так-то крафт есть. Пепечилл

По-хорошему и возможность разбора сделать.

**Comment by Morskoikot** [comment]
> > > Витрины делаются, но витрины невозможно разобрать
> > 
> > 
> > Ну это уже проблема того, что нет разбора. Так-то крафт есть. Пепечилл
> 
> По-хорошему и возможность разбора сделать.

По хорошему также сделать возможность вызвать сигнализацию не через разбитие витрины, скажем отдельной платой в АПЦ либо провод туда добавить что триггерит сигнализацию

**Comment by Morskoikot** [comment]
А иначе, сигнализация есть, а возможности убрать её нет, так как и нет возможности вызвать её менее костыльным способом, и удалённо тоже вызвать нельзя

**Comment by MadGRaf** [comment]
Это банковский сервер. Не разбирается, не восстанавливается. 
![банковский сервер](https://user-images.githubusercontent.com/73444450/181360410-bd0c7537-40e0-4bd1-b73f-8aaa99bc467c.PNG)
![изображение](https://user-images.githubusercontent.com/73444450/181360535-7795fb7f-8f02-482c-a918-734c2158efa4.png)
![изображение](https://user-images.githubusercontent.com/73444450/181360838-cfae3245-5f85-4406-9dee-5e8bc17449e7.png)

EFTPOS считай можешь убрать из списка, потому что я их переработал, в том числе способ получения, скоро вкину PR.
Чисто пройдясь мимо библиотеки сходу могу назвать того, что нет в списке: Requests Console, Book Binder, Visitor Computer (не работает все равно), видеокамеры (которые есть только в лодауте библиотекаря и позволяют стримить картинку на развлекательные консоли в любой сектор), newscaster (полностью разбирается в металл, но крафта на него нет все равно и они еще двух видов бывают, в бриге особенные, хоть визуально и не отличаются), дисплеи статуса, офисные шкафчики и так далее.

**Comment by Den109G** [comment]
Visitor Computer работает, если ставить нормальный `obj/machinery/computer/library/public`, а не плейсхолдер.
Видеокамеры библиотекаря, имхо - имба. Лучше оставить их в одном количестве.
newscaster можно сделать. А автолате печатается frame для него.

**Comment by VasilevAY** [comment]
> Это банковский сервер. Не разбирается, не восстанавливается. ![банковский сервер](https://user-images.githubusercontent.com/73444450/181360410-bd0c7537-40e0-4bd1-b73f-8aaa99bc467c.PNG) ![изображение](https://user-images.githubusercontent.com/73444450/181360535-7795fb7f-8f02-482c-a918-734c2158efa4.png) ![изображение](https://user-images.githubusercontent.com/73444450/181360838-cfae3245-5f85-4406-9dee-5e8bc17449e7.png)
> 
> EFTPOS считай можешь убрать из списка, потому что я их переработал, в том числе способ получения, скоро вкину PR. Чисто пройдясь мимо библиотеки сходу могу назвать того, что нет в списке: Requests Console, Book Binder, Visitor Computer (не работает все равно), видеокамеры (которые есть только в лодауте библиотекаря и позволяют стримить картинку на развлекательные консоли в любой сектор), newscaster (полностью разбирается в металл, но крафта на него нет все равно и они еще двух видов бывают, в бриге особенные, хоть визуально и не отличаются), дисплеи статуса, офисные шкафчики и так далее.

Я в список добавлю эту информацию, в идеале, конечно, скинуть все отдельным PR, но можешь отдельно, если хочешь

**Comment by VasilevAY** [comment]
Отдельно добавить pocket fire extinguisher в протолат

**Comment by Zipliks** [comment]
- Мини огнетушитель - `/obj/item/extinguisher/mini`. Есть в шахтёрском вендоре.
- Dropper - `/obj/item/reagent_containers/dropper`. Есть в медицинском вендоре.
- Holosign Security - `/obj/item/holosign_creator/security`. Есть в Supply Pack'е.

**Comment by Morskoikot** [comment]
> Отдельно добавить pocket fire extinguisher в протолат

Лучше в автолат, в протолате он ни к месту

**Comment by Morskoikot** [comment]
> * Pocket fire extinguisher - `/obj/item/extinguisher/mini`. Есть в шахтёрском вендоре.
> * Dropper - `/obj/item/reagent_containers/dropper`. Есть в медицинском вендоре.
> * Holosign Security - `/obj/item/holosign_creator/security`. Есть в Supply Pack'е.

Имелась ввиду пипетка вирусолога, а не обычная стеклянная, обычная стеклянная набирает от одного юнита, до 5, а пипетка которую нельзя скрафтить, берёт от 0.1 до 1

**Comment by Zipliks** [comment]
> > * Pocket fire extinguisher - `/obj/item/extinguisher/mini`. Есть в шахтёрском вендоре.
> > * Dropper - `/obj/item/reagent_containers/dropper`. Есть в медицинском вендоре.
> > * Holosign Security - `/obj/item/holosign_creator/security`. Есть в Supply Pack'е.
> 
> Имелась ввиду пипетка вирусолога, а не обычная стеклянная, обычная стеклянная набирает от одного юнита, до 5, а пипетка которую нельзя скрафтить, берёт от 0.1 до 1

`/obj/item/reagent_containers/dropper/precision`?

**Comment by Morskoikot** [comment]
> > > * Pocket fire extinguisher - `/obj/item/extinguisher/mini`. Есть в шахтёрском вендоре.
> > > * Dropper - `/obj/item/reagent_containers/dropper`. Есть в медицинском вендоре.
> > > * Holosign Security - `/obj/item/holosign_creator/security`. Есть в Supply Pack'е.
> > 
> > 
> > Имелась ввиду пипетка вирусолога, а не обычная стеклянная, обычная стеклянная набирает от одного юнита, до 5, а пипетка которую нельзя скрафтить, берёт от 0.1 до 1
> 
> `/obj/item/reagent_containers/dropper/precision`?

По коду не скажу, в игре она называется Pipette вроде

**Comment by Zipliks** [comment]
> > > > * Pocket fire extinguisher - `/obj/item/extinguisher/mini`. Есть в шахтёрском вендоре.
> > > > * Dropper - `/obj/item/reagent_containers/dropper`. Есть в медицинском вендоре.
> > > > * Holosign Security - `/obj/item/holosign_creator/security`. Есть в Supply Pack'е.
> > > 
> > > 
> > > Имелась ввиду пипетка вирусолога, а не обычная стеклянная, обычная стеклянная набирает от одного юнита, до 5, а пипетка которую нельзя скрафтить, берёт от 0.1 до 1
> > 
> > 
> > `/obj/item/reagent_containers/dropper/precision`?
> 
> По коду не скажу, в игре она называется Pipette вроде

Ну тогда она, видимо
```
/obj/item/reagent_containers/dropper/precision
	name = "pipette"
	desc = "A high precision pippette. Holds 1 unit."
	icon_state = "pipette"
	amount_per_transfer_from_this = 1
	possible_transfer_amounts = list(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1)
	volume = 1
```

**Comment by VasilevAY** [comment]
**Space pod paintkit**
ФЫР ФЫР ФЫР#3198 : Добавить в карго в виде заказа
**ArtVend**
ФЫР ФЫР ФЫР#3198 : Добавить в карго в виде заказа
**Crematorium**
Scarlet^^#8266 : Возможность создания добавлять не нужно
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**implanter (Death Alarm)**
Scarlet^^#8266 : Добавить в карго в виде заказа
Eshi#3514 : Или добавить в виде крафта за 8 уровень биотехнологий, или возможность создания добавлять не нужно
God Damn Turkey#6964 : Возможность создания добавлять не нужно
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Suit**
Scarlet^^#8266 : Добавить в карго в виде заказа
Andru#7424 : Добавить в карго в виде заказа
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Vial**
ФЫР ФЫР ФЫР#3198 : Добавить в автолат
**/obj/item/storage/fancy/vials (хранилище Vial)**
ФЫР ФЫР ФЫР#3198 : Добавить в автолат
**holosing_creator**
AttHawk#5880 : Добавить в автолат
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**freezer**
ФЫР ФЫР ФЫР#3198 : Крафт (металл)
MissingNone (Денис)#3326 : Добавить возможность создания
**tachyon-doppler array**
Ditzy Shuudan#9689 : Добавить в карго в виде заказа
MissingNone (Денис)#3326 : Добавить возможность создания
**gravity generator**
Andru#7424 : возможность создания добавлять не нужно
**poddor, blast**
God Damn Turkey#6964 : Возможность создания добавлять не нужно
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**long range fax machine**
God Damn Turkey#6964 : Возможность создания добавлять не нужно
**safe**
God Damn Turkey#6964 : Возможность создания добавлять не нужно
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Meassaging Server**
God Damn Turkey#6964 : Возможность создания добавлять не нужно
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Blackbox Recorder**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Space pod paintkit**
God Damn Turkey#6964 : Возможность создания добавлять не нужно
MissingNone (Денис)#3326 : Добавить возможность создания
**holodeck control computer**
MissingNone (Денис)#3326 : Добавить возможность создания
**managment consoles**
MissingNone (Денис)#3326 : Добавить возможность создания
**laptop**
MissingNone (Денис)#3326 : Добавить возможность создания
**button и control**
MissingNone (Денис)#3326 : Добавить возможность создания
**guest pass terminal**
MissingNone (Денис)#3326 : Добавить возможность создания
**Check-In/Out Computer**
MissingNone (Денис)#3326 : Добавить возможность создания
**potted plant**
MissingNone (Денис)#3326 : Добавить возможность создания
**bush**
MissingNone (Денис)#3326 : Добавить возможность создания
**Suit storage unit**
MissingNone (Денис)#3326 : Добавить возможность создания
**cryo_cell**
MissingNone (Денис)#3326 : Добавить возможность создания
**Turret Control panel**
MissingNone (Денис)#3326 : Добавить возможность создания
**transite_tube**
MissingNone (Денис)#3326 : Добавить возможность создания
**station tube station**
MissingNone (Денис)#3326 : Добавить возможность создания
**все структуры /sign/**
MissingNone (Денис)#3326 : Добавить возможность создания
**/structure/closet/crate/can (неавтоматические мусорки)**
MissingNone (Денис)#3326 : Добавить возможность создания
**EFTPOS**
MissingNone (Денис)#3326 : Добавить возможность создания
**pod lock buster**
MissingNone (Денис)#3326 : Добавить возможность создания
**precision**
MissingNone (Денис)#3326 : Добавить возможность создания
**cell charger**
MissingNone (Денис)#3326 : Добавить возможность создания
**Filling cabinet**
MissingNone (Денис)#3326 : Добавить возможность создания
**telescreen и разновидности**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**консоли управления шаттлами (computer/shuttle/...)**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**door_timer**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Nanotrasen automatic teller machine**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Washing Machine**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Fuel tank**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**emergency locker**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
**Rapid-Crate-Sender**
MissingNone (Денис)#3326 : Возможность создания добавлять не нужно
