### ISSUE TITLE
Bug: Не извлекаются Кудзу из seed extractor

### ISSUE THREAD

**Issue by botka4aet** [ss220-space/Paradise#113]
### Ckey

botka4aet

### Описание бага

Если положить семена Кудзу в seed extractor, то обратно их забрать нельзя, они будут висеть мертвым грузом

### Шаги воспроизведения

Положить семена Кудзу в seed extractor
Попробовать забрать

### Ожидаемое поведение

Семечко появится в руке или на машине

### Операционная система

Windows 10 Pro - 19042.1052

### Версия клиента

513.1542

### Примерное время и дата

11:00 9/7/2021 ex 7725

**Comment by Honker9999999** [comment]
Бага нет, все в норме. См. скрины ниже:
![изображение_2021-07-12_091332](https://user-images.githubusercontent.com/74865061/125239518-6ede7300-e2f1-11eb-8874-5e3027954c61.png)
![изображение_2021-07-12_091344](https://user-images.githubusercontent.com/74865061/125239542-76058100-e2f1-11eb-9c3f-0f244d54d9f4.png)
![изображение_2021-07-12_091351](https://user-images.githubusercontent.com/74865061/125239547-7a319e80-e2f1-11eb-9e48-c32bbe5211b6.png)
![изображение_2021-07-12_091358](https://user-images.githubusercontent.com/74865061/125239563-7dc52580-e2f1-11eb-9485-58db7e0865ec.png)
P.S. - Было проверено и на новой, и на относительно старой версиях:
![изображение_2021-07-12_091748](https://user-images.githubusercontent.com/74865061/125239916-0774f300-e2f2-11eb-801c-4e5bf056e162.png)
![изображение_2021-07-12_092009](https://user-images.githubusercontent.com/74865061/125240125-5b7fd780-e2f2-11eb-8add-83e06415a7cd.png)
