### ISSUE TITLE
Issue: Асистухи на инженерах отключают фабрикатор дронов на старте и не только на старте

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#114]
### Проблема

На сервере начали появляться мегамозги на асистухах-инженерах, которые выключают Фабрикатор дронов прямо на старте смены. Случайно или специально - не важно. Фабрикатор выключен - дроны не печатаются == нет дронов всю смену. Собственно вот проблема.

### Решение

Выпилить в консоли кнопку Drone fabricator: Active/Inactive. 

### Плюсы

Больше не будет приколов с выключенным фабрикатором на старте да и в целом. К тому же я не знаю такого фабрикатора/прибора типа протолата в игре, который можно целенаправленно выключить через консоль. Всегда такие вещи работали от АПЦ и выключались только через АПЦ.

### Минусы

А они есть?

**Comment by snipersir** [comment]
Ответа нет. Ответ как НЕТ. Закрываю.

**Comment by Danefalt** [comment]
Не ну в теории если кому-то из нас не лень...
