### ISSUE TITLE
Feat: Эмоция улыбки

### ISSUE THREAD

**Issue by sentirpasseul** [ss220-space/Paradise#1154]
### Проблема

Проблема с отыгрышем эмоций. Не всегда вовремя можно найти нужную эмоцию, а писать через *me долго. 

### Решение

Предлагаю эмоцию "улыбнуться" активировать через скобку ")". То есть, человек говорит "Привет)", а в консоли выводится "Привет" и  "*имя человека* улыбается"

### Плюсы

Улучшается отыгрыш с эмоцией "улыбнуться"
Просто в использовании

### Минусы

Сложная реализация кода (хотя можно утилиту на Python написать и подключить к проекту), подключение NLP обработчиков текста

**Comment by VasilevAY** [comment]
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений согласно закрепленному сообщению в канале
