### ISSUE TITLE
Bug: буря на Лаваленде наносит урон бореру, который находится в носителе

### ISSUE THREAD

**Issue by Troll343** [ss220-space/Paradise#1157]
### Ckey

Troll343 

### Описание бага

Если человек, заражённый борером, получает урон от песчаной бури Лаваленда, то и борер получает урон, что приводит к быстрой смерти мозгового червя.

### Шаги воспроизведения

1. Борер залезает в носителя.
2. Носитель попадает под песчаную бурю.
3. Борер получает урон.
4. Борер умирает.

### Ожидаемое поведение

Борер не должен получать урон, когда находится в носителе.

### Операционная система

Windows 10 Домашняя

### Версия клиента

514.1585

### Название сервера

MAIN

### Примерное время и дата

06.08.2022 20:20

**Comment by VasilevAY** [comment]
https://discord.com/channels/617003227182792704/617004034405957642/1006109543429832804
продублировано в канал в ds

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/1168

**Comment by dikers93** [comment]
чисто в теории, если твоя оболочка в прямом смысле поджаривается, то и в нутри все тоже горит

**Comment by larentoun** [comment]
> чисто в теории, если твоя оболочка в прямом смысле поджаривается, то и в нутри все тоже горит

Так оно и будет

**Comment by larentoun** [comment]
https://github.com/ss220-space/Paradise/pull/1168

**Comment by fake123acc** [comment]
> > чисто в теории, если твоя оболочка в прямом смысле поджаривается, то и в нутри все тоже горит
> 
> Так оно и будет

Ну тады давайте и огонь проверять? Внутренние органы буря и взрыв фуелтанка дамажат одинаково. Механы прожарки бореров должны быть последовательны.
