### ISSUE TITLE
Feat: Кости у Дионы

### ISSUE THREAD

**Issue by PoTapkam** [ss220-space/Paradise#116]
### Проблема

У Дион прописано в лоре и коде прописано, что у них нет костей того же черепа или груди, но поскольку по коду Диона наследник хумана, то есть возможность проломить череп или грудь Дионе и как бы получается ситуация, что проломили того, чего нет и многие врачи теряются и не знают, что делать с этим и приходится через лоок объяснять. 

### Решение

Предлагаю выдать иммун к переломам Дионе, поскольку смотрится комично, что у Дион костей нет, а ей сломали череп или грудь. 

### Плюсы

Не будут ломаться не ломаемые кости которые их нет. Спасение нервов докторов, а также самих Дион, когда весь медбей носится и не знает, что делать, ведь костей то у тебя нет. 

### Минусы

Это можно посчитать как баф Дион, что у них появится иммун к переломам.

**Comment by HN1753236968** [comment]
#118

**Comment by HN1753236968** [comment]
https://github.com/ss220-space/Paradise/pull/118
