### ISSUE TITLE
Feat: Улучшение боргов

### ISSUE THREAD

**Issue by o4zloikeeper** [ss220-space/Paradise#117]
### Проблема

Борги работают хорошо, но, на мой взгляд, не совсем логично. 
_Говорят в сборке Парадайза самые унылые борги в истории сс13. Но я не проверял._

Врачи просят меня (инженерного борга) установить душ возле операционной. Создать душ на инженерном борге я могу. Но для его установки нужно взять его в руки и прикрепить на стену, после чего прикрутить. Гриппер инженерного борга взять душ не способен. 
Нет возможности построить конвейер. Нельзя взять в "лапку" рычаг или ленту.
Необходимо построить Протолат. В состав входят 2 бикера. Гриппер не может взять бикер.
В ходе различных работ было бы полезно иметь голобарьер атмосов, чтобы не допускать лишних утечек, понижения давления и температуры. Но в оснащении есть только никому не нужный в игре инжереный забор. 
_Им даже инженеры пользуются раз в 879 раундов, а борги даже не читали, что там такое._

Медицинский борг не способен установить импланты. Хотя это достаточно простые операции, что роботехи делают это у себя в гараже. Мало того, что нет привычного наркоза (но, допустим, обойдемся обезболом в шприце), так еще и гриппером нельзя поднять имплант, чтобы установить в тело.
Этот же медицинский борг не способен поднять конечность или механический протез, чтобы прикрепить к телу.
Фактически, инжереный борг имеет 100% точность при проведении операций, но часто вы встречаете борга, который эту операцию делает? Медицинский борг при всем своем арсенале и точности больше парамедик, чем хирург. Не логично.

### Добавить боргам больше возможностей для грипперов.
_Как вариант, улучшение (замена) гриппера, при развинии технологий в РнД, на вариант "побольше". 
Про улучшения ниже._

### Пересмотреть инструменты на всех типах боргов.
_Дело в том, что я играю на медицинском борге и на инженерном борге. В основном здесь затронуты именно они. В случае с другими модулями - спрашивайте прохожих либо задумывайтесь самостоятельно, потому что я просто не слишком хорошо знаком с их функциями._

### Возможно добавление новых апгрейдов для боргов.
_Например, замена лома и кусачек на улучшенный вариант - клешни. Замена горелки на эксперементальную, что заправляется самостоятельно. Замена отвертки и ключа на шуруповерт. Медицинскому тоже можно сделать возможность замены инструментов на улучшенные аналоги.
Апгрейды можно поставить на 6-7 уровень исследований, чтобы "имба" открылась не с первых 4 минут смены. Плюс сделать уверенную цену по ресурсам на создание._

_Что если добавить пласталь в инвентарь инженерного борга? Тогда он сможет строить укрепленные стены._

_Кто-нибудь за 20 лет пользовался matter decompiler? Я бы его вообще убрал. Осколки стекла тыкаются горелкой и становятся целым стеклом. Что в него еще насыпать - без понятия. Плюс я слышал, что кроме осколков стелка эта "мясорубка" ничего и не перерабатывает._

### Плюсы

Борги станут адекватнее, смогут выполнять больше работ, не выходя за рамки своих функций.

В случае с инструментами: Меньше жонглирования в инвентаре, выше скорость работы.

Медицинский борг сможет проводить больше различных операций (или вообще их проводить).

### Минусы

А зачем нам персонал? А почему одни борги на станции? Ну и кому я варил борщ?

Имба какая-то.

**Comment by PhantornRU** [comment]
1. За
2. Осталось только телевизор боргам приделать (как вариант боргу-помогатору) чтобы борги стали более функциональнее. И шапки им тоже нужно приделать.

**Comment by Honker9999999** [comment]
1. Против
2. Борги задумывались как помогаторы, не как заменители людей. Добавлять им возможность делать все и сразу... Ну... Не очень. А ещё фраза про самых унылых боргов прикол, учитывая что наши борги идентичны таковым на бее или ТГ за редким исключением.
P.s. Новые апгрейды уже и так голосовались. Не все, но большая часть.

**Comment by rebel228** [comment]
Я пробовал заниматься этим, но потом скрапнул просто потому что получилась имба.
Уже не помню всё на 100%, но на вскидку:
-медборгу для диализа полезно дать возможность брать бикер. Но если это ему разрешить, то получается что он еще становится и химиком. Хирург-парамедик-химик 3в1, это слишком.
-если дать возможность подбирать органы, то получается целый калейдоскоп проблем: внезапно борги получают возможность вырезать мозги и размножаться, собирая армию боргов в роботике.

Короче говоря наскоком проблемы не решить, а нужно проводить рефактор/редизайн дофига чего, держа в голове все аспекты и последствия.
Либо сфокусироваться на фиксе мини-проблем, вроде невозможности подобрать душ.

**Comment by VasilevAY** [comment]
![Uploading image.png…]()
