### ISSUE TITLE
Feat: Животные и парадайз

### ISSUE THREAD

**Issue by cnaper-dodo** [ss220-space/Paradise#119]
### Проблема

Животные-на парадайзе насколько мне известно,у животных меньше всего прав и возможностей(даже на тг где за них можно поиграть только через пинпние админа,возможностей больше).Так почему бы не улучшить этот компонент,с учётом того что в раунде по 160 человек и цивилианом не каждому хочет становиться

### Решение

Добавить худ одежды а так же слоты-по аналогу взять как у големов,но у каждого животного будут свои слоты и их количество.Так же добавить им худ руки-размер предмета и количество рук будут варьироваться в зависимости от животного
Примеры:
Иан-1 рука в виде пасти,в ней может нести большую часть предметов,но пользоваться может только картой и оружием ближнего боя(нести может и аптечки,и коды нюки и тп
Слоты под одежду-голова под шлем,глаза для очков,живот для Ригов/бронежилетов,спина для рюкзака,балкона с кислородом.Так же он может будет сам снимать вещи и убирать в рюкзак,если на него повесят,но вот одень на него вещи сможет только персонал.
Краб-слот под шлем,2 руки для небольших предметов
Поли- только 2 руки под небольшие предметы
Мопс-аналогично иану
Лиса-аналогично иану
Собака РД-аналогично капитану
Свинья-практически как у Иана,но без слота под живот.
Так же животные могут будут ускориться на небольшой промежуток времени,чтобы убежать от лпастности(очень высокая скорость).
Так же им добавить слоты для айди карты 

### Плюсы

-Весело
-у животных будет свое рп
-Иан во время нюки будет бегать с диском
-помощь экипажу

### Минусы

-кодинг
-неродивые люди будут их убивать
-кому то они возможно  будут мешать

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184349970-6de6d6bc-99a5-477c-b50f-6ea1671e31d3.png)
