### ISSUE TITLE
Feat: Привязка новых боргов к ИИ только в том секторе, где стоит это ИИ

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#120]
### Проблема

Когда игроки делают боргов не на станции Кербероса, не важно связаны ли они с НТ или нет - идёт привязка к ИИ на Керберосе. Это никак не стыкуется, но борги всё равно привязываются. И с этим так же борятся админы когда есть какое-то дело с респавном борга.

### Решение

Сделать привязку боргов к ИИ только если они были собраны в секторе с ИИ

### Плюсы

Не будет конфузов когда сделали борга на шатле големов, или на тете или ещё где, а борг из-за законов уехал искать Керберос вопреки любой логике, по-скольку он привязан к ИИ. Плюсом будет то, что если ИИ был, опять же, взломан, то он не убьёт собраших его членов экипажа их шатла/станции сидя в другом секторе от Кербероса. Так же, как я понял, это нужно и админам, поэтому идёт ещё больше толку если это нововведение сделают на сборке. 

### Минусы

Без понятия есть ли таковые

**Comment by Honker9999999** [comment]
А как тогда должны работать привязка для боргов, что прибывают на станцию? Их явно не собрали тут. Ну, и плюсом, ещё до постройки борга можно отключить ему привязку, так что хрен знает.

**Comment by snipersir** [comment]
Всмысле те что прибывают на станцию? При старте раунда? Так там и так всё ясно: есть ИИ - есть привязка, нет ИИ - нет ИИ. Это обычное дело. Никак больше борги не могут прибыть на станцию. На старте раунда доступно 2 борга всего. Я не видел ни разу случаев что борг может прибыть на шатле посреди раунда. Не пойму в чём проблема

**Comment by mayorovp** [comment]
На шаттле прибытия борги прибывают часто, но проблема не в них.

Проблема в том, что аванпост шахтёров подконтролен ИИ и IC (поскольку является обособленной частью станции), и по механике (поскольку там есть камеры). И если какую-нибудь станцию "Тета" ещё можно отделить по номеру сектора, то големы находятся на том же самом Лаваленде что и шахтёры.

**Comment by snipersir** [comment]
Ну как я понял, этот кусок планеты, Лаваленда, арендован корпорацией для работ, или выкуплен. А то что тут за тысячи лет, до НТ на лаваленде, у многих нпс начинается история их возникновения на этом куске планеты, теория того, что они могли тут появиться за долго до НТ, почему-то забыли. Не приземлились же они на лаваленд без ведома НТ. Всё таки их территория работ. Иначе бы про них было известно заранее.

Плюсом, ИИ контролирует только электроприборы вроде АПЦ, консолек, алармов, шлюзы. И на самом аванпосту нет компьютеров как таковых для работы с чем-то серьёзным. Просто управление дверями и светом. Ну и реле для радиосвязи стоит. И всё. По логике синхронизация с ИИ происходит либо там где стоит специальная аппаратура для этого дела, либо где стоит само ИИ.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184349906-9befb2d9-fb85-4fc0-8941-7190929ec59d.png)
