### ISSUE TITLE
Bug: Очки после смерти не создают затемнение

### ISSUE THREAD

**Issue by Velikolepiae** [ss220-space/Paradise#121]
### Ckey

AlexRavenidze

### Описание бага

Начальные очки шахтера после смерти не создают тени из-за чего багаются текстуры

### Шаги воспроизведения

1.Надеть начальные очки шахтера (Optical Meson Scanner)
2.Умереть (В моем случае я умер от лавы на лаваленде, не знаю имеет ли значение)
3.Воскреснуть через дефиб

### Ожидаемое поведение

Начинает быть примерно такая картинка https://imgur.com/a/QWUFOT9

### Операционная система

Windows 10

### Версия клиента

514.1557

### Примерное время и дата

11.07.2021 00:30 МСК

**Comment by tizer7** [comment]
[https://github.com/ParadiseSS13/Paradise/pull/15192](url) решение?
