### ISSUE TITLE
Feat: добавить космических глистов 

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#122]
### Проблема

Теперь съев еду заражённую личинками глистов, член экипажа будет заражён одним из 3 видов космических глистов. Глисты будут развиваться от личинок до полноценных особей, проходя 3 этапа. Первые 2 этапа общие, а 3 у каждого вида свой:
1)Личинки - немного увеличивается скорость с которой голод наступает, ведь паразиты поедают поступающие нутрименты
2)Молодые особи - скорость наступления голода увеличена по сравнению с первой стадией, в чат начинает изредка писаться: "Вы чувствуете дискомфорт в области живота"
3)
3.1)Развивается малокровие, повреждается со временем печень
3.2)Время от времени заражённый задыхается, возможен паралич
3.3)Повреждение апендикса и желудка, капающий урон от токсинов
 

Паразитов можно выявить использовав body scaner
Избавиться от космических глистов можно, при помощи операции на живот "изъятие паразитов"

### Решение

Еда заражается личинками в нескольких случаях:
1)Её трогали грязными перчатками/руками
2)Лежала на тайле где была кровь
3)Еда была зараженна, через ввод личинок через шприц

Вид глистов будет определяться рандомно из 3 при попадание в организм.

Первая стадия развития идёт 5 минут, вторая стадия 10, а третья уже до излечения, либо навсегда

Также нужно сделать новую операция "изъятие червей" на живот и после неё человек избавляется от червей, но не от травм нанесёнными ими.

### Плюсы

Новые интересные ситуации с каплей хаоса, больше работы медикам

### Минусы

Надо кодить, больше работы медикам и куча ассистосов с глистами

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184350031-d5c12b75-e034-4fbb-944d-c641d8fc88aa.png)
