### ISSUE TITLE
Feat: Возможные мобы на рассмотрение и/или на ивенты

### ISSUE THREAD

**Issue by PhantornRU** [ss220-space/Paradise#123]
### Проблема

В списке мобов нашел некоторых мобов (да я дорвался до списка и готов постить кринжатину). 
Для разнообразия геймплея я предлагаю рассмотреть некоторых из них (знаю что возможно их убирали не просто так):

### Решение

Big Legion
Неплохо зайдет в качестве мегафауны и редкого моба как тендрил.
Спавнит легионов поменьше и обладает весомым здоровьем и атакой. Но выглядит упорото
![image](https://user-images.githubusercontent.com/41479614/125184156-c41d7480-e25e-11eb-9873-623832889fec.png)
![image](https://user-images.githubusercontent.com/41479614/125184162-cb448280-e25e-11eb-9f2d-bffbf19bd6c5.png)

Death Squid
Мощный засранец способный ломать целые армированные стены.
Возможна замена тому же Space Dragon (которого тоже выпилили).
![image](https://user-images.githubusercontent.com/41479614/125184218-486ff780-e25f-11eb-9d43-1216cab66432.png)
![image](https://user-images.githubusercontent.com/41479614/125184221-4dcd4200-e25f-11eb-94de-b8c1ab50e702.png)

Пингвин с самбрерро.
Клоуну срочно нужен такой.
![image](https://user-images.githubusercontent.com/41479614/125184324-01363680-e260-11eb-955c-683429c7b50e.png)
![image](https://user-images.githubusercontent.com/41479614/125184328-0bf0cb80-e260-11eb-8542-853fbe1545f1.png)

Черт (Имп)
Дать возможность священнику-антагу призывать сотониских бесов?
![image](https://user-images.githubusercontent.com/41479614/125184358-52dec100-e260-11eb-8ad5-ce3b08c568b9.png)
![image](https://user-images.githubusercontent.com/41479614/125184361-57a37500-e260-11eb-840c-5e641fad0322.png)

### Плюсы

Больше мобов

### Минусы

Их придется дорабатывать?

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184350075-4ebae3d1-ef7a-4fe4-93fe-3a5d436a55ec.png)
