### ISSUE TITLE
Feat: 

### ISSUE THREAD

**Issue by DarkShad379** [ss220-space/Paradise#124]
### Проблема

ИИ не может посылать запросы на цк самостоятельно(с консоли можно, но там непонятны условия доступности, не всегда разрешается). Бывают ситуации когда синдикат захватил командование,главы умерли от пауков при валидханте или станцию доедает блоб при выключенном электричестве.  ИИ с паком законов крюзимова смотря на то как станция доживает последние часы, не может даже сообщить на ЦК с запросом на ЕРТ.

### Решение

Добавить отдельную кнопку в AI commands - Send message Centcom с КД как на консоли. 

### Плюсы

В случае уничтожения консолей, смерти глав, или иных ситуаций ИИшка сможет вызвать помощь.
Когда главы пинают щлены, можно сделать запрос на ЦК с вызовом агентов Душ и Нилла. 

### Минусы

ЦК придется слушать еще и запросы ИИ.

**Comment by semoro** [comment]
Заполните название

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184350435-b2e9ed04-0f67-4180-b2ac-5059e5efa14f.png)
