### ISSUE TITLE
Feat: Ребаланс тазеров и станбатонов/продов. Смещение вектора геймплея.

### ISSUE THREAD

**Issue by PhantornRU** [ss220-space/Paradise#125]
### Проблема

Нередко было слышно что вся игра связывается на том, кто кого быстрее успеет жахнуть палкой по горбу или выстрелить с тазера. От того самое сильное оружие является не гранатометный лаунчер, и не даже борговская мультипушка. А тазер и станбатон.

### Решение

Примеры переработки:
Пускай тазер не тазерит мгновенно, а снимает примерно 60% выносливости. КД у тайзера уменьшится в таком случае.
Станбатон же при ударе вполне легально может снимать 80% выносливости.
Станпрод же усредненно 70%.
Дизейблер оставить таким какой он есть.

Также ввести в игру улучшенный станбатон и улучшенный тайзер, которые и будут мгновенно тазерить и станбатонить. 

Я даже готов заняться кодингом и спрайтингом всех этих вещей, если оно пройдет предложку.

Также сделать зависимость от надетой брони. Чем тяжелее и закрытее броня надета, тем соответственнее меньше выносливости будет сниматься. Так, боевые риги будут больше всего выдерживать тазера, когда обычные риги будут менее устойчивы, а различные куртки и халатики вовсе не иметь резиста.
Соответственно станпрод и тайзер могут дальше держать упавшего человека без выносливости как и раньше, но предстоит сделать на пару ударов и выстрелов больше. Чем крупнее цель, тем предстоит больше выстрелов и ударов.

### Плюсы

- Перестрелки станут перестрелками, а не игрой в кто кого кого перетазерит и перестанит.
- Не будет абсурдных ситуаций где элитный оперативник нюк отряда, высший вампир, продвинутый предатель или полностью облаченный в броню СБшник(да и просто СБшник) будут ложиться от одного удара станпрода/станбатона и заканчивать на этом всё взаимодействия с претендентом на поимку.
- Эши получат защиту от СБшников и боргов-СБшников которые вырезают их одним только тазером и станбатоном.
- Фора антагам на ранних этапах игры до исследований РНД.
- Антаги выдохнут и смогут действительно антажить. У них появятся шансы перед падением совершить какое-либо действие в начале игры.
- У Вардена и СБ появится новое развлечение выбивать улучшенные станбатоны и тазера у РНД помимо их любимых имплантов.
- Дизейблер станет полезнее, так как будет снимать выносливость как и прежде игнорируя броню, да еще и сквозь стекла.

### Минусы

- СБ предстоит больше рассчитывать на свою численность, чем тазера и станбатоны.
- Антагам предстоит рассчитывать на другие методы, а не полагаться целиком и полностью станпроды и украденные станбатоны. Предстоит изъебнуться и ударить жертву минимум 2 раза чтобы положить.
- В среднем предстоит 2 выстрела тазера и 2 удара станбатона. Это нужно делать целых 2 и более кликов вместо одного!
- Из-за снятия выносливости тайзером и станбатоном, жертва успеет сделать пару шагов перед тем как в неё повторно выстрелят или ударит.
- Смещение геймплея в сторону более затяжных поимок, перестрелок, переговоров, так как жертва перед не пернаментным станбатоном и тайзером может успеть совершить действие или даже застанбатонить в ответ, если она оказалась опаснее.
- Нытье робастов

**Comment by HMBGERDO** [comment]
весь билд парадиза построен на станах и сопротивлениях стану. У элитного оперативника есть адреналин имплант, у высшего вампира - абилка, позволяющая ему встать, у предателя - имплант. Эши - племя. Замени тазер на стан - ничего глобально не изменится - также будут сосать. Антаги выдохнут и смогут антажить? А ты знаешь, кто использует станы в основном? СБ и антаги. И не для того, чтобы заробастить друг друга, а чтобы например, похитить свою цель. Перестрелки и сейчас могут быть именно перестрелками, а не ловушкой на стан, возьми на нюкере щит энергетический и перестреливайся, никто тебя тазером не застанит. Двигайся правильно и тоже стреляйся. Никто не мешает это делать. 

Если есть желание поиграть без "этих йобанных имбалансных станов" - вам на ТГ, там станы работают иначе, и в основном цель - стамина. Тут же пол игры висит на станах. Если это перерабатывать - нужно ОЧЕНЬ МНОГО ЧЕГО продумать.

**Comment by PhantornRU** [comment]
В том-то и дело что сколько наблюдаю и сам участвую. Вся игра останавливается на станах. Я понимаю что "не нравится не ешь". Но мне нравится сам проект, но не нравится данный ряд систем. Если найдется поддержка в нём - я буду его перерабатывать с другими разработчиками которые и помогут в балансе и советах.
Но вектор будет тот же - сделать упор на фору в начале игры, взаимодействия СБ с РНД, кооперативные отлавливания для большей успешности.

Не нужно закрывать на это глаза и говорить что билд держится на станах. Он держится совсем не на станах. А вот перестрелки - вполне на них. И от того что где-то сделано на выносливости, а тут на станах, не означает что эту самую выносливость стоит игнорировать.

**Comment by DetectiveEnotsky** [comment]
1. Против.
2. В чём тогда смысл дохуишных реагентов, снижающих время стана и имплантов?
Ты рушишь целую отрасль механик. Да и к тому же, так у всех, почему у нас быть не должно? С этим все согласны, кроме тебя, который видимо пытается, НУ ХОТЬ ЧТО-НИБУДЬ, НУ ПОМЕНЯТЬ.
Опять же, [не нужон](https://tenor.com/view/why-disappointment-stress-depression-gif-12154856)

**Comment by FlyingFloor** [comment]
1. Против.
2. Что ударило в голову людям в последнее время? Мы реально хотим занерфить СБ до уровня "нельзя ничего делать, пока не включен эпсилон"? Я напомню, что кроме перечисленного есть ещё два грузовика способностей антагов, которые дают инстастан. Я смотрю на предложения Пупса и не понимаю: он хочет добиться автопобеды антагов на 1й минуте раунда? Не вижу никаких причин реализовывать это предложение. Так построена боевка на сервере. И её нужно либо полностью перерабатывать, либо не пытаться ломать баланс в сторону антагов (почти каждый из который имеет инстастан).

**Comment by PhantornRU** [comment]
1. За.
2. Сам написал, сам проголосовал и пытаюсь найти себе проблем на задницу в практике по написанию кода (дайте мне уже написать мой гештальт дион)

**Comment by VictorSocks** [comment]
1. Против
2. Боевика Билла основана на станах, против него существует большое количество разных вещей таких как: адреналин, метамфетамин да даже просто уворот от выстрела тазера. Понимаю, что анробасты ноют из-за этого, но такова боевка, если ее менять, то менять ее всю, тобишь тот же адреналин и мет и так далее.

**Comment by Iranimakq** [comment]
1. Против.
2. У антагов есть куча абилок, в том числе инстастаны. У сб абилок нет.
У антагов есть абилки позволяющие снимать с себя стан. У сб только под имплантом ЦНС и то, это просто уменьшение времени.
Тазер и станбатон - критически важное оружие в руках офицера, от которого зависит его жизнь. Которое также может работать и против него самого, если он выронил батон/взять обычный тазер/не авторизовал сибил
Это изменение не нужно. Боевая система стоит уже долгое время. а как говорят классики : "Работает — не трожь!".
Я понимаю что сейчас идёт тенденция гнёта и нерфа СБ из-за наплыва нытиков-анробастов на антагах. Но эта предложка уже крайность какая-то.
Если уж чешется причинное место занёрфить тазера, то пусть хардсьюты и риги дают резист от них. Но станбатоны трогать - грех.

**Comment by AttHawk** [comment]
1. За
2. Как и написал ПУПС абсурдность нашей боевки в том что монтированный на меха лазер слабее раундстартового доминатора по причине: первый застанил - ты на коне. То что билд сейчас основан на станах не значит что это все высечено на стене из админстали и его нельзя поменять. Я чувствую что это будет очень проблемно забалансить и возможно тяжело кодить, попахивает крайне тяжелым коммитом который в соло не сделать даже, но явно нужно двигаться в этом направлении, это сделает геймплей гораздо более интересным.

**Comment by zombie288** [comment]
1. Против
2. Полностью всеми руками против, потому что парашиза крутиться вокруг того, кто кого быстрее застанит, а у каждого антага есть возможность облегчить/полностью выйти из стана (если они захотят тратить на это ресурсы).

**Comment by Sykybekk** [comment]
1. За
2. Всеми руками за. Моментальные станы это раковая опухоль всей боёвки парашизы, ведь именно эта штука зачастую ущемляет все остальные аспекты этого направления билда. Ведь по факту сейчас зачем использовать летал, если можно с одного попадания/удара обезвредить противника и выйграть файт. Да на сервере сделаны специально абилки и характеристики против станов, но это можно поменять.

**Comment by AnImLoVeR** [comment]
1. За(Но с нюансами, в ином случае против)
2. Давайте так, действительно, система стана на парадайзе действительно убийственная, упал ничком и ничего не можешь сделать. Однако же, эта раковая опухоль не может быть побита в данных условиях для антагонистов. Давайте чисто теоретически представим, а что же делать, если ты антагонист-инженер в начале раунда и у тебя цель стоит прямо перед тобой? Правильно, делать станпрод, тащить в техи, убивать, выбрасывать в космос. А как это будет выглядеть теперь? Первый удар(похуй, человек открывает рацию и начинает орать, что его ебут). Второй удар(упал, написал сообщение, только теперь с него начали тянуть наушник). Собственно, вот и обрезали легально антагонистов, потому что раскрыть теперь становится на целых 5-8 секунд легче. Как с этим бороться? Дать возможность моментально снять наушник. Либо запретить говорить после второго удара станпродом(то есть дать некий эффект немоты). Да и вообще, почему, на самом деле, для нас это не очень актуально. Ну во-первых по той причине, что система эта, как ни крути, будет спиливаться с ТГ. А на ТГ в этом плане есть куча возможностей. Во-первых там не система двух ударов, там система одного удара и человек спустя 3-5 секунд падает-таки на пол. И при этом он еще может ползать и чтобы перебить ползание нужно дать станпродом еще раз в ебало. Короче, система спорная, но попробовать можно. Главное, чтобы вы этим своим действом не убили всех антагов, потому что это будет нереальная боль. Итак пока душно, а таким образом будет вообще "Туши свет, бросай гранату".

**Comment by Jordanstolethepreciousslam** [comment]
> 1. За(Но с нюансами, в ином случае против)
> 2. Давайте так, действительно, система стана на парадайзе действительно убийственная, упал ничком и ничего не можешь сделать. Однако же, эта раковая опухоль не может быть побита в данных условиях для антагонистов. Давайте чисто теоретически представим, а что же делать, если ты антагонист-инженер в начале раунда и у тебя цель стоит прямо перед тобой? Правильно, делать станпрод, тащить в техи, убивать, выбрасывать в космос. А как это будет выглядеть теперь? Первый удар(похуй, человек открывает рацию и начинает орать, что его ебут). Второй удар(упал, написал сообщение, только теперь с него начали тянуть наушник). Собственно, вот и обрезали легально антагонистов, потому что раскрыть теперь становится на целых 5-8 секунд легче. Как с этим бороться? Дать возможность моментально снять наушник. Либо запретить говорить после второго удара станпродом(то есть дать некий эффект немоты). Да и вообще, почему, на самом деле, для нас это не очень актуально. Ну во-первых по той причине, что система эта, как ни крути, будет спиливаться с ТГ. А на ТГ в этом плане есть куча возможностей. Во-первых там не система двух ударов, там система одного удара и человек спустя 3-5 секунд падает-таки на пол. И при этом он еще может ползать и чтобы перебить ползание нужно дать станпродом еще раз в ебало. Короче, система спорная, но попробовать можно. Главное, чтобы вы этим своим действом не убили всех антагов, потому что это будет нереальная боль. Итак пока душно, а таким образом будет вообще "Туши свет, бросай гранату".

ЕTVG ajyfhbr cnjbn 4 ТК и вырубает наушник за удар. Если что.

**Comment by Lenerald** [comment]
1. За
2. Я за данное предложение только в случае если это получится нормально реализовать, в чем я сомневаюсь учитывая количество необходимых изменений. Баланс слишком сильно пострадает так-же как и антаги зависящие от станпрода. Если и делать такое изменение то нужно давать новые возможности антагонистам.

**Comment by PhantornRU** [comment]
> 1. За
> 2. Я за данное предложение только в случае если это получится нормально реализовать, в чем я сомневаюсь учитывая количество необходимых изменений. Баланс слишком сильно пострадает так-же как и антаги зависящие от станпрода. Если и делать такое изменение то нужно давать новые возможности антагонистам.

Так они есть, но ими никто не пользуется, потому что станпрод или украденный станбатон эффективнее.
Сонная ручка, усыпляющий шприцемет и прочее прочее. Многими вещами антагонисты из-за станподов и станпродов просто не пользуются. Они гораздо сильнее разбавляют геймплей как и со стороны СБ, а не типичное "подбежал, ударил станпродом, забил насмерть, цель выполнена".

**Comment by DetectiveEnotsky** [comment]
> > 1. За
> > 2. Я за данное предложение только в случае если это получится нормально реализовать, в чем я сомневаюсь учитывая количество необходимых изменений. Баланс слишком сильно пострадает так-же как и антаги зависящие от станпрода. Если и делать такое изменение то нужно давать новые возможности антагонистам.
> 
> Так они есть, но ими никто не пользуется, потому что станпрод или украденный станбатон эффективнее.
> Сонная ручка, усыпляющий шприцемет и прочее прочее. Многими вещами антагонисты из-за станподов и станпродов просто не пользуются. Они гораздо сильнее разбавляют геймплей как и со стороны СБ, а не типичное "подбежал, ударил станпродом, забил насмерть, цель выполнена".

Я тебе так скажу. Ручка\шприцемет и прочее и прочее имеют другие предназначения. В первую очередь ручка - для стелса. Она не издаёт звуков и в чат пишется маленькое сообщение после чего тебя кидает в сон. И ты не можешь говорить. Другое дело станбатон. Издаёт звук, цель сразу орёт в радио и т. д.

**Comment by PhantornRU** [comment]
> > > 1. За
> > > 2. Я за данное предложение только в случае если это получится нормально реализовать, в чем я сомневаюсь учитывая количество необходимых изменений. Баланс слишком сильно пострадает так-же как и антаги зависящие от станпрода. Если и делать такое изменение то нужно давать новые возможности антагонистам.
> > 
> > 
> > Так они есть, но ими никто не пользуется, потому что станпрод или украденный станбатон эффективнее.
> > Сонная ручка, усыпляющий шприцемет и прочее прочее. Многими вещами антагонисты из-за станподов и станпродов просто не пользуются. Они гораздо сильнее разбавляют геймплей как и со стороны СБ, а не типичное "подбежал, ударил станпродом, забил насмерть, цель выполнена".
> 
> Я тебе так скажу. Ручка\шприцемет и прочее и прочее имеют другие предназначения. В первую очередь ручка - для стелса. Она не издаёт звуков и в чат пишется маленькое сообщение после чего тебя кидает в сон. И ты не можешь говорить. Другое дело станбатон. Издаёт звук, цель сразу орёт в радио и т. д.

Если цель успевает орать, то в чем разница проорет она на 2 секунды дольше или нет? Стелс для антагов из-за имбовости станбатонов вещь сложная. Один косяк и ты выходишь из игры. А если у тебя есть станбатон, то тебе и стелсить практически не надо. Ударил, утащил. Всё.

**Comment by HMBGERDO** [comment]
Ты очень сильно не прав, если считаешь, что станбатон позволяет тебе не стелсить на антаге. В текущих реалиях СБ реагирует очень быстро и зачастую очень болезненно для антага, поэтому использовать батон можно только в связке со снятием наушника. Касательно слипипена и шприцемета - их используют. Но слипипен имеет всего 2 заряда, его просто так не поиспользуешь обычно, кетамин нельзя достать, чтобы перезарядить её. Шприцемет - опять же нужно долго подготавливать, но если сделаешь - он очень полезен, и его используют. Просто у нас сейчас почти все новички, которые ничего не знают и не умеют. Касательно СБ - тоже стан не решает обычно. Все антаги, как я уже писал - имеют какую-либо защиту от стана. Ну и опять же тупая робастость позволяет уворачиваться от тазера спокойно.

**Comment by PhantornRU** [comment]
> Ты очень сильно не прав, если считаешь, что станбатон позволяет тебе не стелсить на антаге. В текущих реалиях СБ реагирует очень быстро и зачастую очень болезненно для антага, поэтому использовать батон можно только в связке со снятием наушника. Касательно слипипена и шприцемета - их используют. Но слипипен имеет всего 2 заряда, его просто так не поиспользуешь обычно, кетамин нельзя достать, чтобы перезарядить её. Шприцемет - опять же нужно долго подготавливать, но если сделаешь - он очень полезен, и его используют. Просто у нас сейчас почти все новички, которые ничего не знают и не умеют. Касательно СБ - тоже стан не решает обычно. Все антаги, как я уже писал - имеют какую-либо защиту от стана. Ну и опять же тупая робастость позволяет уворачиваться от тазера спокойно.

Я не говорю что он позволяет не стелсить, я говорю что станбатон позволяет перекрыть слишком много возможностей только одной своей механикой. Потому что это проще.

**Comment by DetectiveEnotsky** [comment]
> > Ты очень сильно не прав, если считаешь, что станбатон позволяет тебе не стелсить на антаге. В текущих реалиях СБ реагирует очень быстро и зачастую очень болезненно для антага, поэтому использовать батон можно только в связке со снятием наушника. Касательно слипипена и шприцемета - их используют. Но слипипен имеет всего 2 заряда, его просто так не поиспользуешь обычно, кетамин нельзя достать, чтобы перезарядить её. Шприцемет - опять же нужно долго подготавливать, но если сделаешь - он очень полезен, и его используют. Просто у нас сейчас почти все новички, которые ничего не знают и не умеют. Касательно СБ - тоже стан не решает обычно. Все антаги, как я уже писал - имеют какую-либо защиту от стана. Ну и опять же тупая робастость позволяет уворачиваться от тазера спокойно.
> 
> Я не говорю что он позволяет не стелсить, я говорю что станбатон позволяет перекрыть слишком много возможностей только одной своей механикой. Потому что это проще.

Пистолет тоже может перекрыть много возможностей своей механикой. Он может стрелять .-.

**Comment by Bizzonium** [comment]
#161 может быть связано

**Comment by Zigamus** [comment]
> #161 может быть связано

Не может, с первого взгляда видно, что в ПРе и ищью разные изменения с разными параметрами.

**Comment by PhantornRU** [comment]
> > #161 может быть связано
> 
> Не может, с первого взгляда видно, что в ПРе и ищью разные изменения с разными параметрами.

Тем не менее я лучше отдам предпочтения твоему, чем своему. Оно гораздо более проработаннее и рабочее.
https://github.com/ss220-space/Paradise/pull/161

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/161
![image](https://user-images.githubusercontent.com/98010665/184350532-fdd70d4e-f95d-4d42-8b89-bbb42128f732.png)
