### ISSUE TITLE
Feat: Увеличение кол-ва готовых форм в принтере 

### ISSUE THREAD

**Issue by PoTapkam** [ss220-space/Paradise#126]
### Проблема

У нас нету множества форм в принтерах, но существует множество форм которые есть на вике и которые необходимы

### Решение

Добавить с вики готовые формы в принтер, чтобы они были и их можно было распечатать. Вот статья с вики https://ss220.space/wiki/index.php/Example_Paperwork

### Плюсы

Народу не потребуется писать от руки в свободной форме или лезти на вике искать или кому то не придется объяснять где взять, АВД не будет душить, новичкам не придется объяснять где взять форму и как ее заполнить. 

### Минусы

Ну их практически нет, кроме того, что придется убить на это некоторое количество времени.

**Comment by PhantornRU** [comment]
1. За
2. Не придется отсылать ассистентов за бланками роботизации.

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/506
