### ISSUE TITLE
Feat: статусные логи

### ISSUE THREAD

**Issue by Moraetea** [ss220-space/Paradise#127]
### Проблема

Будет хорошо и приятно добавить оповещение изменения статуса у персонала через худ или комп в канал к СБ

### Решение

  Принцип примерно такой же как и в логах при заключении в тюряжку.  Можно сделать по форме: [Время на станции] *имя*(должность) изменил у *имя*(должность)  статус на  Arrest, по причине: *причина*.  Так же по аналогии с тюремными логами нужно чтобы они печатались в комнате у хоса. 

### Плюсы

Больше бумаг для подтирания жеппы у хоса.  Вырастет общая эффективность и организованность,  осведомленность СБ :KEKW: Будет легче пресекать щиткурство. 

### Минусы

Пердатели теперь не смогут тихонечко снимать с себя аресты при помощи распечатанных худов.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184350656-261bafb9-6569-4867-8fc6-119342d63f0a.png)
