### ISSUE TITLE
Bug: Хвосты воксов, которые лишены цвета

### ISSUE THREAD

**Issue by DetectiveEnotsky** [ss220-space/Paradise#128]
### Ckey

DanZAMOL

### Описание бага

При выборе хвоста вокса, у которого настраивается цвет, а именно: 

- Vox Tail Band
- Vox Tail Stripe
- Vox Tail Tip

Вне зависимости от выбранного цвета, при заходе в раунд автоматически будет выбран чёрный. Просьба пофиксить данную проблему, что бы у нас появились красочные хвосты, но не продолжили существовать чёрные.

### Шаги воспроизведения

1. Выбрать Вокса.
2. Выбрать любой вариант хвоста, исключая None.
3. Настроить любой цвет кроме чёрного.
4. Зайти в раунд и убедиться, что тот изменился на чёрный.

### Ожидаемое поведение

Хвост, при заходе в игру, должен был быть окрашен в тот цвет, который мы выбрали.

### Операционная система

Windows 10

### Версия клиента

513.1542

### Примерное время и дата

Постоянно и каждый раз

**Comment by OrangeBirdx** [comment]
Плюсую,у Йакаххачи такая же проблема,не важно какой цвет ты ставишь - всегда будет черная разметка

**Comment by Honker9999999** [comment]
Не баг а фича. Воксы против ЛГБТ и не-натуральности, поэтому цвета не работают.

**Comment by Miamicoeur** [comment]
Мне нужен, мой ЦВЕТНОЙ ХВОСТ, дайте его мне..
