### ISSUE TITLE
Верните чередование реагентов в улучшенном химдиспенсоре

### ISSUE THREAD

**Issue by OrangeBirdx** [ss220-space/Paradise#129]
### Проблема

Вернуть для удобства чередование реагентов в химдиспенсере,ранее дополнительные реагенты находились снизу,теперь они упорядочены по алфавиту и порядок сбивается,постоянно адаптироваться проблемно.

### Решение

Вернуть добавленные реагенты с улучшения химдиспенсера в самый низ,как это было ранее

### Плюсы

Не будет путаницы и головных болей у химработников

### Минусы

Возможно обратно исправлять уже проделанную работу.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184351278-240edc23-4611-4038-8859-cc244230f3bd.png)
