### ISSUE TITLE
Feat: Улучшение инструментария инженерного киборга

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#130]
### Проблема

1. Инженерный борг не может при ремонте/строительстве банально установить лампы в патроны, не таская их по одной из проталата.
2. Инженерный борг не имеет возможности устанавливать укрепленные плазма стекла, магнитный держатель не может его ухватить. Не может брать и пласталь, что снижает количество построек, что может сделать борг

### Решение

1. Добавить боргу Light Replacer
2. Добавить возможность хватать захватом различные материалы(пласталь, стекло, укрепленное стекло)

### Плюсы

1. Инженерные борги станут более полезными и на станции будет светлее
2. Инженерные борги смогут устанавливать большее количество конструкций

### Минусы

1. Уборщикам будет меньше работы
2. Борги будут отбирать работу кожанных мешков

**Comment by Honker9999999** [comment]
1. Для этого есть дрон.
2. Это особенность боргов, дабы они не могли полностью заменить инжей или людей. Смысл это убирать я не вижу.
Поэтому в текущем виде против.

**Comment by rebel228** [comment]
1. Лампы меняет киборг-уборщик.
2. Инженерный борг по задумке не улучшеная версия инженера.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184350718-165ef918-cd4f-4c62-bcb9-0c6477ec8ff5.png)
