### ISSUE TITLE
Bug: Дюп солнечных панелей

### ISSUE THREAD

**Issue by VentelR** [ss220-space/Paradise#132]
### Ckey

VentelR

### Описание бага

Дюп (или фича) при создании солнечных панелей. 

### Шаги воспроизведения

Если взять основание соляров (solar panel assembly) которое "плюсик" в руку, ткнуть в него стеклом из другой руки - на полу появится готовая солнечная панель, которую не нужно прикручивать, на данном этапе она уже функциональна. Затем нужно положить "плюсик" на пол, поднять, и повторить. Собранные таким образом панели работают, но при разборе на дают материалов. Таким образом на создание новых солнечных панелей расходуется исключительно стекло, без самих оснований.

### Ожидаемое поведение

При создании солнечных панелей должны расходоваться все материалы.

### Дополнительная информация

Хотелось бы получить официальный ответ, можно ли использовать данный метод для создания новых солнечных панелей.

### Операционная система

win10

### Версия клиента

5.0Public 513.1542

### Примерное время и дата

12:40 МСК 13.07.21

**Comment by semoro** [comment]
В данный момент solar panel assembly нельзя брать в руки 
Баг видимо с сервера EX

**Comment by VentelR** [comment]
> В данный момент solar panel assembly нельзя брать в руки
> Баг видимо с сервера EX

Да, верно, прошу прощения, не нашел где это указать.

**Comment by botka4aet** [comment]
solar panel assembly не берется в руки - это с оффа парадайза.
Баг все еще актуален? Не могу повторить.

**Comment by Bizzonium** [comment]
@botka4aet пару месяцев назад Solar Panel Assembly сделали намного тяжелее, что их теперь только таскать можно, если я правильно помню

**Comment by Den109G** [comment]
А это изменение перенесли на EX? Ошибка, как я понял, случилась именно на этом сервере.

**Comment by Bizzonium** [comment]
@Den109G многих коммитов на EX нет, там РВ заправляет билдом

**Comment by VasilevAY** [comment]
Вам к РВ
