### ISSUE TITLE
Feat:Мозг в Мехе и новая оболочка как из wolfstein.

### ISSUE THREAD

**Issue by Zombara** [ss220-space/Paradise#133]
### Проблема

Проблема: Проблема в том что мозг можно запихнуть лишь 1 киборга уже однобразие.

### Решение

Мое решение состоит в том. Чтобы мозг можно было запихнуть в все Мехы что существуют на paradise.

### Плюсы

Наконец будет возможность людям стать больше чем обычный киборг.

### Минусы

Минусов я не вижу.

**Comment by Den109G** [comment]
Уже можно так сделать. Мозг в ММИ, ММИ в меха. В итоге, мозг управляет мехом. Автоматом принимаем, так как ничего делать не нужно.

**Comment by Zigamus** [comment]
Так мми и так можно запихнуть в меха.

**Comment by VasilevAY** [comment]
https://user-images.githubusercontent.com/98010665/184348325-5335fc54-6d08-4ecb-8668-520e36ba86bf.png
