### ISSUE TITLE
Feat: нерф станбатона и тайзера

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#135]
### Проблема

На данный момент вся боёвка сводится к тому, чтобы тайзером или станбатоном за одно поподание оглушить оппонента и добить.  Дабы сделать игру более активной предлагаю занерфить тайзеры, буквально превращая их в дизейблеры, а те в свою очередь выпилить, а также занерфить станбатон до такого, чтобы потребовалось бы 3-4 удара для оглушения. Соответственно с этим ввести и броню с разной процентной защитой от станов

### Решение

Кодить

### Плюсы

Более активная боёвка

### Минусы

Кодить, усложнение жизни сб

**Comment by keIgaras** [comment]
весь билд парадиза построен на станах и сопротивлениях стану. У элитного оперативника есть адреналин имплант, у высшего вампира - абилка, позволяющая ему встать, у предателя - имплант. Эши - племя. Замени тазер на стан - ничего глобально не изменится - также будут сосать. Антаги выдохнут и смогут антажить? А ты знаешь, кто использует станы в основном? СБ и антаги. И не для того, чтобы заробастить друг друга, а чтобы например, похитить свою цель. Перестрелки и сейчас могут быть именно перестрелками, а не ловушкой на стан, возьми на нюкере щит энергетический и перестреливайся, никто тебя тазером не застанит. Двигайся правильно и тоже стреляйся. Никто не мешает это делать.
Касательно дизейблера - он и сейчас достаточно полезен. Просто многие вместо безопасного оглушения дизейблером - пытаются поймать на стан. Взять те же резиновые патроны - очень полезная вещь. А еще есть транквилизаторные, которые вообще иначе работают, и тоже ОЧЕНЬ полезны.

Если есть желание поиграть без "этих йобанных имбалансных станов" - вам на ТГ, там станы работают иначе, и в основном цель - стамина. Тут же пол игры висит на станах. Если это перерабатывать - нужно ОЧЕНЬ МНОГО ЧЕГО продумать.

**Comment by Sykybekk** [comment]
> весь билд парадиза построен на станах и сопротивлениях стану. У элитного оперативника есть адреналин имплант, у высшего вампира - абилка, позволяющая ему встать, у предателя - имплант. Эши - племя. Замени тазер на стан - ничего глобально не изменится - также будут сосать. Антаги выдохнут и смогут антажить? А ты знаешь, кто использует станы в основном? СБ и антаги. И не для того, чтобы заробастить друг друга, а чтобы например, похитить свою цель. Перестрелки и сейчас могут быть именно перестрелками, а не ловушкой на стан, возьми на нюкере щит энергетический и перестреливайся, никто тебя тазером не застанит. Двигайся правильно и тоже стреляйся. Никто не мешает это делать.
> Касательно дизейблера - он и сейчас достаточно полезен. Просто многие вместо безопасного оглушения дизейблером - пытаются поймать на стан. Взять те же резиновые патроны - очень полезная вещь. А еще есть транквилизаторные, которые вообще иначе работают, и тоже ОЧЕНЬ полезны.
> 
> Если есть желание поиграть без "этих йобанных имбалансных станов" - вам на ТГ, там станы работают иначе, и в основном цель - стамина. Тут же пол игры висит на станах. Если это перерабатывать - нужно ОЧЕНЬ МНОГО ЧЕГО продумать.

Продумаем, ничего страшного в этом нет. Если пара антагов имеют абилки, направленные против стана, это не значит, что весь сервер на этом стоит. В случае дизаблера и тайзер, то тогда просто убрать тайзер из пула эквипа до лучших времён. Станбатон можно и оставить. Но вот тайзер дико урезает пространство для летала, что ведёт к стогнации и дегродации этой сферы сервера. Именно поэтому нерф в сторону тайзера необходим

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/161
