### ISSUE TITLE
Feat: Сделать подбор кандидатов для обычных пауков террора на подобии Принцесс или иначе

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#138]
### Проблема

Сейчас работает режим спавна "кто успел тот и съел"(Click to control). Это жуткий кансер по следующим причинам:
- суицид-спавн в бриге/на мостике, в иных похожих местах;
- баганая кладка принцессы из-за которой 15 минут ресаются пауки
- баганая абилка принцессы кладки яиц (больше не способна делать кладку, ни рестарт, не реконнект не работают)
- нужно сделать 100к кликов по венте чтобы начать лезть в неё(в открытую), а по итогу либо слиться, либо залезть не в вентиляцию, а на тайл вентиляции (просто awesome багуля);
- слив пауков из-за асистух которые идут рашить живых не используя мозги/абилки/тактики
- необходимость использовать методы, вплоть до макроса, чтобы зайти за паука, ибо пинг и иные задержки убивают возможность зайти для других игроков у кого более плохое соединение по тем или иным причинам(сервер/провайдер/пинг/залагавший клиент и т.д.).
(половину списка проблем уйдёт следом в баг репорт)

### Решение

Сделать иной механизм, один из примеров:
- как у принцессы;
- как у свармера, в меню моб спавнера;
- вступать в обычную очередь не смотря на то есть или нет линги, так сказать на будущий рандомный спавн;
- дать возможность вставать в очередь на будущее за определенного паука.

Можно будет не спамить на месте вероятного сообщения "Click to control "

### Плюсы

У всех в очереди будет шанс зайти сыграть. Не нужно будет гореть из-за того что ты караулил и кликал 10к раз по Click to control, а по итогу получилось зайти с 15 попытки, реснуться на мостике при сб и кэпе и слиться за 5 секунд, добив себя токсичной вентиляцией после побега на low hp с мостика.

### Минусы

У кого низкий пинг будет небольшое расстройство по этому поводу, и то не факт.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184351317-18dbb352-bec8-4d18-b5d1-c14d8aa7179e.png)
