### ISSUE TITLE
Feat: Спавн Террор пауков вне "зон моментального уничтожения"

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#141]
### Проблема

Уже несколько игроков, даже на принцессах, в том числе и я сам, стали заложниками щитспавна. Принцесс заспавнило одну на мостике, другую в бриге. Меня за обычного паука заспавнило в камере брига... Если принцессы ещё и имели шанс убежать так как объявления об угрозе ещё не было и это застало всех на мостике в расплох, то спавн за красного паука в бриге обернулся моментальной смертью. Тоесть щитспавн убивает шанс на нормальную игру на нераундстартовом антаге. Если у неактивных свармеров есть неубиваемая капсула и можно дождаться определенного момента, то с пауками такое не пройдёт.

### Решение

Сделать специальные позиции для спавна, как с блобом или с любым иным предметом на карте. Чтобы пауков спавнило вне суицидальных зон вроде брига или мостика. Сделать их в максимально подходящих местах вроде публичных мест типа дорм, библиотеки, комнаты клоуна, в техах с вентиляцией или рядом с вентиляцией. Сделать спавнзоны в большом количестве. Хоть в спальне кэпа, нтр или хопа, но не в камере брига уж точно, особенно когда уже наступило объявление и все вооружены.

### Плюсы

Очевидные - игроки не будут уходить в тильт из-за своеобразного щитспавна-спавнкемпинга.

### Минусы

Нету?

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184351402-8800e0f3-0a23-49fa-b87a-eb8932892745.png)
