### ISSUE TITLE
Bug: ИИ и питание мехов

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#142]
### Ckey

Danefalt

### Описание бага

ИИ после перехода в мех, теряет питание при выходе из зоны с ЛКП, хотя должен питаться от меха.
https://prntscr.com/1b4dlrd

### Шаги воспроизведения

Входим в мех за ИИ
Выходим из зоны с питанием
Profit

### Ожидаемое поведение

Ничего. Все системы ИИ просто должны продолжать работу, потому что питание идёт от меха, а не от комнаты.

### Операционная система

Windows 10

### Версия клиента

514.1557

### Название сервера

WL

### Примерное время и дата

14.01.2021, 20:10 (По МСК)

**Comment by HMBGERDO** [comment]
А собственно, баг ли? У ИИ указано, нельзя покидать станцию, когда он в меха садится, логично что завязано на питании. Силиконы сосатб
