### ISSUE TITLE
Bug: Белый Террор паук не заражает животных кроме обезьяны

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#143]
### Ckey

Connar369

### Описание бага

Собственно, белый паук не впрыскивает яйца в животных которые не умирают с первого укуса. На вики пишет что он впрыскивает в жертву, т.е. в любую, включая животных. По факту кроме обезьяны и экипажа он никого не может заразить, не важно разумные они или нет.

### Шаги воспроизведения

Например, укусы на нейтральной рыбе в домрах или мелких ящерицах от евента не дают эффекта, животные чистые.

### Ожидаемое поведение

Судя по вики должно заражать всех. Конечно кроме машин и роботизированных существ.

### Дополнительная информация

Репорт сделан со слов Ленивый Инженер Dred700#4307 (дискорд), скей: dred700. ОС и версию клиента не спросил, на вид это подкачала механика игры, но если нужно будет - пинганите меня, либо его если это будет иметь значение, заполню до конца.

### Операционная система

Win 7 x64 Pro SP1

### Версия клиента

514.1554

### Название сервера

MAIN

### Примерное время и дата

ИД смены: 3072, ~время: 21:00 МСК ,15.07.21

**Comment by Honker9999999** [comment]
Не баг. Иначе можно было сделать сто пицот миллионов тыщ пауков из симпл мобов. Так и должно быть.

**Comment by snipersir** [comment]
А сделать в них меньше яиц, вплоть до одного и увеличенный раза в 5, хоть в 10 таймер до спавна, шанс что яйцо не сработает в спайдерлинга? Или это очень замороченно получится? 

Я ещё видел как сентиент мобы в наглую ходят группами бить пауков. Может быть для них сделать исключение? Чтобы разрывало тех кто был одарян зелькой сознания? Чтоб мало не показалось.
