### ISSUE TITLE
Играбельные нпс в лаваленде.

### ISSUE THREAD

**Issue by Zombara** [ss220-space/Paradise#144]
### Проблема

Есть такой момент когда все что можно у призраков забиты. И даже аборигенов нет. 

### Решение

Решение: Добавить возможность вселяться в НПС что находятся в лаваленде. Им можно сделать правила как и аборигенам.

### Плюсы

Разнообразие. Скучно гостам точно не будет.

### Минусы

Минус: Шахтерам, аборегенам придется не сладко с умными.

**Comment by Danefalt** [comment]
Не ну в теории это одна-две строчки кода. Так что там уже как выберут игроки.

**Comment by Zombara** [comment]
Ну-с. Когда там окончание прозойдет?

**Comment by Danefalt** [comment]
> Ну-с. Когда там окончание прозойдет?

Когда-нибудь.

**Comment by Zombara** [comment]
Все еще в силе.

**Comment by VasilevAY** [comment]
Тайпан
![image](https://user-images.githubusercontent.com/98010665/184351446-032ec208-dd79-4a8a-8a03-d08153e7d9d8.png)
