### ISSUE TITLE
Предложение по ивенту. "Все антаги"

### ISSUE THREAD

**Issue by ZoNeSRuS** [ss220-space/Paradise#145]
### Проблема

Да проблемы нет, просто хочу поделиться идеей

### Решение

Идея просто, все на станции кто не имеет МШ(А лучше что бы и с ним). Становятся антаганистами со своими целями. Причем спавнятся все и сразу. Триторы, генокрады, вампиры, тенеморфы, культ и другие. Ивент понятно что чисто фановый, и лучше что бы о нем не разглашалось, а он просто произошел, пусть все думают что это обычный раунд.

### Плюсы

Веселье и фан, антаги не будут задушены. Узнаем кто сильнее тенеморфы или культ в драке за техи. Смогут ли генокрады остановить малф ИИ, когда тот отрубит связь. Смогут ли вампиры противостоять нюке? И все это одновременно. Просто раунд полный хаоса и факапных ситуаций. 

### Минусы

При таких раскладах капитана и сб вырежут в первые 10 минут раунда. Хаос может выйти из под контроля и начнется тупой гриф.

**Comment by Danefalt** [comment]
Уже давно очень предлагали же?

**Comment by DayBreakerBrony** [comment]
это же типичный х20

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184352102-afe62749-fea4-4655-be5e-21c51d6a7beb.png)
