### ISSUE TITLE
Bug: Заблюренный рунчат

### ISSUE THREAD

**Issue by ratpielol** [ss220-space/Paradise#1476]
### Ckey

Ratpie

### Описание бага

После приобритения нового ноута при заходе на любой сервер, в том числе и на локальный, трудночитаемый рунчат. Всё остальное - чётко.

### Шаги воспроизведения

1. Иметь мой ноут.
2. Зайти на любой сервер.

### Ожидаемое поведение

Трудночитаемый рунчат.

### Дополнительная информация

Прилагаю скрин проблемы:
![изображение](https://user-images.githubusercontent.com/116360256/197199761-c013298d-dcd4-4f76-aac1-28b44641812e.png)

Что уже было сделанно мною, но не помогло:
- Менял сайз и скейлинг в самой игре
- Менял разрешение дисплея (1920х1080 стандарт)
- Выкрутил все настройки графики и четкости на максимум на dreamseaker.exe через настройки Intel-a
- Чистил кэш BYOND-a
- Переустановка BYOND-a
- Перепроверил язык системы (стоит русский)
- Обновил драйвера
- Перевел винду с домашней на про

### Операционная система

Windows 11 Pro

### Версия клиента

514.1585

### Название сервера

MAIN

### Примерное время и дата

05.08.22

**Comment by frikadeliSpaghetti** [comment]
@ratpielol Поменяй версию винды
