### ISSUE TITLE
Код Станции

### ISSUE THREAD

**Issue by Lenerald** [ss220-space/Paradise#148]
### Проблема

Капитаны в бесконечном множестве игр не волнуются по поводу текущего кода на станции и понижают его (или даже повышают) с опозданием, бывает, по 30 минут, хотя он может сильно портить жизнь обычным работягам (особенно по рп) или антагонистам.
Капитаны в принципе мало что делают в своем большинстве, даже если речь идет об взаимодействии с командой станции. Капитан скорее прибежит в допросную посмотреть на пойманного преступника чем будет беспокоиться о том, какой код на станции, я считаю это не правильно и должно быть одной из ключевых обязанностей Капитана.

### Решение

Сделать понижение кода Капитаном важной частью его существования и придумать наказание за изменение кода (к примеру с красного на синий) с опозданиями в 5, 10, 15 минут после нейтрализации угроз ради которых он и был повышен.
К примеру наказания можно увольнять таких Капитанов офицерами ЦК.

### Плюсы

Код будет понижен вовремя, больше дыхания для не раскрытых Службой Безопасности антагов.
Код будет ощущаться немного более важной частью СРП и станции.

### Минусы

Нужно засекать 15 минут на Капитане.
Нужно придумать наказание из за которого это правило не будут нарушать.

**Comment by Sykybekk** [comment]
Мммм, а если об устранение антага ложная инфа? А если не все антаги из активных убиты? А если об устранение вообще не сообщили? А если непонятно устранена ли угроза?

**Comment by keIgaras** [comment]
> Мммм, а если об устранение антага ложная инфа? А если не все антаги из активных убиты? А если об устранение вообще не сообщили? А если непонятно устранена ли угроза?

То это не имеет никакой разницы, 15 минут прошло, антаг ничего не сдалал, понижается код, так и написано в срп кодов.

**Comment by tizer7** [comment]
Это конечно интересно, но код билда, то тут причем? я вижу решение по этой предложке, только изменение срп капитана, а это изменение вики. Тут только предложки связанные с изменением кода, файлов игры.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184352298-1befd5dd-f0f3-4497-9b13-cf7e3634c626.png)
