### ISSUE TITLE
Проблема с отыгрышем Службы Безопасности

### ISSUE THREAD

**Issue by Lenerald** [ss220-space/Paradise#149]
### Проблема

Проблема уже давно всем ясна, хочу предложить обозначить рамки в правилах более чётко, что возможно поможет в данной ситуации.
Под проблемой я подразумеваю: 24/7 открытые шкафчики в техах, ожидание антагонистов на станции (В сб это сильно распространено), лутбоксы в техах, беготня по тунельчикам. А так-же непонимание игроками СБ назначения техов и антагов в частности. Подавляющее большинство присекают даже малейшие, простительные ошибки антагонистов, помечая их на весь раунд. (Зачастую даже без каких-либо ошибок от антагониста а из за странного поведения, которое присуще любому человеку, но в игре это выглядит откровенно палевно)
Нет ничего познавательного в афк беготне по техам в поисках подозрительных личностей с 0й минуты раунда, а так-же последующие два часа геймплея без антагонистов, цель которых, развлекать как себя, так и рядовых сотрудников NanoTrasen.
Мне кажется текущая сводка правил "Rule 8" и "Rule 3.1" нуждается в расширении, ведь многие игроки даже не знают что их действия являются не слишком логичными и похожими на ВХ когда бегают по техам и открывают ящики в самом начале смены, так все делают, и я тоже так учился играть.

### Решение

По моему мнению все эти проблемы можно как минимум облегчить добавив в правило "Rule 3.1" "Повергейм" Такие действия как: 
  1) Открытие и проверка ящиков на всей станции без видимых на то причин, или поисков чего-то или кого-то. 
  2) Установку боевых имплантов без угроз с которыми без них справится не выходит (Или просто без угроз).
  3) Установку статуса "Monitor" без серьезной причины. Зачастую статус монитор ставится за нахождение в техах, или за другие действия которые совсем не показывают твоей опасности. Ведь ставится этот статус в один клик, и если это всё-же не антаг то в принципе без разницы игрок ведь даже об этом не узнает но если Антаг, "ух я молодец". В тоже время как снять этот статус не раскрыв себя достаточно сложно, ведь последние изменения остаются в консолях.
  4) Установка статуса "Arrest" без весомой причины. Игроки в 90% случаев игнорируют статус "Search" и ставят сразу арест, даже если человека нужно просто обыскать после чего офицеры видя метку арест бьют его палкой по голове и связывают. (после чего их называют щиткурами хотя они вроде сделали всё верно?)
А так-же дополнив правило "Rule 8" "Валидхант" запретив СБ заходить в техи в зеленый код, либо без весомой причины, к примеру, крики или приказ ГСБ.

### Плюсы

1) Больше интересного геймплея для СБ учитывая что антагонисты смогут дышать.
2) Больше игровых ситуаций связанных с техами и их обысками в зеленый код. 
3) Вероятно мои игры на СБ перестанут быть Away From Keyboard, ведь в наше время даже 4 офицера спокойно справятся с любыми антагами учитывая обыски всех подряд в синий/красный коды и бесконечный патруль техов а так-же учитывая уровень игры 99% антагов на серверах.

### Минусы

1) Необходимо отполировать данное предложение сделав его сбалансированным по мнению компетентных людей.
2) Необходимо расставить точные рамки в правилах ПГ и ВХ.

**Comment by Sykybekk** [comment]
С таким успехом давай вообще вырежем сб, а то чего это они используют тайзеры, летал. Чего они бегают, ловят антагов вх получается. И так далее можно продолжать. Просто предложи выпилить сб сразу и всё

**Comment by Lenerald** [comment]
![Screenshot_20210717_113235](https://user-images.githubusercontent.com/86002189/126031349-9f0eaf1a-158a-45a5-ba4e-6b08137ca83f.jpg)
Не ну у тебя предложения попизже я посмотрю, да и первое совсем сб в грязь не втопчет вот ваще

**Comment by FlyingFloor** [comment]
Какую же чушь вы предлагаете. Вместо того чтобы учиться играть на антагах "Ааа давайте запретим СБ играть на сервере, а то они работают. А работать не должны", 
1. В ящиках ищут трупы, бомбы и контрабанду. В чем здесь проблема? 
2. Без угроз обычно тебе и не поставят импланты. Это раз. А два - кто будет решать, какая угроза достойна имплантов, а какая нет? 
3. Если ты проебался и находился там, где тебя не должно быть - не удивительно, что на тебя ставят мониторинг. Ты повел себя странно для человека с твоей должностью. Поэтому на тебя смотрят косо. Простой вариант - не попадаться на глаза СБ, когда делаешь что-то странное. PROFIT.
4. Если ты нарушил КЗ или есть подозрение на нарушение КЗ с твоей стороны - тебя арестуют, доставят в бриг и потом уже обыщут. Никто не ставит "арест" просто по фану.

**Comment by VictorSocks** [comment]
1.Против
2. Может надо научиться играть на антагонистам для начала? Где-то указано, что антагонист это ответственная роль и если вы не уверены в себе то не стоит ставить на нее галочку. Проблема, что антагониста поймали это проблема не сб, а самого антага. Недавно видел как один вампир проник на ЦК победив отряд ЕРТ высланный за ним. А тут вы пишете, что надо нерфить сб. МДА.

**Comment by Lenerald** [comment]
> Какую же чушь вы предлагаете. Вместо того чтобы учиться играть на антагах "Ааа давайте запретим СБ играть на сервере, а то они работают. А работать не должны". Ну и да -
> 
> 1. В ящиках ищут трупы, бомбы и контрабанду. В чем здесь проблема? И то не всегда, не все и не везде (только в техах, но СРП поменяли и теперь даже этого не будет).
> 2. Без угроз обычно тебе и не поставят импланты. Это раз. А два - кто будет решать, какая угроза достойна имплантов, а какая нет?
> 3. Если ты проебался и находился там, где тебя не должно быть - не удивительно, что на тебя ставят мониторинг. Ты повел себя странно для человека с твоей должностью. Поэтому на тебя смотрят косо. Простой вариант - не попадаться на глаза СБ, когда делаешь что-то странное. PROFIT.
> 4. Если ты нарушил КЗ или есть подозрение на нарушение КЗ с твоей стороны - тебя арестуют, доставят в бриг и потом уже (МОЖЕТ БЫТЬ!) обыщут. Никто не ставит "арест" просто по фану. Если есть доказательства/свидетели - тогда уже тебя будут арестовывать до разбирательства.

Конечно никто так не делает, я ведь это всё придумал, да и антаги ебут каждый раунд

**Comment by Lenerald** [comment]
> 1.Против
> 2. Может надо научиться играть на антагонистах для начала? Где-то указано, что антагонист это ответственная роль и если вы не уверены в себе то не стоит ставить на нее галочку. Проблема, что антагониста поймали это проблема не сб, а самого антага. Недавно видел как один вампир проник на ЦК победив отряд ЕРТ высланный за ним. А тут вы пишете, что надо нерфить сб. МДА.

Так запрети тогда людям без опыта нажимать эти галочки чтобы было чем хотя-бы в раундах заниматься за сб)

**Comment by Iranimakq** [comment]
1. Против.
2. Не буду тут расписывать очередной том "Войны и Мир", скажу просто.
Ребят, ребятки. Может быть вы играть на антагах научитесь, а не пукать : "Ой, ЭСБЭ душыт, памагите(9(9("
Как говорил один великий классик - "Импровизируй, Адаптируйся, Преодолевай". В этих трёх словах идеально описана сущность игры за антагониста.
Не хочу бросаться в крайности, но такими темпами, лучше уж СБ удалить. А что? Антагам же дышать надо.
Более всё подробно и по полкам расписал FlyingFloor. Ну и запомните же вы, что ваша цель не победка, а создание геймплея для обычных игроков. А офицеры СБ - такие же игроки, для которых нужно делать геймплей.

Предложка говна, автору советую не играть на антагах.

**Comment by FlyingFloor** [comment]
> > 1.Против
> > 2. Может надо научиться играть на антагонистах для начала? Где-то указано, что антагонист это ответственная роль и если вы не уверены в себе то не стоит ставить на нее галочку. Проблема, что антагониста поймали это проблема не сб, а самого антага. Недавно видел как один вампир проник на ЦК победив отряд ЕРТ высланный за ним. А тут вы пишете, что надо нерфить сб. МДА.
> 
> Так запрети тогда людям без опыта нажимать эти галочки чтобы было чем хотя-бы в раундах заниматься за сб)

мой сикей есть в моем никнейме.

**Comment by FlyingFloor** [comment]
> > Какую же чушь вы предлагаете. Вместо того чтобы учиться играть на антагах "Ааа давайте запретим СБ играть на сервере, а то они работают. А работать не должны". Ну и да -
> > 
> > 1. В ящиках ищут трупы, бомбы и контрабанду. В чем здесь проблема? И то не всегда, не все и не везде (только в техах, но СРП поменяли и теперь даже этого не будет).
> > 2. Без угроз обычно тебе и не поставят импланты. Это раз. А два - кто будет решать, какая угроза достойна имплантов, а какая нет?
> > 3. Если ты проебался и находился там, где тебя не должно быть - не удивительно, что на тебя ставят мониторинг. Ты повел себя странно для человека с твоей должностью. Поэтому на тебя смотрят косо. Простой вариант - не попадаться на глаза СБ, когда делаешь что-то странное. PROFIT.
> > 4. Если ты нарушил КЗ или есть подозрение на нарушение КЗ с твоей стороны - тебя арестуют, доставят в бриг и потом уже (МОЖЕТ БЫТЬ!) обыщут. Никто не ставит "арест" просто по фану. Если есть доказательства/свидетели - тогда уже тебя будут арестовывать до разбирательства.
> 
> Напиши сикей свой

мой сикей есть в моем никнейме.

**Comment by Sykybekk** [comment]
> ![Screenshot_20210717_113235](https://user-images.githubusercontent.com/86002189/126031349-9f0eaf1a-158a-45a5-ba4e-6b08137ca83f.jpg)
> Не ну у тебя предложения попизже я посмотрю, да и первое совсем сб в грязь не втопчет вот ваще

Ой блять, сейчас бы не отличать изменения  направленные на искореннение станов как основы от душнилова сб на твоём уровне. Всё твоё предложение это: "давайте сб запретим выполнять свою работу и вообще пускай стоят на месте"

**Comment by Danefalt** [comment]
Нейтралитет, но скланяюсь к отрицательному решению.
С одной стороны, по любой причине прожимать статусы это проблема. А вот обыскивать те же шкафчики это их работа.
А по поводу боевых имплантов я вообще молчу, они должны быть доступны на постоянку, и не только СБ, но и главам. Да даже гражданским при разрешении. 
Да и те же правила про летал в зелёный я не понимаю. Боже, мы на научной станции огромной мегакорпорации. Это стратегически важный объект. СБ в зелёный должны ходить как янтарное ОБР, а не как охрана пятёрочки.

**Comment by Dreemer556** [comment]
1. Против, с немного другим решением проблем.
2. Я согласен только на то, чтобы СБ закрывало ящики после открытия, а то куда не посмотри всюду ящики нараспашку, что сильно отличается от реальности. Заодно у антага будет микроскопическое преимущество в возможности сныкаться на пару минут и твой ящик не будет гореть синим пламенем потому что он один закрытый. Также я за то, чтобы ограничили поиск антагов/контрабанды до их нахождения. У меня малый опыт СБ и я не видел как играли другие, но мне кажется, что они обыскивают ящики и до того как нашли угрозу, что странно. Правило №1 я полностью поддерживаю.

Теперь по другим. Термалы действительно ставят в большинстве случаев без бумаг и при любом случае, что подтверждает геймплей Wycc. Как это ограничивать я не знаю, уж бюрократия точно зависит от игроков, но кто её проверяет и кто за ней следит? А тот кто следит будет против суперсолдат, которые убьют вампиров даже чисто по рп? 

Про статусы. За свои скудные 10 часов монитор в половине случаев стоял чётко, а в другой половине по причине, но это был просто человек с ИЦ целями, как например гражданский в космосе. Я не вижу в этом проблемы, это их работа и она очень помогает найти угрозу.

Вот аресты за всё моё время стояли чётко. Те кто их ставит вероятно были неопытными, что классика. Я сам лишь на 150-м часу в инженерии решил перевести, что значат режимы в атмосферных датчиках, ибо переводить мне в падлу, хочется играть прямо сейчас. 

Я предлагаю иное решение. Прописать в вики всего СБ некие рекомендации или правила хорошей игры. Мол фигли все СБ-шники нараспашку шкафы оставляют, в жизни тоже всё так стоит? Что есть другие режимы и стоит использовать их, а не ставить сразу арест, что ГСБ или вардену, или НТР, или ещё кому-то стоит напоминать о существовании других режимов, что стоит наказывать (хотя бы устно) тех, кто ставит арест без необходимости, что стоит заполнять бюрократию (хотя кто её захочет заполнять если он не желал ранее?) ведь она придумана не просто так, что стоит написать в СРП учёных пункт:"Не выдавать СБ импланты без необходимых бумаг если на станции не стоит красный код" и что-то в таком духе. Все мои предложения были на скорую руки и если вы имеете идеи лучше предлагайте, можем потом оставить предложение с проблемами, которые я описал и вашим решением.
И это, не забывайте, что у меня 10 часов за СБ. Я спокойно могу ошибаться
