### ISSUE TITLE
Feat: Разум отделенным слаймам

### ISSUE THREAD

**Issue by PhantornRU** [ss220-space/Paradise#150]
### Проблема

Иногда выпадает ивент наделяющий случайного слайма разумом. 
Но когда он делится, его "дети" не обладают разумом. Не порядок.

### Решение

Необходимо наделить разум отделившимся слаймам и предлагать гостам за них сыграть.
Я самолично готов написать код выдачи роли гостам.

### Плюсы

- Больше шума от слаймов, они станут проблемой.
- Слайм теперь не будет "случайным пшиком" в виде ивента. 
- Будет смысл в защите от них.

### Минусы

- Больше шума от слаймов, они станут проблемой
- Больше завареных вентов. Больше повода их заваривать.
- Нужно держать огнетушители при себе.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184352542-081ff471-3534-4429-af3e-58fea1e99cbe.png)
