### ISSUE TITLE
Feat: Добавить(украсть) базу учёных синдиката в космосе

### ISSUE THREAD

**Issue by VictorSocks** [ss220-space/Paradise#152]
### Проблема

На офф парадизах есть база как на лаваленде, но она в космосе

### Решение

Было бы очень хорошо увидеть ее и у нас на сервере.

### Плюсы

Новая гостроль, которая может взаимодействовать с антагонистами, а именно агентами синдиката или нюковцами, а также с простыми исследователями, которые ненароком(а может и специально) забрели туда

### Минусы

Работа с добавлением.

**Comment by VasilevAY** [comment]
тайпан добавлен
![image](https://user-images.githubusercontent.com/98010665/184352493-fb40bea3-b5f1-44ce-8e2e-5d272e8fa3c0.png)
