### ISSUE TITLE
Feat: нерф даблсвордов

### ISSUE THREAD

**Issue by FlyingFloor** [ss220-space/Paradise#153]
### Проблема

В текущем своем состоянии двойные энергомечи являются дичайшей имбой, которая блочит почти весь входящий урон. Если владелец меча при этом имеет антифлэш - он становится убийцей-терминатором, который не получает урон ни из единого типа оружия, которое существует. Мили (станбатон) - блок 75%. Огнестрел - блок 75%. Лазеры - блок 100%. 
А когда появляется стелс-нюка с мечами - ну как бы все, можно стартовать следующий раунд. Да и даже без неё - попытка поймать нормального антага с даблсвордом это чистое казино. 

### Решение

Снизить возможность блока какого-либо типа урона даблсвордом. Наиболее логичным является снижение возможности блока кинетического вооружения до 25%, потому-что с точки зрения РП не очень понятно, каким образом "мечник" способен перехватывать пули/снаряды, так как кроме самого факта наличия оружия он должен обладать сверхчеловеческой реакцией. А при блоке в 25% будет ясно, что это - просто удача, так как пуля попала в меч.  Обычному есворду тоже срезать значения блока, чтобы даблсворд все ещё был выгоднее (цифр одиночного есворда я не помню)

### Плюсы

1. Антаги с даблсвордами начнут больше думать, а не лезть лицом на всех противником, т.к. практически бессмертные
2. У СБ хотя бы появится более реальный шанс противостоять ребятам с даблсвордами. Если они успеют добраться до дробовиков и перезарядить их. 
3. Баланс сильно не пострадает, так как у НТ и без того мало кинетического(огнестрельного) вооружения.

### Минусы

1. Имея даблсворд придётся чуть боле думать, а не просто бежать в любого противника лицом вперёд. 
2. Стелс-нюка сможет проиграть. Иногда.

**Comment by Jordanstolethepreciousslam** [comment]
1.Против
2. Брух ну и хуета. Даблсворд никогда не был имбой. Обычный чел с батоном имеет хорошие шансы уронить мечника а уж если он умеет юзать болы, огнестрел или щит.
Просто для справки у офицеров сб есть щиты которые дают 50% блока всего на свете, включая даблсворд, пули, лазеры и Аллаха. Чтобы уронить даблсвордом требуется от двух до четырех ударов, тогда как батон роняет с первого и навсегда. А уж борг вообще на миниджеке вертел мечников.

**Comment by Lenerald** [comment]
Хахах

**Comment by FatFatFat1** [comment]
А в чем проблема кинуть флешку?

**Comment by FlyingFloor** [comment]
> А в чем проблема кинуть флешку?

в антифлеше. там в дискорде в обсуждении у нас уже очень долго идёт обсуждение по поводу того, еблан ли я или предложение имеет какой-то смысл. можешь почитать на досуге.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184352583-dce914e5-e254-4bb4-8639-8e74c059ed43.png)
