### ISSUE TITLE
Feat: Respawnability у Oberver

### ISSUE THREAD

**Issue by semoro** [ss220-space/Paradise#154]
### Проблема

Сейчас заходя за обсервера игрок не получает respawnability
Для получения respawnability используется абьюз спавна и смерти за мышь

### Решение

Вариант 1. Дать обсерверам respawnability по умолчанию
Вариант 2. Убрать возможность получения respawnability через смерть за мышь

### Плюсы

Избавление от абьюза
В варианте 2, уменьшение использования меты

### Минусы

В варианте 2 больше нельзя будет поиграть за mid-round антага, если зашли за обсервера

**Comment by Bizzonium** [comment]
Очевидно, что нужно, как минимум, исправить баг с получением respawnability через мышь.

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/309

**Comment by Den109G** [comment]
А как `Fix mech's weapon cooldown` связан с `Respawnability`?

**Comment by VasilevAY** [comment]
> А как `Fix mech's weapon cooldown` связан с `Respawnability`?

Азиз привязал к issue - значит связано 
но вообще да, не посмотрел

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184354602-fd39f925-d626-4d18-9517-3cbefe300529.png)
