### ISSUE TITLE
Feat: проблема ПГ и почему правило ПГ убивает РП. 

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#155]
### Проблема

В правилах сервера присутствует одно правило, которое лично меня жутко бесит. Это правило на ПГ. Оно заставляет отыгрывать тебя обыденную картошку, которая в критичной ситуации на адреналине и панике не может сделать ничего, кроме как бежать, хотя в реальном мире есть не один случай подвигов и не очень ради которых люди жертвуют даже собой, несмотря на то, что "у людей есть страх за жизнь, бла бла🤨" 

### Решение

Предлагаю наконец-то дать мементорам и модерам кнопочки. А к кнопочкам добавить возможность снимать или давать респавнабилити. в зависимости от степени нарушения правила ПГ не давать в ебучку темпом, а как минимум снимать респавнабилити в раунде. Таким образом все подвиги заимеют "цену" которую игрокам придётся уплатить за свои действия, как люди платят своей жизнью ради убийства врагов или спасения друзей. Майндгейм, епта

### Плюсы

Правило пг перестанет делать из людей бесформенных кукол которые боятся бахнуть лимитку, когда им уже совсем осталось жить мало. Думаю, большая часть людей ИРЛ бахнуло бы в себе гранату, умирая от рук человека, которого вполне себе можно захватить с собой. речь не о гриферских 300/300 а карманных 100/100,когда можно забрать с собой на тот свет обидчика. 

### Минусы

Больше ПГ, больше кринж рп, накодить кнопку надо.

**Comment by DayBreakerBrony** [comment]
P. S. речь не о том чтобы убрать правило ПГ, а облегчить наказание за его лёгкие проявление просто удалением респавнабилити человека с раунда

**Comment by tizer7** [comment]
Против.
Смягчение наказания за ПГ = больше ПГ.

**Comment by Lenerald** [comment]
Против
Ты не понимаешь что предлагаешь

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184352631-a4be5616-3579-4a25-819c-f5d02b752d12.png)
