### ISSUE TITLE
Feat: Дать дронам возможность разварить вентиляцию изнутри

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#156]
### Проблема

Лезешь в вентиляцию на дроне в одном месте, чтобы быстро попасть в другую часть карты, а по итогу узнаешь что там всё заварено. Мало того заварено всё в радиусе 100 тайлов из-за пауков/бореров/прочей живности. Летишь назад - а там тоже заварено. По итогу находишь единственную венту в техах и делаешь троекратный путь до пункта назначения. А потом, тебе ещё надо по условиям твоей роли стараться не показываться на глаза экипажу, да и вообще любой живности. И если тебя увидят как ты развариваешь вентиляцию - так вообще разнесут на куски ломом со словами "С-@#$!-А! ГРЕБАНЫЙ ДРОН РАЗВАРИВАЕТ ВЕНТУ Б-#@$@ТЬ! СВОЛОЧЬ!" и т.д. от того, что, видите ли, заваренная вентиляция не дает ресаться антагам, и им безопаснее чувствуется на станции.

### Решение

Разрешить дрону открывать заваренные скрабберы и вентиляции изнутри. Дать абилку пауков террора, переименованную, чтобы не смотрелось странно. К тому же, дроны визуально меньше, чем те же Террор пауки (которые по размеру заполняют весь тайл), и теоретически могут развернуться в венте со сваркой и "разварить" её.

### Плюсы

- Можно будет вылезти, где вздумается и не заморачиваться о том как пройти через всю станцию не пострадав от тупых сб/асистух и прочей живности +- не попасть под лом разъяренного инженера;
- Соблюдаем своё рп на дроне, работаем быстро-чисто-скрытно от глаз асистух;
- Остальные антаги могут получить из этого выгоду, им дадут дышать, тем же борерам/паукам/обезьянам-генокрадам/морфам/свармерам. И не только антагам, например, евент с пауками будет снова актуальным(весь раунд, а не только на старте);
- К тому же это работа дронов - восстанавливать станцию в прежнее состояние. Заваренные венты это не нормальное состояние. 
p.s. Зачастую в комнате нет давления/воздуха, а причина почему не работает вентиляция - её заварил инж, ушёл и больше никогда не вернется чтобы открыть её обратно, и никто её не разварит(либо извилин мало понять в чём проблема, либо хотят чтоб шкура была целее - лучше без воздуха чем с открытой вентой, правда же?).

### Минусы

По началу, обычные игроки будут ложить кирпичи, видя как вентиляция открывается открывается сама по себе, думая что там коричневый паук/принцесса/морф(?). А потом привыкнут.

**Comment by tizer7** [comment]
Против.
Твоя задача отыгрывать свою роль за дрона игноря всех остальных, за исключением того, что правило предписывает не вмешиваться в рп других игроков. Нет запрета показываться на глаза. Нельзя давать дронам разваривать венты. Не можешь ползать по вентиляции - ходишь пешком.

**Comment by Jordanstolethepreciousslam** [comment]
Разваривать венты снаружи дрон вполне может и ему разрешено. Даже при пауках или борерах. Потому что ему похуй на экипаж, он восстанавливает станцию.

**Comment by snipersir** [comment]
Так а что мешает разваривать венту изнутри? Для дронов будет проще достигать места поломок, антагам будет чем дышать. Что не так то?

**Comment by Jordanstolethepreciousslam** [comment]
То что это очень имбалансно. Дрон может разваривать при террорах и борерах но во первых он должен для этого вылезти, во вторых это требует времени. Его можно за это время уничтожить или просто пойти и взорвать его через консоль. А если он будет изнутри разваривать даже носа не высунув то во первых ты даже понять не сможешь что это дрон разварил а не ты забыл, во вторых его в это время нельзя уничтожить.

**Comment by snipersir** [comment]
Позвонить в инженерку и сказать всех выключить?

**Comment by Jordanstolethepreciousslam** [comment]
Это если инжинерку не сожрали полностью и ты реально о дронах вспомнишь

**Comment by snipersir** [comment]
Ну раз через венту постоянно кто-то лезет - инженеры наконец станут использовать всеми забытые PIPE CAP в RPD. Надоело наблюдать открывание венты - ставь заглушку! Вот и всё решение. Я ни разу не видел ни одного инженера/юнита/дрона, кроме меня самого, кто использовал заглушку на трубы, ибо открученные трубы и так не выпускают воздух с концов, хотя должны.

**Comment by snipersir** [comment]
Играть становится всё менее интереснее со всей этой однообразностью и духотой... Я вас понял. Закрываю сие предложение в конце дня.
