### ISSUE TITLE
Feat: Уменьшить спрайт борера, сделать его по размеру как червя генокрада(а может и мыши)

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#157]
### Проблема

Сейчас, борер - это длинная зеленая колбаса-улитка, огромная на столько, что больше чем мозг в голове. Вроде мозговой червь, должен быть меньше по размеру, а на деле эта огромная колбаса лезет в одно ухо и умудряется не вытолкнуть мозг через другое... Плюсом его спалить как нехрен делать, только плассталиевые столы и прочие предметы со спрайтом до нижнего края тайла и спасают. Я видел червя генокрадов и, если память не подводит, он размером с мышь, бегает как заполошный по полу хрен поймаешь, так ещё может трансформировать тело во что вздумается если залезет во что-то. Как-то не справедливо, хотя борер в разы безопаснее и даже полезнее если игроки отыгрывают нормальное рп(что редко случается).

### Решение

- Сделать борера размером с мышь/червя генокрада;
- Немного увеличить скорость передвижения(?)(желательно);
- Поднять спрайт от нижнего края тайла на пару пикселей выше, чтобы не был столь заметен (желательно).

### Плюсы

- Повышенная выживаемость за борера(например, возможно, получится сбежать от дюранда, стреляющего по тебе Соларисом вот уже 2 минуты, пока ты стоишь на месте)

### Минусы

Без понятия. Слишком жирный бафф?

**Comment by Dreemer556** [comment]
1. За, но на пол шишечки
2. Я тоже считаю бореров очень палевными, но их размер меня устраивает. Как по нему попадать когда он убегает если он будет меньше? (Спрайт червя генки не видел. Могу ошибаться) А вот о небольшом поднятии на пару пикселей я очень за. Они слишком сильно палевны под столом, что усложняет забирание в голову (а их и так очень легко достать и противостоять иными способами. Банально уйти). В поднятии скорости не вижу ничего плохого, но от дюранда убегать мне не приходилось. Тут хз

**Comment by snipersir** [comment]
На счёт трудно попасть странно, бореры ползут 1 тайл в секунду. Как по ним не успеть попасть это трудно представить. А про дюранда это личная история. Меня убивал дюранд 3 минуты из солариса в упор пока я ползал перед ним, хотя впрямом смысле в 5м от самого дюранда на половину медбея разросся блоб и спамил спорами и блобернаутами. Обычный борер оказался опаснее огромного блоба...

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184352862-e38e921c-57c8-4d1f-945e-d8657b2229d6.png)
