### ISSUE TITLE
Feat: Добрых снов

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#158]
### Проблема

Спим мы достаточно часто: на операции, на столе абдукторов, нахерачившись пивом. А вот хорошие, добрые сны видит только определенная группа людей, и то достаточно редко("мертвый вульпканин").

```
мертвый скрелл
мертвый унатх
мертвый таяра
мертвый вульпканин
мертвый слайм
мертвый ипк
мертвый вокс
мертвый плазмамэн
мертвый грэй
мертвый кидан
мертвая диона
мертвый драск
сбойное ядро ИИ
кРоВь
был вызван
ужасное чувство страха охватывает тебя
красные огни
говорящий мим
ЗАЧЕМ ТЫ ЭТО ДЕЛАЕШЬ
они знают
уБеЙ иХ
почему
ХоНк
аааАААааааААААААаа
пЭйПеРвОрК
мы ВИДИМ тебя
плитка
мы ждали тебя [DREAMER]
жуткие клоуны
кНоХ
они близко
некуда бежать
демон
МОНОЛИТ
ИДИ КО МНЕ
Я ВИЖУ ТВОЕ ЖЕЛАНИЕ
ТВОЙ ПУТЬ ЗАВЕРШАЕТСЯ
ВОЗНАГРАЖДЕН БУДЕТ ТОЛЬКО ОДИН
```
Ну слишком уж грустно.

### Решение

Добавить больше добрых, приятных снов, чтобы даже во время отключки, пока тебе антаг вырезает мозг, тебе снился, например, гринтекст

### Плюсы

Будет больше позитива

### Минусы

Люди не захотят просыпаться(

**Comment by Danefalt** [comment]
Ну так мы играем в игру про предотвращение чрезвычайной ситуации. Персонажи просто чувствуют будущие через сны ¯\_(ツ)_/¯

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184352918-5bff5c1c-97cd-4bb3-8aa8-2c1c569f843f.png)
