### ISSUE TITLE
Невозможность залететь за МИД раундовых антагов.

### ISSUE THREAD

**Issue by ZoNeSRuS** [ss220-space/Paradise#160]
### Проблема

Свармеры, пауки, черви, все это конечно весело но объединяет их одна проблема. Кто первый кнопочку нажал тот и играет. Что как бы не совсем честно как по мне. Есть игроки которые просто сидят на чиле, но не  против поиграть на тех же свармерах, но хер им по одному месту. Рольки разбирают меньше чем за секунду как итог ты сидишь дальше с лицом жабки.

### Решение

Сделать систему как при создании разумных животных или ЕРТ, но с задержкой не в минуту, а в 5 секунд. Все кто хочет, но не обладает реакцией мангуста смогут поиграть.

### Плюсы

Залететь за свармеров, пауков и прочих станет проще, все будут иметь равные шансы поиграть.

### Минусы

Робасты будут не довольны.

**Comment by Dreemer556** [comment]
1. За
2. Наконец можно будет залететь не на реакции кобры или закликивании той зоны, а просто сыграв в рулетку. Одни плюсы

**Comment by tizer7** [comment]
За.

**Comment by Danefalt** [comment]
Лучше ещё добавить мидраундовых обычных антагов. То есть, когда ты заходишь во время раунда, просто как обычный персонаж, в зависимости от префов тебе может выпасть роль. А такая система уже есть в сске, нужно её только смержить сюда.

**Comment by rebel228** [comment]
Это сделано потому например тот же паук может вылупиться посреди отсека, и если за него сразу никто не зайдет то его просто убьют.
Во вторых почему не честно, что тот кто активно следит за игрой имеет больше шансов попасть, чем тот кто просто сидит на чилле?

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184352991-7e102156-f205-4b84-9fe0-a4deca032d66.png)
