### ISSUE TITLE
Отвратительный внешний вид НВ Худов из РНД

### ISSUE THREAD

**Issue by terribaum** [ss220-space/Paradise#162]
### Проблема

Отвратительный внешний вид худ очков. 

### Решение

Предлагаю переделать Худы в те которые есть на вики (и возможно в коде?)
![изображение_2021-07-19_063611](https://user-images.githubusercontent.com/80427882/126099111-aa7ae582-ed91-49a3-81a3-0e384da7efd7.png)

### Плюсы

Стильные Худы!

### Минусы

Стильные Худы?

**Comment by DetectiveEnotsky** [comment]
У каких именно очков. Те, которые в вики - ПНВшные ХУДы. Они на то и ПНВ, что бы выглядеть так.
А если ты про те худы, что есть как очки, тобиш обычные, то зачем?
Так, что голос против

**Comment by HMBGERDO** [comment]
Какие именно "очки" тебе не нравятся? Худы монокуляры на один глаз? Нормально вроде, что не так то?

**Comment by terribaum** [comment]
> У каких именно очков. Те, которые в вики - ПНВшные ХУДы. Они на то и ПНВ, что бы выглядеть так.
> А если ты про те худы, что есть как очки, тобиш обычные, то зачем?
> Так, что голос против

У нас ПНВ Худы так не выглядят(во всяком случае на мейне)

**Comment by terribaum** [comment]
> Какие именно "очки" тебе не нравятся? Худы монокуляры на один глаз? Нормально вроде, что не так то?

Я не против Худов Монокуляров.Я против ПНВ Худов-они все еще тоже монокуляры,что даже глупо.

**Comment by HMBGERDO** [comment]
> > Какие именно "очки" тебе не нравятся? Худы монокуляры на один глаз? Нормально вроде, что не так то?
> 
> Я не против Худов Монокуляров.Я против ПНВ Худов-они все еще тоже монокуляры,что даже глупо.

собственно, ИРЛ многие ПНВ так и есть, монокуляром. Можно сделать и обычными очками, на официалке так. Но как мне кажется, у нас сейчас нормально, плюсом у них есть красивая анимация, где они немного моргают. Я за то, чтобы оставить такими, какие они есть

**Comment by terribaum** [comment]
> > > Какие именно "очки" тебе не нравятся? Худы монокуляры на один глаз? Нормально вроде, что не так то?
> > 
> > 
> > Я не против Худов Монокуляров.Я против ПНВ Худов-они все еще тоже монокуляры,что даже глупо.
> 
> собственно, ИРЛ многие ПНВ так и есть, монокуляром. Можно сделать и обычными очками, на официалке так. Но как мне кажется, у нас сейчас нормально, плюсом у них есть красивая анимация, где они немного моргают. Я за то, чтобы оставить такими, какие они есть

Так проблема в том что они даже не на все лицо.Что вообще не логично.У тебя по факту один глаз только освещает

**Comment by HMBGERDO** [comment]
> > > > Какие именно "очки" тебе не нравятся? Худы монокуляры на один глаз? Нормально вроде, что не так то?
> > > 
> > > 
> > > Я не против Худов Монокуляров.Я против ПНВ Худов-они все еще тоже монокуляры,что даже глупо.
> > 
> > 
> > собственно, ИРЛ многие ПНВ так и есть, монокуляром. Можно сделать и обычными очками, на официалке так. Но как мне кажется, у нас сейчас нормально, плюсом у них есть красивая анимация, где они немного моргают. Я за то, чтобы оставить такими, какие они есть
> 
> Так проблема в том что они даже не на все лицо.Что вообще не логично.У тебя по факту один глаз только освещает

оно ИМЕННО так и работает ИРЛ. В чём проблема?

**Comment by FlyingFloor** [comment]
> > > > Какие именно "очки" тебе не нравятся? Худы монокуляры на один глаз? Нормально вроде, что не так то?
> > > 
> > > 
> > > Я не против Худов Монокуляров.Я против ПНВ Худов-они все еще тоже монокуляры,что даже глупо.
> > 
> > 
> > собственно, ИРЛ многие ПНВ так и есть, монокуляром. Можно сделать и обычными очками, на официалке так. Но как мне кажется, у нас сейчас нормально, плюсом у них есть красивая анимация, где они немного моргают. Я за то, чтобы оставить такими, какие они есть
> 
> Так проблема в том что они даже не на все лицо.Что вообще не логично.У тебя по факту один глаз только освещает

Вот короче, если нужен наглядный пример.
![image](https://user-images.githubusercontent.com/87566870/126514478-d1fc43f4-1b2a-412a-bd48-3689c1f4d660.png)

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353052-b3927db7-988a-4753-8389-fbdee990a55e.png)
