### ISSUE TITLE
Дайте людям спокойно срать в туалетах

### ISSUE THREAD

**Issue by Frostillikus21** [ss220-space/Paradise#163]
### Проблема

Не дают посрать/поафкашить/собрать шмотки на антага в туалетах

Нет, это не шутка, это уже целая проблема.

### Решение

Запретить сбешникам вламываться в туалетные кабинки в зелёный код без веских на то причин.

### Плюсы

Люди смогут спокойно афкашить в туалетах, антаги собирать свою херню

### Минусы

Антаги будут упорно ломиться в туалеты чтоб собрать свой станпрод

**Comment by PhantornRU** [comment]
Хватит это терпеть! xD

**Comment by tizer7** [comment]
Закрывай и оформляй в дискорде. Тут предложки подразумевающие изменение кода.

**Comment by Zigamus** [comment]
открывай и оформляй тут, в дискрде теперь предложка закрыта
![Без имени-1](https://user-images.githubusercontent.com/59314481/126315769-6a1c79c8-891f-4dae-8f35-fd576d896c69.png)
