### ISSUE TITLE
Feat: Новый антагонист "Мародёр"

### ISSUE THREAD

**Issue by dj-34** [ss220-space/Paradise#164]
### Проблема

-

### Решение

Предлагаю завести нового антагониста, не хардкод и не слишком замысловатая идея.

Суть в том, что ты появляешься как анатагонист среди раунда, выбранным из гостов (или доп. антагом в начале раунда), с целью нанести как можно больше ущерба станции, заодно подняться по своему социальному статусу разными способами. Например, можно саботировать станцию, совершать выгодные сделки, менять краденые и казённые вещи, убеждать людей в своей "доброй" цели и правоте. разъебывать мостик в хлам, бриг превращать в заброшенную и нерабочую часть станции, оставлять ХоСа без бумаг, РД без протолата, а капитана оставлять без трусов в самый разгар хаоса. Все зависит от твоего воображения.

Вот небольшое описание для антага. Важное отличие от других антагонистов, что Мародёр - не убийца и не подрывник, он лишь приносит убытки НТ под видом обычного рабочего, косвенно работая на Синдикат, хоть и не имея много общего с ним, кроме своей выгоды работы на него. Это подтверждает то, что он не имеет никаких кодовых фраз, аплинка и иных доказательств причастия к Синдикату.

### Плюсы

- Больше РП, меньше убийств.
- Больше смешных, интересных и разнообразных ситуаций.
- Новый антаг, всё-таки.

### Минусы

- Кодить, писать описание и правила(((((
- Больше РП, меньше убийств.

**Comment by keIgaras** [comment]
Это называется морф😁

**Comment by PhantornRU** [comment]
Так а че он делает то? По описанию больше на хиджакера без цели украсть шаттл похоже, а просто разъебать станцию.

**Comment by ZoNeSRuS** [comment]
У нас же уже есть ассистухи.

**Comment by Dreemer556** [comment]
1. Против
2. Косвенно это делают любые антаги за Синдикат. Я гадил для выполнения цели станции, видел как люди подрывали вход в бриг, видел как захватывали РНД, чтобы не пришли детали для цели станции, видел самоподрыв слуги теней, который унёс с собой СЕ и 70% инженеров, которые работали над целью, решал проблемы с запуском плазмы в мед. В общем, антаги так и так гадят, чтобы у них было больше времени на выполнение своих целей или частично саботировать работу отделов
