### ISSUE TITLE
Feat: Плащи из кожи голиафа для всех и везде на Лаваленде

### ISSUE THREAD

**Issue by DjeyTi** [ss220-space/Paradise#165]
### Проблема

При игре за Пепельного заметил, что в меню крафта доступен плащ из шкуры голиафа. Но чтобы сделать его требуется доступ к биогенератору (нужна кожа), которым Пепельные не могут пользоваться по правилам. Других способов достать данный ингредиент нету.

### Решение

Дать жителям Лаваленда возможность дублить шкуру голиафа или ксеноморфа, тем самым получать нужную нам кожу. На данный момент, при процессе дубления обоих типов шкур мы получаем бесшёрстную шкуру, которая нигде не применяется. Поэтому предлагаю заменить бесшёрстную шкуру на кожу при дублении.

### Плюсы

1) У жителей Лаваленда теперь будут стильные плащи из шкуры голиафа;
2) Облегчит игру за Пепельных.

### Минусы

1) Облегчит игру за Пепельных.

**Comment by FatFatFat1** [comment]
Ты бы хоть вики полистал. Это уже можно делать

**Comment by DjeyTi** [comment]
> Ты бы хоть вики полистал. Это уже можно делать

Можешь скинуть сылку? А то возможно просто слепой.

**Comment by tizer7** [comment]
> Ты бы хоть вики полистал. Это уже можно делать

Да, верно. Сложновато немного, но можно. 

Предложку закрывай.
