### ISSUE TITLE
Изменение вирусологии

### ISSUE THREAD

**Issue by Sylph6** [ss220-space/Paradise#166]
### Проблема

Я считаю, что на данный момент у вирусологии есть небольшая проблема в виде лимита свойств вируса, что на данный момент составляет 6. Играя за вирусолога мой коллега сделал полезный вирус буквально за 5-10 минут игры, а что спрашивается дальше? Если посмотреть на тех же генетиков у которых 55 блоков по 3 под блока....у них море работы, учитывая, что их постоянно отвлекают и прочее.

### Решение

Я прошу увеличить лимит свойств вируса с 6 до 8.

### Плюсы

Это добавит работы вирусологам и разнообразит возможности комбинации симптомов в одном вирусе, что позволит создавать невероятно полезный вирус, так и оторвижопную бубонную простуду.
Будет полезно как для хорошего вирусолога, так и для антагониста.

### Минусы

Очевидных минусов не вижу, хотя конечно это как то повлияет на общий баланс.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353102-7f79164c-4e70-401f-bc20-0309d3b336c6.png)
