### ISSUE TITLE
Feat: Больше музыки!

### ISSUE THREAD

**Issue by PoTapkam** [ss220-space/Paradise#167]
### Проблема

На самом деле у нас уже достаточно давно есть дискошар который играет музыку и все треки так или иначе обитатели бара его прослушали предлагаю расширить ассортимент песен в дискошаре. 

### Решение

Создать какую то голосовалку из песен которые можно легально добавить в билд и закинуть в дискорд добавить хотя бы 5 песен или пускай администрация выбирает треки и кидает на одобрение людей.

### Плюсы

Больше музыки

### Минусы

БОЛЬШЕ МУЗЫКИ!

**Comment by Danefalt** [comment]
Так, а почему просто не дать людям заливать треки с ютуба/спотифая/саундклауда/вк и прочего на дискошар, а потом банить дебилов за нарушение атмосферы, если они включат моргенштерна? KEKW
(Зато можно будет включать "Над нами баржи Аббадона" в бриге :PogD:)

**Comment by Dreemer556** [comment]
1. За
2. А какие тут минусы? Идея здравая. Особенно с голосовалкой вариантов админов

**Comment by PhantomMi3** [comment]
1. Интересная идея Я за.
2.  Минусом будет то что какойнибудь шалопай включит: ДИКИЙ ФЛЕКС.MP69 и ХОНК БАТЛ МИМ ПРОТИВ КЛОУНА.XONK

**Comment by OpsCoretango** [comment]
Вот людям которые добавят David Bowie-Space Oddity, готов деньгу отсыпать.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353425-c35e352b-bc56-4361-940b-1f4daef1fdcf.png)
