### ISSUE TITLE
Feat:фактическое отсутствие ДНК у рас без крови

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#168]
### Проблема

у рас без крови (плазмамены, слаймомены, нуклеации) нет крови, поэтому фактически в них невозможно превратить с помощью стабильного мутагена. К тому же раз у них нет крови при их убийстве невозможно анализировать днк на предметах, что делает их ещё скрытнее при игре за тритора. 

### Решение

добавить МЕХАН, который даст возможность забирать у них подобие крови для изменения расы. Ладно, слаймомены и нуклеотиды не клонируются, скажем, что у них нет ДНК. НО ПЛАЗМАМЕНЫ КЛОНИРУЮТСЯ, значит днк у них есть и должен быть соответствующий механ сбора ДНК. Также добавить возможность оставить днк при ранениях

### Плюсы

больше плазмаменов на станции!!! фан от превращения людей в копию себя, интересный способ убить за тритора. 

### Минусы

они сразу же сгорят в кислородной среде и задохнуться... сложнее играть за плазму тритора, поскольку будешь оставлять следы.

**Comment by Danefalt** [comment]
Не ну вообще, ДНК есть у всего что живое.
Чтож, как это можно реализовать:
У нуклеации сделать что-то типо выделений, которые от части исполняют функции крови. Объяснить это можно реакцией кристаллов СМ с животными клетками (Но я без понятия, так ли это должно работать).
У слаймов - слизь. Они слаймы в конце концов.
А у плазмемаменов даже парится не надо, есть же жидкий форон.

**Comment by DayBreakerBrony** [comment]
апаю предлогу, потому что пропустили большинство

**Comment by PhantomMi3** [comment]
1. ЭЭЭх Я всегда играю на нюклиации и Я шитаю что это просто ненадо им, так как они умирают безвозратно да и по лору это не зделать.
2.Против.

**Comment by DayBreakerBrony** [comment]
> 1. ЭЭЭх Я всегда играю на нюклиации и Я шитаю что это просто ненадо им, так как они умирают безвозратно да и по лору это не зделать.
>    2.Против.

если ты против только нуклеаций, то может кинешь не против, а просто предложишь то же самое без нуклеаций?

**Comment by PhantomMi3** [comment]
> > 1. ЭЭЭх Я всегда играю на нюклиации и Я шитаю что это просто ненадо им, так как они умирают безвозратно да и по лору это не зделать.
> >    2.Против.
> 
> если ты против только нуклеаций, то может кинешь не против, а просто предложишь то же самое без нуклеаций?

А может ты удалиш их из списка?

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353482-674b4714-4500-4082-969f-913622f1587b.png)
