### ISSUE TITLE
Feat: Русская рулетка и ГСБ

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#169]
### Проблема

нету

### Решение

в шкафчике ГСБ есть русский револьвер. предлагаю добавить пункт в космозакон: нарушитель сможет сыграть в русскую рулетку, чтобы мгновенно выйти из брига. количество пуль, которые необходимо прощёлкать зависит от тяжести нарушения (от 1ХХ до 5ХХ).Таким образом за драку нужно прощёлкать 1 пулю для выхода, а за убийство - 5.

### Плюсы

особо азартные синдикековцы смогут выйти из брига с помощью ревика

### Минусы

особо азартные синдикековцы смогут выйти из брига с помощью ревика(?) 
нарушение срп, прописать в срп😳
придётся не воскрешать умерших иначе смысла нет

**Comment by Sykybekk** [comment]
Это гениально. Но как частый наблюдатель пользователей этого инструмента на брифингах сб(я сам его и давал офицерам) могу сказать, что шансы выжить по статьям от 3xx - 5xx очень малы

**Comment by mayorovp** [comment]
Посмотрите как часто люди забивают себя кулаками в камере, просто чтобы не сидеть без дела лишние 15 минут. А вы предлагаете им сделать то же самое, но легально да ещё с возможностью выхода из брига!

**Comment by AttHawk** [comment]
Предложка звучит примерно как «а давайте добавим гладиаторские бои за место в очереди ГП, ну потому что эта, ну прикольно жи»

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353536-ea424c46-f7fe-4e2f-8be1-a8ca39fed345.png)
