### ISSUE TITLE
Ускорить скорую помощь

### ISSUE THREAD

**Issue by AugustBebel** [ss220-space/Paradise#170]
### Проблема

За парамеда нет смысла использовать скорую потому что она настолько медленная, что люди уже тащащие тело тебя просто игнорят, зная что скорая медленнее простого таскания. В итоге скорая нужна только если тело истекает кровью, да и то спорно что хуже — истечь кровью или потерять время на дефиб.

### Решение

Ускорить скорую до скорости обычного человека. Или даже чуть быстрее. Может даже дать возможность прикреплять больше одной тележки.

### Плюсы

Люди не будут игнорить скорую и её будет смысл использовать.

### Минусы

Никаких.

**Comment by Dreemer556** [comment]
1. За
2. Шикарная идея, что тут думать

**Comment by mayorovp** [comment]
> В итоге скорая нужна только если тело истекает кровью, да и то спорно что хуже — истечь кровью или потерять время на дефиб.

А я просто открепляю тележку и таскаю её за собой. В итоге и кровью никто не истекает, и скорость не теряется.

Так что скорую нужно или ускорять, или убирать из игры (оставив тележку).
