### ISSUE TITLE
Bug: Усиленное плазма-стекло плавится

### ISSUE THREAD

**Issue by semoro** [ss220-space/Paradise#171]
### Ckey

Semoro

### Описание бага

Усиленное плазма-стеко плавится от температуры, обычное нет

https://github.com/RV666/Paradise/blob/b66446200c3e1498f4bc264cb488224311b7065e/code/game/objects/structures/window.dm#L578
https://github.com/RV666/Paradise/blob/b66446200c3e1498f4bc264cb488224311b7065e/code/game/objects/structures/window.dm#L586

### Шаги воспроизведения

---

### Ожидаемое поведение

Усиленное плазма-стекло не должно плавится

### Операционная система

Windows 10

### Версия клиента

---

### Название сервера

MAIN

### Примерное время и дата

20.07.2021

**Comment by botka4aet** [comment]
Ты проверил в самой игре?
Потому что в коде https://github.com/RV666/Paradise/blob/b66446200c3e1498f4bc264cb488224311b7065e/code/game/objects/structures/window.dm#L647 прописан возврат без всякого разрушения
