### ISSUE TITLE
Bug: Интеркомы не работают во время ионосферной аномалии

### ISSUE THREAD

**Issue by semoro** [ss220-space/Paradise#172]
### Ckey

Semoro

### Описание бага

Интеркомы не работают во время ионосферной аномалии

### Шаги воспроизведения

Тест на локалке:
 - Вызываем ионосферную аномалию
 - Включаем hot mic на интеркоме, не видим сообщений

### Ожидаемое поведение

Интеркомы работают

### Операционная система

Windows 10

### Версия клиента

---

### Название сервера

MAIN

### Примерное время и дата

---

**Comment by mayorovp** [comment]
Дополнительная информация: интеркомы работают на "Коробке", но не работают на Дельте.

Иными словами, они работают на сервере EX, но не работают на WL. А раньше (до смены карты) на WL тоже работали.
