### ISSUE TITLE
Feat: Интегралочки на парашизу

### ISSUE THREAD

**Issue by Predeiter** [ss220-space/Paradise#174]
### Проблема

Хочу предложить добавить на парадайс систему и механики интегральных схем из фиников/ТГ.
Хочется узнать кому еще интересно это.

### Решение

Свиснуть и адаптировать код из фиников(или с ТГ, вообще с ТГ было бы лучше из-за лучшего UI в составлении компонентов в сборке).

### Плюсы

Новый механ для РнД и разумистов. Больше возможностей для прошаренных.
Ну и возможно если хватит мозга сам же это и запилю.

### Минусы

Балансить это говно. Интегралки - слОжна. По-факту только для себя я их и предлагаю.

**Comment by Leck-Ti** [comment]
#Интегралочки на парашизу
За

**Comment by PhantornRU** [comment]
Я дурак и не понимаю что за интегралочки и что они делают. Как похоже и все кто читал эту предложку (большинство).

**Comment by Predeiter** [comment]
> Я дурак и не понимаю что за интегралочки и что они делают. Как похоже и все кто читал эту предложку (большинство).

http://wiki.infinity-ss13.info/index.php/%D0%98%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D1%86%D0%B5%D0%BF%D0%B8

**Comment by valldemar2017** [comment]
Полностью за.
Появиться больше контента для учёных, а то через час раунда обычно есть уже всё: все технологические уровни, включая иллегал и алиен; зелья из ксено на любой вкус и цвет; все меха, даже ХОНК. Из забот остаётся лишь унылая работа за стойкой на раздаче.
Можно будет хоть поломать голову и развечь себя после первого часа раунда.

**Comment by blind0** [comment]
Абсолютно точно за.
Топовая фича, с помощью которой можно мутить страшные вещи.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353593-c9bbe9a7-c64a-4c7c-97f3-ead78e616c94.png)
