### ISSUE TITLE
Feat: Ивент торговцев

### ISSUE THREAD

**Issue by EnjSadman** [ss220-space/Paradise#177]
### Проблема

В данный момент торговцы появляются очень редко, т.к. являются мажорным ивентом, и не спавнятся раньше определённого времени и делят своё место с такими мажорами как пауки террора, блоб и прочими.

### Решение

Переместить торговцев в категорию Moderate.Из того что я понял в коде модерейты с интервалом 30-45 минут с прошлого модерейта. Т.е. около ~10 ивентов за раунд. Задать небольшой вес, дабы избежать слишком частого выпадения.

### Плюсы

Чаще полезный ивент, с некоторым социальными взаимодействием.

### Минусы

Вероятно поломает некоторый баланс, начав выпадать слишком рано.

**Comment by FlyingFloor** [comment]
За.
Хоть торговца будет иногда видно. И поиграть за него, дай бог, получится.

**Comment by ZmeionishW** [comment]
Интересная идея. Нельзя не одобрить, ибо торговцы по ряду причин в данный момент, миф.

**Comment by Dreemer556** [comment]
За.
За всё время игры (230 часов) лишь один раз видел этот ивент в чате, но у нас был красный код, и лишь один раз видел вживую на стриме Муни. Проблема в том, что даже если он прилетит, то у нас красный код. Сколько раундов вы видели, что зелёный код больше получаса с момента победы над опасностью? Обычно каждые 5-10 минут генки или вампиры светятся, а потом пауки или блоб из-за чего красный код не падает весь раунд. По мне, над этим тоже надо думать

**Comment by PhantomMi3** [comment]
Отличная идея Я ЗА!
