### ISSUE TITLE
Дройды и СБ.

### ISSUE THREAD

**Issue by Zombara** [ss220-space/Paradise#178]
### Проблема

Много ли раз ты смотрел звездные войны война клонов? Если ты скучаешь по Дройдам. Решение есть.

### Решение

Решение. Добавить для БОрга СБ новую модельку: B2 Сб.

https://cdn.discordapp.com/attachments/866800055457284136/867097434698154014/vfV8KseiHM.gif

### Плюсы

Новая моделька бравого СБ, страх для клонов.

### Минусы

Тут их не нашел.

**Comment by OpsCoretango** [comment]
Я как зек ща буду по вульповски от досады выть о закрытии обсуждения предложки ааауууфф.

К делу:[https://thumbs.gfycat.com/WildPeacefulConure-size_restricted.gif](Оу Май)

**Comment by ZmeionishW** [comment]
Хорошая предложка. НИчего плохого в ней не вижу

**Comment by PhantornRU** [comment]
Роджер роджер.

**Comment by Dreemer556** [comment]
За. Красиво и прикольно. Лазерные мечи уже есть

**Comment by Zombara** [comment]
Предложение тоже в силе.

**Comment by Zombara** [comment]
Не потерялся.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353739-844c1453-263a-4d52-aa4d-e150a1cef683.png)
