### ISSUE TITLE
Feat: Переработка СРП

### ISSUE THREAD

**Issue by ZmeionishW** [ss220-space/Paradise#179]
### Проблема

Всем прекрасно известно, что СРП в нашем билде это во-первых, филькина грамота на тему того, что ты вроде как должен делать, а вроде как всем абсолютно на них похуй.
Зачем на практике нужно СРП? Чтобы попробовать иногда доебать глав, доебывать СРП СБ и крааааааайне редко кого-то другого типо роботехника. 
Что это за собой влечет? Итак, во-первых, шансы у АВД что-то сделать минимальны, потому что СРП либо идут нахуй(красный-синий код), или же они просто не охватывают большую часть действий. НТ-реп? Сколько играю, всего пару раз видел, чтобы НТ-реп замечал нарушение СРП от глав, при том, это было СРП Хопа.
Почему это проблема? А проблема в том, что у нас мидл-рп сервер, и из-за недостаточной прописанности СРП получается, что множество персонажей по рп получают деньги...за нихуя. Или же иной момент. Учёный, допустим, должен слушаться РД. Почему? Потому что ему в раунде пишется, что это его глава и его надо слушать. Все. Никаких прав как специалиста по своей работе у него нет,а у РД напротив, нет никаких обязанностей по проведению организационных работ в отделе. Вещи вроде выдачи задач своим отделам от РД являются частной инициативой, а не обязанностью. Что приводит к чему? А к тому, что мало того, что глава зачастую вообще не понимает, что происходит с его сотрудниками, выполняет работу отдела как персонаж с повышенным допуском. Все. Или же, в другом случае. Учёный может просто развернуться и уйти из РНД гулять по станции, ссылаясь на то, что он исследует состояние станции, что вообщем-то не будет нарушением вообще ничего, и если только РД прямым приказом не скажет ему что-то сделать, что впрочем обладает околонулевой силой из-за непрописанности, то он может пойдет что-то делать. И вы скажете, Ну он же обязан слушаться главу, он же обязан работать. Нет. Приписка в начале раунда что вы того-то слушаетесь, и вы тот-то тот, не является ничем значимым из-за того, что, опять таки, у тебя в всех ОФИЦИАЛЬНЫХ ДАННЫХ НА ВИКИ О ТОМ, В КАКОЙ СТЕПЕНИ ОН ДОЛЖЕН ВЫПОЛНЯТЬ СВОЮ РАБОТУ  И СЛУШАТЬСЯ ГЛАВУ СТОИТ РОВНОЕ НИХУЯ! РД может приказать, по такой логике. тебе пойти в туалет и посидеть там 30 минут, а за нарушение приказа уволить нахуй. 
Конечно это может казаться не очевидной проблемой, потому что все кладут на это хуй. И заходя за роль занимаются работой и стараются слушаться глав, потому что тебе может прилететь и в жбан и тд, но наличие каких-то относительно важных вещей на традициях и самомнении некоторой администрации не нормально.

### Решение

Планово переписать все СРП во всех отделах. Например: 
![image](https://user-images.githubusercontent.com/74469730/126404653-d98edd56-4d67-4766-be67-1b090fb1b2bb.png)
Тут изображено обычное СРП Учёного. Я предлагаю следующий вариант
ЗК
1. Вы обязаны слушать распоряжения РД относительно выполнении исследовательской работы, и исполнять их по мере сил
2. Вы обязаны выполнять свои рабочие обязанности до логического и адекватного результата, или же до достижения выполнения плана поставленого РД.
3. Учёному запрещается распространять опасные предметы за двери своего отдела(Гранаты, оружие, опасные экстракты...)
4. Учёный занимающийся исследованием токсинов должен получить разрешение у РД на тестовый взрыв, после чего предупредить весь остальной экипаж о проведении испытаний. В случае отсутствия РД, учёный должен предупредить командование о необходимости проведения испытания и провести его.
5.Учёным запрещено проносить на станцию аномальные объекты и проводить на них опыты своевольно без разрешения РД или же командования станции
6. Учёным запрещено создавать  Portable Wormhole Generator без разрешения РД.
7. Учёным запрещено выдавать импланты, оружейные кейсы, специфические инструменты(ЕКА, плазменный резак) без разрешения РД, исключая офицеров службы безопасности и ГСБ,
8. Учёным запрещено создавать платы для ИИ без разрешения РД или командования.
9. Учёным запрещается прекращать свою работу без весомых причин(Необходимость перекусить, получить мед.помощь) или без разрешения РД
10. РАспространение токсинных бомб дозволено только с разрешения РД или командования и только среди шахтёров и исследователей.
СК
Правила 1-10 переносятся из ЗК
11. Учёным разрешено переносить гранаты до арсенала по заказу отдела СБ.
12. Учёным предписывается запросить инструкции по проведению работы в текущей ситуации
КК
Правила 1-10 переносятся из ЗК
Правила 11-12 переносятся из СК
13.Учёные обязаны закрыть ставни и не покидать отдел до поступления особых распоряжений со стороны командования
14. Учёные обязаны прекратить все опасные исследования(Работы в эксп-е, проведение испытаний бомб, создания животных из золотого экстракта)
15. Учёным строго предписывается находится вместе и запрашивать инструкции у РД или командования о работе отдела в данной ситуации.
Вариант представлен как тестовый, так-как вероятнее всего я что-то упустил из вещей, которые необходимо внести в СРП учёного

### Плюсы

1. Всем будут кристально понятны свои задачи, действия в различных ситуациях.
2. АВД и НТ-реп смогут понимать что должен делать отдел в данный момент, у кого что спрашивать и как действовать и как замечать различные проблемы.
3. Клоуны на командовании и внутри отделов смогут гореть в аду намного быстрее и аргументированней. 

### Минусы

1. Душнилово по СРП
2. Придется писать новое СРП
3. Клоуны на педалях опять скажут, что грубое нарушение СРП без причины не признак долбоёба для банхамера, а рабочая схема, ибо СРП созданы чтобы их нарушать.

**Comment by tizer7** [comment]
Тут, есть проблема, что это дохуя работы для мозга. Ты продумай и перепиши на свое усмотрение всё СРП отделов и педали рассмотрят его. А вот это: "заставить переписать" - не прокатит.

**Comment by Sykybekk** [comment]
11-13 полнейшний бред.
Хочешь переписать срп, давай прописывай для каждого отдела админы глянут.

**Comment by ZmeionishW** [comment]
> Тут, есть проблема, что это дохуя работы для мозга. Ты продумай и перепиши на свое усмотрение всё СРП отделов и педали рассмотрят его. А вот это: "заставить переписать" - не прокатит.

Просто проблема в том, что я не очень хочу сидеть и переписывать все СРП, чтобы потом педоли сказали мне, что такой вариант им не нравится.  Я хочу чтобы предложение прошло голосовалку и я взял какую-либо педаль и начала сидеть с ней делать СРП.
Как люди не хотели писать лор, пока не было информации о том, что он будет принят и что это офицальный проект, так и тут.

**Comment by ZmeionishW** [comment]
> 11-13 полнейшний бред.
> Хочешь переписать срп, давай прописывай для каждого отдела админы глянут. К тому же наблюдается расхождение в твоём срп. В одном говорит нельзя выносить опасное из рнд, в другом уже можно

Ну да. Проеб вышел. Но я в целом предложил общую модель.

**Comment by Dreemer556** [comment]
В целом, есть положительные моменты. 1 и 2 правила мне нравятся, но всё другое спорно. Во-первых эот реально душка для игроков. Мы сюда пришли веселиться и чутка в работку долбиться, а не соблюдать сотни и сотни правил. Тот же КЗ имеет дыры благодаря которым ты можешь нарушать и обходить его но ни это ли простор для веселья? 
Дак ещё первые часов 20 за СЕ у меня пухла голова после каждого раунда от объёма информации, а тут оооооой. Даже привыкнув к нагрузке она у тебя будет пухнуть от объёма правил и информации. Для эксты - вполне хорошо, там ты только работаешь, а когда твою ногу доедает ксеноморф, капитан просит сменить законы ИИ, отдел взрывается, горит, всё сломано, выстрелы, крики это не нужно. А также в стрессовой ситуации все эти правила будут игнорироваться как главами, так и учёными, чтобы спасти свою жизнь, а это ли не плохо? 
СРП учёных я не знаю и за них не играл, но там вроде подразумевается всё это. Какие-то правила перекрывает КЗ, как например про гранаты, а что-то создаёт веселье из-за неопытного косяка новичка. Лично я получаю кайф от историй как например капитан сожравший какое-то сердце и превратился в большую ебаку за ему бан на время кинули. Или СБ-шник, который пиздит уборщика за его моющую гранату.

Спрашивать РД для создания инструментов для инженерии ну как-то сложно. Если каждый шахтёр, инженер, СБ-шник, эксплорер подойдёт и попросит спец вещь для работы, то хана мозгам РД отвечать на всё "Разрешаю". Про взрывы тоже. Это блин полигон, нафига предупреждать глав?
8 хорошо, но людям тоже нужно отдохнуть, по РП-шить, бухнуть, заняться фигнёй в конце концов. Я за СЕ катался на мул боте когда мне было скучно. Станция не сломалась, никто не работал (работы нема) и мы всем отделом поржали вместе с ИИ. Прикольно же

**Comment by ZmeionishW** [comment]
> В целом, есть положительные моменты. 1 и 2 правила мне нравятся, но всё другое спорно. Во-первых эот реально душка для игроков. Мы сюда пришли веселиться и чутка в работку долбиться, а не соблюдать сотни и сотни правил. Тот же КЗ имеет дыры благодаря которым ты можешь нарушать и обходить его но ни это ли простор для веселья?
> Дак ещё первые часов 20 за СЕ у меня пухла голова после каждого раунда от объёма информации, а тут оооооой. Даже привыкнув к нагрузке она у тебя будет пухнуть от объёма правил и информации. Для эксты - вполне хорошо, там ты только работаешь, а когда твою ногу доедает ксеноморф, капитан просит сменить законы ИИ, отдел взрывается, горит, всё сломано, выстрелы, крики это не нужно. А также в стрессовой ситуации все эти правила будут игнорироваться как главами, так и учёными, чтобы спасти свою жизнь, а это ли не плохо?
> СРП учёных я не знаю и за них не играл, но там вроде подразумевается всё это. Какие-то правила перекрывает КЗ, как например про гранаты, а что-то создаёт веселье из-за неопытного косяка новичка. Лично я получаю кайф от историй как например капитан сожравший какое-то сердце и превратился в большую ебаку за ему бан на время кинули. Или СБ-шник, который пиздит уборщика за его моющую гранату.
> 
> Спрашивать РД для создания инструментов для инженерии ну как-то сложно. Если каждый шахтёр, инженер, СБ-шник, эксплорер подойдёт и попросит спец вещь для работы, то хана мозгам РД отвечать на всё "Разрешаю". Про взрывы тоже. Это блин полигон, нафига предупреждать глав?
> 8 хорошо, но людям тоже нужно отдохнуть, по РП-шить, бухнуть, заняться фигнёй в конце концов. Я за СЕ катался на мул боте когда мне было скучно. Станция не сломалась, никто не работал (работы нема) и мы всем отделом поржали вместе с ИИ. Прикольно же

Ну душнилово будет не такое сильное как кажется, а в нынешнем виде СРП просто филькина грамота которая нарушается всеми. Довведение строгих СРП не обязательно означает что ты обязан следовать каждому пункту в полной мере,а  скорее дает пространство для действий с точки зрения бюрократии и РП, а так же позволяет приструнить тех игроков, которые заходят не поиграть в игру по её правилам, а заходят хуйней пострадать.

**Comment by ZmeionishW** [comment]
И основная проблема не в том, что ты страдаешь хуйней. А в том, что страдая хуетой ты мешаешь играть остальным. Сделал свои уровни исследований и иди чиль отдыхай по станции до востребования. Сделал заказ РД в химии РНД? Ну делай свои вещи или чиль. Никто же не мешает.

**Comment by rebel228** [comment]
Разделю твое предложение на две части.

Во первых ты по сути добавил два положения:
а) Нужно работать на работе
б) Нужно слушаться начальника
Зачем перечислять в СПР очевидное? Если человек просто берет профу ради доступа и в принципе на рабочем месте больше не появляется, то к нему будут вопросы со стороны администрации. Если человек в случае возникновения критической ситуации где от него нужны действия по профессии их не делает (инженер не запускает движок, медик не работает когда в медбее тела лежат штабелями) то так же к нему будут вопросы.
Умеренно отлынивать от работы и чиллить, когда нет острой нужды - часть игры и главам не нужны дополнительные пункты СРП что бы их уволить. 

Во вторых в примере ты поужесточал все остальные СРП. Когда ничего нельзя и на всё нужно спрашивать разрешение это не будет интересно ни рядовым сотрудникам, ни главам, которых будут постоянно донимать по пустякам.

Проблема не в СРП. СРП регулируют особые процедуры, специфичные для каждого отдела, а не являются армейским уставом.
Если АВД и НТ реп не разбираются в СРП и наплевательски относятся к их нарушению, то это не очень качественный отыгрышь с их стороны и всё.

**Comment by Danefalt** [comment]
Есть одна проблема.
Если переписывать СРП, то нужно чтобы оно не противоречивало само себе. А для этого нужно либо жёстко курировать всю команду, либо же дать одному человеку писать его. Так что тут уж как выйдет.

**Comment by ZmeionishW** [comment]
> Разделю твое предложение на две части.
> 
> Во первых ты по сути добавил два положения:
> а) Нужно работать на работе
> б) Нужно слушаться начальника
> Зачем перечислять в СПР очевидное? Если человек просто берет профу ради доступа и в принципе на рабочем месте больше не появляется, то к нему будут вопросы со стороны администрации. Если человек в случае возникновения критической ситуации где от него нужны действия по профессии их не делает (инженер не запускает движок, медик не работает когда в медбее тела лежат штабелями) то так же к нему будут вопросы.
> Умеренно отлынивать от работы и чиллить, когда нет острой нужды - часть игры и главам не нужны дополнительные пункты СРП что бы их уволить.
> 
> Во вторых в примере ты поужесточал все остальные СРП. Когда ничего нельзя и на всё нужно спрашивать разрешение это не будет интересно ни рядовым сотрудникам, ни главам, которых будут постоянно донимать по пустякам.
> 
> Проблема не в СРП. СРП регулируют особые процедуры, специфичные для каждого отдела, а не являются армейским уставом.
> Если АВД и НТ реп не разбираются в СРП и наплевательски относятся к их нарушению, то это не очень качественный отыгрышь с их стороны и всё.

СРП* Это не особые процедуры и специфика отдела, а СТАНДАРТНЫЕ РАБОЧИЕ ПРОЦЕДУРЫ. Допустим ситуация которая была у меня. У нас пауки террора(По обьяве) Красный код. Я за роботехника вбегаю в РНД чтобы распечатать 2 нужные штуки для дюры. Там стоит РД который делает диски. Для карго. При пауках террора. Допустим он хотел, чтобы у них были очки чтобы заказать оружие, но давай взглянем 2 час раунда и поймем, что у них есть очки для заказа. РД начинает устраивать гачи разговоры за это мешая, очевидно, бороться за живучесть станции. В тот раз я рискнул жизнь за 5 минут до этого проскочив к пауку террора, что пытался залить плазмой все РНД из-за чего чуть не откис. Он меня за это все увольняет. Простая практика, если прописать конкретные действия(Я не стал вносить подобного рода вещи в тестовое СРП, так как это требует обсуждения с администрацией) то можно было бы в СРП прописать обязанность делать мехов, что привело бы к тому, что РД не мог бы меня уволить, так как он по факту мешал бы исполнять мое СРП.
СРП может дать большой простор для отыгрыша, защищая одного сотрудника от его главы в случае личного или не очень конфликта. Или же защищая главу от капитана.
То что администрация будет банить тех, кто страдает хуйней на рольке, конечно хорошо. Но тот факт, что в данный момент главы увольняют людей потому что так логично, а не потому что они не выполняют свои ПРОПИСАННЫЕ обязанности.
В данный момент, судя по логике. Если РД скажет учёному кабанчиком метнуться за ресурсами, а учёный скажет что ему лень ходить за ресами и вообще этим занимается его коллега....Ну РД имеет полное право его уволить за непослушание. По хуйне, по сути, но имеет.
Насчёт АВД И НТ-репа. ОНи по факту не выполняют свою деятельность. Единственные люди которых можно душить и проверять по СРП достаточно хорошо это СБ, Сколько играл на главах, НТ-реп не следил на выполнением СРП глав(потому что их практически нет), а являлся звеном переговоров с НТ.

**Comment by ZmeionishW** [comment]
> Есть одна проблема.
> Если переписывать СРП, то нужно чтобы оно не противоречивало само себе. А для этого нужно либо жёстко курировать всю команду, либо же дать одному человеку писать его. Так что тут уж как выйдет.

Ну я предполагал, что если предложка пройдет, то я возьму вахтёра стула, лучшую педаль таума и будем кумекать как СРП прописать. Впрочем, ЧСВ Стула может не позволить ему опуститься до СРП, а таумчик будет занят ивентами и тем как их провести

**Comment by Danefalt** [comment]
> > Есть одна проблема.
> > Если переписывать СРП, то нужно чтобы оно не противоречивало само себе. А для этого нужно либо жёстко курировать всю команду, либо же дать одному человеку писать его. Так что тут уж как выйдет.
> 
> Ну я предполагал, что если предложка пройдет, то я возьму вахтёра стула, лучшую педаль таума и будем кумекать как СРП прописать. Впрочем, ЧСВ Стула может не позволить ему опуститься до СРП, а таумчик будет занят ивентами и тем как их провести

Опять всё самой делать...

**Comment by blind0** [comment]
**Мнение:**

Абсолютно точно против данной затеи, ибо по-моему смысол срп скорее не в том, чтоб всех заставить играть по правилам, а в том, чтобы иметь причину отсеять долбоёбов, которые только и делают что рул 0 нарушают.
Введение такого срп, как предложил ТС, убьёт наглухо любую возможность для самодеятельности, что в следствии убьёт желание играть в такую сосаку13.


**Так же по пунктам:**

- Для бюрократии у нас есть хоп, авд и главы, не надо эту скучную поеботу во все роли пихать.
- После такого рефакторинга срп, серв перейдёт из разряда мидрп в хардрп, онлайн просядет до нуля, все съебутся на более вменяемые сервера.
- Если тебе так хочется более глубокого отыгрыша и соблюдения правил, надо идти на специализированные сервера, а не менять этот серв под свои нужды.
- Главный смысл всех правил, стандартов и прочего, это дать игрокам понять, как надо делать, чтобы всем игралось хорошо и если чел отходит от этих устоев не мешая никому играть, это не должно наказываться.


**Итог:**

- Автор нонкреатив хардрпшер, выпей йаду!
- Весь топик не имеет смысла, закрывайте его и кидайте в мусорку.

**Comment by PhantornRU** [comment]
Против.
Работай на работе, слушай начальства, без начальства ничего не делай. Работай работку. Работай.
Но чувак. Я пришел играть в игру, а не в работку? Работка это часть геймплея чтобы играть в игру. Играть в СС13, а не симулятор космического ученого из реальной жизни. Я пришел сюда веселиться, а не слушать и слышать везде странные пункты СРП которые толком не запомнишь все, так как хватит одного запоминания "работай и ничего не делай".
Миддл РП сервер на то и Миддл что идёт твой полёт фантазии, а твоя предложка для Хард РП. Не делай из Миддла - Хард. Это не всем нравится. И уж поверь, я с этим знаком очень тесно на кучи проектах в разных играх.
+ предложка невнятная. Нужно что-то переделать чтобы оно было для чего-то. Что? Если уж предлагаешь, дык внеси все предложки и пропиши каждый пункт. Или за тебя должны банальной писаниной заняться? Это ж даже не кодинг и мапинг. Написать пару строчек каждый может или задать хотя бы примерный вектор направления переработки СРП каждого отдела.

**Comment by ZmeionishW** [comment]
Ну окей, предложка в жизни не пройдет голосовач и все будет печально, а почему? А потому что набежало стадо пусечек, которые вообщем-то никогда отвественно на мид-рп не играли, скорее всего, и не будут.
Никого никогда не смущает то, что отношения работника с его главой и работой абсолютно не регломентированы и в принципе, увольнять глава может по любой хуйне устраивая душню и с другой стороны, у главы не очень большой простор для командования. Потому что причин на увольнение у главы нет, кроме как неподчинение приказу(Согласно нынешнему СРП зачастую) При этом если у работника происходит личный конфликт с главой, то вообщем-то он сразу может собирать вещички, ему ничто не поможет. Впрочем, если глава хочет выполнять свои командные обязанности, а капитану что-то там не нравится, то ты сосешь бибу. Всегда.
НТ-реп и АВД так же останутся абсолютно бесполезными профами, потому что пуси выше не играли то на этих должностях и их прямое назначение никогда не выполняли.
Вообщем-то. Уважаемое Шуссойд-комьюнити которое пришло сюда за фаном и бояться Хай-рп.
Наверное когда допишут Лор и заставят ему следовать, они тоже будут ныть про хай-рп.
Хотя вообщем-то хорошие и прописанные СРП просто дадут возможность увеличить пространство дял игры у каждой роли.

**Comment by blind0** [comment]
Блять, твоё "upgraженое" срп приведёт только к одному, мозгоебли от долбоёбов, которые дрочат на СРП, начнётся тотальное душнилово, людям просто будет не интересно играть, весь балдёж от сосаки просто пропадёт, всё скатится в ебанутую рутину и работкодрочерство, люди будут боятся лишний шаг сделать, чтобы не быть выебанными бюрократами, но да есть плюс, авд и нтр, отныне будут рулить всей станцией, ибо что не так, они сразу выкатят жалобу и в зависимости от того насколько сильно ты провинился, тебя либо уволят, либо жалоба полетить педалям и тебе вбанят роль.
Ну и нахуя такую  игру надо? Как сказали ранее, если тебе нравится хайРП, иди на хайРП сервера, нахуя этот серв под свои хотелки менять?

**Comment by ZmeionishW** [comment]
> Блять, твоё "upgraженое" срп приведёт только к одному, мозгоебли от долбоёбов, которые дрочат на СРП, начнётся тотальное душнилово, людям просто будет не интересно играть, весь балдёж от сосаки просто пропадёт, всё скатится в ебанутую рутину и работкодрочерство, люди будут боятся лишний шаг сделать, чтобы не быть выебанными б

Очнись братишка, ты обосрался. Если у тебя будет прописанное СРП тебя будет за что по фактам ебать. Сейчас тебя на любой рольке могут ебать за просто так.
Передланное СРП серьёзно игру не изменит, а просто даст простор бюрократам, позволит тебе же одарённый послать нахуй свою главу, если он требует какую-то не логичную хуету.

**Comment by blind0** [comment]
> > Блять, твоё "upgraженое" срп приведёт только к одному, мозгоебли от долбоёбов, которые дрочат на СРП, начнётся тотальное душнилово, людям просто будет не интересно играть, весь балдёж от сосаки просто пропадёт, всё скатится в ебанутую рутину и работкодрочерство, люди будут боятся лишний шаг сделать, чтобы не быть выебанными б
> 
> Очнись братишка, ты обосрался. Если у тебя будет прописанное СРП тебя будет за что по фактам ебать. Сейчас тебя на любой рольке могут ебать за просто так.
> Передланное СРП серьёзно игру не изменит, а просто даст простор бюрократам, позволит тебе же одарённый послать нахуй свою главу, если он требует какую-то не логичную хуету.

Ты понимаешь что эта ебля по фактам, спокойно будет в обратку лететь?  просто сервер превратится в СССР времён Сталина, постоянная атмосфера доносов, а наши великие партийные вожди АВД,НТР, будут рулить всем.
Твоё переделанное СРП, серьёзно игру не изменит только для тебя, место бюрократов сейчас у параши, и то у них даже 
 сейчас достаточно простора для действий, а ты просто хочешь выдать им абсолютную власть.
 
Послать нахуй главу за нелогичную хуйню можно и сейчас, для этого не нужно прописанное СРП, а просто по тем же фактам расписываешь почему глава долбоёб и идёт нахуй, если он тебя увольняет идёшь к тому же АВД, ну либо 
в меру самоантажишься и бананы под главу который тебя демоутнул кидаешь, тут уже огромный простор для творчества.
 
 Ну и в текущих реалиях, я пока не встречал глав уёбков, которые бы демоутили по хуйне, чтоб тебя демоутнули нужно либо быть диким душнилой, либо отбитым долбоёбом. 
 
 Людей надо направлять, как играть, чтоб всем вкатывало, а не вводить кучу тупых правил, протоколов, чтобы тупо ограничивать их свободу действий.
 
 Такшо, очнись братишка, ты хуйню запостил.

**Comment by Frozored** [comment]
Предложение описывает ситуации, которые чисто теоретически могут происходить _(иди и сиди в туалете)_, но будут нарушать Rule 4, за которое у нас на сервере банят. За систематическое нарушение СРП, кстати, тоже бан. Я против. Свою идею можете закинуть в деструктивный анализатор, но вряд ли она нам что-то прокачает.
/thread

**Comment by Daymonchemist** [comment]
**Мнение**

Частично за это предложение, так как сам вынашиваю мысли об изменении срп и добавлении бюрократии в медицинский отдел. 

Идея в своей сути неплохая, однако нужно выделить грань между адекватно прописанным СРП и реальным душением игроков, как писали до меня. Внесение пункта о подчинении своему главе будет логичным. Обязать всех работать - не правильно. 
В целом, мне кажется будет правильно дать отделам немного бюрократии. Еще раз - НЕМНОГО. Буквально заполнить форму о проделанной работе или что-то вроде того, чтобы велся учет потраченных ресурсов. Это логично с точки зрения мира, это даст больше возможностей бюрократам по типу авд, в то же время это не обременит самих игроков, которым надо будет заполнить за игру 5 одинаковых бумажек, ух ты. 

Также может имеет смысл дождаться лора, под него дописать срп.

Если сухо теперь

**Плюсы**

- Улучшение логики мира
- Работа для АВД и НТР
- Улучшение системы бюрократии на сервере
- Возможность использовать бюрократию в рп
- Отношение к бумажкам не как к бумажкам, а документам

**Минусы**

- Ужесточение бюрократии
- Замедление из-за нее игрового процесса
- Необходимость переписывать, а потом переучивать срп
- При неадекватном ужесточении - душнилово
- Отношение к бумажкам не как к бумажкам, а документам

Со своей стороны готов помогать в переписывании, если до этого дойдет. Если кому потребуется - пингуйте, кину варик для меда свой, как только додумаю его

**Comment by Artrery** [comment]
Не могу точно сказать как отношусь к данному предложению но скорее отрицательно чем положительно. Моё мнение что новое СРП было бы желательно, но очень важно, и ещё раз для особо одарённых ОЧЕНЬ ВАЖНО, провести грань между более подробно прописанными СРП которые дополняют игровой процесс и сраной душниловкой которую никто не любит. Поэтому я считаю что приведённый ТСом пример чересчур душный, но СРП дополнить всё таки стоит

- ТС душный бюрократ и фанат времён сталина.

- Хотим СРП но не слишком душное.

P.S.
Поддерживаю Daymonchemist

**Comment by ZmeionishW** [comment]
Прошу опять обратить внимание, что представленный вариант срп не окончательный и само срп будет написано в содействии с админами, что означает что оно будет продуманным и не слишком душным.

**Comment by BingoPlotva** [comment]
**Мнение**

Изначально я был против этого предложения, так как во-первых: по своей сути нынешнее СРП не создавало никаких проблем и гармонично выстраивало отношения между работником и главой. Во-вторых: в случае нарушений или проблем с сотрудниками в отделе, то их решали при помощи АВД и представитель НТ никогда не оставался в стороне от работы станции. Зачем менять СРП, которое и так нормально работало, и с которым не возникало до этого проблем ? Для меня остаётся загадкой. 
 
К тому же, автор не упоминает, какие наказания будут следовать за определённые нарушения СРП (будет ли просто уволен сотрудник, выплатит ли он штраф или он отлетит после бана? ), нет всё ещё плана и более подробного списка СРП всех отделов и, тем паче, станции, и если за него проголосуют, то это будет игра в рулетку, где после  поправки СРП могут быть ещё хуже нынешних, но назад уже не отозвать предложение. 

И также, судя по предложению, автор планирует из медиум-РП сервер перенести в Хард-РП. Здесь уже дело каждого, но следует понимать, что после изменений на сервере будет больше: духоты, нытья, жалоб, банов и конфликтов. При чём, если СРП будет регулировать каждую мелочь, а не трактоваться универсально, то это будет настоящий АД для всех. 

Но после своих рассуждений и выводов, я передумал и решил поддержать предложение: 

1. Больше духоты для работы админов и автору. 
2. Ещё больше жалоб, которые будет разбирать Стул. 
3. Отток игроков, которые всё же решили отдать предпочтение реальной жизни, а не изучению несколько сотен страниц СРП. 
4. Аннигиляция любого, который отойдёт от плана системы. 
5. Теперь НТР и АВД 24/7 будут унижать любого игрока, который не знает, как оформлять документы. 

И мне так понравилось обозримое будущее для нашего сервера ШуссоПарадайзБанд220, что решил поддержать предложение (хотя о какой СРП  и зарплате сотрудника может идти речь, когда у нас даже экономики нет нормальной, но это не важно). 
Я надеюсь, что духота будет настолько непереносимой, что даже самый стойкий начнёт задыхаться и помирать, и  такую забаву не хочется пропускать. Возможно, я смогу увидеть цирк с уставами, как в настоящей армии, в котором учёные будут умирать в своих отделах из-за того, что РД и руководство партии не разрешило их выпускать, пока они не выполнят задачу по созданию силовой брони, на которую уйдёт 510 лет.

**Comment by WannaGovna** [comment]
Мнение 
Идите нахуй с вашим СРП. Тут лор никак не допишут. 
Готового варианта нет, есть огрызок под РНД. А если переделывать РНД, то дописывать ещё СБ и Меду как минимум, что делать с ебланами из рассадника разумизма.
О чем головалка то Борь? О том, что СРП надо обновить? Са в курсе как бы.

**Comment by ZmeionishW** [comment]
> Мнение
> Идите нахуй с вашим СРП. Тут лор никак не допишут.
> Готового варианта нет, есть огрызок под РНД. А если переделывать РНД, то дописывать ещё СБ и Меду как минимум, что делать с ебланами из рассадника разумизма.
> О чем головалка то Борь? О том, что СРП надо обновить? Са в курсе как бы.

Понял-Принял. Пошел ты нахуй.

**Comment by AIDATA1** [comment]
#Переработка СРП
Плюсы по моему мнению: 
1. Возможность раскрыть полный потенциал АВД и НТР.
2. Хоть какое то РП будет с главами отделом и самих глав между собой(потому что придётся коммуницировать между собой чтобы отдел функционировал как отдел, а не просто помещение.)
3. Свобода отыгрыша: Звучит как парадокс, но когда что либо находится в жестких рамках, начинаешь думать как это обойти(возможно интересно различным бунтарям/триторам) или как можно обыграть ситуации возникшие.
4. Главы почувствуют себя главами, а не ребятами с доп доступом. Возможность вести отчётность от отдела(каждого подразделения), добавит серьезности и ответственности за действия. 

Минусы по моему мнению:
1. Сложность СРП: Много людей не любят СРП потому что это будет дроч бумажек, это заставит людей ДУМАТЬ. 
2. Создание нового СРП должно быть очень продуманным, а это и время и люди должны быть задействованы. Не будет смысла если СРП не будет охватывать весь спектр професси для которой написан(в стандартной ситуации конечно)
3. Меньше экшена: Делая СРП более продуманным, возможно столкнёмся с тем, что придётся лишиться некой «мобильности», ввиду свободного гуляния вне отдела или просто ни хрена не делания.

P.S Считаю важным предложением, потому возможно список будет обновляться

**Comment by PoTapkam** [comment]
Против. Я сам играю за РД и так душнила, что у тебя отделы постоянно тебя доебывают спрашивают, что делать и т.д, а тут еще такая залупа будет. Тем более когда будет красный код и станцию будут ебать всем похуй будет на СРП абсолютно, когда блоб будет доедать станцию, когда пауки терроров будут ебать отделы и сжирать экипаж и т.д. А ща в ЗК и так нормально, тогда еще для ЗК пропишите для новичков, что выдавать нельзя, поскольку новички могут, что то выдать из за своего незнания не тем лицам, тип те же кейсы с оружием могут выдать или платы ИИ и т.д. Тогда они сходу в бан отправятся, зашел как то новичок за ученого выдал один кейс и отправился в бан KEKW.

РД и так работает за весь отдел, а тут еще СРП такое. Теперь прежде чем устраивать кого то на ученого через РД надо спрашивать все СРП KEKW ржака. Тот же экстракт который серебряный из ксено не опасен, но может ослепить нахрен всех, ну че еду создает чего бухтеть. 

Там уже был в  принципе выше разговор за то, что РД будет " РД тут инженер пришел можно ему инструменты?" " РД тут еще один инженер пришел можно ему тоже инструменты?" " РД тут инженер просит квадратичные конденсаторы выдать можно ему?" " РД тут уборщик для тележки просит апгрейд можно ему?" "А еще швабру просит можно ему выдать?" "РД тут зелья просит инженер можно выдать?" (сразу множим эту фразу на х100) ну и все в таком духе. 

Платы ИИ и так ни кому не выдают, а если кому то очень надо, они и так спиздят или сделаю их. Экспрементатором и так никто не пользуется практически от него толку нету вообще. 

Давайте запретим химию в РНД в красный код, ведь если она рванет дополнительная угроза как ни как. А также все баки в токсинах, сперва ставим МШ, потом выдаем один бак на руки, хочешь еще бак, ставим уже трекер и т.д 

Давайте тогда еще пропишем Механику такое же СРП, поскольку у него обычно в 90% случае стоит пролат и он к себе таскает ресы, а то как то не хорошо получается. В этом СРП пернуть нельзя без позволения РД, таким макаром давайте напишем в СРП СБ, что Офицеры не могут задерживать преступников без разрешения ГСБ. 

-ГСБ тут человек с дробовика убивает людей, нам его задерживать?
-ГСБ прием? 
-Ну ГСБ не отвечает значит пусть

В этот момент ГСБ помирает в бриге. 

Как будет выглядеть СРП для меда 

-СМО можно я сделаю кислоту для медикаментов?
-СМО можно я сделаю такой то реагент для такого?
-СМО можно я органы абдукторов вырежу из пациентов? 
-СМО тут мертвые офицеры можно их клонировать?
-СМО тут яд паука можно я вколю ему противоядие? 
-СМО сходите за едой, а то я по СРП из отдела не могу уйти до кухни. 

Ну поорали и хватит, на самом деле какие то адекватные правки еще возможны, но точно не данные которые тут привел автор.

**Comment by DayBreakerBrony** [comment]
Знаете, тут даже клувни ванну говна вылил. А так предложение дельное, сам играю за закон и чувствую, что на станции нету крепкой бюрократической хватки, которая была бы очень присуща для такого серьёзного филиала НТ. СРП некоторых отделов (РД, мед) лучше оставить нетронутым или облегчить, или ужесточить, но только в некоторых пунктах и взамен на облегчение, а вот СРП закона, сб, и прочей хуеты надо серьёзно ужесточить. Если в армии раздолбаи, а юрист диплом купил, какой от них толк? Ебантяи ходят. А РНД технологии развивает, там нужны творческие люди с чистыми мозгами, в которых мало рамок. Ну, вы понимаете суть. Ничто не должно в СРП мешать игроку выполнять его работу. А то будет ещё: ГСБ разрешите человечЬка за драку посадить :pepeRot:, ГСБ разрешите бригмеду стол поставить :NOPErot:
я готов помочь писать СРП закона или СБ, если вам надо. Celestian_Priest#5776 или известный в узких кругах "бригед, наколи мне купола"

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353816-0fd7d162-547f-4d79-ac79-75130d7cd573.png)
