### ISSUE TITLE
Пятница 13

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#182]
### Проблема

Добавить раундстартовый ивент с ТГ, где все сотрудники станции просыпаются в случайных местах (в том числе и техах), при этом в стельку. В тоже время по всей станции разбросанно пиво, и всё в рвоте.

### Решение

Просто смержить код со скайрата, может сделать некоторые правки. 

### Плюсы

Рофельное начало раунда.

### Минусы

Рофельное начало раунда.

**Comment by mayorovp** [comment]
Капитана надо в таком случае спавнить в шаттле прибытия и трезвыми. Вроде как он только прибыл на станцию, а там такое...

**Comment by PhantomMi3** [comment]
ДА ! 
ЭТО ГЕНИАЛЬНО!!!
Я за!
