### ISSUE TITLE
Feat: Переработка Шепелявости и Chav

### ISSUE THREAD

**Issue by JokerLul** [ss220-space/Paradise#184]
### Проблема

Бесполезность генов "Шепелявость" и "Chav", так как они сделаны для англоговорящих серверов, а у нас сервер для СНГ. 
![image](https://user-images.githubusercontent.com/87811301/126633991-0e156968-2a15-49d6-bec8-f9c2c8bf6738.png)
![image](https://user-images.githubusercontent.com/87811301/126634033-25185e5b-ea39-435c-8feb-a05879dce781.png)

### Решение

У шепелявости сделать так, чтобы буква "С" заменялась на "Ф". Chav (Унизительное прозвище определённой группы молодых людей в Великобритании, гопота по нашему) предлагаю либо полностью адаптировать на русский, чтобы ряд слов заменялись русскими аналогами, что сложно, либо просто заменить ген на Lizard/Xenos, чтобы буквы "С" и "Ш" многократно дублировались, как у унатхов (Шшшшшахтер, принесссси ресссссссурсы)

### Плюсы

Неработающие гены начнут работать и будут оказывать на носителя эффекты речи, схожие к первоначальным

### Минусы

Больше клоунов у окна генетиков

**Comment by mayorovp** [comment]
Предлагаю следующую таблицу замены:

вместо - заместо
его - ивоный
её - иёный
их - ихний

Также в случайное место предложения надо вставлять обособленное слово-паразит, одно из списка:

впринцепе
вабще
вкраце

**Comment by dj-34** [comment]
Накидайте еще предложений

**Comment by Daymonchemist** [comment]
Можно добавить всякие междометия, как у сильного акцента вульп идет "Bork!"
Например: нах, мля и тд

В качестве именно замены слов: 
Ок, хорошо = четко, базар
Ладно = лады

А дальше просто идем копипастить феню:
Повар = батя
револьвер/ствол = волына
Убил = грохнул, завалил
Дурак, идиот = валет
Труп = жмур
Пистолет = зажигалка
Друг = кадр
Испуглася = очко заиграло
Бриг = кича

**Comment by mayorovp** [comment]
А давайте не будем смешивать феню и безграмотность? Надо что-то одно оставить...

**Comment by DayBreakerBrony** [comment]
раз уж это именно гопота, то оставить надо именно феню

**Comment by Danefalt** [comment]
> Предлагаю следующую таблицу замены:
> 
> вместо - заместо
> его - ивоный
> её - иёный
> их - ихний
> 
> Также в случайное место предложения надо вставлять обособленное слово-паразит, одно из списка:
> 
> впринцепе
> вабще
> вкраце

вашний
Нашний
Залазий
Перелазий
Кароче

**Comment by mayorovp** [comment]
> раз уж это именно гопота, то оставить надо именно феню

Так-то да, но меня смущает тот факт, что феня - отдельный язык, и ему надо учиться. Не представляю как знание фени можно добавить на генном уровне.

А вот "ген безграмотности"  выглядит куда реалистичнее - гормон там допустим какой-нибудь вырабатывается, который угнетает определённые доли мозга.

**Comment by JokerLul** [comment]
> > раз уж это именно гопота, то оставить надо именно феню
> 
> Так-то да, но меня смущает тот факт, что феня - отдельный язык, и ему надо учиться. Не представляю как знание фени можно добавить на генном уровне.
> 
> А вот "ген безграмотности" выглядит куда реалистичнее - гормон там допустим какой-нибудь вырабатывается, который угнетает определённые доли коры мозга.

Chav по сути уже является геном, который заставляет англоговорящего игрока говорить как гопник. Нам лишь нужно чтобы игрок был русскоговорящим, а как знание тех или иных слов можно привить генами это уже вопрос десятый...Chav же вывели, вот и феня будет. Вообще феня звучит круто, Daymonchemist накидал крутые примеры, жаль мы не знаем какие слова заменяются в английской версии, чтоб хотя бы знать, что адаптировать, а пытаться испохабить каждое слово практически нереально, русский язык он так-то богатый...

**Comment by mayorovp** [comment]
В оригинале список вот такой: 

https://github.com/ParadiseSS13/Paradise/blob/beca3b43b5fee41c6833ef35d03ce6174ae8dfe1/code/game/dna/mutations/disabilities.dm#L308-L368

**Comment by JokerLul** [comment]
Ну если опираться на список, то примерно так:
Арестовать - Повязать
Плохо - Хреново
Бар - Кабак
Ломать - Раздолбать
Круто - Балдеж
Убить - Грохнуть
Тюрьма - Зона
Выпить - Бухнуть
Драка - Махач
Еда - Хавка
Поесть, покушать - Пожрать/похавать
Друг - Кореш
Мужик - Чувак
Привет - Здарова
Здраствуйте/Здрасьте - Салам Алейкум
Да - Агась
Нет - Не
Офицер - Служивый
Украсть - Стащить
Устать - Задолбаться
Сигареты - Сижки
Зажигалка - Жига

Понимаю, что склоняемые существительные нужно будет писать по 6 раз из-за падежей, а глаголы по 3 раза в разных временах. Большинство слов из списка скипнул, потому что их адекватно локализировать на руский просто невозможно. Предлагайте синонимы к профессиям и сокращениям глав, а также слова, которые часто используются на сервере. Не нужно заменять и писать уже имеющиеся жаргонные слова, типа Клонилка - Мать труба. Также не заменяйте слова на слова другого рода, типа Мозг - Извилина, потому что если кто-то скажет: "нужен новый мозг" это прозвучит как "нужен новый извилина". Также можете предлагать другие варианты уже предложенных мною слов

**Comment by DayBreakerBrony** [comment]
умереть - зажмуриться)

**Comment by mayorovp** [comment]
Мне нравится список от @JokerLul, надо только добавить туда предложение с междометиями от @Daymonchemist и убрать "Салам Алейкум", поскольку последнее звучит слишком интеллигентно.

**Comment by mayorovp** [comment]
Ещё можно добавить грубости в названия рас:

человек - ???
грей - ???
диона - дерево
кидан - жук
КПБ - жестянка
плазмамен - ???
скрелл - ???
слаймомен - ???
таяра - киска
унатх - ???
вокс - ???
вульпа - псина
драск - ???

**Comment by DayBreakerBrony** [comment]
плазмамен - факел
слаймомен - желе
грей - серый, чужой, пришелюга
человек - хуман

**Comment by Def0lt13** [comment]
Туалет - гальюн

**Comment by mayorovp** [comment]
А морские термины-то тут каким боком?

**Comment by Zigamus** [comment]
> Так-то да, но меня смущает тот факт, что феня - отдельный язык, и ему надо учиться. Не представляю как знание фени можно добавить на генном уровне.


У русских феня заложена прямо в гены.
