### ISSUE TITLE
Feat: Операционный стол в бригмед

### ISSUE THREAD

**Issue by EpicSider** [ss220-space/Paradise#186]
### Проблема
Проблема актуальна для Кербероса, насчет других серверов не в курсе.
Отсутствие операционного стола приводит к невозможности оказать полноценную помощь СБ и заключенным, т.к. часто их приносят с внутренними кровотечениями и переломами, а так же есть необходимость проверять на различные антаг атрибуты, по типу имплантов, треллов шедоулингов, бореров и .т.д.

### Решение

Поставить раундстартом в бригмед хотя бы операционный стол. В идеале конечно ещё набор хирурга, анастетик и компьютер, но это не обязательно. Почему именно раундстартом? Потому что неоднократно сталкивалась с полным игнором от инженеров на неоднократные просьбы установить ТОЛЬКО стол, который ставится буквально за 10 секунд, не требуя никаких инструментов или особых зап.частей и знаний по установке. Время ожидания инженеров доходили вплоть до двух часов, а в одном раунде и вовсе за три часа никто не пришел ставить, хотя я говорила 4 раза в радио и писала на пда главному инженеру. Еще раз повторюсь, это не единичный случай, такое постоянно, в зависимости от лени инженеров, один инженер, когда я его выцепила в меде так и сказал: "Простите, но мне лень". Бригмед и так работает один и без операционного стола таскать пациентов в мед для операции это трата времени, которого порой и так нет.

### Плюсы

Улучшения геймплея за бригмеда, экономия времени человека, избавляя его от бесполезных потуг призвать хоть кого-то на установку стола. 

### Минусы

Отсутствуют.

**Comment by tizer7** [comment]
на кушетке\столе обычном оперируй, ты же почти боевая единица. переносить трудности твоя работа. 
вот даже раздел на вики [гетто хирургия](https://ss220.space/wiki/index.php/%D0%A5%D0%B8%D1%80%D1%83%D1%80%D0%B3%D0%B8%D1%8F#.D0.93.D0.B5.D1.82.D1.82.D0.BE-.D1.85.D0.B8.D1.80.D1.83.D1.80.D0.B3.D0.B8.D1.8F) для этого есть. нежные какие все пошли.

**Comment by EpicSider** [comment]
Ты в адеквате, не? Мы работаем на супер продвинутой станции, и у меня из оборудования для операций кушетка? И мне кухонными ножами может еще операции проводить? Что за чушь ты несешь.

**Comment by EpicSider** [comment]
Кстати, раз уж зашла речь. В СРП бригмеда написано, что он обязан поддерживать чистоту в своем отсеке и бриге ц целом при необходимости, а чем? ему не дают ничего для этого. В то же время в меде как минимум 7штук клинеров стоит раундстартом.

**Comment by Sykybekk** [comment]
Ты медсестричка и всё, если что-то жёсткое то пора в мед

**Comment by DayBreakerBrony** [comment]
против.
не все бригмеды будут рады столу, т. к. каждый ставит его туда, где ему хочется.

**Comment by OpsCoretango** [comment]
> Кстати, раз уж зашла речь. В СРП бригмеда написано, что он обязан поддерживать чистоту в своем отсеке и бриге в целом при необходимости, а чем? ему не дают ничего для этого. В то же время в меде как минимум 7штук клинеров стоит раундстартом.

Попроси робоеба или по цепочке к хирургу имплант уборщика поставить. Реально решает.

**Comment by OpsCoretango** [comment]
> против.
> не все бригмеды будут рады столу, т. к. каждый ставит его туда, где ему хочется. 

Именно что не все, но когда ВСЕ, то отвлекают инжей а те должны еще пласаль взять но, ой я забыл пласталь "пошел в карго".

**Comment by AugustBebel** [comment]
ИМХО бригмеду не нужен операционный стол. Ну как не нужен — нужен конечно, но не нужен именно для прописанной в СРП работы — а именно латание избитых заключённых и реанимацию. По моему мнению бригмед — это медсестра/медбрат брига, а не уберспециалист во всех областях. НО! Если бригмед убергигачад, то он и оперстол себе выбьет и импланты для всего СБ достанет.

Короче, если инженеры не хотят работать, пиши жалобы их начальству и суетись. Оперстол хочется именно тебе, так что придётся приложить усилия. Нормальный ГСБ описается от счастья что бригмед профи и напичкает СБ имплантами без секса с очередями в меде.

**Comment by EpicSider** [comment]
Ой, вот вы конечно сказочники. По порядку: робоебы и импланты уборщика+хирурга: прихожу говорю робо, напечатайте импланты, в ответ: мы не печатаем ничего, идите в РНД, в рнд очередь из 9 человек, оно и понятно, ведь робоебы ничего не печатают. 18минут в очереди и импланты у меня, отлично, ищем свободного хирурга, в хирургии 2 человека стоят в оцереди на лечения кровотечений, ждем. Еще 35 минут подождать операционный стол, а тут уже и теслу выпустили, пора улетать, ммммм кайф геймплей, почти час проводить в очередях и ожиданиях, что бы улететь, ну да, это РП игра, и каждую катку за бригмеда я РПшу ЖДУНА в очереди и ждуна стола. Далее про импланты и счастье ГСБ - пошла я значит, получила импланты в робо, помпы, велд шилд, секьюрити худы и даже  термалы в красный код уговорила дать без письменного разрешения, естественно у ГСБ спросила, можно ли взять сходить. Делала неоднократные объявы в секьюрити рацию о том, что все есть, только приходи и получи удовольствие. И знаешь что? Никто сам не пришел. Ходила как наркодилер, со словами по типу: ГСБ, имплантики не желаете? Офицеры, имплантики не желаете? Стол нужен и еще как, вот как раз кому не нравится где они стоит, пусть зовет инженеров на перепланировку помещения, это уже дело вкуса. А по факту бригмеду он необходим для адекватного оказания помощи, быстро и без геморроя. Слипер и сканер НТ поставить додумалось, а стол поставить нет. 2565 год на дворе, пора бы медика адекватно укомплектовывать для лечения защитников станции, и клинер поставить. А то совсем как унга бунга, в крови захряснет.

**Comment by Sykybekk** [comment]
> Ой, вот вы конечно сказочники. Приведу частные случаи, но которые иногда, а порой и часто имеют место быть. По порядку: робоебы и импланты уборщика+хирурга: прихожу говорю робо, напечатайте импланты, в ответ: мы не печатаем ничего, идите в РНД, в рнд очередь из 9 человек, оно и понятно, ведь робоебы ничего не печатают. 18минут в очереди и импланты у меня, отлично, ищем свободного хирурга, в хирургии 2 человека стоят в очереди на лечения кровотечений, ждем. Еще 35 минут подождать операционный стол, а тут уже и теслу выпустили, пора улетать, ммммм кайф геймплей, почти час проводить в очередях и ожиданиях, что бы улететь, ну да, это РП игра, и каждую катку за бригмеда я РПшу ЖДУНА в очереди и ждуна стола. Я не говорю, что так каждую катку, но бывает и такое, что робоебы не умеют печатать и не знают где и как, не говоря о том что не умеют ставить или ставят, потом обнаруживаешь у себя заражение. Далее про импланты и счастье ГСБ - пошла я значит, получила импланты в робо, помпы, велд шилд, секьюрити худы и даже термалы в красный код уговорила дать без письменного разрешения, естественно у ГСБ спросила, можно ли взять сходить. Делала неоднократные объявы в секьюрити рацию о том, что все есть, только приходи и получи удовольствие. И знаешь что? Никто сам не пришел. Ходила как наркодилер, со словами по типу: ГСБ, имплантики не желаете? Офицеры, имплантики не желаете?
> По итогу. Стол нужен и еще как, вот как раз кому не нравится где он стоит, пусть зовет инженеров на перепланировку помещения, это уже дело вкуса. А по факту бригмеду он необходим для адекватного оказания помощи, быстро и без геморроя, а так же проведения проверочных операций на антагах, что бы не тащить потенциально опасного пациента в мед. Слипер и сканер НТ поставить додумалось, а стол поставить нет. 2565 год на дворе, пора бы медика адекватно укомплектовывать для лечения защитников станции, и клинер поставить. А то совсем как унга бунга, в крови захряснет.

Затариваться имплантами без острый нужды, ммм манчикизмом попахивает

**Comment by EpicSider** [comment]
> 
> 
> > Ой, вот вы конечно сказочники. Приведу частные случаи, но которые иногда, а порой и часто имеют место быть. По порядку: робоебы и импланты уборщика+хирурга: прихожу говорю робо, напечатайте импланты, в ответ: мы не печатаем ничего, идите в РНД, в рнд очередь из 9 человек, оно и понятно, ведь робоебы ничего не печатают. 18минут в очереди и импланты у меня, отлично, ищем свободного хирурга, в хирургии 2 человека стоят в очереди на лечения кровотечений, ждем. Еще 35 минут подождать операционный стол, а тут уже и теслу выпустили, пора улетать, ммммм кайф геймплей, почти час проводить в очередях и ожиданиях, что бы улететь, ну да, это РП игра, и каждую катку за бригмеда я РПшу ЖДУНА в очереди и ждуна стола. Я не говорю, что так каждую катку, но бывает и такое, что робоебы не умеют печатать и не знают где и как, не говоря о том что не умеют ставить или ставят, потом обнаруживаешь у себя заражение. Далее про импланты и счастье ГСБ - пошла я значит, получила импланты в робо, помпы, велд шилд, секьюрити худы и даже термалы в красный код уговорила дать без письменного разрешения, естественно у ГСБ спросила, можно ли взять сходить. Делала неоднократные объявы в секьюрити рацию о том, что все есть, только приходи и получи удовольствие. И знаешь что? Никто сам не пришел. Ходила как наркодилер, со словами по типу: ГСБ, имплантики не желаете? Офицеры, имплантики не желаете?
> > По итогу. Стол нужен и еще как, вот как раз кому не нравится где он стоит, пусть зовет инженеров на перепланировку помещения, это уже дело вкуса. А по факту бригмеду он необходим для адекватного оказания помощи, быстро и без геморроя, а так же проведения проверочных операций на антагах, что бы не тащить потенциально опасного пациента в мед. Слипер и сканер НТ поставить додумалось, а стол поставить нет. 2565 год на дворе, пора бы медика адекватно укомплектовывать для лечения защитников станции, и клинер поставить. А то совсем как унга бунга, в крови захряснет.
> 
> Затариваться имплантами без острый нужды, ммм манчикизмом попахивает

Отсутствие инструментов это не острая нужда? А что тогда острая нужда? когда у меня куча трупов будет лежать и все в крови? Тогда идти ставить импланты? Самое время наверное будет, да?

**Comment by Sykybekk** [comment]
> > > Ой, вот вы конечно сказочники. Приведу частные случаи, но которые иногда, а порой и часто имеют место быть. По порядку: робоебы и импланты уборщика+хирурга: прихожу говорю робо, напечатайте импланты, в ответ: мы не печатаем ничего, идите в РНД, в рнд очередь из 9 человек, оно и понятно, ведь робоебы ничего не печатают. 18минут в очереди и импланты у меня, отлично, ищем свободного хирурга, в хирургии 2 человека стоят в очереди на лечения кровотечений, ждем. Еще 35 минут подождать операционный стол, а тут уже и теслу выпустили, пора улетать, ммммм кайф геймплей, почти час проводить в очередях и ожиданиях, что бы улететь, ну да, это РП игра, и каждую катку за бригмеда я РПшу ЖДУНА в очереди и ждуна стола. Я не говорю, что так каждую катку, но бывает и такое, что робоебы не умеют печатать и не знают где и как, не говоря о том что не умеют ставить или ставят, потом обнаруживаешь у себя заражение. Далее про импланты и счастье ГСБ - пошла я значит, получила импланты в робо, помпы, велд шилд, секьюрити худы и даже термалы в красный код уговорила дать без письменного разрешения, естественно у ГСБ спросила, можно ли взять сходить. Делала неоднократные объявы в секьюрити рацию о том, что все есть, только приходи и получи удовольствие. И знаешь что? Никто сам не пришел. Ходила как наркодилер, со словами по типу: ГСБ, имплантики не желаете? Офицеры, имплантики не желаете?
> > > По итогу. Стол нужен и еще как, вот как раз кому не нравится где он стоит, пусть зовет инженеров на перепланировку помещения, это уже дело вкуса. А по факту бригмеду он необходим для адекватного оказания помощи, быстро и без геморроя, а так же проведения проверочных операций на антагах, что бы не тащить потенциально опасного пациента в мед. Слипер и сканер НТ поставить додумалось, а стол поставить нет. 2565 год на дворе, пора бы медика адекватно укомплектовывать для лечения защитников станции, и клинер поставить. А то совсем как унга бунга, в крови захряснет.
> > 
> > 
> > Затариваться имплантами без острый нужды, ммм манчикизмом попахивает
> 
> Отсутствие инструментов для работы это не острая нужда? А что тогда острая нужда? когда у меня куча трупов будет лежать и все в крови? Тогда идти ставить импланты? Самое время наверное будет, да? Или ты про боевые импланты для сб? Думаю спустя час смены, в красный код, когда антаги лютуют, это вполне достаточная причина затарить импланты, не говоря о том, что ГСБ я уведомила.

На серьёзное лечение есть медбей и его персонал. Твоя же задача просто стабилизировать и вылечить насколько это возможно без операций, и потом отправить в медбей, если необходимо

**Comment by AttHawk** [comment]
отсутствие операционного стола у бригмеда - прекрасная причина для РП с инжами и РнД в начале раунда дабы они его построили. Если зайти в крайность, давайте каждому отделу свою личную станцию отстроим с блекджеком и вульпами, чтобы все было сразу и ничего не надо было делать.

**Comment by DayBreakerBrony** [comment]
а давайте вся станция пустая будет кроме инженерного? будем каждый раунд заново строить станцию

**Comment by DayBreakerBrony** [comment]
или давайте сделаем бригмеда от которого нет толка кроме как мендером потыкать заключённого? будем ходить в мед ставить импланты, а потом находить свои трупы в крематории без мозгов и сердца.

**Comment by DayBreakerBrony** [comment]
Бригмед в первую очередь - МЕДИК БРИГА. Не **ПАРА**медик, а просто physician - терапевт. Его цель - поддерживать работоспособность сотрудников СБ и жизнедеятельность заключённых. Если у заключённого будет перелом, его в мед тащить чтоли? не несите хрень, бригмеду НУЖЕН стол, как бы вы этого не хотели в своих влажных "рп" мечтах. :KEKlown:

**Comment by Elisei24** [comment]
Люто плюсую. Обрубок, а не бригмед получается без стола, учитывая частоту внутренних кровотечений/переломов.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353362-7d793152-b0a8-47e7-932e-64dd3784b4ce.png)
