### ISSUE TITLE
Feat: роли дискорда

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#187]
### Проблема

нет плашек других заслуженных ролей. бесит! почему есть вульпы, но нет таяр, греев, драсков, скреллов, воксов, плазмаменов, слаймоменов, вринов, нуклеаций и т. д. да и к тому же "заслуженный синт" это роль мать вашу! 

### Решение

Давайте уже сделаем в дискорде плашки остальных рас. "Заслуженный силикон" это кринж, так как силиконы - роль. Но я не претендую, делать миллиард ролей "заслуженный бригмед, капитан, подсос гсб" и т. д. не вижу делать смысла так как на человеке запоминаются его подвиги обычно. 

### Плюсы

Наконец-то остальные хорошие расы останутся необделёнными в ролях. лично я буду рад получить себе плашку заслуженной плазмы. 

### Минусы

НЕТУ! если у хедадминов или са нет времени даже в дискорде улучшения сделать, то как у них хватает времени на сервер? ну элементарно ведь. и круто.

**Comment by PhantomMi3** [comment]
Я ЯДЕРНАЯ БОМБЯ И Я ЭТО ЗАСЛУЖИЛ!
Я за.
Я ПОЧЕТНЫЙ Нюклианин!

**Comment by Honker9999999** [comment]
Плашкодрочество конечно, но за заслуженного хумана я за.

**Comment by EnjSadman** [comment]
Опять с нового тайда люди хотят себе плашки. Ничего не менятся. Не нужны

**Comment by Danefalt** [comment]
Их изначально создавали как ролф. Делать новые не собираются, и это неоднократно говорили.
Ave Vulp!

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184353952-2605f7b2-4c3e-4c37-a92c-3a3ea9ee2084.png)
