### ISSUE TITLE
Feat: НерфКарго

### ISSUE THREAD

**Issue by Den109G** [ss220-space/Paradise#188]
### Проблема

Карго может заказать 50 пластали за 50 очков, переплавить и продать плазму с манифестом. 
В итоге, карго получает халявных 50 металла и 6-9 очков с манифеста и ящика.
(TL;DR) Карго обманывает ЦК и зарабатывает на этом.

### Решение

Увеличить стоимость 50 пластали до 55-65.

### Плюсы

Карго не будет перепродавать плазму ЦК.
Логика, ведь ящик с меньшим количеством пластали не может себя окупить (в буквальном смысле).

### Минусы

Хиджакеры не будут копить очки на свои игрушки.
Об этой "фиче" знают немногие и даже если узнают, то многие не будут этим заниматься.

**Comment by mayorovp** [comment]
Почему вообще возможно заказать с ЦК металл, можно заказать сплав металла с плазмой - но нельзя заказать плазму? Надо вообще этот ящик убрать из списка.

**Comment by Den109G** [comment]
Это, возможно, сделано для ночно-раундов и для роботехов. 
Чтобы не ждать шахтёров, РнД заказывают пласталь, что тратят на мехов.
