### ISSUE TITLE
Исправить проблему с тем что после rune revive не сбрасывает blur зрения

### ISSUE THREAD

**Issue by semoro** [ss220-space/Paradise#19]

**Comment by MorgoWizard** [comment]
После использование руны Revive у воскресшего сохраняется Blur эффект после смерти (тестировалось ~10-15 минут)

**Comment by MorgoWizard** [comment]
@VasilevAY 
Путём различных тестов я пришёл к тому, что на локалке в соло не проходит проверка `if(client?.screen)` и соответственно не работаёт proc убирающий эффект (т.к. оживлять нужно другим мобом, а _мёртвый_ оказывается без клиента и соответственно без экрана
![image](https://user-images.githubusercontent.com/84981163/185791817-25983917-896d-4ebf-bfdf-814207c5f099.png)

**Comment by MorgoWizard** [comment]
@VasilevAY, ну провёл я тест с двумя клиентами. Баг отсутствует.

Убил пешку. Пешка была с блюром посмертно. После возрождения руной блюра нет.
