### ISSUE TITLE
Feat: Изменить систему "всем главам от 30-ти лет" на широкий спектр возрастных требований

### ISSUE THREAD

**Issue by AttHawk** [ss220-space/Paradise#192]
### Проблема

Сейчас основной возраст сервера 30 лет, по причине "хочу чтобы были доступны все рольки на одном персе". Это довольно сильно бьет по РП составляющей, и порождает кучу кринжмоментов с таяра-17-лет-космодесанта на капитане и ему подобными.

### Решение

Изменить требования возраста к должностям, пример на скриншоте. При выборе итогового числа руководствовался необходимым опытом/обучением для выполнения обязанностей в данной профе
![image](https://user-images.githubusercontent.com/85886313/126751347-e54ad836-69e9-4488-ad38-e8495461b47d.png)

### Плюсы

-Разбавление среднего возраста людей на станции с 30 лет, которых судя по статистике около 70%
-Улучшение РП составляющей сервера 

### Минусы

-Возможные  проблемы после дописывания лора и смены продолжительности жизни разных рас
-Вой формата "мне не дают играть на моей любимой {раса_нейм} 30 годиков", а также "у нас медРП сервер, что за душение начинается"

**Comment by DayBreakerBrony** [comment]
будут просто 42 ставить и все. не вижу смысла особого
нейтрально

**Comment by Honker9999999** [comment]
Можно исправить как на бее - чем старше тем челик медленнее. И сразу вульпочки 30 лет пропадут, ибо "эээээ че медленным быть? Да ну в пизду".

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184354066-e695f4bf-d34b-42fa-a0ca-823f2c0bed96.png)
