### ISSUE TITLE
Увеличить время до первой голосовалки на вызов шатла?

### ISSUE THREAD

**Issue by tizer7** [ss220-space/Paradise#193]
### Проблема

Только сегодня наблюдал картинку как после 3 часов игры, при куче живых пауков, игроки проголосовали за шатл. 
Правила при пауках террора четко запрещают вызов шатла, пока пауки не уничтожены. Эта "фича" ломает эту часть игры, где станция должна любой ценой справиться с угрозой перед тем как эвакуироваться. Частенько наблюдаю картину, что игроки просто не хотят устранять угрозу, а предпочитают драпать при первых же сложностях.
 
![Снимок экрана 2021-07-23 194029](https://user-images.githubusercontent.com/87470137/126760502-6232660b-17bf-4dc4-a062-784aa509d153.png)

### Решение

Сейчас используется время до первой голосовалки в 120 минут (могу ошибаться). Оно устанавливается на сервере в конфиг файле config.txt параметром VOTE_AUTOTRANSFER_INITIAL. Предлагаю обсудить увеличение этого параметра до 180 или 240 минут.
Пишите: За\против. Если за, то время 180 / 240 или ваш вариант.

### Плюсы

Шатлоебы будут недовольны.
Никакого драпающего персонала от того, что станцию чуток "поцарапало".

### Минусы

Шатлоебы будут недовольны.
Больше долгих раундов, если нет глав.

**Comment by Honker9999999** [comment]
Закрывай. Время до первого шаттла уже давно 180(банально посчитай - голосовач идет при 3 часах, в одном часе 60 минут, 3*60 - 180.). А до 4 часов - мейн и ВЛ не экста, игроки захотят - смогут и до 4, и до 6 часов играть. Если захотят. Ограничивать их смысла нет.

**Comment by AttHawk** [comment]
выглядит как снобский вброс про "шатлоебов". Половина шаттлов вызывается когда полностью закрыто РНД, зафармлен лаваленд, сделаны вирусы в меде, у ботаников полная жопа гибтоматов и людям реально нечем заняться. вторая половина вызывается когда тесла/сигна/хиджакер/нюкеры разъебали полстанции а инженеров 2 калеки и  инжерт пустить некому по причине отсутствия  педалей

**Comment by AttHawk** [comment]
а  проблема скрина в том что голосование за крютрансфер это не за вызов шаттла, а за конец раунда

**Comment by tizer7** [comment]
задушили. ладно, затерпим.
