### ISSUE TITLE
Bug: Новые симптомы вирусов заспамливают чат

### ISSUE THREAD

**Issue by AttHawk** [ss220-space/Paradise#194]
### Ckey

AttHawk

### Описание бага

Пак симптомов вирусов от Джордана постоянно спамит в чат надписью о своем наличии

### Шаги воспроизведения

-Получить вирус с новым симптомом
-Наблюдать спам в чате

### Ожидаемое поведение

Однократное появление надписи в начале заражения

### Операционная система

windows 10

### Версия клиента

513.154

### Название сервера

WL

### Примерное время и дата

22.07.2021

**Comment by Jordanstolethepreciousslam** [comment]
Так а в чем баг? Вирусы не работают так. Куча симптомов спамит сообщения на последней стадии. Вечная юность, Эволюционное ускорение, а также абсолютно все вредные симптомы. Если говорить вирусах типа sensory restoration и Self-Respiration, то они дают далеко не "однократное появление надписи в начале заражения". Они спамят на всем протяжении неактивных стадий и перестают сообщать носителю что они работают ровно на той стадии на которой они начинают работать.
