### ISSUE TITLE
Feat: Mechа Expansion

### ISSUE THREAD

**Issue by OpsCoretango** [ss220-space/Paradise#202]
### Проблема

Старый дизайн модуля Exosuit Sleeper, Отсуствие полноразмерных меховских аналогов на основе уже открытых технологии. 
Усиление Мехов. 
End game Mech content.
Дизайны. 

### Решение

Специализированный Класс
 -Мех Виски
 -Мех Одиссей. 

  [Odysseus] Одиссей
ЕМП добавляет запрещенные медикаменты а E-mag Нанокальций, бить Дефибрилятором на харме.
Скорость увеличена до бега человека.
~~Бак внутреннего фабрикатора увеличен до 150 единиц - 10 заполненных шприцов.~~  Отклонено, баланс.

 >[ Exosuit Sleeper] 
Провести редизайн интерфейса Exosuit Sleeper вместо обычного белого листа с наименованием и цифрами как в обычном Слиппере.
Веществам огранить допустимый пул в 10u потому что Глюкоза которая сжирает 40u а у тебя 75u общего не круто.

 >[Mech Defibrillator] Меховской дефибриллятор, вот его особенно не хватает.  Изучается рядом с меховским Jaws of Life по времени. 

>[Healing Beam] Лечащий луч - 
из арсенала вооружения полевых медиков ТСФ от корпорации Vey-Med. Аналог шприцемету.
Открывается ~~на 8ом уровне~~ в РнД потому что лицензию Vey-Med не давала.

  [Whiskey] Виски
Walking Factory of producing Alcohol(Ходячий завод по производству Бухла)
ЕМП или E-mag добавляет запрещенные напитки
>Разливная рука (я пытался придумать) возможность взаимодействия с жидкостями в стаканах, колбах.
Сигаретный синтезатор
Ай, у нас и так борги есть, удачи [тому](https://cdn.discordapp.com/attachments/498961079506960404/976545233238130720/unknown.png)
 кто все таки придумает Барменский Мех.. 

 -Все мехи (глобально) 
> Ремонтный дрон с некоторым шансом тушит пожар в условиях Лаваленда и космоса ~~( потому что вылезать и постоянно чинить, залезать и идти до душа, носить огнетушитель, или взорваться потому что тушить нечем..)~~ . 

>Кроме Одиссея со встроенным Medhud теперь все Мехи имеют свои Визоры/hud в кабину

Upgrades
>[Actuator Enforcer]Улучшение приводов. Увеличивает скорость передвижения на 1,2х но ест много энергии. 
>[Ion Thrusters] Дает возможность летать в космосе и в невесомости
>[Enforced Ion Thrusters]  Увеличивает скорость полета в 1,5х в условиях невесомости, жрет много энергии.
>[Jump Thruster] Прыжковый двигатель. Прыжок в одну сторону на ? тайлов как у Jump Boots. Полет в невесомости в одну сторону. Не устанавливается Кларку, Кобре, Tracked Mech Closet из-за гусеничного привода.

 - Инженерно-Шахтерский класс.
      Ripley and Clark ~~Ratchet and Clank~~

Рипли и Кларку дается Мезонный Визор в кабину.

- Дается Возможность приварить Пласталь или Металл к корпусу APLU Ripley и APLU Firefighter влияет только на шанс `deflect_chance` но если это уже сделано не дает возможность навесить шкуры Голиафа. Выбор :artChair между шансом или сопротивлением урону.

> [ Big Kinetic aссelerator ] Большой кинетический Акселератор который уже изначально копает 3х3, имеет больший урон, перезарядка как с первым KA Cooldown Decrease но невозможна установка модулей как в обычный Акселератор из-за ограничений в коде. 
С помощью него возможен полет на мехе в космосе, и это хорошая комбинация Plasma Cutter 217-D. Изучается в РнД по времени перед появлением резака. 
Универсал по применению.
-Boom 

> [Mech Jackhammer] Вибрационный Меховской Бур  - сделанный на технологии вибраций, крошит камни и дробит кости, по сути копает быстрее алмазной дрели и соответственно ест больше энергии за счет 1,5х возросшего кпд, бьет наверное больно. Еще никогда откапывание всего Лаваленда не было так близко и так не далеко. 
Дорогой в создании и открывается на последнем этапе исследований в РнД. 
-Jack it harder!

> [Hydraulic Hand] Гидравлическая ладонь с запястьем. 
Аналог Hydraulic Clamp, Обладает полным функционалом как загрузка деревянных ящиков,шкафов. 
Умеет работать с кнопками, хватать предмет и бросать на землю, бить но хуже чем Дюранд без способности ваншота пласталевой стены, швырять объекты (с большей силой чем живое существо), хватать в Grab мобов и персонажей и кидать,перемещать в руке.  (звучит как захват трупа шахтера и доставка на базу. 
Жертва может сбежать из цепкой руки как от человека. (послабление) 
Если коротко, это словно ваша рука. Требуется исследование.
Not for squashing, i swear!

> [Exosuit Scrubber] - Атмосферный Пылесос
При активации засасывает в танк все опасные и не опасные газы со встроенным фильтром для выбора что из воздуха откачать а что от смеси воздуха и плазмы отделить воздух. Уходим в изолированную комнату где то в инженерке и выпускаем плазму для откачки. 
Don't suck my donut

 Крафт

>[Coaxial Emitter] - Станковый Эммитер который инженеры поставили кустарным способом на Огнеборца ( utility Мех любой). Тут нужен крафт. И у СБ будут вопросы. 
Задачи: Гнать материю, воевать с блобом, самодельное оружие. 
Визуально выглядит как спаренное с манипулятором орудие с явной сваркой и укреплением трубами. 
- I need more Power!

>[Mech Custom Flamer] Кустарный Меховской Огнемет. 
-[Описание] Джонни, неси изоленту и провода с сигналлером. Худшее оружие геноцида.

Боевой класс мехов:

  [Cobra] "Кобра" - Sshhh, i catch you. NT copyright Reserved.
>Мех среднего класса на гусеничной платформе. Напоминает гибрида Кларка и Мародера с освещением фонаря кабины в стиле СБ шлема Рига(Представьте шлем рига СБ как кабину и гусеницу кларка.)
Хм, почему я предлагаю Мародёра?
Характеристики:
ХП выше чем у Гигакса но меньше Дюранда. 
4 Слота. 
Move speed: Равен или меньше чем у Кларка. 
Способности: 
Дымовая граната, Перцовая граната, полет, ПНВ, Security Hud.
Сопротивление урону - Средний коэффициент если проводить сравнение между Гигаксом и Дюрандом.

>Дюранд
Получает в кабину визор ПНВ(NVG)

> Durand MK1
Получает в кабину визор ПНВ

>Гигакс, Темный Гигакс
Получает в кабину визор ПНВ.
Гигакс получает Security hud в придачу.

>Мародеры
Получает в кабину визор ПНВ/Тепловизор

>Сераф
Получает в кабину визор ПНВ/Тепловизор/Xray
получает Multi-hud в придачу.

>Фазон:  
Ghost Cloak Module
Получает в кабину визор ПНВ/Тепловизор

>[Plastitanium shield] 
При выборе все кинетические, лазерные снаряды имеют 40% шанс отскочить в сторону куда смотрит мех а если щит пробит то броня меха накладывает шанс на успех рикошета но использование дюрандом абилки.. честно, похоже произойдёт кошмар. 
Не защищает от противотанкового ионного оружия.
Своровать из Infinity не ошибка!

[Droid`s] 
По сути задумка о наплечных турелях - **Скрещиваем ED-201 и меховское снаряжение**, вырезаем патруль.

 Лазерный дроид: дроид открывает огонь по неавторизованным элементам и уходит на охлаждение кулдауном в пол. минуты. Выбор энергетического заряда от Тейзера до Летала. 

Deathsquad pulse droid: маленький друг Серафа по свершению геноцида. 
Стрельба 10 секунд, кулдаун 30 секунд. 

Battle upgrades.
 
> [Actuator Battle Enforcer] Боевое Улучшение приводов. Увеличивает скорость передвижения на 1,5х меха но ест много энергии. 

>Energy Mech Shield - увеличенная версия энергетического щита, отрубается через EMP, имеет на 20% больше здоровья.

Косметика и дизайн : портирование из Baystation дизайны мехов.

>Mk1 ripley design, Deathsquad Ripley design, гигакс что-то там.
Спавнить рандомно их в техах, заказывать/продавать в карго. 

~~Силикону дать выбор заспавниться на мехе Рипли - Старый Дюранд/Гигакс. Можно устроить отдельной профессией.
Такого опыта чтобы мехом управлял Робомозг нигде нет. Будем первыми?~~

Самодельный класс мехов:
>[Tracked Mech Closet]
Шкафный мех теперь не один, добавив конвейерную ленту он может быть оснащен "типа" гусеницами

### Плюсы

Фишки для мехов которые игроки точно захотят применить, опробовать,  оценить в игре. 

### Минусы

Вопросы баланса, дизайна, кодинга, где найти кодера который этим заинтересуется?

**Comment by OpsCoretango** [comment]
Пойду спать.
Пришлось переписать все потом потерять, опять записывать. Residentsleeper

**Comment by OpsCoretango** [comment]
Может кто то выскажет оценку или мнение?

**Comment by ZmeionishW** [comment]
> Может кто то выскажет оценку или мнение?

Очень много кодинга и я правда, не могу увидеть пути как это балансить. Как по мне, лучшей идей будет портировать с инфинити систему мехов, потому что там вообщем-то все это есть, только относительно лучше.
Впрочем, если это будет в игре, это будет забавно

**Comment by Predeiter** [comment]
Даже перекинув мехов из фиников что опять не упростит задачу, так как система ресурсов немного другая да и скорее всего флаги ресов други, баланс пойдет в разнос + учитывая мой issue так и подавно.

**Comment by Sykybekk** [comment]
Можно сделать полностью кастомизируемых мехов. То есть сделать так, чтобы на этапе строительства самого шасси можно было определять будущие статы и скиллы меха, добавлять всякие модули и подсистемы по своему желанию. Как-то так могу предложить

**Comment by OpsCoretango** [comment]
> Можно сделать полностью кастомизируемых мехов. То есть сделать так, чтобы на этапе строительства самого шасси можно было определять будущие статы и скиллы меха, добавлять всякие модули и подсистемы по своему желанию. Как-то так могу предложить

Смешно, но если представить код и базу на которой он делается..
Рп действие: "обосраться от страха"

**Comment by Sykybekk** [comment]
> > Можно сделать полностью кастомизируемых мехов. То есть сделать так, чтобы на этапе строительства самого шасси можно было определять будущие статы и скиллы меха, добавлять всякие модули и подсистемы по своему желанию. Как-то так могу предложить
> 
> Смешно, но если представить код и базу на которой он делается..
> Рп действие: "обосраться от страха"

Явно у кого-то проблемы со свободой мысли, ухе

**Comment by OpsCoretango** [comment]
> > > Можно сделать полностью кастомизируемых мехов. То есть сделать так, чтобы на этапе строительства самого шасси можно было определять будущие статы и скиллы меха, добавлять всякие модули и подсистемы по своему желанию. Как-то так могу предложить
> > 
> > Смешно, но если представить код и базу на которой он делается..
> > Рп действие: "обосраться от страха"
> 
> Явно у кого-то проблемы со свободой мысли, кхе

Парадайз, он странный по себе.
Система привязки алгоритмов.

По сути роботехи это сборщики на основе готовых чертежей а не завод но мы **Научная станция** поэтому эксперименты и прототипы не забывая что все второстепенное а первостепенное это цели станции и изучение Bluespace, Plasma.
Ракетно-двигательная, Грави-propulsion, Гусеничное, Шагоход. 

Пресловутый и не нужный мне но кому то баланс.
А если характеристики забагуются. 

По итогу, кодеры пойдут по легкому, эффективному пути в обход болота. 

Идея хороша но мысль с большим объемом так и останется в Issue с переадресом "сам закодируй".

**Comment by OpsCoretango** [comment]
Ку ку, мне Bonk за ping.

**Comment by OpsCoretango** [comment]
Переосмыслил все это и пришел к выводу что относительно по мехам стоит делать на имеющихся уже кодам и ресурсам.
Т. е Dash у Рипли, Дефиб и 3х3 крашер еще выполнимо в теории а мед. луч или пластитановый щит, боевой дроид это уже ну пахнет мертвечиной.

**Comment by hnappinn** [comment]
В коде и так есть медлуч. У ерт и нюки. Надо только под мех переделать

**Comment by OpsCoretango** [comment]
почему Азиз не сжег эту кладовку идей Overhaulа мехов?
Пысы. Заметка: Переделать спрайты ракетометов на 4 ствольную систему в связи с недавними событиями.

**Comment by OpsCoretango** [comment]
Переписал и урезал лишнего свой майн капут и добавил кое что уникальное которое врядли понравиться а балансер в гробу переворачивается.
Да.. вы можете за робомозг раундстартом выбрать старый дюранд без ничего или обычный рипли с шахтерским снаряжением. И таких громозеков по слотам максимум будет два.

Боже, я обожаю избивать трупы.

**Comment by OpsCoretango** [comment]
Типа если вы выбрали старого Дюранда то вы считаетесь СБшником но половину игры будете стоять в ангаре или охранять ГСБ

**Comment by OpsCoretango** [comment]
Переделан иссуй, вырезано + добавлено.

**Comment by OpsCoretango** [comment]
Исправлено описание Enforced Ion Thrusters

**Comment by OpsCoretango** [comment]
кто возьмётся допустим за деньги?

**Comment by TrashDoxx** [comment]
> кто возьмётся допустим за деньги?

Об этом сейчас можешь не думать. Сначала пройденная предложка - потом работа.

**Comment by OpsCoretango** [comment]
> > кто возьмётся допустим за деньги?
> 
> Об этом сейчас можешь не думать. Сначала пройденная предложка - потом работа.

Действительно, у меня про Одиссей предложка есть судя по поиску.
Опять писать, о да 😒

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184354677-c8ffabf5-803d-405f-90a5-3644a304e0d6.png)
