### ISSUE TITLE
Спавнрейт антагов

### ISSUE THREAD

**Issue by Frostillikus21** [ss220-space/Paradise#203]
### Проблема

На данный момент я знаю, что вроде как на каждые 10 человек приходится один антаг, а значит что на 130 человек будут условные 13 антагов, остальные 117 человек нормальные, но это только усугубило ситуацию как по мне. 
К чему я веду  собственно. 
Хотелось бы повышения спавнрейта культа, революции и мага. Их действительно мало и за весь день их можно не увидеть вообще, реву я в последний раз видел лично на позапрошлой неделе, да и та забажилась из-за типа который ливнул

### Решение

Временно повысить спавнрейт перечисленных антагов и проверить реакцию игроков и если всем будет нравиться то оставить.

Так же добавить перечисленных на мидгейм спавн, чтобы после очередного слива раундстартовых ещё было желание продолжать играть у тех кто заскучал. Главное чтоб не спавнились когда станция на половину разрушена, а то будет пепеклаун

### Плюсы

Большее разнообразие, люди смогут научиться играть не только на генках и триторах, а так же противостоять другим антагам.
Может начаться полный хаос и шустайдовцы уйдут от нагиба антагов.

### Минусы

Может начаться полный хаос и шустайдовцы уйдут от нагиба антагов.
Некоторое время новички которым падают тот же культ будут быстро сливаться.

**Comment by DayBreakerBrony** [comment]
полностью согласен

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184354729-7a05c7f1-e166-4aac-b8c4-df599a5105f8.png)
