### ISSUE TITLE
Bug: Блюспейс заводик или дюп металлических стержней

### ISSUE THREAD

**Issue by ahapk** [ss220-space/Paradise#204]
### Ckey

blind0

### Описание бага

Бесконечное получение металлических стержней за счёт бага с защищённым полом.

### Шаги воспроизведения

1. Берём 2 свободных тайла
2. Один тайл покрываем металлическими стержнями(защищённый пол)
3. ставим мусоропроводную трубяру(trunk) перед защищённым полом в направлении защищённого пола
4. на мусоропроводную трубяру(trunk) ставим либо корзину(bin), либо воронку(chute), всё прикручиваем завариваем.
5. кидаем любой кусок мусора в корзину/воронку
6. получаем на выходе кусок мусора и +1 металлический стержень.
7. для создания заводика повторить всё это кучу раз.

### Ожидаемое поведение

1. Берём 2 свободных тайла
2. Один тайл покрываем металлическими стержнями(защищённый пол)
3. ставим мусоропроводную трубяру(trunk) перед защищённым полом в направлении защищённого пола
4. на мусоропроводную трубяру(trunk) ставим либо корзину(bin), либо воронку(chute), всё прикручиваем завариваем.
5. кидаем любой кусок мусора в корзину/воронку
6. получаем на выходе кусок мусора, +1 металлический стержень и сломанный пол.
7. для создания заводика - погрустить, ибо баг не работает.

### Дополнительная информация

![image](https://user-images.githubusercontent.com/29610081/126858990-d27a9d68-dea2-47ea-bf66-bd4f6e8ed4ae.png)
**Это мой блюспейс заводик, каждый цикл даёт +17 стержней, для катализации процесса нужно использовать обезьянку, для стабильности работы, пока не знаю что нужно.**

### Операционная система

win10

### Версия клиента

513.1542

### Название сервера

MAIN

### Примерное время и дата

23.07.21 18:00(МСК)

**Comment by blind0** [comment]
доработал схему, это супер эффективный дюп.
![доработанный блюспейс заводик](https://user-images.githubusercontent.com/45512381/126877204-910ba771-17ed-4a72-98c7-a230acd2021c.png)
