### ISSUE TITLE
Feat: Картриджы огнетушителей плазмаменов

### ISSUE THREAD

**Issue by Gnatr** [ss220-space/Paradise#207]
### Проблема

У плазмаменов есть встроенный костюмный огнетушитель с 5-ю зарядами, но единственный способ их пополнить на данный момент это заказывать в карго набор плазмаменов с новыми костюмами. 
В это же время существует картридж пополнения. Достать сие предмет в данный момент можно только щитспавном,

### Решение

Добавить картриджы в лат и ящик пламаменов из карго заказов.

### Плюсы

Плазмаменам не придется заказывать в карго ящики при каждом случайном поджоге, да и костюм раундстартовый 
 под профу можно оставить.

### Минусы

Будут поджоги.

**Comment by AttHawk** [comment]
Круто, классно, да, надо такую штуку. Ни разу за плазму не играл, даже не знал о такой проблеме. Можно еще в автолат добавить, огнетушители там есть.

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/308
