### ISSUE TITLE
Feat: Новый слот для плащиков и прочей чепухи

### ISSUE THREAD

**Issue by Isareluss** [ss220-space/Paradise#210]
### Проблема

На данный момент, плащики используются не так часто, так как они занимают слот костюмов, а отдельного слота для них нет. На билдах с тг уже давно есть такой слот, в который можно поместить плащи, одеяла и много чего ещё.

### Решение

Предлагаю добавить этот самый слот. Благодаря которому можно будет носить плащики и одеяла. 

### Плюсы

Новый крутой слот, много стиля, чады ассистенты с одеялами на спине. 

### Минусы

Чады ассистенты с одеялами на спине, возможные баги и проблемы со спрайтами.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184355558-d3527592-b911-4704-ad44-d3227b117b47.png)
