### ISSUE TITLE
Bug: дисконнекты по полчаса

### ISSUE THREAD

**Issue by assaultmachine** [ss220-space/Paradise#211]
### Ckey

assaultmachine

### Описание бага

Короче, дело вот в чём: неделю назад начались тупо дисконнекты с мейна и вл (на остальных не играю). Играешь минут 20-30 - вылет и невозможность зайти на полчаса. В дс азис предположил, что кикает меня овх, что действительно так: после дисконнекта сам сайт https://www.ovh.ie/ перестаёт грузится и все сервисы, которые лежат на овх, также перестают грузится. Замечено, что корни этой хуйни идут именно с ss220, ибо если я не играю на сервере, сам сайт овх и все сервисы работают стабильно.

### Шаги воспроизведения

1. Играешь
2. Вылетаешь

### Ожидаемое поведение

1. Играешь
2. Не вылетаешь

### Операционная система

win10

### Версия клиента

513.1542

### Название сервера

MAIN

### Примерное время и дата

последнюю неделю

**Comment by GrekkOS** [comment]
Подтверждаю, меня точно также, могу назвать ещё человек 5-6 с такой же проблемой, думаю, что нас даже больше.

**Comment by tizer7** [comment]
Если пошла такая пляска, то предлагаю под этот шумок переехать на сервак в москве, чтоб инпут лаг поменьше был и всем дышалось легче, в том числе серверной части игры. А не это хуйня в еврозоне с моим пингом в 160 мс и в 14 хопов. Хватило же мозгов у кого то запихнуть сервак подальше от игроков.

**Comment by zombie288** [comment]
Человек из еврозоны против, играю с пингом ~50.

**Comment by assaultmachine** [comment]
> Человек из еврозоны против, играю с пингом ~50.

да, мухосранск под Курском

**Comment by assaultmachine** [comment]
> Человек из еврозоны против, играю с пингом ~50.

Из Курска с таким же ±10 пингом играю

**Comment by MorgoWizard** [comment]
@VasilevAY, сервак же уже давно поменялся? Походу неактуалочка
