### ISSUE TITLE
Feat: Выпилить автошатл при Абдукторах

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#212]
### Проблема

Абдукторы начали сверхэффективно выполнять свои цели, учитывая, что на мейне асистухи (и не только) не робасты - их легко похищают. Счетчик уже прыгает до 19 человек за раунд с одной группы. И автошатл в начале смены начинает выносить мозг.

### Решение

Выпилить автошатл. Абдукторов выполнивших свои цели почетно отправлять в отставку, либо давать новые странные задачи.

### Плюсы

Нет автошатла через 30 минут с начала смены. Врачам и хирургам будет веселее работать.

### Минусы

0

**Comment by AttHawk** [comment]
Началось, сначала «ой антагов душат, закройте техи пожалуфто» а теперь «ой, абдукторы душат, уберите шаттл». Если ходить по 2-3 чела то только супер робастные абдукторы смогут что-то сделать, но люди же бессметные и получить анальное зондирование прикольно наверное, поэтому всем пофиг, либо кокпитан/гсб/другие главы эту информацию не доносят, что уже проблема людей с 50+ часами на отделах что играть не умеют

**Comment by Den109G** [comment]
Прям вижу 30 или 60 ассистентов стоят к инженерке и грейтайдят её, ведь у них появилась цель "Поговорите с теслой".
Очень весело будет как СБ (чисто физически нельзя будет их всех посадить), так и другим игрокам, которым просто хотелось поиграть против нюки или призывать бога Лаг'Си.

**Comment by snipersir** [comment]
Абдукторы не раундстартовые антаги и им не нужно жить в техах на станции, у них тарелка - их дом.

**Comment by Den109G** [comment]
> Абдукторы не раундстартовые антаги и им не нужно жить в техах на станции, у них тарелка - их дом.

Абдукторы могут быть раундстартовыми антагами, как и блоб.

**Comment by snipersir** [comment]
Абдукторы не того плана антаги что им нужно жить в техах на станции, у них тарелка - их дом, им насрать что на станции творится

**Comment by snipersir** [comment]
> Прям вижу 30 или 60 ассистентов стоят к инженерке и грейтайдят её, ведь у них появилась цель "Поговорите с теслой".
> Очень весело будет как СБ (чисто физически нельзя будет их всех посадить), так и другим игрокам, которым просто хотелось поиграть против нюки или призывать бога Лаг'Си.

Вырезать из арсенала абдукторов большую часть имплантируемых органов. Оставить всего по 2 штуки от каждого вида, и не будет никакой орды асистух у инженерки.

**Comment by Honker9999999** [comment]
Напомню, что шаттл работает ЛИШЬ при раундстарт абдукторах. При случайных ивентовых - нет.

**Comment by Jordanstolethepreciousslam** [comment]
Не надо выпиливать автошатл. Он то как раз спасает от муторной хуеты связанной с 150 ассистосами блюющими плазмой, слизнями и кровью по всей станции. Лучше выпилить самих абдукторов ибо антаги говна. Ну или хотя бы понерфить их ибо щас ты на сб им ничего не сделаешь без ПМки от админа.

**Comment by OpsCoretango** [comment]
А может ружье метку изобрести ну типа, берем дробовик со снарядом отслеживания типа

**Comment by snipersir** [comment]
> Не надо выпиливать автошатл. Он то как раз спасает от муторной хуеты связанной с 150 ассистосами блюющими плазмой, слизнями и кровью по всей станции. Лучше выпилить самих абдукторов ибо антаги говна. Ну или хотя бы понерфить их ибо щас ты на сб им ничего не сделаешь без ПМки от админа.

Откуда до 1 часа игры у тебя возникают 150 асистух блюющих плазмой слизнями и кровью на всей станции?.. "Спасение от муторной хуеты" ты рофлишь? Каждый раунд так проходит на мейне. В связи с этим у меня к тебе вопрос "зачем ты играешь если не любишь всё это"??????

**Comment by snipersir** [comment]
Какие то вы странные люди. Ненавидите игру, предложку топите, при этом продолжаете играть в игру от которой вас тошнит...

**Comment by Jordanstolethepreciousslam** [comment]
> Какие то вы странные люди. Ненавидите игру, предложку топите, при этом продолжаете играть в то от чего вас тошнит...

У тебя какой-то синдром утенка или что. В игре много тупой хуеты которая просто безбалансна. Например Ксеноморфы. Что то я не вижу "Ну игра такая с ксеноморфами зачем играешь если не нравится". Это так не работает. СС13 не имеет доработанных до конца билдов в принципе. В каждом есть баги, в каждом есть проблемы с балансом и в каждом есть еще много работы.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184355615-4865fec4-092a-4d21-be30-2e4744e245cf.png)
