### ISSUE TITLE
Bug:  "Эпилепсия"

### ISSUE THREAD

**Issue by Ssehes** [ss220-space/Paradise#219]
### Ckey

Ssehes

### Описание бага

После излечения шприцем с чистым СЕ больного эпилепсией(приобретенной через шприц с геном) остается шатание персонажа.

### Шаги воспроизведения

1. Получить ген с эпилепсией
2. Уколоть персонажа
3. Вылечить персонажа шприцем с чистым СЕ

### Ожидаемое поведение

Персонажа перестанет колбасить

### Операционная система

Windows 10

### Версия клиента

513.1542

### Название сервера

WL

### Примерное время и дата

25.07.21 Примерно в 22-23 по МСК

**Comment by Zigamus** [comment]
Заменить ген. блок недостаточно, нужно въебать мутадона, тогда гены почистятся.

**Comment by JokerLul** [comment]
Трусить перестанет со временем. Бахни чистый и мутадона для верности, и минут через 5 тебя отпустит

**Comment by Ssehes** [comment]
Вопрос в том, откуда должен игрок знать об этом? в руководстве нихрена не написано об этом и соответсвенно воспринимается как баг. Варианта вижу два, либо исправить что бы трусить переставало сразу, либо руководство дополнять =\
