### ISSUE TITLE
Bug: Как уничтожать всё и вся на мехе

### ISSUE THREAD

**Issue by blind0** [ss220-space/Paradise#220]
### Ckey

blind0

### Описание бага

Баг сбрасывает кд на любом оружии меха, позволяя пользоваться лазерами,тазерами,пулемётами,ракетками без какого-либо ожидания.

Я бы дал этому багу категорию СУПЕРОПАСНО, ибо смог на дюранде с помощью него выебать эш дрейка и кровожадного шахтёра.

### Шаги воспроизведения

1. берёте меха
2. берёте пушку меха и вставляете в меха
3. в руку берёте свою id карту
4. с id картой в руке, садитесь в меха.
5. выбираете оружие в панели меха
6. И теперь во время стрельбы постоянно клацаете X, чтобы менять руки
7. profet, стрельба с меха без кд, работает абсолютно на всё вооружении

### Ожидаемое поведение

1. берёте меха
2. берёте пушку меха и вставляете в меха
3. в руку берёте свою id карту
4. с id картой в руке, садитесь в меха.
5. выбираете оружие в панели меха
6. И теперь во время стрельбы постоянно клацаете X, чтобы менять руки
7. nonprofet, стрельба с меха с кд, сосём бибу, блоба захуярить за миллисекунду теперь не выйдет.

### Дополнительная информация

Видосик чтоб было понятно 100% как баг абузить.

https://user-images.githubusercontent.com/45512381/127110610-ca6bff6c-ff92-4c0a-9cab-a48950d4d4df.mp4

### Операционная система

win10

### Версия клиента

513.1542

### Название сервера

MAIN

### Примерное время и дата

Баг работает всегда, не думою што это важно.

**Comment by OpsCoretango** [comment]
Меня на серафе, Йерофант кончил со всем топовым оружием, броней и дроидом.

**Comment by Frozored** [comment]
Предлагаю убрать этот баг только для резака, а остальное оружие не трогать и оставить как фичу
