### ISSUE TITLE
Feat: Радиоканал боргов на русской раскладке не работает

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#221]
### Проблема

Использование в чате радиоканала :b на русской раскладке в виде :и не работает

### Решение

Сделать, чтобы работало :shr

### Плюсы

Борги и ИИ смогут быстрее и проще общаться друг с другом

### Минусы

Никаких

**Comment by Zigamus** [comment]
Это баг, а не предложение.

**Comment by Zigamus** [comment]
Перепиши в баги
