### ISSUE TITLE
Feat: Вкладка эмоций для боргов

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#222]
### Проблема

У боргов есть особые, доступные им эмоции, которыми не особо удобно пользоваться, вводя команды, да и мало кто о них знает

### Решение

Добавить боргам вкладку Robotic Emotes с хоткеями на эмоуты

### Плюсы

Общение с боргами будет более "живым"

### Минусы

Больше орущих боргов

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184354827-1c726258-1105-4e4a-9b8a-6289d2299db0.png)
