### ISSUE TITLE
Feat: ATMOS holo projector

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#223]
### Проблема

У инженерного борга, предназначенного для работы в трудных условиях, нет голографического прожектора атмоса, позволяющего блокировать газы, что пригождается при спасении жоп кожаных мешков

### Решение

Добавить боргу голографический прожектор атмоса

### Плюсы

Борги станут чуточку более полезными и не будут дергать атмотехов лишь для того, чтобы поставить барьер

### Минусы

Еще больше путаницы в инструментах борга

**Comment by AttHawk** [comment]
Да, предложка норм, чертежи есть а атмос проектора нет

**Comment by snipersir** [comment]
У него вместо атмосного проектора стоит инженерный. Как насмешка в догонку - инженерный борг сам же не может через него проезжать. Кто делал инструментарий для него - гений.

**Comment by HMBGERDO** [comment]
> У него вместо атмосного проектора стоит инженерный. Как насмешка в догонку - инженерный борг сам же не может через него проезжать. Кто делал инструментарий для него - гений.

ну, вообще-то может, через alt, как и через другие барьеры. Если не ошибаюсь - отсутствие атмосного голобарьера у борга с официалки, там также и как-то все живут.
В остальном - можно добавить, повышаем полезность железного друга, понижаем необходимость в экипаже

**Comment by MaliciousPancake** [comment]
> > У него вместо атмосного проектора стоит инженерный. Как насмешка в догонку - инженерный борг сам же не может через него проезжать. Кто делал инструментарий для него - гений.
> 
> ну, вообще-то может, через alt, как и через другие барьеры. Если не ошибаюсь - отсутствие атмосного голобарьера у борга с официалки, там также и как-то все живут.
> В остальном - можно добавить, повышаем полезность железного друга, понижаем необходимость в экипаже

Смех смехом, а он действительно не может проезжать через знак, даже с альтом

**Comment by HMBGERDO** [comment]
реально не может. Ну значит силиконы сосатб.

**Comment by Danefalt** [comment]
Что же, раз никто не берётся...
Тут две вещи:
Баг - борги не могут проходить через голобарьеры даже на низкой скорости.
И предложка - добавить ему голопрожектор атмоса.
Я не гарантирую что в скором времени это будет обеспечено, но я постараюсь как только освобожусь.
