### ISSUE TITLE
Постройка/заказ принтеров

### ISSUE THREAD

**Issue by AugustBebel** [ss220-space/Paradise#224]
### Проблема

Сейчас невозможно строить принтеры, те же ксероксы, те же копировальные аппараты. Более того, их нельзя заказать в карго. В итоге такая банальная техника почему-то в ограниченном количестве на нашей «передовой» станции.

### Решение

Дать возможность заказывать/строить принтеры.

### Плюсы

Все перестанут грабить библиотеку на принтеры.

### Минусы

В библиотечном принтере будет быстро кончатся тонер. В библиотеку будут ещё меньше ходить.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184354915-b4f2227f-0d44-498c-9f3e-fc26048ad9be.png)
