### ISSUE TITLE
Feat: резня 

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#226]
### Проблема

после гринтекста нельзя повеселиться и спустить пар, а так же харкнуть в харю тому самому щиткуру который ебал тебе мозг. Агрессия копится и выводит людей на нарушения. 

### Решение

Разрешить дм после гринтекста 

### Плюсы

Люди смогут спустить пар на нерадивых щиткуров и прочих гадов в конце раунда, поржать от резни 

### Минусы

Возвращение нарушений за дм до Грина. Клувни выпьет ванну говна.

**Comment by tizer7** [comment]
против.
может для выпуска пара игроки вспомнят про голодэк, в кои то веки?

**Comment by Danefalt** [comment]
Веселится нужно после раунда. Ждите переработки ЦК, её уже заканчивают. И можно будет спокойно продолжать РП даже там.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184354946-56f65ca4-1a8b-4494-b342-443b15e054ec.png)
