### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by VadaOni** [ss220-space/Paradise#2260]
### Ckey

Vada Oni

### Описание бага

На Керберосе 2 мыши Рататуй, одна у повара возле раковины, вторая у ботаников на нижних грядках 
![image](https://user-images.githubusercontent.com/127536463/224373878-a944cb94-180d-4a83-b738-f7b0ae8cc882.png)

### Шаги воспроизведения

Раундстартом

### Ожидаемое поведение

Скорее всего, должна быть только одна мышь 

### Дополнительная информация

Сегодня (10.03.2023 18:30) скачал с вики новую версию локалки и решил прочекать что там поменяли, и заодно новых животных в отделах, нашел абсолютно случайно

### Операционная система

Windows

### Версия клиента

514.1589

### Название сервера

MAIN

### Примерное время и дата

10.03.2023 18:40

**Comment by SAADf603** [comment]
закрыто https://github.com/ss220-space/Paradise/pull/2261
