### ISSUE TITLE
Bug: Радиоканал боргов на русской раскладке не работает

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#228]
### Ckey

maliciouspancake

### Описание бага

Использование в чате радиоканала :b на русской раскладке в виде :и не работает

### Шаги воспроизведения

1. Быть боргом/ИИ
2. Попробовать написать через ":и"

### Ожидаемое поведение

Должна была сработать замена на ":b"

### Операционная система

Windows 10

### Версия клиента

5.0 Public, 513.1542

### Название сервера

MAIN

### Примерное время и дата

26.07.2021

**Comment by Honker9999999** [comment]
Древний баг, и просто так не фиксится. При попытке фикса код таяр начинает ругатся, так что либо выпил хвостатых, либо нет русской раскладки.

**Comment by MaliciousPancake** [comment]
> Древний баг, и просто так не фиксится. При попытке фикса код таяр начинает ругатся, так что либо выпил хвостатых, либо нет русской раскладки.

Может, в те ли случае, можно их чат кинуть хоткеем на отдельную кнопку или сочетание? Ctrl+T, к примеру

**Comment by mayorovp** [comment]
А таяры-то тут при чём?
