### ISSUE TITLE
Feat: тазеры и дисейблеры

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#232]
### Проблема

В реале тазеры и дисейблеры хуярят током. сильно. а как мы знаем, ток сугубо отрицательно влияет на нервную систему. Дисейблер же в свою очередь просто бьёт по стамине, предположительно, по лёгким. Выходит нереалистично, что можно хоть 100500 раз затазерить человека, а урона нет. Плюс воздействие тока от двери даёт просто бёрн. с хуя ли? 

### Решение

сделать урон от тазера и батона по мозгу 2 единицу, от дисейблера ничего не добавлять. Станпроду сделать урон 5 единиц по мозгу. От электродвери 15 по мозгу и 15 берна. P. S. дополнительный урон в 5 единиц от хармбатона. 

### Плюсы

возможность посчитать количество станов/тазеров у человека.
Реализм, так как воздействие тока и правда хреново влияет на нервную. 
сбегающий преступник может забыть как юзать интерфейсы.
щиткур будет лишний раз думать прежде чем врубать батон. 
справедливый аджаст, как для батона так и для станпрода. у станпрода в сторону большего урона ввиду того, что он не дозирует электричество. у батона вменьшую, т. к. старается меньше давать дюлей. прибавка от харма так как подаётся дополнительное напряжение. все вполне логично, нормальный аджаст для СБ и антагов.

### Минусы

картошка из человека которого хуярят станпродом,проще стать щиткуром. 
лечить лишний урон
тритор со станпродом сделает картошку из цели на харме (5+5 брейндамага за удар)
меньше и так нужного маннитола

**Comment by HMBGERDO** [comment]
>> щиткур будет лишний раз думать прежде чем врубать батон.
это так не работает

такое себе, звучит как новый способ убить через урон мозгу. Какое-то интересное применение этой штуки тут не вижу. Зато за случайный станбатон будут крики ОН МЕНЯ УБИВАЕТ АА ПОМОГИТЕ

**Comment by Frostillikus21** [comment]
Вообще звучит как возможность ещё сильнее банить щиткуров

**Comment by DayBreakerBrony** [comment]
> > щиткур будет лишний раз думать прежде чем врубать батон.
> 
> это так не работает
> 
> такое себе, звучит как новый способ убить через урон мозгу. Какое-то интересное применение этой штуки тут не вижу. Зато за случайный станбатон будут крики ОН МЕНЯ УБИВАЕТ АА ПОМОГИТЕ

я уже пояснил, что интересное применение заключается в том, что с большим брейндамагом можно и забыть как дверь открыть

**Comment by DayBreakerBrony** [comment]
> > щиткур будет лишний раз думать прежде чем врубать батон.
> 
> это так не работает
> 
> такое себе, звучит как новый способ убить через урон мозгу. Какое-то интересное применение этой штуки тут не вижу. Зато за случайный станбатон будут крики ОН МЕНЯ УБИВАЕТ АА ПОМОГИТЕ

а если человек после задержания даже внятно говорить не сможет и с большим дамагом по телу, сразу понятно, что человек щиткурит. и дать пизды ему за такое

**Comment by AttHawk** [comment]
Заряд на ирл тазерах и шокерах идёт по поверхности тела, даже не всякую одежду пробивает, и опасность для здоровья только у кардиостимуляторников в основном, плюс щиткурение станет гораздо болезнее для жертвы, такой себе вариант

**Comment by Den109G** [comment]
Может на мейне это и так, но на ВЛе редко кого просто так задерживают.
С моей стороны, это гриф-подобная вещь от разработчиков/кодеров или тебя, за реализацию или идею.
Да и сравнивать ИРЛ с СС.... Тут чтобы спастись от любого тока нужно взять лишь перчатки. А тазер спокойно работает через хардсьют, который защищает от космоса на минуточку.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184355117-3da778c5-2a93-45e6-9da8-83186a9e9e40.png)
