### ISSUE TITLE
Feat: Разядривание аномальных ядер

### ISSUE THREAD

**Issue by blind0** [ss220-space/Paradise#234]
### Проблема

Ядра аномалий по большей части бесполезны и используются только для создания фазона и очень редко их распыляют в деструкторе.

### Решение

Добавить возможность выпускать из ядра аномалию.

Выпуск аномалии:

https://user-images.githubusercontent.com/45512381/127530367-7f7ded1e-0d49-41b9-8148-fa5021422b69.mp4

Аномальные ловушки:

https://user-images.githubusercontent.com/45512381/127530391-dafe0d9b-0da3-4323-8cd0-904ab6d9baa5.mp4

### Плюсы

Новый прикол для антажек.
Меньше будет подрывов от флюкс аномалий, ибо больше людей будут охотится за ними.

### Минусы

Ролькохантерам, станет проще определять антажек.
Больше я чёт минусов не вижу.

**Comment by Danefalt** [comment]
Раз всем пофиг... То делай ПР, раз уж у тебя готовый код. Либо кидай пример кода разрабам чтобы они всё сделали
¯\_(ツ)_/¯

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184355170-ed78f41f-87bc-406a-aa35-e522d629e12d.png)
