### ISSUE TITLE
Feat: Добавить игровой автомат "Сапёр"

### ISSUE THREAD

**Issue by iscorekin** [ss220-space/Paradise#2345]
[Отчет](https://discord.com/channels/617003227182792704/755125334097133628/1090303029347098654)

### Проблема

В баре мало развлечений.

### Решение

Добавить игровой автомат "Сапёр" в дормы и бар. 
За победу будет выдаваться 80-150 билетиков.

### Плюсы

Весёлая и интересная классика игровой индустрии, в которой будет круто провести некоторое время спокойствия в раунде.

### Минусы

Станет больше асистух, которых повязали за реплику даблы в баре.

**Comment by iscorekin** [comment]
Беру и делаю.

**Comment by VasilevAY** [comment]
> Беру и делаю.

не забудь закинуть предложку в книгу-отложений и привязать ПР к данному issue

**Comment by pilygun** [comment]
Ну и где сапер? Я жду вообще-то

**Comment by ArtemDerp** [comment]
Ну и где сапер? Я жду вообще-то

**Comment by pilygun** [comment]
Я все еще жду сапера

**Comment by pilygun** [comment]
@ROdenFL Закрывай)))

**Comment by ROdenFL** [comment]
у меня прав нету
