### ISSUE TITLE
Новая озвучка объявлений 

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#235]
### Проблема

Прямо сейчас в игре как-таковых объявлений нет. Разве что пару по ивентам и коды. Это же можно исправить, взяв огромную кучу аннонсов. Осталось только пройти голосование. 

### Решение

Вся работа уже сделана, осталось только дождаться решения игроков.
ПР: https://github.com/ss220-space/Paradise/pull/199

### Плюсы

Меньше писков от которых начинает идти кровь из ушей, и больше вокзального духа на станции.

### Минусы

Мы теперь станция "Исход"

**Comment by pahanya** [comment]
Новая озвучка всеми силами старается показаться крутой и РиАлИсТиЧнОй, но звучит как вокзальный громкоговоритель где-то глубоко в провинции. Голос и звуки совершенно не попадают под атмосферу станции. Оповещения в некоторых моментах слишком затянуты.

**Comment by PoTapkam** [comment]
А можно послушать работягам там файликами? А то я все понимаю код кодом, но файликов нема, но идея с переводом и озвучкой хорошей, если она будет такая же в исполнении конечно.

**Comment by Danefalt** [comment]
> А можно послушать работягам там файликами? А то я все понимаю код кодом, но файликов нема, но идея с переводом и озвучкой хорошей, если она будет такая же в исполнении конечно.

Можно форкнуть мой репозиторий. Там должно быть всё это. Касательно расположения:
sound/AI, в папке example находятся старые файлы озвучки, для сравнения.

**Comment by ImJustKisik** [comment]
За
Новые звуки, значит. Собственно, необходимость новой озвучки очевидна, потому что однообразный писк при различных сообщениях - есть зло и от него стоит избавится. 
Соответственно, поэтому я за включение этой озвучки в билд. Единственным минусом является то, что она не русифицирована. Но с переводом сообщений в чате всё интуитивно понятно. 
(Для русификации голосовых сообщений можно воспользоваться WaveNet, может кто захочет занятся этим на досуге). 
Подытоживая: Озвучка - хорошо, перевод - ещё лучше.

**Comment by DayBreakerBrony** [comment]
1.За
2.Форкнул, послушал. На "Exodus" немного все равно, а вот с ивентов с сирены кринжанул. Но озвучка хорошая, звучит мягко, и атмосферно для станции, а не гребаный писк или внезапный скример "EMERGENCY SHUTTLE HAS BEEN CALLED". Короче говоря озвучка мне Нравится и я хотел бы видеть её в игре.

**Comment by Danefalt** [comment]
> 1.За
> 2.Форкнул, послушал. На "Exodus" немного все равно, а вот с ивентов с сирены кринжанул. Но озвучка хорошая, звучит мягко, и атмосферно для станции, а не гребаный писк или внезапный скример "EMERGENCY SHUTTLE HAS BEEN CALLED". Короче говоря озвучка мне Нравится и я хотел бы видеть её в игре.
> P. S. у озвучки есть один недостаток. Когда админы будут проводить ивенты и врубать музончик длинные клаксоны объявлений и дельты будут только мешать, но я думаю что статичная атмосферность станции стоит намного больше, чем ивентоая, более редкая

"А СКАЩЮАЛ КРЮТРАНСФЕР ХАС КОЛЛД ФОР ЗЕ СТЕТИОН, ИТ ВИЛЛ АРИВЕ АТ ФЕВ МИНЮТЕС", а так, да. В постоянном режиме слышать спокойные, хорошо озвученные аннонсы просто приятно для ушей. Не будет резкого отключения гравитации и слов в общем канале "что произошло?", ведь есть отдельный аннонс со звуком для отключения гравигена (Мы пытались понять что там вообще говорится KEKW, и пришли к такому "Feedback search detected a mass distribution systems. Artificial gravity has been disabled thus the system run initialises for the failures may exilt in a gravitational collapse and formation of black holes. Have a nice day.", и включения соответственно (первый звук перед началом аннонса офигенный). Забудьте про писк после вызова ОБР, ведь они тоже получили своё. Да даже у капитанского аннонса есть свой саунд. И это ещё не говоря и о других вещах (Мне кста вот что нравится в озвучке перегрузки ЛКП: Там в последней фразе говорится, что в качестве меры безопасности, на **космической станции** отрубают электричество. Или взять те же ивенты, раньше около половины использовала файл для аннонса аномалий, которые телепортируют (чёрных дыр если проще), сейчас же даже у блюспейс аномалии есть свой собственный аннонс, а это самая редкая аномалия в игре (если мне не изменяет память).

**Comment by semoro** [comment]
1. За
Анонсы звучат приятно, улучшат общую атмосферу
Некоторые возможно длинноваты, но для улучшения атмосферности самое то

**Comment by AttHawk** [comment]
За
Если переименовать станцию в экзодус то вообще топ 🤡  А в целом круто, важно, нужно, классно, особенно то что не читающие чат не будут спрашивать "А почему (радномное событие нейм)?"

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184355249-f27985bb-0812-4f6b-89c8-bef913e3004a.png)
