### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Rocket1222** [ss220-space/Paradise#2370]
### Ckey

Rocket1234444

### Описание бага

нету текстуры у предмета Bear Trap

### Шаги воспроизведения

раундстартом в комнате уборщика появляется этот предмет

### Ожидаемое поведение

что бы его было видно а он не был прозрачным

### Дополнительная информация

![image](https://user-images.githubusercontent.com/126243052/226455557-0bf18c64-c8e9-4d44-86e6-988350ada448.png)
![image](https://user-images.githubusercontent.com/126243052/226455604-d0c3b129-d5d6-4cc1-baab-1b05bbb53cca.png)

### Операционная система

Windows 10

### Версия клиента

514.1589

### Название сервера

MAIN

### Примерное время и дата

23:16 21.03.2023

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/226822849-0478b2a5-da60-4174-9e63-bf689b5b823a.png)
![image](https://user-images.githubusercontent.com/98010665/226822876-defde354-4862-4553-8b5b-3ecef0fed5f9.png)
d
Раундстартом в комнате уборщика в указанном месте не нашел медвежью ловушку

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/226823168-cd9940a9-5c22-4b33-8891-b22519903267.png)
в strongdmm тоже не обнаружилось ничего

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/226823239-ae51b112-ebc4-4e26-b74c-179df707205d.png)
При создании предмете спрайт отображается корректно. 
Issue закрывается из-за неактуальности/невозможности воспроизвести баг
