### ISSUE TITLE
Feat: Инженерные улучшения

### ISSUE THREAD

**Issue by Gottfrei** [ss220-space/Paradise#238]
### Проблема

Многие объекты в игре не могут быть разобраны или, хотя бы, отвинчены от пола, для передвижения в другое место

### Решение

Добавить возможность ХОТЯ БЫ отвинчивать ВСЕ такие предметы, я понимаю что это, возможно, много работы, не в курсе как работает код игры

### Плюсы

Возможность перестройки, улучшения и доработки любых мест на станции, без необходимости разрушать, иногда не возводимые, объекты

### Минусы

Придется перелопатить много кода?

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/projects/2
in progress
