### ISSUE TITLE
Feat: однородность нюкеров. 

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#239]
### Проблема

в каждом раунде про нюку, каждый отряд нюкеров ВСЕГДА состоит из людей. Считаю это неправильным и скучным, особенно когда твою расу (я вот плазмамен, например) форсспавнит за хумана, а у этого ебучего мешка надо дышать кислородом и жрать.

### Решение

добавить возможность войти за нюкеров следующим расам(включая, но не ограничиваясь)так как это распространит знания среди нешарящих за Анатомию рас и породит возможности создания подклассов, например:
КПБ (легковозрождаемый танк, способный самочиниттся и принимать на лицо много урона)
Плазмамены (идеальный экономный работник в космосе, т. к. большой баллон плазмы, нужен только риг и необязательно есть)
таяры ((НЕ ВУЛЬПЫ!!!) Юнит, природный для разведывательных целей и быстрых штурмовых операций.)
список будет дополняться. Если игрок заходит за недоступную для нюкеров расу, выдавать ему случайную из доступных. 

### Плюсы

люди начнут шарить за Анатомию редких рас, лорная достоверность, т. к. не только хуманы работают на синдикат. возможность играть за нюкеров на любимой расе (вульпы вон) 

### Минусы

нытье механоебов на бафф и так имбовой нюки
зверинец у синдиката 
полуимбовые таяры в синди

**Comment by Honker9999999** [comment]
1. Против.
2. Нахуя? Люди в нюке не баг, а фича. Как и в ЕРТ. Как и в дедскваде. С чего ты взял что по лору они берут иные расы на высокие должности? Не видел такого момента ни в настоящем, ни в пилящемся лоре. Маняфантазии некоторых админов, что любят заходить за вульпочек на синди-офицеров не считаются.
Каким образом это прокачает знания анатомии иных рас не знали даже чеченцы, ибо... А как? Их убивать больше будут и так прокачают знания? Что-то мне подсказывает(но что...) ты с такой логикой игрой ошибся, это подходит для какой-то "Охота 2020 три де", но уж никак для СС13(хотя, может гитхабом ошиблись?)

**Comment by DayBreakerBrony** [comment]
> 1. Против.
> 2. Нахуя? Люди в нюке не баг, а фича. Как и в ЕРТ. Как и в дедскваде. С чего ты взял что по лору они берут иные расы на высокие должности? Не видел такого момента ни в настоящем, ни в пилящемся лоре. Маняфантазии некоторых админов, что любят заходить за вульпочек на синди-офицеров не считаются.
>    Каким образом это прокачает знания анатомии иных рас не знали даже чеченцы, ибо... А как? Их убивать больше будут и так прокачают знания? Что-то мне подсказывает(но что...) ты с такой логикой игрой ошибся, это подходит для какой-то "Охота 2020 три де", но уж никак для СС13(хотя, может гитхабом ошиблись?)

нахуя другим расам с кем-то сотрудничать, если нет возможности отстаивать права, своей группы на должности? Да и к тому же это оперативники, а не отряд капитанов валидхантеров. Например, воинственные расы туда можно было бы запихнуть. по новому лору у плазмаменов Гражданская война технократов и теократов, соответственно НТ против Синди. Можно много лорных фич найти и создать, тем более что нюкеры реально начнут Чувствовать как отряд Синдиката: синдиката, который объединяется ради борьбы с НТ. и не факт, что люди - лучшие бойцы, Учитывая, как огромен космос.

**Comment by DayBreakerBrony** [comment]
> 1. Против.
> 2. Нахуя? Люди в нюке не баг, а фича. Как и в ЕРТ. Как и в дедскваде. С чего ты взял что по лору они берут иные расы на высокие должности? Не видел такого момента ни в настоящем, ни в пилящемся лоре. Маняфантазии некоторых админов, что любят заходить за вульпочек на синди-офицеров не считаются.
>    Каким образом это прокачает знания анатомии иных рас не знали даже чеченцы, ибо... А как? Их убивать больше будут и так прокачают знания? Что-то мне подсказывает(но что...) ты с такой логикой игрой ошибся, это подходит для какой-то "Охота 2020 три де", но уж никак для СС13(хотя, может гитхабом ошиблись?)

а про дедсквады и ерт можно сказать, что НТ не доверяет никому, кроме хуманов. Они же капиталюги ебаные.

**Comment by Danefalt** [comment]
> > 1. Против.
> > 2. Нахуя? Люди в нюке не баг, а фича. Как и в ЕРТ. Как и в дедскваде. С чего ты взял что по лору они берут иные расы на высокие должности? Не видел такого момента ни в настоящем, ни в пилящемся лоре. Маняфантазии некоторых админов, что любят заходить за вульпочек на синди-офицеров не считаются.
> >    Каким образом это прокачает знания анатомии иных рас не знали даже чеченцы, ибо... А как? Их убивать больше будут и так прокачают знания? Что-то мне подсказывает(но что...) ты с такой логикой игрой ошибся, это подходит для какой-то "Охота 2020 три де", но уж никак для СС13(хотя, может гитхабом ошиблись?)
> 
> а про дедсквады и ерт можно сказать, что НТ не доверяет никому, кроме хуманов. Они же капиталюги ебаные.

Я раскрою прикол:  У нас по лору ксеносы спокойно могут доходить до ЦК и работать там.
А что уж говорить о синдикате, которому так и так нужны кадры для борьбы с НТ.

**Comment by DayBreakerBrony** [comment]
Добивай этого хонкера, даня!! ксеносов в нюку.

**Comment by Honker9999999** [comment]
> > > 1. Против.
> > > 2. Нахуя? Люди в нюке не баг, а фича. Как и в ЕРТ. Как и в дедскваде. С чего ты взял что по лору они берут иные расы на высокие должности? Не видел такого момента ни в настоящем, ни в пилящемся лоре. Маняфантазии некоторых админов, что любят заходить за вульпочек на синди-офицеров не считаются.
> > >    Каким образом это прокачает знания анатомии иных рас не знали даже чеченцы, ибо... А как? Их убивать больше будут и так прокачают знания? Что-то мне подсказывает(но что...) ты с такой логикой игрой ошибся, это подходит для какой-то "Охота 2020 три де", но уж никак для СС13(хотя, может гитхабом ошиблись?)
> > 
> > 
> > а про дедсквады и ерт можно сказать, что НТ не доверяет никому, кроме хуманов. Они же капиталюги ебаные.
> 
> Я раскрою прикол: У нас по лору ксеносы спокойно могут доходить до ЦК и работать там.
> А что уж говорить о синдикате, которому так и так нужны кадры для борьбы с НТ.

ХА! ВОТ ТЫ И ПОПАЛСЯ!
Смотрим лор синдиката: "В то время как Nanotrasen официально классифицирует Синдикат как террористическую группу, как публично, так и через свою политику правоприменения на своих станциях, теоретики заговора утверждают, что Синдикат и Nanotrasen могут активно вступать в сговор. Некоторые журналистские группы часто утверждают, что в силу плохого этического поведения Nanotrasen, не было бы сюрпризом, если бы компания тайно наняла Синдикат для устранения проблемных сотрудников. Однако эти теории не имеют никаких доказательств, и руководство Nanotrasen отрицает какую-либо причастность к этой террористической группе."
Настолько надо что НТ похуй? Прикол.
Во вторых:
"Впрочем, есть несколько слушков в самых гнилых барах, гласящие что вся верхушка НТ - и вовсе насквозь ксенофобна, и что именно из-за их решения иные расы не берут на должности выше членов Центрального Командования или в некоторые отдельные "Организации" внутри НТ... Но это ведь лишь лживые слухи, распускаемые конкурентами НТ, ведь так?"
Ой, доходить до ЦК могут? Ну да, могут. Ага. С постоянным гноблением от вышестоящего начальства, но могут. Ну и нахуя ты спизданул про НТ непонятно.

Во вторых - у нас пишется новый лор, но даже по текущему ты обосрался. Прикольно а главное смешно. Во вторых - ВЕСЬ синдикат это кто? Это бывшие ЧЕЛОВЕЧЕСКИЕ корпорации, которые не хотят мириться с монополистом. Ключевое - "ЧЕЛОВЕЧЕСКИЕ". Нанимать иные расы как расходный материал? Да без "Б". Делать из них кого-то повыше? Нахуй надо. Это все согласовано с текущим лором:
"В основном в Синдикате работают низкоуровневые и малообеспеченные корпоративные сотрудники. Они выполняют различные поручения. Те, кто работает на Синдикат таким образом, либо отчаянно нуждаются в деньгах, либо имеют существующие долги, либо шантажируются."
НТ просто использует их. Какие тайны они знают? Никаких. Поэтому они могут быть абсолютно кем угодно. 
"Команды ядерных оперативников зачастую состоят из бывалых пиратов, которые работают в этом секторе в течение длительного времени, или результативных агентов, которые приняли Синдикат в качестве своего работодателя."
Много пиратов вульп знаешь около солнечной, блять, системы?(а я напомню для не сведующих в лоре - Кибериада и Керберос находятся около звезды "Э́псилон Эрида́на", ИРЛ существующая звезда, одна из самых близких к Солнцу звезд, 10.5 световых годиков или около того). Видимо, очень много?



> Добивай этого хонкера, даня!! ксеносов в нюку.

Не даня, а лёха.

**Comment by DayBreakerBrony** [comment]
слыш, 

> > > > 1. Против.
> > > > 2. Нахуя? Люди в нюке не баг, а фича. Как и в ЕРТ. Как и в дедскваде. С чего ты взял что по лору они берут иные расы на высокие должности? Не видел такого момента ни в настоящем, ни в пилящемся лоре. Маняфантазии некоторых админов, что любят заходить за вульпочек на синди-офицеров не считаются.
> > > >    Каким образом это прокачает знания анатомии иных рас не знали даже чеченцы, ибо... А как? Их убивать больше будут и так прокачают знания? Что-то мне подсказывает(но что...) ты с такой логикой игрой ошибся, это подходит для какой-то "Охота 2020 три де", но уж никак для СС13(хотя, может гитхабом ошиблись?)
> > > 
> > > 
> > > а про дедсквады и ерт можно сказать, что НТ не доверяет никому, кроме хуманов. Они же капиталюги ебаные.
> > 
> > 
> > Я раскрою прикол: У нас по лору ксеносы спокойно могут доходить до ЦК и работать там.
> > А что уж говорить о синдикате, которому так и так нужны кадры для борьбы с НТ.
> 
> ХА! ВОТ ТЫ И ПОПАЛСЯ!
> Смотрим лор синдиката: "В то время как Nanotrasen официально классифицирует Синдикат как террористическую группу, как публично, так и через свою политику правоприменения на своих станциях, теоретики заговора утверждают, что Синдикат и Nanotrasen могут активно вступать в сговор. Некоторые журналистские группы часто утверждают, что в силу плохого этического поведения Nanotrasen, не было бы сюрпризом, если бы компания тайно наняла Синдикат для устранения проблемных сотрудников. Однако эти теории не имеют никаких доказательств, и руководство Nanotrasen отрицает какую-либо причастность к этой террористической группе."
> Настолько надо что НТ похуй? Прикол.
> Во вторых:
> "Впрочем, есть несколько слушков в самых гнилых барах, гласящие что вся верхушка НТ - и вовсе насквозь ксенофобна, и что именно из-за их решения иные расы не берут на должности выше членов Центрального Командования или в некоторые отдельные "Организации" внутри НТ... Но это ведь лишь лживые слухи, распускаемые конкурентами НТ, ведь так?"
> Ой, доходить до ЦК могут? Ну да, могут. Ага. С постоянным гноблением от вышестоящего начальства, но могут. Ну и нахуя ты спизданул про НТ непонятно.
> 
> И в третьих - у нас пишется новый лор, но даже по текущему ты обосрался. Прикольно а главное смешно. Во вторых - ВЕСЬ синдикат это кто? Это бывшие ЧЕЛОВЕЧЕСКИЕ корпорации, которые не хотят мириться с монополистом. Ключевое - "ЧЕЛОВЕЧЕСКИЕ". Нанимать иные расы как расходный материал? Да без "Б". Делать из них кого-то повыше? Нахуй надо. Это все согласовано с текущим лором:
> "В основном в Синдикате работают низкоуровневые и малообеспеченные корпоративные сотрудники. Они выполняют различные поручения. Те, кто работает на Синдикат таким образом, либо отчаянно нуждаются в деньгах, либо имеют существующие долги, либо шантажируются."
> НТ просто использует их. Какие тайны они знают? Никаких. Поэтому они могут быть абсолютно кем угодно.
> "Команды ядерных оперативников зачастую состоят из бывалых пиратов, которые работают в этом секторе в течение длительного времени, или результативных агентов, которые приняли Синдикат в качестве своего работодателя."
> Много пиратов вульп знаешь около солнечной, блять, системы?(а я напомню для не сведующих в лоре - Кибериада и Керберос находятся около звезды "Э́псилон Эрида́на", ИРЛ существующая звезда, одна из самых близких к Солнцу звезд, 10.5 световых годиков или около того). Видимо, очень много?
> 
> > Добивай этого хонкера, даня!! ксеносов в нюку.
> 
> Не даня, а лёха.

если тебя это ещё больше взбесит, то я лично прослежу чтобы синдикат очень близко работал с ксеносами.я ведь сам лорописец.

**Comment by DayBreakerBrony** [comment]
и кстати. Мнения на гите пишите, а не галки ставьте. это касается всех в книге предложений, а так же к дане. потому что сказано было, что только с гита мнения считаются

**Comment by VictorSocks** [comment]
Кто не знал, но на синдикат на постоянной основе работают и учёные уже могут быть: дионами, таярами, вульпами, унатхами, скреллами, слаймоменами. У оперативников нюки же названия как у каких-то учёных, например: biotech operator #3, что даёт мысль что нюкеры набираются из этих ученых. Это не написано в лоре, просто на сейчас удаленной базе Синди на лаве можно было заспавнится за одну из этих рас.

**Comment by Suchinessa** [comment]
1. Против
2. Не надо пускать ксеноебов к лору. Если отряд нюкеров или ЕРТ это хуманы, значит они хуманы, потому что так надо, потому что Хуманы в плане баланса самая нормальная раса, без финтифлюще в виде хила сваркой, самоподрыва путем снятия костюма и отсутвия голода. Хотите играть на вульпочках - уберайте галочку с Ядерного оперативника. А уважающая себя компания НТ вообще не позволит себе пускать в отряд ЕРТ НЕ людей

**Comment by Qwadrob** [comment]
1. Против
2. У нас меняется лор. Доступ к новому лору есть мало у кого и тут мы предлагаем " лорная достоверность" за это уже просто против, дождись "лора" для "достоверности". 
Далее "если тебя это ещё больше взбесит, то я лично прослежу чтобы синдикат очень близко работал с ксеносами.я ведь сам лорописец." Звучит как обида ебаная и нет не проследишь, то что тебе дали возможность писать не значит, что нет редактора.
И как раз по лору НТ и Синдикат это людские корпорации, которые делались людьми и для людей, у синидиката просто может не быть банальных веще для плазмамена - которые найти, заказать, доставить не самый простой процесс. Как говорил Хонк выше - не логично видеть пиратов около метрополии людей. 
Не понимаю как убийство ксенорас поможет изучить их анатомию. Только если тебя кинет за грёбаного ксеноса и ты вынужден будешь тратить время на нюке что бы читать про расу которую ты не хотел. Напомню что человеки стандартная раса за которую начинает 90% игроков.

**Comment by AttHawk** [comment]
1. Против
2. Нет с позиции геймплейной, так как хуманы единственная раса без плюсов, минусов и приколов в плане лечения.
По поводу неготового лора пока говорить рано, но вся предложка звучит как "хочу на вульпочке пур-пур, на плазме бах-бах и на КПБ бип-буп"

**Comment by Zigamus** [comment]
> если тебя это ещё больше взбесит, то я лично прослежу чтобы синдикат очень близко работал с ксеносами.я ведь сам лорописец.

_Борис запомнит это_

В случае чего теперь есть аргумент в пользу того, что подобное решение с твоей стороны субъективное и основывается не на общем благе, а на том, чтоб уделать оппонента в споре.

**Comment by Zigamus** [comment]
Против

> таяры ((НЕ ВУЛЬПЫ!!!) Юнит, природный для разведывательных целей и быстрых штурмовых операций.)
Что таяры, что вульпы, это юнит, который не отличается от человека ничем, кроме уязвимости к вспышкам.

Странно для НТ при наличии большого количества людей брать на столь нишевые должности ксеносов, ксеносы росли в других условиях, учились другим боевым искусствам, их психика отличается от людской, так что в итоге это выглядит как замечательный способ для НТ заебаться, получив в итоге результат не лучше, чем при полной команде людей.

**Comment by Dreemer556** [comment]
Вопрос логики. Как игрок будет изучать анатомию если его задача ебать экипаж попутно веселя народ? Вот, товарища подстрелили и ты понесёшь его в мед? Нет, ты его бросишь умирать и даже отойдёшь, ибо он пизданёт буквально через минуту. Представлю себя на месте ядерника. За 200 часов он мне выпал один раз. Я буду спасать своего сокомандника? Да положу болт и продолжу веселится отрезая головы лазерным мечом. Мы хоть и команда но у нас в первую очередь стоит цель - уничтожить станцию к хуям. Синдикат бы делал психологическую подготовку именно на такое.

Ещё, если человек хочет изучить анатомию, он пойдёт работать медиком. Если он не хочет изучать и не умеет, то бросит своего товарища даже если отменить самоподрыв после смерти

**Comment by Honker9999999** [comment]
> если тебя это ещё больше взбесит, то я лично прослежу чтобы синдикат очень близко работал с ксеносами.я ведь сам лорописец.

Жалко, но ты не лука, не бот, не картоха и не СА. Писать то можешь, но вот примут ли это они... Вопрос.

**Comment by LoveTrapov** [comment]
1. Против
2. Просто поддерживаю все против выше, не вижу смысла писать тоже самое. Звучит как глупая хотелка, нежели полезное предложение.

**Comment by zombie288** [comment]
1. Против
2. Сейчас бы ксеносов добавлять в сверхэлитную штурмовую группу, чья задача максимально быстро взорвать станцию...
`если тебя это ещё больше взбесит, то я лично прослежу чтобы синдикат очень близко работал с ксеносами.я ведь сам лорописец.`, смеялись всем селом.

**Comment by OpsCoretango** [comment]
1.Нейтрально
2. Если это касается воксов то соглашусь но остальное это против ингейм логики.
Соответственно предлагаю вероятность появление за вокса и его подвидов.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184355881-6f751ce0-89f4-4b4d-a23c-d894e5a8635a.png)
