### ISSUE TITLE
Feat: добавить новый игровой режим для гостов

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#240]
### Проблема

В игре появляется новая территория "Неосвоенные земли". Это место является предметом интересов некоторых имеющих власть личностей, именно поэтому на него отправляется группа добровольцев с оборудованием в руках и оружием на перевес.
Отряд состоящий из добровольцев первым делом высаживается на поверхность планеты и устанавливает связь с НТ, после чего отряд получает своё задание. Эти задания бывают нескольких видов: поиск артефактов, уничтожение аванпоста неприятелей, уничтожение опасного вида фауны, добыча некоторых полезных ископаемых из грунта, добыча генетичечкого материала, поиск пропавших, оборона того или иного объекта. Какое бы задание не выпало бы на участь отряда, его членам в любом случае будет не сладко. Ведь их выживание зависит лишь от них. Продовольствия, конечно, хватит на какое-то время, но при затяжном выполнение задания еду придётся добывать на месте; количество медикаментов ограничено, придётся выбирать умереть одному сейчас или другому потом; флора и фауна не рада гостям и будет активно пытаться убить нежданных гостей; кроме вас на планете имеются и другие желающие поживиться местными "богатствами", будьте готовы дать им отпор.

### Решение

Каждый новый раунд, когда будут заходить игроки им будет даваться 15 минут на сборы оборудования, экипировки и прочего. Все вещи игроки помещают на небольшой корабль и после сборов садятся на него и вылетают. До 15 минуты нужно  минимум 4 карточки нажать на консоль запуска, чтобы запустить корабль, после 15 хватит и одной. После этого корабль прилетает на поверхность и все последующие госты уже спавняться в нём. Далее игроки ставят телекомы и получают задание и начинают его выполнение. После выполнения одного можно запросить новое задание.
Поиск артефактов: просто идем артефакт и тащим его на корабль, чтобы задача была выполнена 
Уничтожение аванпоста: дать полный контроль над аванпостом НТ, путём взлома консоли управления + убить всех его обитателей
Уничтожение фауны: убить указанное животное
Добыча ископаемых: ставим буры и обороняем их пока всё делается, потом оттаскиваем ящик с рудой на корабль
Добыча генетического материала: dna инжектором хуячим по указанным животным и растениям, а после на корабль его
Оборона: не дать умереть всему отряду + не дать уничтожить тот или иной объект.

### Плюсы

Новый режим для гостов, ксочка с элементами выживания и адвенчуры, больше идей для ивентов

### Минусы

Кодить, исправлять ошибка и кодить

**Comment by Jordanstolethepreciousslam** [comment]
То есть тот же самый лаваленд ага. У нас и так из-за атмоса лавы и гейта падает таймер нахуй а ты предлагаешь еще один z-уровень размера лаваленда. Выглядит просто как эксплорер с большим количеством шагов и на лаве.

**Comment by Sykybekk** [comment]
> То есть тот же самый лаваленд ага. У нас и так из-за атмоса лавы и гейта падает таймер нахуй а ты предлагаешь еще один z-уровень размера лаваленда. Выглядит просто как эксплорер с большим количеством шагов и на лаве.

Если ничего умнее очередного нытья не можешь, то блять не пиши тут

**Comment by Jordanstolethepreciousslam** [comment]
Хм. Не помню чтобы я тебя спрашивал что мне делать. Но раз уж так играем, то давай ты не будешь предлагать то что не сделал? Ну или хотя бы то что уже делаешь. Пока что это пердеж в лужу уровня "я джва года ждал такую игру".

**Comment by Sykybekk** [comment]
> Хм. Не помню чтобы я тебя спрашивал что мне делать. Но раз уж так играем, то давай ты не будешь предлагать то что не сделал? Ну или хотя бы то что уже делаешь. Пока что это пердеж в лужу уровня "я джва года ждал такую игру".

Ага, пишет  тот кто может только высрать: "ой это есть, это сложно я тупой пук-пук, я не умею это и поэтому другие не умеют и не хотят". Завались и пиздуй отсюда, все равно нихуя не делаешь

**Comment by Jordanstolethepreciousslam** [comment]
Я напомню что это issue репозитория а не твоя ЖЖшка. Не тебе мне указывать что мне писать, где и когда. Если так невыносимо тяжело воспринимать факты то просто удались из гитхаба. Всё равно пока ничего кроме полутора рофлопредложек ты не сделал.

**Comment by Sykybekk** [comment]
> Я напомню что это issue репозитория а не твоя ЖЖшка. Не тебе мне указывать что мне писать, где и когда. Если так невыносимо тяжело воспринимать факты то просто удались из гитхаба. Всё равно пока ничего кроме полутора рофлопредложек ты не сделал.

**Comment by Jordanstolethepreciousslam** [comment]
Вот бы сразу так.
