### ISSUE TITLE
Технические фабрикаторы + ресурсное сило

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#241]
### Проблема

Сейчас очередь в РНД это жёсткая ебля говна в серии "Мне только спросить", в то время как учёным максимально насрать и они занимаются своими делами в других местах. Из-за чего мы получаем, что работа отделов идёт более медленнее:
Медики не могут получить системы контроля надрезов, из-за чего часть персонала меда сидит в очередях.
Шахтёры не могут добывать ресурсы, потому что стоят в очередях.
Инженеры требуют улучшенных инструментов и т.д.

### Решение

Добавить техфабы с ТГ. Их суть проста: По сути это уникальные протолаты каждого из отделов которые в состоянии делать абсолютно всё что может пригодится именно этому отделу. Протолат же может делать всё сразу.
https://pastenow.ru/9e843183a60937a33f1e17b102acb4d7 - пример меню техфаба (медицинский)
https://pastenow.ru/9547bc0bbe491e40274c86ca5e53bbdd - пример комнаты с техфабом (инженерный, консоль для его использования если что не нужна, рядом стоит обычная гражданская)
А чтобы каждый из отделов не ебался с тасканием ресурсов, можно добавить сило.
https://pastenow.ru/7a8827022d47c47b7edbe90cc64af7fb - пример самого сило.
В чём его суть - Сило автоматически перевозит ресурсы по всей технике станции, которая к нему привязана (И к РЦД такую штуку тоже можно сделать). Это же видно и на техфабах, достаточно взглянуть на строку с ресами: "Material Amount: 0 / Unlimited (remote)". 

### Плюсы

Техфабы: Ускоренная работа отделов, меньше матов на учёных, более спокойная жизнь учёных.
Сило: Меньше возни по всей станции со шкафчиками, так же ресурсы можно брать прямо из техфабов, не идя до печи.

### Минусы

Меньше социала (Сказала бы я, если бы не понимала как он устроен в сске).
ТГ под лицензией, так что берём лазейку в лице скайрата, на которых техфабы так же имеются.

**Comment by Longmanrus** [comment]
Всеми руками за предложение! Вообще, много фич с ТГ хочется перетащить на парадайз.

**Comment by Jordanstolethepreciousslam** [comment]
Можно вообще каждому отделу по отдельной станции. Не ну а чо. Мы же здесь чтобы как можно эффективнее дрочить работку а не чтобы взаимодействовать с персоналом других отделов. Можно раундстартом в каждый отдел консоли РнД с протолатом и фулл уровнями поставить, а сверху шаттл и консоль карго. Тогда точно не придется ждать никого и сделать все самому. В самом деле же, голубая вульпа капитан должа выглядеть красиво и махать хвостиком а не следить за работой отделов и вмешиватся в нее. Да лёха? Или это слишком скучно?

**Comment by Danefalt** [comment]
> Можно вообще каждому отделу по отдельной станции. Не ну а чо. Мы же здесь чтобы как можно эффективнее дрочить работку а не чтобы взаимодействовать с персоналом других отделов. Можно раундстартом в каждый отдел консоли РнД с протолатом и фулл уровнями поставить, а сверху шаттл и консоль карго. Тогда точно не придется ждать никого и сделать все самому. В самом деле же, голубая вульпа капитан должа выглядеть красиво и махать хвостиком а не следить за работой отделов и вмешиватся в нее. Да лёха? Или это слишком скучно?

Если ты не умеешь в социал в сске, то это не моя проблема. Посмотри на ТГ сервера. Там техфабы есть, но при этом уровень РП тоже не плох. Взять почти любой нынешний ТГ сервер, он создавался для механодрочеров, но что можно заметить? Ситуации. Даже на ТГ с их упором на механ там есть ситуации.

**Comment by Jordanstolethepreciousslam** [comment]
Ты прежде чем стрелки переводить обьясни почему у тебя _учёным максимально насрать и они занимаются своими делами в других местах_ если ты такой пиздатый фурри кокпитан? Слишком занят обжиманиями с щитом на мостике? Если люди не могут в социал и забивают на свои обязанности то функционал убивающий необходимость в этом социале не нужен в принципе.

**Comment by LoveTrapov** [comment]
1. Против
2. А давайте поставим автоматические хилки вместо меда. Давайте руду вместо шахтёров, которые то и дело умирают, будет добывать какой ни будь бур, и автоматически направлять в печь. Вместо бармена просто автомат со всеми напитками. Вместо кухни раздатчики с едой. Библиотекарей тоже удалим, лучше пускай книги раундстартом на полках будут. Короче, все поняли я думаю.

**Comment by DayBreakerBrony** [comment]
За.
Осуждая комментаторов выше. А давайте станцию каждый раз заново отстраивать? Это же ПА ЭРПЕ. Перестаньте бросаться в крайности. Сейчас РНД и правда является тем, что описала Даня. Ёблей мозгов, и учёных, у которых робоебы пиздят все ресурсы, и людей на стойке, которым попались учёные в первый день, не знающие половину названий. Я за, но с одним условием:
если у каждого отдела будет свой протолат, то стоит сделать так, чтобы и доступ к прототипам у него был соответственный. а то мед протолат крафтит дрейки и ЕКА со всеми модулями, это как то уже не по арпи. Только нужные меду вещи. И так же с каждым другим отделом. У нас 26-ой век сука, а нормально обеспечить станцию ресурсами не выходит.

**Comment by DayBreakerBrony** [comment]
И чтобы доступ к этому протолату был ограничен по СРП, и доступ к нему был только у главы и подглавы (варден, км)

**Comment by Danefalt** [comment]
> И чтобы доступ к этому протолату был ограничен по СРП, и доступ к нему был только у главы и подглавы (варден, км)

Такое будет только у СБ, потому что техфаб СБ в состоянии печатать оружие, боевые импланты, летальное оружие и прочие. У остальных же будет доступ у всего отдела.

**Comment by Danefalt** [comment]
> За.
> Осуждая комментаторов выше. А давайте станцию каждый раз заново отстраивать? Это же ПА ЭРПЕ. Перестаньте бросаться в крайности. Сейчас РНД и правда является тем, что описала Даня. Ёблей мозгов, и учёных, у которых робоебы пиздят все ресурсы, и людей на стойке, которым попались учёные в первый день, не знающие половину названий. Я за, но с одним условием:
> если у каждого отдела будет свой протолат, то стоит сделать так, чтобы и доступ к прототипам у него был соответственный. а то мед протолат крафтит дрейки и ЕКА со всеми модулями, это как то уже не по арпи. Только нужные меду вещи. И так же с каждым другим отделом. У нас 26-ой век сука, а нормально обеспечить станцию ресурсами не выходит.

Если что, сейчас имеется только такая система. Техфабы могут печатать только оборудование именно того отдела, к которому он принадлежит, и такая система была всегда. Иначе было бы легче сразу поставить протолаты.

**Comment by AttHawk** [comment]
Против
Это не будет сподвигать челов на ученых учиться и узнавать, а что собственно они могут у себя в протолате сделать. И так супер смешно когда к ним заваливается работяга с ~~завода~~ шахты и начинает учить их как делать прототипы и работать с ними. Видел на ВЛ как РД взял за яйца СЕ и они расширили приемку РнД добавив лишнее окно выдачи и второй комплект автолат-протолат-циркуит, вот это по РП, а не ученый который полгода выясняет у уборщика "А как швабра называется? 🐵 ", тем самым и создавая очередь.

**Comment by Danefalt** [comment]
> Против
> Это не будет сподвигать челов на ученых учиться и узнавать, а что собственно они могут у себя в протолате сделать. И так супер смешно когда к ним заваливается работяга с ~завода~ шахты и начинает учить их как делать прототипы и работать с ними. Видел на ВЛ как РД взял за яйца СЕ и они расширили приемку РнД добавив лишнее окно выдачи и второй комплект автолат-протолат-циркуит, вот это по РП, а не ученый который полгода выясняет у уборщика "А как швабра называется? 🐵 ", тем самым и создавая очередь.

Ты уже определись. Ты хочешь сказать что это нужно или что это не нужно? Учёные так и так успеют научится, тем более при нормальном РД, так зачем минут на 20 задерживать других игроков в очередях? Или же ты ИРЛ работаешь в регистратуре в больнице или ещё где?

**Comment by terribaum** [comment]
1.За
2.Комментаторы выше не понимают одной простой сути-карта геймплейно не вывозит.Наш сервер уже почти постоянно держит топ 1 по онлайну в сске.Очередь в рнд превращается в абсурд.Помимо войны за ресурсы с роботехами,ученые должны обслуживать персонал постоянно.И все это при нарастающем коде с которым запросы возрастают.Так что я двумя руками за.

**Comment by VictorSocks** [comment]
1. Против
2. То что учёные не успевают, проблема самих учёных. Пусть люди учатся все успевать. Я сам стоял на раздаче и понимаю что куда-либо отойти от стойки нереально. Да, мне нравится такое, а всякая псевдоавтономность сломает социалочку, так как у нас люди дрочат работку и будут дрочить работку с этими "техфабами" и "сило" ещё больше никак не взаимодействуя с другими отделами. Пусть всё остаётся как есть.

**Comment by botka4aet** [comment]
1. Против.
2. Ученые могут сделать протолаты, а так же настроить то, что там можно печатать.
Те все это реализуемо уже сейчас.

**Comment by Danefalt** [comment]
> 1. Против.
> 2. Ученые могут сделать протолаты, а так же настроить то, что там можно печатать.
>    Те все это реализуемо уже сейчас.

А эти протолаты  будут раундстартом у каждого отдела, включая карго и сервис?

**Comment by DayBreakerBrony** [comment]
> 1. Против.
> 2. Ученые могут сделать протолаты, а так же настроить то, что там можно печатать.
>    Те все это реализуемо уже сейчас.
ну давай, спавнись за инжа, строй каждому отделу протолат, зови учёных и проси ограничить печатаемые вещи. а потом каргония будет снабжать их типа? да хуй там. намного проще реально сделать техфабы, а снабжать их будет каргония с помощью сило.

**Comment by Honker9999999** [comment]
> >    ну давай, спавнись за инжа, строй каждому отделу протолат, зови учёных и проси ограничить печатаемые вещи. а потом каргония будет снабжать их типа? да хуй там. намного проще реально сделать техфабы, а снабжать их будет каргония с помощью сило.
Зато взаимодействие, РП там. Можно каждому отделу по отдельной станции с блекджеком и шлюхами, но нахуя?

**Comment by Danefalt** [comment]
> > > ну давай, спавнись за инжа, строй каждому отделу протолат, зови учёных и проси ограничить печатаемые вещи. а потом каргония будет снабжать их типа? да хуй там. намного проще реально сделать техфабы, а снабжать их будет каргония с помощью сило.
> > > Зато взаимодействие, РП там. Можно каждому отделу по отдельной станции с блекджеком и шлюхами, но нахуя?

С сило ещё весело: Автоматически идёт от печи, до всей техники которая привязана к нему. Это так же позволит брать ресурсы из печи, не идя до самой печи, но доступ там можно всё-таки порезать, чтобы не было абуза со стороны обычных смертных, без доступа к печке.
А ведь ещё подключение к сило можно устроить и для РЦД, при помощи специальной модификации в протолате или в инженером техфабе, с помощью которой можно будет привязать РЦД к сило, позволяя брать ресурсы прямо из печи, для строительства, находясь в любой точке станции. В итоге пока в печи есть ресурсы, они есть и в РЦД.

**Comment by Danefalt** [comment]
> > > ну давай, спавнись за инжа, строй каждому отделу протолат, зови учёных и проси ограничить печатаемые вещи. а потом каргония будет снабжать их типа? да хуй там. намного проще реально сделать техфабы, а снабжать их будет каргония с помощью сило.
> > > Зато взаимодействие, РП там. Можно каждому отделу по отдельной станции с блекджеком и шлюхами, но нахуя?

И советую научится играть в социал в сске. Такая ебля мозгов это не социал, это как не странно ебля мозгов. А вот РП и взаимодействие, это когда ты к примеру за медсестру попросил какого-то ассистуху сматерить тебе стол (с учётом того что ресурсы у тебя есть), потому что ты не умеешь в это, или когда ты просто встречаешь своего ИЦ знакомого, и приглашаешь его просто выпить в баре. А ИЦ знакомые это ещё лучше, поэтому что это по сути личная жизнь твоего персонажа, это и есть другие участники РП. А не очереди из серии:
>Драсте
Че надо
БоХ дайте
Нахуя
Ну надо
Бля ресов нет
А меня это ебёт? БоХ мне запилил быстро блять

И в итоге, такие посиделки в РНД затягиваются минут на 20 ничего не деланья.
И раз уж про тех же инжов, а кто тебе сказал что учёные впринципе-то согласятся на это? А инженеры будут это делать? А карго собирается по всей станции разносить все виды ресурсов каждому лично? Это не РП, это мозгоёбство.

**Comment by AttHawk** [comment]
> > > > ну давай, спавнись за инжа, строй каждому отделу протолат, зови учёных и проси ограничить печатаемые вещи. а потом каргония будет снабжать их типа? да хуй там. намного проще реально сделать техфабы, а снабжать их будет каргония с помощью сило.
> > > > Зато взаимодействие, РП там. Можно каждому отделу по отдельной станции с блекджеком и шлюхами, но нахуя?
> 
> И советую научится играть в социал в сске. Такая ебля мозгов это не социал, это как не странно ебля мозгов. А вот РП и взаимодействие, это когда ты к примеру за медсестру попросил какого-то ассистуху сматерить тебе стол (с учётом того что ресурсы у тебя есть), потому что ты не умеешь в это, или когда ты просто встречаешь своего ИЦ знакомого, и приглашаешь его просто выпить в баре. А ИЦ знакомые это ещё лучше, поэтому что это по сути личная жизнь твоего персонажа, это и есть другие участники РП. А не очереди из серии:
> 
> > Драсте
> > Че надо
> > БоХ дайте
> > Нахуя
> > Ну надо
> > Бля ресов нет
> > А меня это ебёт? БоХ мне запилил быстро блять
> 
> И в итоге, такие посиделки в РНД затягиваются минут на 20 ничего не деланья.
> И раз уж про тех же инжов, а кто тебе сказал что учёные впринципе-то согласятся на это? А инженеры будут это делать? А карго собирается по всей станции разносить все виды ресурсов каждому лично? Это не РП, это мозгоёбство.

А тут проблема не в том что не хватает протолатов каждому отделу, а в том что челы приоритезируют собственный манч, а не РП с учеными. Если это исправить большая часть проблем сама уйдет, не будет челов которые приходят в РнД просто потому что они манчи и им надо БоХ/импланты/пушки/еще что-то. При этом работает это в обе стороны, потому что ученые в случае если им не ебать мозг у стойки/в рацию, никогда в жизни не выйдут из отдела сами что-то сделать для других. 

>А карго собирается по всей станции разносить все виды ресурсов каждому лично?

Конкретно про карго, а оно и должно этим заниматься, а не сидеть у себя, заказывать дробовики и натирать в шкафу плакат VIVA LA CARGONIA

**Comment by Jordanstolethepreciousslam** [comment]
> встречаешь своего ИЦ знакомого, и приглашаешь его просто выпить в баре.

Ну вот с такого и начинается деградация билда. Когда никаких предпосылок и никакой необходимости в других отделах нет, и пиком социала является бессмысленный и беспощадный чай в дормах на протяжении часов или лежание друг на друге и хаги. А потом "Кроме бухания и болтовни нечем занятся, давайте ЕРП разрешим".

> И советую научится играть в социал в сске. Такая ебля мозгов это не социал, это как не странно ебля мозгов.
Советую научится справлятся с трудностями и общатся с людьми, а не аутировать в соло и ныть что нада техфабы потому что Лёша слишком интроверт и написать на пда АВД или Главе Отдела для него непреодолимая задача и ему нужно всё на блюдечке. Эта мозгоебля - то что что составляет осмысленный отыгрыш. Если человек слишком эгоистичен и не исполняет свои обязанности то ты используешь рычаги влияния. Будь то авторитет или сколачивание банды для выбивания нужных ресурсов. Если тебе слишком трудно дрочить работку потому что другие люди несговорчивы, то просто уйди на локалку. Там тебе никто не помешает. А гонять чай в баре можно через дискорд.

**Comment by Jordanstolethepreciousslam** [comment]
Я всё еще не вижу зачем вообще нужно облегчать РАБОТКУ. Просто нахуя. Тебе так всрались циферки в игре про 2Д космонавтиков? Абсолютно все отделы на станции и так слишком автономны. Мед может работать с раундстартовым инструментарием и готовить себе химикаты. Шахтеры могут ломать ебла мегафауне без помощи кого либо вообще. Карго вообще отдельная республика. Единственный зависимый отдел это РнД которому нужны ресурсы шахтеров. Всё. Больше ничего никому не нужно. Разве что цель станции. Которая напомню цель СТАНЦИИ а не отдела. Наоборот, Отделы нужно делать более зависимыми друг от друга. Потому что сейчас отделы друг другу нахуй не нужны.  Только РнД без ресов сасает писюн да без меда воскрешать некому.

**Comment by Jordanstolethepreciousslam** [comment]
Я просто напомню что цель раунда во взаимодействии людей. НЕ работа. НЕ четвертый энергоблок. НЕ тесла в клоунской. НЕ макс уровни. НЕ фулл апгрейды оборудования. НЕ фулл стак трофеев с мегафауны. Всё это можно сделать на локалке. Выебнутся этим ни перед кем не получится потому что всем похуй. Это лишь временное развлечение пока антагонисты подготавливаются к действию и повод ВЗАИМОДЕЙСТВОВАТЬ с игроками.

**Comment by Jordanstolethepreciousslam** [comment]
>  Ускоренная работа отделов

В каком месте это вообще плюс? Чтобы откровенно нехуй было делать уже на 30-ой минуте раунда вместо 80-ой?
Или тебя незадроченная работка останавливает от социала? Каким нахуй образом? В игре и так никто не обязан работать кроме меда и инжей.

**Comment by hnappinn** [comment]
1. За
2. Наконец медики могут делать хирургические приборы, а не пытаться просить сделать их в других отделах когда на станции пиздец и нету времени ходить туда сюда, но нужно срочно делать операции и лечить людей. Сб смогут печатать себе ПуШОчКИ, а не утруждать постоянно учёных которые и так заняты, или самим вломиться в рнд и печатать так как уже залутали доступ в рнд. Инженеры смогут сделать сразу после выпуска теслы заземлитель и поля с эмитерами, а не пол часа ебаться с бюрократией в рнд когда всю станцию ломает тесла. 

По поводу того что писали про взаимодействия. Даже с этими добавлениями социалочка от части будет работать (именно социалочка, а не ебля мозгов). Хочешь детали? Иди в рнд или инженерку. Хочешь пушочки? Иди в сб. Хочешь дифиб и другие мед приколы? Иди в мед. Может я чего-то не понимаю, но в чем интерес слишком сильно тянуть, когда оно не всегда есть?

Насчёт того что учёным делать нехуй. Кроме изучения есть ещё интересные вещи, можно делать гранаты, реагенты, свои механоебский приколы, слаймы, своя идея для раунда и тд. Учёный это профа не только для спидрана изучений и раздачи вещей.

Плохо ли что раунды будут быстрее? Не думаю, мне кажется будет на оборот интереснее, и без лишней мозгоебли

**Comment by hnappinn** [comment]
Судя по большинству комментариев разных людей. Они даже не понимают как эти техфабы и сило работают. Если бы были такими имбалансными или не нужными, то их бы небыло на ТГ и на гунах

**Comment by OpsCoretango** [comment]
Гайс, мб сделать и посмотреть что будет вместо тысячи слов?

**Comment by Honker9999999** [comment]
> Судя по большинству комментариев разных людей. Они даже не понимают как эти техфабы и сило работают. Если бы были такими имбалансными или не нужными, то их бы небыло на ТГ и на гунах. А на бее рнд вообще почти не нужно, все и так со старта есть. Там учёные в основном делают работку для учёных

Знаешь почему они есть на ТГ? Потому что ТГ это буквально билд ради пострелушек, прикольчиков и иного. Там - это оправданно, ибо как-бы да.
А вот про бей полный пиздеж. Что и у кого есть "Изначально"? Может улучшения изначально? Сразу ИКС у медиков? Или хоть лазерный скальпель максимального тира? А, нет, нихуя из этого нет. Но тогда что "И так со старта есть"? Пыль? Воздух? Стандартное оборудование что и у нас есть? Загадка. Может это все хорошо спрятано под полом, и его просто каждый раунд достают? Ну а вдруг?

**Comment by Zigamus** [comment]
Голосование окончено по времени.

**Comment by hnappinn** [comment]
> > Судя по большинству комментариев разных людей. Они даже не понимают как эти техфабы и сило работают. Если бы были такими имбалансными или не нужными, то их бы небыло на ТГ и на гунах. А на бее рнд вообще почти не нужно, все и так со старта есть. Там учёные в основном делают работку для учёных
> 
> Знаешь почему они есть на ТГ? Потому что ТГ это буквально билд ради пострелушек, прикольчиков и иного. Там - это оправданно, ибо как-бы да.
> А вот про бей полный пиздеж. Что и у кого есть "Изначально"? Может улучшения изначально? Сразу ИКС у медиков? Или хоть лазерный скальпель максимального тира? А, нет, нихуя из этого нет. Но тогда что "И так со старта есть"? Пыль? Воздух? Стандартное оборудование что и у нас есть? Загадка. Может это все хорошо спрятано под полом, и его просто каждый раунд достают? Ну а вдруг?

Насчёт пострелушек, пушки ты в одном сб техфабе там не сделаешь, придется брать детали у инженеров или учёных чтобы собрать пушку. И так много с чем забалансено. Не понял аргумент "билд про пострелушки", а парадайс тогда не билд про пострелушки? В чем разница? 

На бее улучшенные хирургические инструменты не дают очень сильных бонусов к скорости по сравнению с простыми операциями, они больше полезны для тех у кого низкие навыки или операции где нужен высокий шанс (к примеру на каталке). Стазис мешки есть, оборудование есть, лекарства сам сделаешь, запасное оборудование и запасной хирургический набор есть на складе. Чего тебе ещё для лечения не хватает? И эти прототипы из рнд считаются прототипами, так что если так сильно хочется их получить, то надо пройти круги ада бюрократии. Сначала поиграй на других билдах, а потом пиши
