### ISSUE TITLE
Дройды и Люди.

### ISSUE THREAD

**Issue by Zombara** [ss220-space/Paradise#242]
### Проблема

Всем вам не нравиться, что у вас нету защитников которых вам нужно прямо сейчас?

### Решение

Решение: Компание КНС предлагает вам приобрести Механизм который моментально выведет к вам отключенных Дройдов (B1 скоро будут тоже и модельку механизма можно на какую нибудь. И к тому же как вы вызывайте такого дройда из механизма, У госта будет оповещение о том что его можно взять). У дройдов B2 и B1 будут различные разновидности: Красный это охранный. Он служит верой и правдой любому кто его приобрел но с ИИ они не соединяются как и остальные. Но в отличий от остальных у него встроен режим и оглушение и бластера, B2 обычный это начальная стадия B2 в нем нету ничего интересного и B2 Коммандир. Он похож на Инженера но в отличий от инженеров он довольно Умный и у него встроен более продвинутый ИИ и после чего тот может спокойно командывать остальными B2 и не иметь эмоций и тупизмы. У него вооружение будут обычные бластерная рука, оглушалка и связь с всеми дройдами. (Данные дройды будут находится в неком Механизме у Робототехников и между прочем они способны проявлять эмоций и им возможно свойственно тупить) Так же у этих дройдов изначательно вставлен бластерные руки и это означает что никакой человек не украдет оружие и не применит против же своего носителя.

![](https://cdn.discordapp.com/attachments/866800055457284136/871064486193279006/unknown.png)

### Плюсы

Новое воруженная сила что возможно поможет с халками, блобами или синдикатами, фанатам звездных войн сразу же приглянется данным дройдам. Очень легки к создание.

### Минусы

Придется кодить, чем-то похожие на КРБ но в отличий от КРБ и B2 лишь в том что они уже встроены с оружием. Хейтеры к ЗВ?

**Comment by assaultmachine** [comment]
чё

**Comment by Zombara** [comment]
Чел. Ты не понял предложение или что?

**Comment by OpsCoretango** [comment]
#длинно-обзорево

Проблемой по мнению автора считается что каждому индивиду на станции не хватает защитника.

Рекоммендация: уточнить проблему в соотвествии административного строгого шаблона и избежания публ. стиля.

Компания КНС вымышлена и за историю Onyx Station, вообще в целом лора Станции 13 о ней я ничего не слышал. Но допустим, как вас еще не поглотил Hephaestus или НТ Космическому карпу Космо-фед. магов только известно.
Окей.. допускаем и это. 

"Любому кто его приобрел" допустим из отдела карго без возможности сборки роботехниками потому что этого нет в чертежах для Инженерного отдела или СБ. (Потому что в здравом уме гражданского с таким "другом" не пустят)

Откуда у КНС продвинутый ИИ?
Объясните как вы представите что у компании КНС имеется такая технология которая имеется "ИМХО"  на опер базах с офицерами Синди, и НТ?
(Не стоит оставлять без внимания что НТ это акула и Волк с Уолл Стрит в космического масштаба с жадным и хитрым нравом)

Закончили.
Я ждал этих дроидов как и другие но поработай еще лучше над их лором и откуда они, также КНС возможно разрабатывала военную и полево-санитарную версию если у них рынок в сторону ЧВК и Армии, ну возможно..
У них не должно быть ионных движков но обычные магбуты есть, у всех броня значит и резист.. какой? Охранный явно больше от рукопашки с комбой от лазера и огнестрела но страдает от взрывов и электричества.
У военного наверное есть энерго щит и броня сосредоточенная под кине-энерго снаряды.

Для читателей тут отличие что они дроиды и Б2 версия уже похоже на борга но какая у них будет функциональность уже пусть решает он с рекомендацией от меня "глянь че у боргов с модулями которые можно засунуть в сумме".

А идея о продуктах от других компаний которые уступают или равны без возможности опережения(исключение Вей мед который уделывает НТ в мед. науке)  считаю жизнеспособной.
Всем доброй ночи или дня, господа.

**Comment by Zombara** [comment]
> #длинно-обзорево
> 
> Проблемой по мнению автора считается что каждому индивиду на станции не хватает защитника.
> 
> Рекоммендация: уточнить проблему в соотвествии административного строгого шаблона и избежания публ. стиля.
> 
> Компания КНС вымышлена и за историю Onyx Station, вообще в целом лора Станции 13 о ней я ничего не слышал. Но допустим, как вас еще не поглотил Hephaestus или НТ Космическому карпу Космо-фед. магов только известно.
> Окей.. допускаем и это.
> 
> "Любому кто его приобрел" допустим из отдела карго без возможности сборки роботехниками потому что этого нет в чертежах для Инженерного отдела или СБ. (Потому что в здравом уме гражданского с таким "другом" не пустят)
> 
> Откуда у КНС продвинутый ИИ?
> Объясните как вы представите что у компании КНС имеется такая технология которая имеется "ИМХО" на опер базах с офицерами Синди, и НТ?
> (Не стоит оставлять без внимания что НТ это акула и Волк с Уолл Стрит в космического масштаба с жадным и хитрым нравом)
> 
> Закончили.
> Я ждал этих дроидов как и другие но поработай еще лучше над их лором и откуда они, также КНС возможно разрабатывала военную и полево-санитарную версию если у них рынок в сторону ЧВК и Армии, ну возможно..
> У них не должно быть ионных движков но обычные магбуты есть, у всех броня значит и резист.. какой? Охранный явно больше от рукопашки с комбой от лазера и огнестрела но страдает от взрывов и электричества.
> У военного наверное есть энерго щит и броня сосредоточенная под кине-энерго снаряды.
> 
> Для читателей тут отличие что они дроиды и Б2 версия уже похоже на борга но какая у них будет функциональность уже пусть решает он с рекомендацией от меня "глянь че у боргов с модулями которые можно засунуть в сумме".
> 
> А идея о продуктах от других компаний которые уступают или равны без возможности опережения(исключение Вей мед который уделывает НТ в мед. науке) считаю жизнеспособной.
> Всем доброй ночи или дня, господа.

Я не думаю что кто-то для них будут делать Резисторы.  А так ИИ у них немного улучшен чем наши любимые B1 и особенно это наблюдается у Командных составов.

**Comment by OpsCoretango** [comment]
> 
> https://user-images.githubusercontent.com/87912834/128068502-c69ed5d8-7e82-4d29-8620-fb60f26eda48.mp4
> 
> 

Не хороший вы млять человек
Тарков©
2ч ночи в наушниках на фулл(Сам ты идиот :( )

**Comment by OpsCoretango** [comment]
> > 
> > https://user-images.githubusercontent.com/87912834/128068502-c69ed5d8-7e82-4d29-8620-fb60f26eda48.mp4
> > 
> > 
> 
> Не хороший вы млять человек
> Тарков©
> 2ч ночи в наушниках на фулл(Сам ты идиот :( ) 

ауч

**Comment by Hemfast** [comment]
это очень хорошая идея, но есть одно но. он будет нафиг никому не нужен. почему? да всё просто, постоянно играя за робототехников, я за всё время помню только 4 раза когда кто-то из гостов решил вселиться в дроида после смерти.
более того, людей умеющих именно отыгрывать на дроидах процентов 30, остальные будут вызывать только раздражение своим "человеческим" языком.

**Comment by Zombara** [comment]
Предложение еще в силе.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184355917-7466c6eb-a4d6-4da0-8905-b9febefab9d5.png)
