### ISSUE TITLE
Feat: изменение выбора человека в пинпоинторе 

### ISSUE THREAD

**Issue by Slisenz** [ss220-space/Paradise#245]
### Проблема

При использовании пин поинтера крайне неудобно искать нужного тебе человека среди других, имена никак не упорядочены и человечек может быть рандомно находится в этом списке. Когда же онлайн составляет 150 человек, то найти кого то в этом списке крайне тяжело. Для парамеда это настоящий ад, у тебя помер человек на мониторе, а вместо того чтобы идти и спасать его ты сидишь и скролишь список туда сюда в надежде найти человечка

### Решение

Отсортировать список по первой буквы фамилии/имени или же сделать поиск по имени/фамилии(ввод вручную)

### Плюсы

Парамед (или другой член экипажа) сможет за секунды настроить пинпоинтер на поиск нужного человека , путём копипасты из крюмонитора в пинпоинтер. 

### Минусы

Придётся лопатить код(наверное)

**Comment by Danefalt** [comment]
За
Удобство и не более. Как по мне это вообще не должно проходить голосование, по скольку это по большей части удобство UI, а не серьёзное предложение которое прям сильно повлияет на игру.
Вообщем, как у меня будет свободная минутка, то думаю займусь, если конечно, другой разраб это не подхватит быстрее.

**Comment by zombie288** [comment]
За
Поддерживаю комментаторов выше, пинпоинтер сейчас крайне неудобная штука и добавить поиск по имени было бы очень здорово.

**Comment by Danefalt** [comment]
Самая сложная проблема сейчас - найти код его UI. 
Кстати, скорее всего прийдётся работать с TGUI, а я этого не хочу.
Вообщем, как найду то что нужно, начнётся и работа, сам код не будет прям настолько сложным. Ждём.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184355983-9626dd7a-b892-41c5-9c23-8d63c3f8b9f7.png)
