### ISSUE TITLE
Feat: Костюмы плазмаменов и их цвет. 

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#246]
### Проблема

Сейчас работники плазмамены какого-то чёрта не могут менять цвет своего костюма, когда другие чады с отделов спокойно меняют себе одежду. Это очень мешает за тритора, когда ты буквально светишься своим изначальным отделом, например РНДшник на СБ, да ещё и с монитором, ибо нанят. Да и некрасиво к тому же. 

### Решение

Добавить возможность перекрасить костюм плазмамена в зависимости от доступа надетой в слот карты. Пример: Бригмед:
1.Мед. костюм плазмаменов
2.Бриг костюм плазмаменов
Варден:
1.Стандартный бриг костюм плазмаменов
2.Варденовский костюм плазмаменов. 
ГСБ:
1.Стандартный бриг костюм плазмаменов
2.Варденовский костюм плазмаменов. 
3.Костюм плазмамена-ГСБ
и так далее, по желанию самого носителя костюма. 

### Плюсы

Наконец-то МОЖНО БУДЕТ ЗА БРИГМЕДА КРАСНУЮ ФОРМУ НОСИТЬ!

Красивые цвета под цвет отдела

Не душим плазма-антагов

### Минусы

Кодить функцию для костюма, прописывая доступные цвета в зависимости от доступа.

**Comment by AttHawk** [comment]
За
на плазме играет полтора землекопа, но фича полезная, было бы здорово

**Comment by Gnatr** [comment]
За
Конечно антажить на плазме это садомазо, хотя если цвет можно сменить по доступу то ID агента заменит хамелеон
Кстати про шлем не забудьте, я застрелюсь если сменить можно будет только одежду

**Comment by Dreemer556** [comment]
За
И если не просто хамелеон отделов, а прям разные раскраски и капсула для переодевашек, то это прям оргазм. За него хоть можно антажить. А то мне хватило когда спалился, нас на станции было два и жёлтый только я. Как скрыться? А вот хер знает

**Comment by Jehvehard** [comment]
За
Эту проблему нужно было решить давно.

**Comment by Zigamus** [comment]
@DayBreakerBrony предложка прошла голосовалочку, можно делать коммит.

**Comment by VasilevAY** [comment]
Человек не сделал ПР по предложке
![image](https://user-images.githubusercontent.com/98010665/184356226-5565b57a-112a-4e8c-ba0e-13caae84ddec.png)
