### ISSUE TITLE
Обновлённый КЗ

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#248]
### Проблема

Что мы имеем сейчас: Наш КЗ не предусматривает многих ситуаций, и имеет в себе множество дыр. С точки зрения юрисдикции он не в состоянии сущестовать впринципе. 

### Решение

Так что я с Глинстом представляем вам новую версию КЗ - https://docs.google.com/document/d/12cDkVtp9SXaLXTfAsJRCST2UQxgZnUMJrcsQAm7oTwM/edit?usp=drivesdk 
Новый космический закон позволит игрокам получить законы, формулировка которых схожа с реальными, что несомненно положительно скажется на уровне РП игроков. Законы написаны с низкой казуистичностью, что позволяет избежать проблем с формулировками, что присутствуют в действующем КЗ. Кроме того, законодательная база расширена и дополнена, что позволит расширить объем отыгрываемых преступлений и самих ситуаций связаных с ними. Что в свою очередь улучшит качество РП среди игроков, как тех, что нарушают закон, так и со стороны СБ. Так же, были добавлены штрафы, в качестве альтернативы аресту. 
В дополнении, можно с ТГ добавить консоль ордеров, в которой можно будет оплатить штраф. При установлении статуса на арест, будет так же всплывать окошко с выбором размера штрафа (0 - если штраф не требуется). Тем самым, после оплаты штрафа в консоли, статус будет автоматически сниматься. 

### Плюсы

*  Новый, свежий КЗ только из-под клавиатуры и "бешенного принтера" лучших законотворцев НТ, которым надоело, что вместо законов вторая версия правил сервера!
* Введены штрафы как альтернативная мера наказаний паралельно предупреждениям, которые всё равно никто не выдаёт. 

### Минусы

- Нужно учить новый КЗ. 
- Принцип нумерации статей может показаться на первый взгляд неудобным.

**Comment by AttHawk** [comment]
За
НО!
Во-первых, надо напустить граммарнаци в файл и пересмотреть некоторые формулировки (например аннигиляция крайне всрато звучит)
Во-вторых, все статьи, наказания за которые связаны с порицанием или штрафом работать не будут, по причинам смерти экономики и похуизма. 
И в целом я пока очень бегло пробежал глазами, вполне возможно еще что-то есть заслуживающее правок, но идея здравая

>Новый, свежий КЗ только из-под клавиатуры и "бешенного принтера" лучших законотворцев НТ, которым надоело, что вместо законов вторая версия правил сервера!
Это я бы в минус записал 🤡

**Comment by ImJustKisik** [comment]
> За
> НО!
> Во-первых, надо напустить граммарнаци в файл и пересмотреть некоторые формулировки (например аннигиляция крайне всрато звучит)
> Во-вторых, все статьи, наказания за которые связаны с порицанием или штрафом работать не будут, по причинам смерти экономики и похуизма.
> И в целом я пока очень бегло пробежал глазами, вполне возможно еще что-то есть заслуживающее правок, но идея здравая
> 
> > Новый, свежий КЗ только из-под клавиатуры и "бешенного принтера" лучших законотворцев НТ, которым надоело, что вместо законов вторая версия правил сервера!
> 
> Это я бы в минус записал 🤡

Просто вычиткой заняться некому, я безграмотный, а данефалт такие пёрлы в формулировках выдавал, что вас бы "поимело дисциплинарное взыскание"

**Comment by Danefalt** [comment]
> Просто вычиткой заняться некому, я безграмотный, а данефалт такие пёрлы в формулировках выдавал, что вас бы "поимело дисциплинарное взыскание"
> 
> **В гугл доках есть функция, чтобы предложения для исправлений делать, если кто-то желает - милости прошу**

Да-да я, нужно же чтобы вас что-то имело)

**Comment by AttHawk** [comment]
в общем, я чуть более внимательно поглядел сами формулировки, там кучу всего переделывать и дорабатывать, вам надо за пример общей стилистики брать ИРЛные своды законов, если уж целью стоит исправить:
>Наш КЗ не предусматривает многих ситуаций, и имеет в себе множество дыр. С точки зрения юрисдикции он не в состоянии сущестовать впринципе.

**Comment by Dreemer556** [comment]
За
Тут прекрасно всё. Про штрафы, AttHawk сказал, что они не будут работать, но тут есть проблема. Во то время когда на СБ хорошая нагрузка у нас может не хватить камер на каждого сосистоса, который не знает закон, но это херня, в статусе ты на месте ставишь человеку штраф и идёшь дальше, а не ведёшь его в бриг и садишь в камеру, что минута-две лишнего времени за какую=то хрень. Назал, наказал быстро, КЗ соблюдён. 

И я бы заменил все где есть слово "люди" на гуманоидов или вовсе разумных существ. Потому что согласно подобным формулировкам человека избивать нельзя, а любого ксеноса можно (просто пример). Или ксеноморфа Анатолия, который мирно лечит людей

**Comment by IDINAHUIPIDORAZ** [comment]
ВЫ ЗАЕБАЛИ СО СВОИМИ СРП УЕБАНЫ ПИЗДОГЛАЗЫЕ РАХИТЫ ТУПОРЫЛЫЕ!
ПАРАШИЗА ХУЙНЯ ПОЛНААЯЯЯЯ ДЛЯ ОТБИТЫХ СУК У КОТОРЫХ НЕТ ЛИЧНОЙ ЖИЗНИ! 

ИНВАЛИДЫ ЛЕНИВЫЕ ЛЕСНЫЕ УЕБИЩА ПЕДАЛИ! ОСКОТИНЕВШАЯ ТУПАЯ ФЛАФСКАЯ 
! НЕ ТРОГАЙТЕ НИЧЕГО И НЕ МНГНЯЦТЕ! СКОТИНЫ ДЕРЬМОДЕМОНЫ СДОХНИТЕ НАХУЙ ВСЕЕЕ! ЕБУВЕЕЕ ГАВНОДЕЛЬНАЯ ХУЕТА ДЛЯ ДЕБИЛОВ ПОШЛИ НАХУЙ ВСЁ! СОСИТЕ ХУЙ И СГОРИТЕ В АДУ!

Я БЫЛА НОРМАЛЬНАЯ НО ВЫ СУКА ВСЕ ИСПОРТИЛИ! 

ВЫ БЛЯДИНЫ ЕБАНАШКИ ТУПОРОЛЫЕ НА ПЕДАЛЯХ И ФУРРИЕБСКИХ ПИДОРАСОВ! ЕБАНУТЫЕ СУКИ

**Comment by IDINAHUIPIDORAZ** [comment]
ЕБАННАЯ ХУЙНЯ ТЫ УЕБАНСКАЯ МАНДА БЕЗМОЗГЛАЯ, НЕ ИГРАЙ В ЕБАННОЕ ДЕРЬМО ДЛЯ ПАРАШИЗОВ! ССЫ В ЕБАЛО АДМИНАМ И ФУРРЕЙ! ВЗРЫВАЙТЕ НАХУЙ ВСЁ! УЕБИЩЕ ГОВНОЗАЛУПСКОЕ НАХУЙ ЧИТАЮЩЕЕ ПОШЛО НАХУЙ И СДОХНИ

**Comment by IDINAHUIPIDORAZ** [comment]
ЗАКРОЙТЕ НАХУЙ СЕРВЕР ПИДОРОУЕБСКИЕОСКОТИНЕВШИЕКАКЛОШВАЙНЫ! ЗАКРОЙТЕ ВАШ ГОВНЯЦКИЙ СЕРВЕР! ВЫРЕЖЬТЕ ВСЕХ! ЗАКРОЙ ГОВНЯЦКИЙ СЕРВЕР! ПОШЛИ НАХУЙ ЧИТАЮЩИЕ, ИГРАЮЩИЕ И НЕ ЖИВУЩИЕ! ВЫ ПРОКЛЯТЫ НАХУЙ ВСЕ! ВСЕ БЛЯТЬ ПРОКЛЯТЫ БЛЯТЬ НАХУЙ БЛЯТЬ ДО 7 КОЛЕНА ПРОКЛИНАЮ ВАС! СДОХНИТЕ

**Comment by IDINAHUIPIDORAZ** [comment]
РУБИ НАХУЙ ТОПОРАМИ СРАННЫХ МУДОЗВОНЯЩИХ ССЫКУЩИХ В ЖОПУ ЕБУЩИХ ПАРАШИЗОВ НЕДОДЕЛАННЫХ! НИНАФИСА БЛЯТЬ СУКА БЛЯТЬ ГАНДОНЫ ЛЕСНЫЕ ХУЙНИ ИЗ  ДЕРЬМА СОБАК И СПЕРМЫ ИГРОКОЕБУЧЕГОПЕДАЛЬЕБСКОГОКАКЛОШВАЙНА

**Comment by IDINAHUIPIDORAZ** [comment]
ПРОКЛИНАЮ НАХУЙ ТЕБЯ БЛЯТЬ ЧИТАЮЩИЙ В ЖОПУ ЕБУЩИЙ ПАРАШИЗСКИЙ КУСОК ФУРРИЙСКОГО ДЕРЬМА!!! 1111!!

**Comment by IDINAHUIPIDORAZ** [comment]
ПАРАШИЗА ПРОГНИЛА ВСЯ НАХУЙ В ПИЗДЕЖЕ, ОБМАНЕ, ХАМСТВЕ И В ТОКСИЧНОСТИ! БЕГИТЕ ВСЕ НАХУЙ С ЭТОЙ ХУЙНИ! ТАМ ЕБУТ В ЖОПУ ФУРРИ ДРУГ ДРУГА И ПИЗДЯТ ДРУГИХ ! СТАНЦИЯ - ЭТО БЕЗДНА, ГДЕ СОКРЫТЫ ХУЕВИЙШЕЕ СТОРОНЫ ЧМОШНЫХ 2D И 3D ОРГАНИКОВ! ТАМ НЕТ ЖИЗНИ - ТАМ СМЕРТЬ И БОЛЬ! ГОВНО КОРОЧЕ ЕБАННОЕ. СЪЕБЫВАЙТЕ НАХУЙ ОТТУДА

**Comment by ImJustKisik** [comment]
Вот, наконец-то конструктивная критика пошла!

**Comment by IDINAHUIPIDORAZ** [comment]
Я хочу искреннее извиниться за своё поведение перед игроками сс13... Я даже не знаю, что на меня на шло... НЕ СЛАТЬ ВАС НАХУЙ В СТОКРАТ СИЛЬНЕЕ ХУЕСОСЫ НЕ БЛАГОДАРНЫЕ! Я ЖИЛА И ЛЮБИЛА ЭТОТ МИР СКАЗКИ И ПИЗДЕЖА А ТЕПЕРЬ МЕНЯ ЭТА ЗАЕБАЛО НАХУЙ! ЛЕНИВЫЕ ПЕДАЛЬСКИЕ ЖОПЫ НЕ РАССМАТРИВАЮТ ЖАЛОБ! ТРАПУЮЩИЕ И ДРОЧИЩИЕ ХУЕСОСЫ ФУРРИ И БРОНИ ДРУГ НА ДРУГА! Я ЗАЕБАЛАСЬ! Я ХОЧУ ЧТОБЫ ПАРАШИЗА СГОРЕЛА К ХУЯМ СОБАЧИМ ИЛИ НАЧАЛА МЕДЛЕННО В КИСЛОТЕ РАЗЛАГАТЬСЯ! НЕ ТЕРПИТЕ ВСЮ ПОЕБОТУ ЧТО ВСТРЕЧАЕТСЯ В ВАМ НА СТАНЦИИ И В ЖИЗНИ! ХУЯРЬ НАХУЙ ДО СМЕРТИ И ПОТОМ ЕЩЁ НАСРИ НА ЕГО ЛИЦО СВЕРХУ БЛЯТЬ ЭТОМУ ЕБАННОМУ ПЛЕБЕЮ БЛЯТЬ! ЖРИ ДЕРЬМО! ЖРИИ! ДЕРЬМО ЖЕ ВКУСНОЕ И НЕЖНОЕ!

**Comment by IDINAHUIPIDORAZ** [comment]
СОЖРИТЕ ВКУСНОЕ И СОЧНОЕ ДЕРЬМЕЦО! НУ, ДАВАЙ, КУШАЙ! ЕБАННАЯ СОБАКА НЕ ЕРПЕШИЙ, БЛЯТЬ ЕБАННАЯ СОБАКА НЕ ЕРПЕШАЙ БЛЯТЬ ЕБАННАЯ СОБАКА НЕ ЕРПЕШАЙ БЛЯТЬ ЕБАННАЯ СОБАКА НЕ ЕРПЕШАЙ БЛЯТЬ НЕ ЕРПЕШАЙ БЛЯТЬ

**Comment by IDINAHUIPIDORAZ** [comment]
РАЗБАНЬТЕ ЛИЧИНЕССУ ПОЛИНУ НУ ПЖ ПЖ ПЖ <3

**Comment by terribaum** [comment]
Хорошо пошло. Аж жар с экрана.

**Comment by tizer7** [comment]
Против.
Я как человек не раз читавший "консультант плюс", различные юридические документы, имеющий судебные тяжбы за плечами, заявляю, что и 6 страниц этого чтива выше, не осилил. Если читать дальше то кровь из глаз пойдет.
Да и к тому же считаю, что то большее, чем существующий КЗ, игроки не осилят.

**Comment by AugustBebel** [comment]
Ящитаю что в нынешнем КЗ нужно добавить пункт «выброс в мусорку» и все проблемы исчезнут.

По сути: 
— Аннигиляция как статья нраица. Забить ассистуху баллоном и оставить труп с датчиками не то же самое что забить его баллоном, оторвать башку и выбросить в космос. Может стоит назвать «Уничтожение тела» или типа того.

— Преступление против корпорации тоже хорошая статья. А то сейчас по КЗ покушение на ассистоса и офицера ЦК идёт по одной статье. 

—  Штрафы — тоже хорошо. Было бы ещё лучше если бы деньги были более актуальны, а не только про покупке шмоток у ТСФ, но и так сойдёт.

— Чем текущая нумерация не угодила? С виду то же самое, но в профиль и, главное, непонятно зачем вообще менять. Если цель имитировать УК, то текущая нумерация просто напросто лучше и проще. 02.4 понять сложнее чем 402 даже потому что тяжесть преступления идёт первой цифрой, а не последней.
