### ISSUE TITLE
Feat: Добавить возможность размещать штампы в тексте

### ISSUE THREAD

**Issue by MHSPlay** [ss220-space/Paradise#249]
### Проблема

Добавить возможность размещать штампы в тексте
![image](https://user-images.githubusercontent.com/41786546/128279819-a850e3d5-aa42-4fe6-a35b-b68f352fc33e.png)

### Решение

Добавить [stamp] в бумаги и дать выбор куда ставить либо [stamp] или в конце бумаги

### Плюсы

Больше разнообразия в документах
Это добавляет визуальной красоты 

### Минусы

на 1 действие больше

**Comment by Danefalt** [comment]
На ТГ есть возможность выбирать место для штампа, когда ты его ставишь

**Comment by tizer7** [comment]
Ой, нахуй надо. Закрывай.

**Comment by Danefalt** [comment]
> Ой, нахуй надо. Закрывай.

Я могу меньше чем за минуту написать код для этого.
