### ISSUE TITLE
Feat: Порт системы случайных врагов и друзей и полный запрет метадружбы

### ISSUE THREAD

**Issue by Jordanstolethepreciousslam** [ss220-space/Paradise#250]
### Проблема

Метадружба является большим внутриигровым преимуществом над другими игроками. Начиная от хождения хвостиком и слежением друг за дружкой на предмет "не ебнул ли антаг" и заканчивая выдачей должностей, допуска, ресурсов и антажек. 
"хорошей" метадружбы не существует по определению. Любая метадружба дает преимущества как минимум просто потому что вместе - безопаснее.
Саму метадружбу очень легко оправдать, а использование метаинформации очень легко скрыть.

![image](https://user-images.githubusercontent.com/78968085/128363100-a7fef636-50d9-49ec-be2b-525811e3eb1d.png)
Твоя цель - в паравозике. Паравозик неразлучен весь раунд. Убивать кого то кроме цели - нельзя. Усыпить газом не получится. Всем участникам паровоза разрешается отбивать у тебя своего товарища. Удачи

### Решение

Портировать систему выдачи случайных друзей и врагов в начале раунда.(включаемую по желанию)
Запретить полностью метадружбу и межраундовые знания о персонажах.(Нет, имена знать можно, они есть в ПДА у всех)

P.S
В отличие от любой другой моей предложки, эту я скорее всего лично сам делать не буду
### Плюсы

+Новички не столкнутся с ситуацией когда их цель - игрок с 500 часами, неотрывно ходит в компании таких же игроков с сотнями часов или постоянно переписывается с ними.
+Новичкам на антаге может выдать опытного игрока в качестве друга.
+Никакого трайбализма когда станция является по сути солянкой из нескольких кланов.
+Просто взаимодействуя друг с другом по наставлению рандома, игроки будут мирится друг с другом и заводить новые знакомства.
+Последовательные правила. Сейчас избирательная амнезия приводит к тому что в теории на станции одни сверх-профессионалы с ангельским характером.
+Облегчение работы администрации

### Минусы

-Лишь частично решит проблемы с поддавками
-ряяяя, не хочу кокоса, хочу жиииинкуууууууу.

**Comment by Lenerald** [comment]
За
Я полностью согласен с жорданом насчет того, насколько метадружба может испортить жизнь другим игрокам, админам будет проще разбираться в проблемах связанных с ней а так-же у игроков появится новая возможность найти новые знакомства. Старые игроки метадрузья(500 часов как сказал жордан) действительно являются серьезной проблемой в случае если их встретит антагонист, мало того что в теории они могут сидеть в дискорде, что сложно отследить, они еще и являются умелыми игроками в станцию, что вдвойне понижает шансы на успех в схватке с ними.

**Comment by tizer7** [comment]
За, частично. 
Для комплексного решения нужен следующий подход:
принудительный рандом имени, всем без исключений + 
> Запретить полностью метадружбу и межраундовые знания о персонажах.

эта совокупность это значительно упростит разбор ситуаций метакоопа.
Оправдать почему один ckey тусуется с тем же ckey из прошлого раунда, имея другие имена будет оооочень проблематично таким персонажам.

минус: не всем понравится идея рандомных имен, и поэтому это может не пройти.

**Comment by kylon01** [comment]
За
ОПГ мета-компашки сбивающиеся в группы - зло, по вышенаписанным причинам.
А рандом друг и враг хорошая затея. Новый повод для прикольного РП. 
Ну и возможность выбора этой функции должна быть обязательно функциональна. 
У меня все.

**Comment by Frozored** [comment]
Привет, Джордан. Помнишь меня? Я твой одноклассник. Я узнал тебя по твоим шизоидным словам и высера…
1. Против
2. Во-первых я сам решаю с кем хочу общаться, а с кем — нет. Мне это нравится и я не хочу это менять. 
    Во-вторых твоя система никак не поможет игрокам: Новичок-антагонист в любом случае не сможет убить ветерана с 
    500 часами или незаметно у него что-то украсть. Наличие мета-друзей на это не влияет.
    В-третьих: опытные друзья — потрясающе, но ты предлагаешь одним людям склонять к самоантагонизму других.
    В-четвёртых: Система "Друзья/враги" ещё одна головная боль для администратора, которую нужно будет проверять перед баном/помилованием. Ну и из-за третьего пункта увеличится систематическое количество нарушений СРП и фактов самоантаногизма.

**Comment by DayBreakerBrony** [comment]
За.
Наконец-то Джордан стал бороться с причиной, а не следствием. такие паровозы и метадружба портит большое количество ситуаций за антага (ОСОБЕННО ДЛЯ РП АНТАГОВ ВРОДЕ МЕНЯ), Поэтому я категорически ЗА это предложение. вульпы ставят крестики, а чады РПшники смело ебашут в галку. 

П. С. меня бесят и метадрузья, и паровозы. но отыгрывать отношения из прошлого раунда я бы не запрещал, а то совсем вульп порвёт. все надо в меру

**Comment by VictorSocks** [comment]
1. Против
2. Предложение Джордана запрещает мне РП с тем с кем я уже работал раньше и заставляет меня дружить с рандомами которых я вообще не знаю, кринж. Нет, раундстартовый рандомный друг это конечно хорошо, но я хочу дружить не только с кем попало. Поэтому я предлагаю прописать ограничения по метадружбе в правилах и СРП к примеру, паравозик фыр фыр фыр это кринж и должно быть разрешено только в рамках обучения ассистентов всяких(сам так делал на СЕ), отлеживание на диване и полное игнорирование запросов экипажа, например на инженере, это кринж и тоже должно караться, если не авд то педалями в рамках рула 3, чрезмерная дружба на рабочем месте тоже не должна влиять на прием на работу и отношение на работе и все необходимые бумаги на поступление на должность должны быть заполнены, а не принимать на работу из-за того что это твой метадруг.

**Comment by normie5-cell** [comment]
За
Я вам запрещаю иметь друзей

**Comment by JammBad** [comment]
Против
Абсолютно нежизнеспособная идея, все описанные автором плюсы едва ли будут работать. Как было отмечено выше, новичок-антаг сможет только при большом везении заробастить умелого ветерана. Развяжите уже руки антагонистам, чтобы они легально могли всех свидетелей валить, если робаст позволяет. Также никто не будет отыгрывать никакую дружбу с рандомным Панти Кучем только потому что его прописало в друзьяшках механом, точно также, как сейчас все забивают на задания от абдукторов. 
Один хрен, если вы дадите всем принудительно рандомные имена, то метакореша будут узнавать друг друга по внешности. Если будет и внешность строго случайная, то ловите всякую кринжуху вроде зеленоволосых семидесятилетних трапоофицеров с фиолетовыми бородками. Это, видимо, то повышение ролеплея, ради которого запрещали предрестартовый ДМ? Это плюс к тому, что стандартные имена абсолютно позорно адаптированы, САША Костюшкин, ДИМА Петрушкин, ЖОРА Ричардс. Дело даже не в том, что славянские имена соседятся с западными фамилиями, а в том, что кто-то не удосужился в рандомизатор закинуть полные имена. Это же идентификационная карта, личное дело в крупной компании, а не список друзей в контактике. Вот так предлагается выправлять атмосферу на станции?
Единственное с чем согласен, это то, что пора закрепить на вики, каждый раунд - это отдельная история. Имейте какую-то общую с друзьяшками предысторию, ладно. Но никаких упоминаний предыдущих смен. Петю размазало взрывом по медбею в прошлой смене, а он в новой с друзьяшками вспоминает, как в баре тогда лампово синячил. Вот это уже дичь, да

**Comment by AugustBebel** [comment]
Против.

Паравозы и метадрузяшки это говно говна, но лечить можно уже существующими правилами, а не введением сомнительных костылей. Просто нужно разъяснить людям что паравозы с одними и теми же сикеями из смены в смены это хуже одного известного червя и нужно давить и репортить. 

По поводу предыдущих смен — текущие правила опять всё ставят на свои места. Только текущая смена пошла по пизде и вспоминать можно только хорошее, предыдущие смены были обычной рутиной. То есть писать в заявлении о приёме на работу «5 смен на шахтёре» или говорить «О, опять вы!» это нормально, а душить людей основываясь на предыдущих раундах нехорошо.

**Comment by LoveTrapov** [comment]
1. Против.
2. Я не хожу паровозиком, частенько отлетаю от антагов, но мне хочется играть РП не с рандомным лысым ассистухой, а с людьми в которых есть уверенность и которые показывают достойный уровень РП. (И при этом не знакомить персов каждый раунд...) Да и в целом, запрещать что то только потому что вас бесит одна компашка метадрузей звучит бредово.

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
1. За
2. А теперь представим, что у нас есть тритор. Цель тритора где-то в паровозике. У тритора есть возможность убивать свидетелей. Но ей он не сможет воспользоваться, потому что тогда припишут ДМ. Тогда попробует застанить цель и увести? Да, хуй там, плиткой закидают, лишь бы жонку спасти. Как выход - ужесточить правило о метадружбе и реально запретить такие паровозики.

**Comment by LoveTrapov** [comment]
> 1. За
> 2. А теперь представим, что у нас есть тритор. Цель тритора где-то в паровозике. У тритора есть возможность убивать свидетелей. Но ей он не сможет воспользоваться, потому что тогда припишут ДМ. Тогда попробует застанить цель и увести? Да, хуй там, плиткой закидают, лишь бы жонку спасти. Как выход - ужесточить правило о метадружбе и реально запретить такие паровозики.

Помните, что цель антагониста - сделать раунд интересным. Так если кто то всю игру ходит в компании может его раунд и так интересный и антагу стоит заняться чем то другим? Почему игра должна крутиться вокруг антагов и их целей, если они существуют не более чем для разбавления раунда, в частности миноры.

**Comment by Honker9999999** [comment]
> Помните, что цель антагониста - сделать раунд интересным. Так если кто то всю игру ходит в компании может его раунд и так интересный и антагу стоит заняться чем то другим? Почему игра должна крутиться вокруг антагов и их целей, если они существуют не более чем для разбавления раунда, в частности миноры.

"ЕГО" раунд может и интересный... Для него и его друзей. Но... В этом и есть проблема метакооп компания. Они то конечно общаются, РПшат и всякое такое, это да. Но с кем они это делают? Правильно, лишь среди себе подобных. Между собой, иными словами. Вопрос - интересный ли это раунд для кучи других людей, что к их метакооп компании не относятся? Делают ли ОНИ раунд интереснее для них? Вот например для того ассистента, на которого всем похуй ибо "Ну вот это моя подруженька друг друголечек, его я возьму инженером, а ты нахуй иди хули сюда приперся?" Бармена, к которому никто из них не ходит ибо "Ну мы уже спиздили бухломат. Какие ещё РП ситуации в баре? Какие "Напился и пошел в драку"? Какие ещё нахрен "Напился и изливает душу бармену"? Нахуй это надо, лучше пойду ЕРПшить с вульпочками-друзяшками!" Конечно, все не настолько плохо, я вероятнее всего утрирую, но смысл я думаю вы поняли. 

Мы тут играем в игру про "Попробуй выжить на СС(или в СС, эт как посмотреть), страдая от тупости, антагов, событий и ещё раз тупости!" или в "Работка и дроч друг подружке"? Метакооп компании - рак, как и инженелобби и медбее лобби на тех-же опухах. 
Смысл КАЖДОГО игрока сделать раунд интереснее для ВСЕХ, не только себя и своих друзей, а если вы хотите с этим спорить... Ну, ваше право. Но тогда пожалуйста, прочитайте нулевое правило любого проекта и пройдите куда-нибудь в район мужского полового органа(оно же - пошел нахуй)

**Comment by LoveTrapov** [comment]
> > Помните, что цель антагониста - сделать раунд интересным. Так если кто то всю игру ходит в компании может его раунд и так интересный и антагу стоит заняться чем то другим? Почему игра должна крутиться вокруг антагов и их целей, если они существуют не более чем для разбавления раунда, в частности миноры.
> 
> "ЕГО" раунд может и интересный... Для него и его друзей. Но... В этом и есть проблема метакооп компания. Они то конечно общаются, РПшат и всякое такое, это да. Но с кем они это делают? Правильно, лишь среди себе подобных. Между собой, иными словами. Вопрос - интересный ли это раунд для кучи других людей, что к их метакооп компании не относятся? Делают ли ОНИ раунд интереснее для них? Вот например для того ассистента, на которого всем похуй ибо "Ну вот это моя подруженька друг друголечек, его я возьму инженером, а ты нахуй иди хули сюда приперся?" Бармена, к которому никто из них не ходит ибо "Ну мы уже спиздили бухломат. Какие ещё РП ситуации в баре? Какие "Напился и пошел в драку"? Какие ещё нахрен "Напился и изливает душу бармену"? Нахуй это надо, лучше пойду ЕРПшить с вульпочками-друзяшками!" Конечно, все не настолько плохо, я вероятнее всего утрирую, но смысл я думаю вы поняли.
> 
> Мы тут играем в игру про "Попробуй выжить на СС(или в СС, эт как посмотреть), страдая от тупости, антагов, событий и ещё раз тупости!" или в "Работка и дроч друг подружке"? Метакооп компании - рак, как и инженелобби и медбее лобби на тех-же опухах.
> Смысл КАЖДОГО игрока сделать раунд интереснее для ВСЕХ, не только себя и своих друзей, а если вы хотите с этим спорить... Ну, ваше право. Но тогда пожалуйста, прочитайте нулевое правило любого проекта и пройдите куда-нибудь в район мужского полового органа(оно же - пошел нахуй)

1. Да утрируешь
2. А от того что убьюсь об антага раунд много для кого интересным станет?
3. Ладно, я пошёл

**Comment by Honker9999999** [comment]
> 1. Да утрируешь
> 2. А от того что убьюсь об антага раунд много для кого интересным станет?
> 3. Ладно, я пошёл

1. Ок
2. Внезапно, но веселее чем если ты молча будешь бегать. Этим ты сам говоришь что являешься членом метадружбы или что?
3. Ок

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
> > 1. За
> > 2. А теперь представим, что у нас есть тритор. Цель тритора где-то в паровозике. У тритора есть возможность убивать свидетелей. Но ей он не сможет воспользоваться, потому что тогда припишут ДМ. Тогда попробует застанить цель и увести? Да, хуй там, плиткой закидают, лишь бы жонку спасти. Как выход - ужесточить правило о метадружбе и реально запретить такие паровозики.
> 
> Помните, что цель антагониста - сделать раунд интересным. Так если кто то всю игру ходит в компании может его раунд и так интересный и антагу стоит заняться чем то другим? Почему игра должна крутиться вокруг антагов и их целей, если они существуют не более чем для разбавления раунда, в частности миноры.

Нихуя ты придумал.
"Ему интересно и похуй, что он твоя цель, которую ты должен убить".
Я надеюсь, у тебя выключены антаги и ты просто фурриеб без мозга. В другие моменты тебя будет жаль

**Comment by LoveTrapov** [comment]
> > > 1. За
> > > 2. А теперь представим, что у нас есть тритор. Цель тритора где-то в паровозике. У тритора есть возможность убивать свидетелей. Но ей он не сможет воспользоваться, потому что тогда припишут ДМ. Тогда попробует застанить цель и увести? Да, хуй там, плиткой закидают, лишь бы жонку спасти. Как выход - ужесточить правило о метадружбе и реально запретить такие паровозики.
> > 
> > 
> > Помните, что цель антагониста - сделать раунд интересным. Так если кто то всю игру ходит в компании может его раунд и так интересный и антагу стоит заняться чем то другим? Почему игра должна крутиться вокруг антагов и их целей, если они существуют не более чем для разбавления раунда, в частности миноры.
> 
> Нихуя ты придумал.
> "Ему интересно и похуй, что он твоя цель, которую ты должен убить".
> Я надеюсь, у тебя выключены антаги и ты просто фурриеб без мозга. В другие моменты тебя будет жаль

Ну и в чём я не прав? Цели антага не обязательны для выполнения, не несут особой ценности для РП, короче в целом не обязательны, спрашивается почему тогда я должен жертвовать своим удовольствием от игры ради дрочера на гринтекст? Я играю РП в компании, антаг не может меня убить, вопрос, почему это должно быть моей проблемой и почему я должен ему поддаваться?

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
> > > > 1. За
> > > > 2. А теперь представим, что у нас есть тритор. Цель тритора где-то в паровозике. У тритора есть возможность убивать свидетелей. Но ей он не сможет воспользоваться, потому что тогда припишут ДМ. Тогда попробует застанить цель и увести? Да, хуй там, плиткой закидают, лишь бы жонку спасти. Как выход - ужесточить правило о метадружбе и реально запретить такие паровозики.
> > > 
> > > 
> > > Помните, что цель антагониста - сделать раунд интересным. Так если кто то всю игру ходит в компании может его раунд и так интересный и антагу стоит заняться чем то другим? Почему игра должна крутиться вокруг антагов и их целей, если они существуют не более чем для разбавления раунда, в частности миноры.
> > 
> > 
> > Нихуя ты придумал.
> > "Ему интересно и похуй, что он твоя цель, которую ты должен убить".
> > Я надеюсь, у тебя выключены антаги и ты просто фурриеб без мозга. В другие моменты тебя будет жаль
> 
> Ну и в чём я не прав? Цели антага не обязательны для выполнения, не несут особой ценности для РП, короче в целом не обязательны, спрашивается почему тогда я должен жертвовать своим удовольствием от игры ради дрочера на гринтекст? Я играю РП в компании, антаг не может меня убить, вопрос, почему это должно быть моей проблемой и почему я должен ему поддаваться?
> P.S. Лить токс кстати совсем не обязательно

Токс тут по причине "я нарушаю атмосферу игры, катаясь с друзьями-зверушками по станции и используя метадружбу гриферю антагам жизнь". 
Просто как предложение - либо запретить паровозик, либо разрешить полностью вырезать паровозик. Ибо без причины бегать паровозиком - долбоебизм

**Comment by LoveTrapov** [comment]
> > > > > 1. За
> > > > > 2. А теперь представим, что у нас есть тритор. Цель тритора где-то в паровозике. У тритора есть возможность убивать свидетелей. Но ей он не сможет воспользоваться, потому что тогда припишут ДМ. Тогда попробует застанить цель и увести? Да, хуй там, плиткой закидают, лишь бы жонку спасти. Как выход - ужесточить правило о метадружбе и реально запретить такие паровозики.
> > > > 
> > > > 
> > > > Помните, что цель антагониста - сделать раунд интересным. Так если кто то всю игру ходит в компании может его раунд и так интересный и антагу стоит заняться чем то другим? Почему игра должна крутиться вокруг антагов и их целей, если они существуют не более чем для разбавления раунда, в частности миноры.
> > > 
> > > 
> > > Нихуя ты придумал.
> > > "Ему интересно и похуй, что он твоя цель, которую ты должен убить".
> > > Я надеюсь, у тебя выключены антаги и ты просто фурриеб без мозга. В другие моменты тебя будет жаль
> > 
> > 
> > Ну и в чём я не прав? Цели антага не обязательны для выполнения, не несут особой ценности для РП, короче в целом не обязательны, спрашивается почему тогда я должен жертвовать своим удовольствием от игры ради дрочера на гринтекст? Я играю РП в компании, антаг не может меня убить, вопрос, почему это должно быть моей проблемой и почему я должен ему поддаваться?
> > P.S. Лить токс кстати совсем не обязательно
> 
> Токс тут по причине "я нарушаю атмосферу игры, катаясь с друзьями-зверушками по станции и используя метадружбу гриферю антагам жизнь".
> Просто как предложение - либо запретить паровозик, либо разрешить полностью вырезать паровозик. Ибо без причины бегать паровозиком - долбоебизм

Да я и не спорю, но запрет дружбы из раунда в раунд это слишком радикальное решение проблемы.

**Comment by Daymonchemist** [comment]
Против

Ух ты, предложка еще живая, я думал канула в лету. Ну да ладно. 
Давайте сразу отчертим - я ни разу не участвовал в подобных паровозиках, диваны в инженерке видел раза 3, из них 2 на госте, а третий на авд, антаги у меня были долго вырублены, а сейчас просто не выпадают.

Теперь по существу. Во-первых, подобные поровозики сейчас перестали появляться, как я заметил. Была неделя угара от компашки вульп, когда и взъелись все (а особенно автор данного предложения), начался дикий токс, из-за чего ужесточились правила дискорда. С тех пор проблема не поднималась нигде, она себя не проявляла. То есть, предложение направлено на исправление мимолетного и уже закончившегося поведения нескольких игроков. Перерегулирование - плохо, как мне кажется. А тут предлагают его.

Во-вторых, поцитирую дискуссию из дискорда тут. Тот факт, что вы знакомы и имеете приятные отношения наоборот может помогать ролеплею. Именно между "метадрузьями" возможен подкуп, шантаж и прочее. Да, из конкретно этого момента выпадают другие люди. Но создание системы случайных имен, друзей и врагов убьет такие моменты окончательно. Подкупить СЕ, чтобы тот дал нулевой закон ИИ, майндслейв именно опытного и скиллового игрока. Для этого не обязательно должен быть кооп, но такое скорее (гораздо скорее) произойдет в случае метадружбы, так как антагонист будет уверен в игроке и выгодности своих действий. 

В-третьих, (частично возвращаясь к первому) у нас имеются правила, по которым вы можете требовать наказать эту компанию. Если конкретнее, то правила 3, 3.2, 4. 

В-четвертых, знания о прошлых сменах критично важны в некоторых ситуациях. Мой личный пример - мне надо уйти по ирл причинам с смо, я назначаю врио. У меня есть на выбор 4-5 врачей, но я точно знаю кому дам эту должность, так как уверен в адекватности и опыте игрока. А опытных врачей я не буду долго муштровать тестами в медбей, потому что я знаю, что они это знают. Разумеется, это сопровождается разговором, может парой шуток или ссылкой на несуществующие слухи об опытности персонажа, то есть "по сейлогам проходит", но суть остается той же. Такие метазнания, иногда и метадружба, в итоге улучшают жизнь всем. Я меньше трачу времени на прием в отдел, опытные врачи быстрее попадают в отдел, персонал получает более быстрое и качественное лечение. Я буду дружить с опытными врачами, с которыми работаю больше 10 смен, и это, имхо, правильно.

Ну и под конец, сейчас я слышу только о проблемах в отделе сб. И они не связаны с метадружбой. Если мой опыт принципиально неправильный и ваш отличается, то с радостью вас послушаю, почитаю.

**Comment by DayBreakerBrony** [comment]
> Против
> 
> Ух ты, предложка еще живая, я думал канула в лету. Ну да ладно.
> Давайте сразу отчертим - я ни разу не участвовал в подобных паровозиках, диваны в инженерке видел раза 3, из них 2 на госте, а третий на авд, антаги у меня были долго вырублены, а сейчас просто не выпадают.
> 
> Теперь по существу. Во-первых, подобные поровозики сейчас перестали появляться, как я заметил. Была неделя угара от компашки вульп, когда и взъелись все (а особенно автор данного предложения), начался дикий токс, из-за чего ужесточились правила дискорда. С тех пор проблема не поднималась нигде, она себя не проявляла. То есть, предложение направлено на исправление мимолетного и уже закончившегося поведения нескольких игроков. Перерегулирование - плохо, как мне кажется. А тут предлагают его.
> 
> Во-вторых, поцитирую дискуссию из дискорда тут. Тот факт, что вы знакомы и имеете приятные отношения наоборот может помогать ролеплею. Именно между "метадрузьями" возможен подкуп, шантаж и прочее. Да, из конкретно этого момента выпадают другие люди. Но создание системы случайных имен, друзей и врагов убьет такие моменты окончательно. Подкупить СЕ, чтобы тот дал нулевой закон ИИ, майндслейв именно опытного и скиллового игрока. Для этого не обязательно должен быть кооп, но такое скорее (гораздо скорее) произойдет в случае метадружбы, так как антагонист будет уверен в игроке и выгодности своих действий.
> 
> В-третьих, (частично возвращаясь к первому) у нас имеются правила, по которым вы можете требовать наказать эту компанию. Если конкретнее, то правила 3, 3.2, 4.
> 
> В-четвертых, знания о прошлых сменах критично важны в некоторых ситуациях. Мой личный пример - мне надо уйти по ирл причинам с смо, я назначаю врио. У меня есть на выбор 4-5 врачей, но я точно знаю кому дам эту должность, так как уверен в адекватности и опыте игрока. А опытных врачей я не буду долго муштровать тестами в медбей, потому что я знаю, что они это знают. Разумеется, это сопровождается разговором, может парой шуток или ссылкой на несуществующие слухи об опытности персонажа, то есть "по сейлогам проходит", но суть остается той же. Такие метазнания, иногда и метадружба, в итоге улучшают жизнь всем. Я меньше трачу времени на прием в отдел, опытные врачи быстрее попадают в отдел, персонал получает более быстрое и качественное лечение. Я буду дружить с опытными врачами, с которыми работаю больше 10 смен, и это, имхо, правильно.
> 
> Ну и под конец, сейчас я слышу только о проблемах в отделе сб. И они не связаны с метадружбой. Если мой опыт принципиально неправильный и ваш отличается, то с радостью вас послушаю, почитаю.

По вашей логике люди без друзей никогда не будут замечены как кандидаты на посты ВрИО, а я как человек асоциальный осуждаю подобный блат. Да, вы играете интересное РП, но это рп нравится только вам. Вы не устроите интересный конкурс на пост или т. д. и обделите других. Это эгоистично, ровно как и играть РП только для себя и своих друзей.

**Comment by Daymonchemist** [comment]
> По вашей логике люди без друзей никогда не будут замечены как кандидаты на посты ВрИО, а я как человек асоциальный осуждаю подобный блат. Да, вы играете интересное РП, но это рп нравится только вам. Вы не устроите интересный конкурс на пост или т. д. и обделите других. Это эгоистично, ровно как и играть РП только для себя и своих друзей.

Вы не совсем тогда знаете ситуацию в медбее или я не совсем раскрыл пример. Если персонаж находится в медбее длительное время и не имеет выраженных ментальных проблем (под этим я имею сильную инфантильность или алкоголизм), то я его рассматриваю как кандидата на пост. Если я не выберу лучшего, то позову всех на выбор к себе и спрошу их. Но роль смо не популярна, на врио вызываются мало игроков в принципе. Если есть играющий на смо - то точно он будет, ему привычна эта роль. У него резюме лучше. Для меня такие вещи скорее как резюме, чем дружба и "кумовство". 

Ещё мне кажется немного странным ругать блат в ролеплее, когда он не портит никому игру и обоснован, но тут уже на вкус и цвет

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184357166-b02aa825-2a87-4845-9829-04efbe5865f8.png)
