### ISSUE TITLE
Feat: Переработка СМ на Дельте, Вертикальные Холодильники. 

### ISSUE THREAD

**Issue by OpsCoretango** [ss220-space/Paradise#251]
### Проблема

#Delta
Усложненная интеграция TEGов в комплекс Суперматерия+атмос. 
Невозможность заказа или сборки холодильников расположенных вертикально. 

### Решение

Полная переработка с консультацией от мастеров СМ по их желанию и обеспечение безопасности в условии потенциального повышения КПД и соотвественно взрыва.
Вариативность при окончательной сборке холодильника с предложением Horizontal, Vertical или добавить функцию Rotate. 

### Плюсы

Облегченная интеграция в зоне содержания СМ.
Облегченная Интеграция с ТЕГ обеспечит быстрое выполнение задач по цели станции: Bluespace Harvester. 

### Минусы

Погоня за энергией и мощные взрывы во славу Богу СМ от компании Нуклеарий.
Меньший кооэфицент запусков на азоте.

**Comment by OpsCoretango** [comment]
Конкретно про морозильник
При постройке вам собирается только в горизонтальном положении, я же предлагаю при сборке вы выбираете в белом контекстном меню его положение.  При СМ когда их все выбивало это было серьезной проблемой а если в нынешний СМ это попытатся проделать то.. будет ваще никак его установить нормально.

**Comment by girafe969** [comment]
Про какие холодильники идёт речь? Freezer? К нему же есть доступ с любого направления, какая разница горизонтальный у него спрайт или вертикальный

**Comment by OpsCoretango** [comment]
> Про какие холодильники идёт речь? Freezer? К нему же есть доступ с любого направления, какая разница горизонтальный у него спрайт или вертикальный

Дело в подключении трубы и "There is pipe already installed".
С вертикальным труба коннектится справа и горизонтально снизу.

**Comment by girafe969** [comment]
> > Про какие холодильники идёт речь? Freezer? К нему же есть доступ с любого направления, какая разница горизонтальный у него спрайт или вертикальный
> 
> Дело в подключении трубы и "There is pipe already installed".
> С вертикальным труба коннектится справа, у горизонтально снизу.

Ясно, смолгей не знает, что направление, к которому подключается труба можно изменить гаечным ключом, дело закрыто

**Comment by OpsCoretango** [comment]
> > > Про какие холодильники идёт речь? Freezer? К нему же есть доступ с любого направления, какая разница горизонтальный у него спрайт или вертикальный
> > 
> > Дело в подключении трубы и "There is pipe already installed".
> > С вертикальным труба коннектится справа, у горизонтально снизу.
> 
> Ясно, смолгей не знает, что направление, к которому подключается труба можно изменить гаечным ключом, дело закрыто. В следующий раз с подобной проблемой обращайтесь в хелп-чат, а не книгу предложений

О боже..
Вертикальный холодильник подключается только с правой стороны а горизонтальный freezer снизу.
Нету у него доступа с любого направления, нету.. ибо на локалке он бы охлаждал если труба была в противоположной стороне. 
Вы о чем? Посмотрите в атмосе и СМ коннект холодильника пожалуйста.
Представьте какого то мученика который пытается сделать **охладитель для плазмы** или ТЕГ с Freezer.
Почему вы думаете про трубу?

**Comment by OpsCoretango** [comment]
> > > Про какие холодильники идёт речь? Freezer? К нему же есть доступ с любого направления, какая разница горизонтальный у него спрайт или вертикальный
> > 
> > Дело в подключении трубы и "There is pipe already installed".
> > С вертикальным труба коннектится справа, у горизонтально снизу.
> 
> Ясно, смолгей не знает, что направление, к которому подключается труба можно изменить гаечным ключом, дело закрыто. В следующий раз с подобной проблемой обращайтесь в хелп-чат, а не книгу предложений

Я прошу вас перечитать ваш ответ на мой ответ перед смоллгеем а потом подумать над этим

**Comment by OpsCoretango** [comment]
> ### Проблема
> 
> Усложненная интеграция TEGов в комплекс. 
> Невозможность заказа или сборки холодильников расположенных вертикально. 
> 
> ### Решение
> 
> Полная переработка с консультацией от мастеров СМ по их желанию и обеспечение безопасности в условии потенциального повышения КПД и соотвественно взрыва.
> Вариативность при окончательной сборке холодильника с предложением Horizontal, Vertical. 
> 
> ### Плюсы
> 
> Облегченная интеграция в зоне содержания СМ.
> Облегченная Интеграция с ТЕГ обеспечит быстрое выполнение задач по цели станции: Bluespace Harvester. 
> 
> ### Минусы
> 
> Погоня за энергией и мощные взрывы во славу Богу СМ от компании Нуклеарий.
> Меньший кооэфицент запусков на азоте. 

Да у него есть вертикальный вариант в камере содержания СМ.
С увеличением температур будет большой взрыв, а что если переработать контур с цветовым пояснением где холодный и горячий контур как то саму камеру подальше от прибытия и техов увести(моя мечта скорее уж)
Есть вариант обустроить с ускорителем частиц но безопаснее его взорвать.

**Comment by Longmanrus** [comment]
Зачем там вообще холодильники, если теплообменники через космос намного эффективнее охлаждают? ТЭГ сейчас можно
без боли прикрутить к СМ реактору. Но места для него там реально маловато.

**Comment by OpsCoretango** [comment]
> Зачем там вообще холодильники, если теплообменники через космос намного эффективнее охлаждают? ТЭГ сейчас можно
> без боли прикрутить к СМ реактору. Но места для него там реально маловато. 

Дело не в этом что там делают эти Freezer, а в том чтобы добавить им функциональность поворота(Rotate).

Смотри, там справа горячий идет а на том перекрестке где waste их комбо, я там должен вставить объект в 2 тайла где стоит миксер в общей площади 4-6 тайлов. Вообще по плану хотел поставить 2 ТЭГа потому что у меня опыт с Оникса и соотвественно подобающее обращение с оборудованием.
Либо ничего не делать в узком пространстве или ломаем стену и расширяем.
Хотя есть в планах тупо снести теплоотводы слева и отключить атмос потом поставить дохрена теплопроводов в пользу свободной площади для маневров в инженерном плане.

**Comment by Danefalt** [comment]
> Дело не в этом что там делают эти Freezer, а в том чтобы добавить им функциональность поворота(Rotate).

Их всегда можно было поворачивать.

**Comment by OpsCoretango** [comment]
> > Зачем там вообще холодильники, если теплообменники через космос намного эффективнее охлаждают? ТЭГ сейчас можно
> > без боли прикрутить к СМ реактору. Но места для него там реально маловато. 
> 
> Дело не в этом что там делают эти Freezer, а в том чтобы добавить им функциональность поворота(Rotate).
> 
> Смотри, там справа горячий идет а на том перекрестке где waste их комбо, я там должен вставить объект в 2 тайла где стоит миксер в общей площади 4-6 тайлов(трубы мешают сцуко и атмос в отношении СМ самый странный что я видел :(   ) . Вообще по плану хотел поставить 2 ТЭГа потому что у меня опыт с Оникса и соотвественно подобающее обращение с оборудованием.
> Либо ничего не делать в узком пространстве или ломаем стену и расширяем.
> Хотя есть в планах тупо снести теплоотводы слева и отключить атмос потом поставить дохрена теплопроводов в пользу свободной площади для маневров в инженерном плане. 

    А как потому что Rotate или при сборке поворот не работает а ключом ты его присоединяешь.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184357237-c2aba3d9-e454-41a6-b9a1-70ee022ac2b8.png)
