### ISSUE TITLE
Bug: vox breath mask не позволяет поесть

### ISSUE THREAD

**Issue by Corb750** [ss220-space/Paradise#2531]
### Ckey

Corbi

### Описание бага

Нельзя есть за вокса так маска перестала позволять это

### Шаги воспроизведения

зайти за вокса и попытаться поесть 

### Ожидаемое поведение

утолить голод 

### Операционная система

win11

### Версия клиента

514.1585

### Название сервера

MAIN

### Примерное время и дата

21:53 31.03.23

**Comment by Ohar** [comment]
Не баг же.
Есть через мсаску и правда нельзя.
Сними маску, поешь, надень обратно.
