### ISSUE TITLE
Feat: Телепатия для Символа Разумизма

### ISSUE THREAD

**Issue by Frozored** [ss220-space/Paradise#254]
### Проблема

Не смотря на то, что данный предмет имеет чисто декоративный характер, многие его любят и часто просят у РД (иногда даже воруют). Хочется, чтобы у такого уникального предмета была и уникальная фишка.

### Решение

Сделать так, чтобы при одевании Символа Разумизма у члена экипажа появлялась телепатическая связь как у греев. И исчезала при снятии.

### Плюсы

1. Метаюмор
2. Быть ученным-предеталем, у которого есть телепатическая связь, ещё веселее и интереснее.

### Минусы

1. Предложение не несёт никакой пользы

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184361387-aa3723bf-d6fe-490a-8be2-cc7fe7b65d19.png)
