### ISSUE TITLE
Вайдскрин и обновлённый чат

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#255]
### Проблема

Как выглядит сска? Легко - Две части экрана, в одной игра, в другой чат, и каждая из сторон занимает ровно половину экрана. Старая схема, к которой уже все привыкли, и наслаждаются ей. Но есть и те, вроде меня, кто считает немного другой внешний вид игры более удобным.
К тому же, возьмём отдельно чат - это мешанина из всего: Из простого чата, из OOC, из дедчата (опционально), из админлогов (опционально), в нём сосредоточено абсолютно всё, и иногда среди всей этой кучи можно и потерятся.

### Решение

Добавить вайдскрин и чат с ТГ. Они будут в разы удобнее, и сейчас объясню почему. (Джордан, не надо).

Что можно сказать про чат:
https://pastenow.ru/f9ae277c300d10a004e8e58155b0a5dc - пример вкладок с нового чата.
https://pastenow.ru/7a4ffe0deb6d26aaad91cc85c8b7ca3b - общие настройки чата.
https://pastenow.ru/530d87998514df43f9a63f4841b24c4e - настройки вкладок.
Такая версия в разы удобнее, а интерфейс более понятный. Не будет больше ситуаций где ты теряешься в чате, или к примеру когда тебе нужно сделать пару скринов для мемов, а там куча лишнего, а обрезать это тебе лень.

Что можно сказать про вайдскрин:
https://pastenow.ru/8a33733f099c31ddfc00ed598c70117b - настройки вайдскрина (Игровые префы)
https://pastenow.ru/b7d89e34500671b6b40e11cf50fc834d - внешний вид игры (21x15)
https://pastenow.ru/9651e6b4f3f8a66071c75facff68cec4 - внешний вид игры (15x15, стандарт)
https://pastenow.ru/d17449371d98d8464c5d573e1515d2f5 - В дополнение: Жертва ввиде размера чата при использовании вайдскрина.
При игре с вайдскрином размер чата уменьшается, но плюс это или минус решать вам. Кому-то может быть так даже удобнее. Во-вторых, глаза меньше устают: Игра и чат буквально в двух разных углах, из-за чего нужно постоянно перемещаться между ими. С вайдскрином же, глаза всегда ближе к центру, из-за чего фокусироваться на чат становится легче, при этом, не отрывая взгляд от происходящего в самой игре.

### Плюсы

Чат:
* Более красивый внешний вид UI.
* Возможность организации чата путём вкладок, тем самым облегчая себе жизнь.

Вайдскрин:
* Расширенный угол обзора.
* Более близкое положение игры к центру экрана.

### Минусы

Чат:
_Пустота_

Вайдскрин:
* Урезанный чат.
* Больший угол обзора, а значит, _аНтАгАв дУшАт_.

**Comment by normie5-cell** [comment]
За 50/50
Тг чат еще понять можно.
Вайдскрин нет. Во-первых, эта хрень с углом обзора внесёт дисбаланс так как игрокам с мониторами 4:3 будет не удобно его использовать. Во-вторых, че вообще значит "чат станет меньше" и "более близкое положение игры к центру экрана" если окна можно регулировать. (https://imgur.com/a/CAwgSEB)
А вот как вайдскрин  выглядит на 4:3 мониторах (https://imgur.com/a/p5PaNZs) появляются полосы сверху и снизу. А вот как на гунах попытались это решить (https://imgur.com/a/7C9unOp)
Если и добавлять вайдскрин, то только чтобы дальше обычного угла обзора было видно все как в мезонах, то-есть только плитку, стены

**Comment by Danefalt** [comment]
> Во-вторых, че вообще значит "чат станет меньше" и "более близкое положение игры к центру экрана" если окна можно регулировать. (https://imgur.com/a/CAwgSEB)
> А вот как вайдскрин выглядит на 4:3 мониторах (https://imgur.com/a/p5PaNZs) появляются полосы сверху и снизу.

А ничего что при регуляции экрана тоже появляются полосы, но уже по бокам?

**Comment by normie5-cell** [comment]
> > Во-вторых, че вообще значит "чат станет меньше" и "более близкое положение игры к центру экрана" если окна можно регулировать. (https://imgur.com/a/CAwgSEB)
> > А вот как вайдскрин выглядит на 4:3 мониторах (https://imgur.com/a/p5PaNZs) появляются полосы сверху и снизу.
> 
> А ничего что при регуляции экрана тоже появляются полосы, но уже по бокам?

Первая ссылка, второй скрин. Полос у меня нет. Но у меня и 4:3 конечно

**Comment by Zigamus** [comment]
Я ответственно заявляю, что это просто улучшение технической части и если найдется человек, который это сделает, то голосований проводить не надо. Такой ПР примут и без голосований.
