### ISSUE TITLE
Bug: neurotoxin & neurotoxin2

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#262]
### Ckey

maliciouspancake

### Описание бага

https://github.com/RV666/Paradise/blob/8954d31b1b9ed25caff5e712f6a8c040812ede68/code/modules/reagents/reagent_containers/syringes.dm#L208
В коде значится id "neurotoxin", принадлежащий алкогольному напитку. 
https://github.com/RV666/Paradise/blob/8954d31b1b9ed25caff5e712f6a8c040812ede68/code/modules/reagents/chemistry/reagents/alcohol.dm#L920
Токсин обозначает id "neurotoxin2".
https://github.com/RV666/Paradise/blob/8954d31b1b9ed25caff5e712f6a8c040812ede68/code/modules/reagents/chemistry/reagents/toxins.dm#L616

### Шаги воспроизведения

Залезть на гитхаб и посмотреть

### Ожидаемое поведение

В составе шприцов заменить id

### Операционная система

Win10

### Версия клиента

.

### Название сервера

MAIN

### Примерное время и дата

08.08.2021

**Comment by botka4aet** [comment]
Откуда ты получаешь коробку со шприцами? Из аплинка?

**Comment by 1heShogun** [comment]
Не баг, а фича. В описании шприца сказано, что содержимое необходимо для парализации. Напиток нейротоксин как раз это и делает.

**Comment by botka4aet** [comment]
> Не баг, а фича. В описании шприца сказано, что содержимое необходимо для парализации. Напиток нейротоксин как раз это и делает.

```
	if(current_cycle >= 13)
		update_flags |= M.Weaken(3, FALSE)
	if(current_cycle >= 55)
		update_flags |= M.Druggy(55, FALSE)
	if(current_cycle >= 200)
		update_flags |= M.adjustToxLoss(2, FALSE)
```
?

**Comment by 1heShogun** [comment]
не вижу тут бага, все работает исправно.

**Comment by WannaGovna** [comment]
в игре 2 нейротоксина, один из них напиток, другой йад страшный...А баг то где?

**Comment by botka4aet** [comment]
> в игре 2 нейротоксина, один из них напиток, другой йад страшный...А баг то где?

Что в шприце синдиката нейротоксин-напиток, а не нейротоксин-токсин

**Comment by Frozored** [comment]
Позавчера только купила дротикомет и выстрелила нейротоксином в инженера. Где-то через две минуты он откис. Неплохой такой коктейль.

**Comment by 1heShogun** [comment]
> Что в шприце синдиката нейротоксин-напиток, а не нейротоксин-токсин

Так и должно быть. Шприц сделан для парализации жертвы, нейротоксин-коктейль с этим справляется. Нейротоксин-токсин же наносит урон мозгу и может вообще убить

**Comment by botka4aet** [comment]
В шприце 1 токсин. В игре их два
list_reagents = list("neurotoxin" = 5, "capulettium_plus" = 5, "sodium_thiopental" = 5)
