### ISSUE TITLE
Bug: Напрочь сломанная ботаника

### ISSUE THREAD

**Issue by GlassOil** [ss220-space/Paradise#264]
### Ckey

GlassOil

### Описание бага

Максимальное количество веществ в растениях установлено на 50u, тогда как сами растения из tg станции где этот максимум на 100u, в итоге имеем огромное количество растений, которые без всяких модификаций НЕ вмещают в себя те вещества которые просто должны в них находиться

### Шаги воспроизведения

1) Взять семечко любого растения с 100 потенцией и наличием суммы родных % веществ больше 49 (Lifeweed, Blumpkin, Ambrosia vulgaris, Death nettle и ещё целая куча растений)
2) Посадить и вырастить семечко
3) Засунуть растения в блендер или съесть\скормить.
4) Проверить вещества и убедиться, что некоторых просто не будет или их количество будет сильно снижено (ОЧЕНЬ заметно на омега конопле)

### Ожидаемое поведение

Выращенные растения после съедания или блендера дают полный перечень и количество веществ которые в них содержаться. 

### Дополнительная информация

Выход веществ будет по формуле 1+% (при 100 потенции), всегда по порядку в зависимости от их расположения в растении если мелить в блендере, так Lifeweed всегда даст 36u omnizine и 14u tetrahydrocannabinol, где-то потеряв 2u tetrahydrocannabinol и вообще все 16u cannabidiol которые должны присутствовать. 
Если растение кушать, а не мелить, то вещества попадут в случайном (?) порядке, но их сумма всё равно будет сильно меньше той, что должна.
В tg есть несколько растений сумма веществ которых превышает 100u, таким растения в качестве личной особенности (Аля возможность съесть яблоко за один укус, или сделать из тыквы шлем) максимум специально увеличен, это Cherry Bomb с 125u и Omega Weed c 420u. Причём у нас максимум на вишня бомбе не изменён! Он так и остался 125, а вот на всём остальном сильно понижен, особенно обидно за омега коноплю, которая даже половину своих же веществ не вмещает. 
Баг считаю очень сильным, полностью ломающим потенциал ботаники, так как по логике, растения должны не только свои вещества вмещать, но ещё и иметь свободное место для вставки через модификации, а на данный момент не то что модифицировать бессмысленно, так чистые растения не работают так как им надо.
Исправляется поставкой максимума веществ основываясь на которые и создавались растения - 100u (Омега конопля с вишне бомбой должны иметь особую фишку на дополнительно увеличенный максимум)

### Операционная система

Windows 10

### Версия клиента

514.1561

### Название сервера

MAIN

### Примерное время и дата

-09.08.2021

**Comment by botka4aet** [comment]
Это поправимо.
Не понял только причину повышенной вместимости конопли и вишни

**Comment by GlassOil** [comment]
У вишни сам не понимаю, ведь на данный момент её сумма меньше 100u, но на тг и у нас её максимум установлен на 125u, а в коде остался комментарий свидетельствующий о повышении данного максимума "что бы вместился весь порох". Просто моя теория, что раньше в ней было либо ещё одно вещество, либо пороха было банально больше, но в одном из патчей поменяли, а максимум оставили специально в качестве особенности растения или просто забыли вернуть его.
Насчёт конопли, дело в том, что она содержит в себе 18 веществ по 5%, это 108u в сумме, а значит, что ей и 100u максимума не хватит. Вот и была добавлена ей особенность и отсылка на 4:20, но если честно, если сохранять эту отсылку то 420u в одном растении как-то многовато... Хоть количество требуемых укусов для съедания и зависит от прямого количества веществ в растении, а значит что бы передать все её вещества придётся делать МНОГО укусов, но всё же как-то... Но тут я считаю чисто вопрос на усмотрение администрации, поставить ей ~150u в максимум, или же сохранить отсылку

**Comment by botka4aet** [comment]
Тут есть несколько моментов
1) Есть ген, который увеличивает вместимость растений в два раза(как раз получается сотня)
2) Наверное растение должно заполняться реагентами равномерно.
К примеру если 75% вещества А и 75% вещества Б, то на выходе должно получиться 50 на 50.
А не как сейчас 75% А и 25% Б.

По поводу 50 - можно изменить и на 100, но тогда с геном можно будет 200 взрывчатого создать.

**Comment by GlassOil** [comment]
1) Да этот ген существует, но в первую очередь он предназначен для добавления дополнительного свободного пространства в растение, что бы помимо его веществ можно было добавить ещё и свои. А сейчас ситуация, что этот эксклюзивный ген (он всего в одном растении встречается) необходимо добавлять просто что бы цветок работал так как и было запланировано ему изначально, а места под доп вещества уже и не остаётся, только если вырезать имеющие, а это всё же не очень правильно и опускает продвинутую ботанику просто в мусорку.
2) Должно конечно, но вся механика наполненности растений работает по другому. Да там вещества указаны как бы в %, но на деле нет, если указанно что в растении 70% пороха, то при максимальной потенции (другие значения нет смысла рассматривать) в нём всегда будет 71u. Изменение расчёта наполненности может потребовать переработки вообще всей ботаники, по этому как по мне проще не выдумывать золотую курицу и дать растениям работать так как они изначально запланированы.
И нет, механики манипуляций с % нету, а значит будь в растении максимум хоть 100, хоть 1000 из 71u пороха в нём больше не сделаешь. Нельзя изменить % или вставить второй раз этот же порох, всегда будет 71u, просто при наличии пространства можно будет вставить помимо пороха ещё что-то, собственно и исполняя основную идею продвинутой ботаники с множественными но малыми концентрациями веществ, ведь в основном все вещества в мелкий концентрация, аля потассиум 11u, вода 21u. Из этого не сделаешь бомбу в помидоре взрывающую пол станции.
