### ISSUE TITLE
Добавить Chemistry Bag в RnD

### ISSUE THREAD

**Issue by Bizzonium** [ss220-space/Paradise#27]
![image](https://user-images.githubusercontent.com/8555356/120656777-950c2a00-c48c-11eb-9293-08383b9fe0f2.png)

**Comment by MorgoWizard** [comment]
@VasilevAY, на Дельте есть в РнД этот ранец. Думаю более не актуально
![image](https://user-images.githubusercontent.com/84981163/185125229-f4434fde-d420-41a8-8dc3-b56860d7d19c.png)

**Comment by VasilevAY** [comment]
> @VasilevAY, на Дельте есть в РнД этот ранец. Думаю более не актуально ![image](https://user-images.githubusercontent.com/84981163/185125229-f4434fde-d420-41a8-8dc3-b56860d7d19c.png)

Принято, закрываю

**Comment by VasilevAY** [comment]
> @VasilevAY, на Дельте есть в РнД этот ранец. Думаю более не актуально ![image](https://user-images.githubusercontent.com/84981163/185125229-f4434fde-d420-41a8-8dc3-b56860d7d19c.png)

Если еще ПР найдешь, когда он был добавлен - вообще будет красиво

**Comment by Den109G** [comment]
Надеюсь не мешаю. Вот, v1.5.
https://github.com/ss220-space/Paradise/pull/243
