### ISSUE TITLE
Feat:  Позволить использовать дефибриллятор вместе с Rod of Asclepius

### ISSUE THREAD

**Issue by Elisei24** [ss220-space/Paradise#271]
### Проблема

При активации Asclepius Rod одна рука становится занятой всегда, что логично
Однако новоиспеченный медик теряет возможность как-либо использовать дефибриллятор, что идёт вообще в разрез с концепцией посоха. Тот, кто призван лечить, а не вредить, банально не может реанимировать.

### Решение

Сделать возможным использование дефиба из одной руки, при условии, что в другой находится Rod of Asclepius.

### Плюсы

Канонично, логично

### Минусы

Не обнаружено

**Comment by Elisei24** [comment]
Не в пределах экрана, а на соседних тайлах. 

> ммммммм Хуита
> 
> Весь смысл посоха в пассивном лечении вокруг. Всех. В пределах экрана.
> Если единственный медик долбан, и решил принести клятву посоху, принесённому с лаваленда, то в чём проблема?
> Так сказать, кто ему доктор кекВ
> 
> Бтв, на рукоятях дефибриллятора есть кнопки. Где ты логику увидел, что с прилипшим к руке посохом ты должен мочь дефибриллировать...

**Comment by pahanya** [comment]
Лучше уже пофиксить, что при ампутации руки с посохом он начинает дюпаться. А так, 1 рука это вполне логичный минус этого посоха.

**Comment by Elisei24** [comment]
Пусть тогда и оперировать запрещает, ведь одной рукой нельзя.
Все прекрасно понимают, что это просто недоработка механик, которая никем не предполагалась, но всё-равно против

> Лучше уже пофиксить, что при ампутации руки с посохом он начинает дюпаться. А так, 1 рука это вполне логичный минус этого посоха.

**Comment by Elisei24** [comment]
> > Пусть тогда и оперировать запрещает, ведь одной рукой нельзя.
> > Все прекрасно понимают, что это просто недоработка механик, которая никем не предполагалась, но всё-равно против
> > > Лучше уже пофиксить, что при ампутации руки с посохом он начинает дюпаться. А так, 1 рука это вполне логичный минус этого посоха.
> 
> Нет. Один ты.
> 
> Скальпель одной рукой держать не можешь?
> 
> Чему я конечно удивляюсь в прделожке

По твоему оперируют одной рукой? Отличное предположение

**Comment by hnappinn** [comment]
> ммммммм Хуита
> 
> Весь смысл посоха в пассивном лечении вокруг. Всех. В пределах экрана.
> Если единственный медик долбан, и решил принести клятву посоху, принесённому с лаваленда, то в чём проблема?
> Так сказать, кто ему доктор кекВ
> 
> Бтв, на рукоятях дефибриллятора есть кнопки. Где ты логику увидел, что с прилипшим к руке посохом ты должен мочь дефибриллировать...

Вообще ничто не мешает поставить один электрод на тело, и вторым нажать на активацию разряда ( мне кажется не обязательно кнопки надо нажимать на обеих электродах или это можно настроить в самом дефибрилляторе). А по логике парадайса, ручной дифиб же работает в одной руке

**Comment by hnappinn** [comment]
> Пусть тогда и оперировать запрещает, ведь одной рукой нельзя.
> Все прекрасно понимают, что это просто недоработка механик, которая никем не предполагалась, но всё-равно против
> 
> > Лучше уже пофиксить, что при ампутации руки с посохом он начинает дюпаться. А так, 1 рука это вполне логичный минус этого посоха.

Как раз таки наоборот. Один из главных плюсов посоха был мультитаск в операциях, но его сделали доступным для всех

**Comment by Elisei24** [comment]
Плюсую. Учитывая и главный дебафф посоха. Не то что бить и стрелять нельзя, все предметы больше маленького персонаж вместо броска "gently puts on the ground"

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184357319-82e9c61a-dbbd-492b-8713-2eab55012a71.png)
