### ISSUE TITLE
ЕОРГу - ЕОРД

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#272]
### Проблема

Не так давно, ЕОРГ (Резня после шаттла) была запрещена, как вы это знаете. Однако некоторые _альтернативноРПшные_ игроки не совсем рады такому решению, да и обновлённое ЦК ещё не успело пройти проверку. Как следствие - череда банов за ДМ после гринтекста и анархия на ЦК после шаттла.

### Решение

Однако, есть решение. ЕОРД - Режим после гринтекста, который регулярно практикуется на СМах (Ввиду отсуствия шаттла впринципе). Суть режима - тотальная резня с бесконечным респавном и пушечками. Каждый игрок при спавне получает экипировку какой-либо фракции (В нашем случае - ОБР, ТСФ, Синдиката, СССП и других гендеров), всего с двумя задачами - выжить и убить всё живое. Респавн у режима, повторюсь, бесконечный (OOC>EORD Respawn), и возможен только после гринтекста. А это значит что абсолютно каждый игрок сможет в нём поучавствовать вплоть до окончания раунда.
Что мы получим в итоге:
1. Спокойное и тихое ЦК, где экипаж отдыхает и пьёт чай после долгой смены.
2. РЕЗНЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯ! (К слову, карту придётся делать отдельно).

### Плюсы

* Меньше анархичности на ЦК.
* Больше веселья гостам.
* Место, где все смогут вывести пар путём тотальной аннигиляции всего живого.
* Меньше банов за ЕОРГ.

### Минусы

* Это будет очень сильно нагружать сервер, в момент работы ЕОРДа (Потому что сотни тел одновременно стреляются и умирают, и ещё сотня уже лежит на земле сложив руки на живот, и ещё пару сотен на подходе) 
* Код? Маппинг? Ну... С кодом особо проблем не будет, нужно лишь подвести его под нынешний чтобы он нормально работал. А с маппингом так вообще всё легче, карта не должна быть сложной, главное КСерской.

**Comment by hnappinn** [comment]
Я ОБОЖАЮ ЭТОТ РЕЖИМ. РЕЗНЯЯЯЯЯЯЯ. А тот кто хочет без ДМа, просто не будет туда телепортироваться. Все довольны

**Comment by Danefalt** [comment]
> Я ОБОЖАЮ ЭТОТ РЕЖИМ. РЕЗНЯЯЯЯЯЯЯ. А тот кто хочет без ДМа, просто не будет туда телепортироваться. Все довольны

Галочку в книге отложений поставь сначала KEKW

**Comment by Qwadrob** [comment]
Лучшее решение проблемы

**Comment by LoveTrapov** [comment]
Один минус перевешивает все плюсы, и так фризы каждые 20 секунд, куда ещё то нагружать?

**Comment by Slisenz** [comment]
1. За
2. Резня

**Comment by Danefalt** [comment]
> Один минус перевешивает все плюсы, и так фризы каждые 20 секунд, куда ещё то нагружать?

Нужно смотреть по СМам. Бей и так очень нестабильный билд, и очень лагучий, но ЕОРД там живёт. Так что нужно надеяться что и этот билд выдержит.

**Comment by hnappinn** [comment]
> Один минус перевешивает все плюсы, и так фризы каждые 20 секунд, куда ещё то нагружать?

Ну возможные лаги когда осталось 1-2 минуты до конца раунда, не так уж и плохо. Но я почти полностью уверен что лагов не будет

**Comment by DetectiveEnotsky** [comment]
Лаги будут. Change my mind. Мost Based, кто-то решит сделать плазмафлуд или бахнуть большую бабахалку, а это атмос. Атмос перегрузит сервер, возможно сломается и возможно повиснет тикер, из-за чего проджектайлы повиснут в воздухе и никаких пиу пиу.

**Comment by Danefalt** [comment]
> Лаги будут. Change my mind. Мost Based, кто-то решит сделать плазмафлуд или бахнуть большую бабахалку, а это атмос. Атмос перегрузит сервер, возможно сломается и возможно повиснет тикер, из-за чего проджектайлы повиснут в воздухе и никаких пиу пиу.

Там нельзя сделать плазмафлуд или бухнуть большую бабахалку. Их просто нельзя сделать. Плазмафлуда не будет, потому что там рабочего атмоса вообще не будет, как и на всём z2, а сделать большую бабахалку ты не то что не успеешь, так тебе ещё и негде. Тебя просто кидают в пустое поле с пушкой и говорят "не здохни".

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184357518-7a8020e0-9c7d-4298-8409-6823bc565c88.png)
