### ISSUE TITLE
Перестройка части Мед отдела

### ISSUE THREAD

**Issue by Bolmorr** [ss220-space/Paradise#274]
### Проблема

Слишком много беготни врачам и куча лишнего народу в отделе.

### Решение

1) Мед отдел https://sun4-10.userapi.com/impg/kJmnJAg7W5TTXxkt9QkpI4a0_xw_JQa2EyJNkA/VIYeUai0yCE.jpg?size=480x480&quality=96&sign=63c497a2c27e1fa38122fd75b7fec748&type=album](url)
1.1) Мед отдел https://sun9-43.userapi.com/impg/UIVseSm8LnKNJ9C6yKcozfoG_Sw1uZpBHhJelQ/jYmHs2JPuSE.jpg?size=480x480&quality=96&sign=9649fe2cae75ab65eb94d3d9ddd5c56c&type=album(url)
2) Комната клонирования https://sun9-11.userapi.com/impg/8NV9xnvgJXoWgprdwdaVcsKs9_iDdwZ67yAJqA/NUyTpCGKNMU.jpg?size=480x480&quality=96&sign=335f6b1e9e7b3dd68cfe001dde7ac307&type=album(url)
2.1) Комната клонирования https://sun9-80.userapi.com/impg/I0JnGkrl-79JIhxYUq1nKBUzxk6VHf_qDTz8ig/tNOFPoX4LY4.jpg?size=480x480&quality=96&sign=db5ac0832a74fd4d271d39106702d40b&type=album(url)
3) Ящики с кровью и запасные каталки https://sun9-43.userapi.com/impg/8dJ2vvYhF-D5QRuh7JN3qx0ZyjYKbfURoYwz6A/kUcA-vBszjg.jpg?size=222x284&quality=96&sign=57f75665800857f3cce0aacf2b52cf95&type=album(url)
----------------------------
Обновил планировку и расставил возможные места для персонала:
1) https://sun9-13.userapi.com/impg/OMbpzanNiGMW-IrSEaBiRf9Y9EoOfKtzF0Khlg/vqK7Le40TFo.jpg?size=480x480&quality=96&sign=18d30230f3c9e467818932249983e147&type=album(url)
2) https://sun9-82.userapi.com/impg/VWN3qUGS6xNxiPADgYtQiWJVMTb62Oq5UtXoTw/0y_J9UZF9wo.jpg?size=480x480&quality=96&sign=b53edbaf930210348681470a773c4f84&type=album(url)
Добавил пол и разметки:
 https://sun9-43.userapi.com/impg/ITDFxqKSHeaiT7r77iA0l7-RnUqkrDprg-xdcQ/GutrhhmSt8E.jpg?size=480x480&quality=96&sign=a156afbd098b9fec911aa85d37dde069&type=album(url)
### Плюсы

Относительно изолированный и безопасный мед отдел, с лишней преградой от любой угрозы. 6 рабочих мест для врачей с полным доступом к оборудованию и припасам. Теперь не вся станция знает что ты клон.

### Минусы

**Comment by LoveTrapov** [comment]
Кстати по поводу клонёрки идея хорошая, её припрятать от посторонних глаз, куда ни будь к вирусологии например

**Comment by Danefalt** [comment]
Жди таума. Лучше бы это вообще кинуть в предложения по дельте в дискорде, но да ладно.

**Comment by Bolmorr** [comment]
Да я думал тоже кинуть, но там же больше баги и не большие фиксы

**Comment by Elisei24** [comment]
Неплохо. Надоедает этот хаос в холле медбэея, да и бегать туда-сюда с трупом надо, от сканера к слиперу, от слипера к химику, от химика к крио.
Наверняка можно придумать планировку и получше, но мне предложить нечего

**Comment by Daymonchemist** [comment]
1. В целом за, "но"...
2. Идея хорошая, здравая. Однако к твоему предложению у меня парочка вопросов

- Зачем эти 2 рукава у "рабочей" части? Они не особо используются людьми, а просто убирают площадь.
- Существующая сейчас пропорция сканеров/слиперов более адекватна, чем 1 к 1, потому что сканер используется намного быстрее, а также в твоем варианте уменьшается свободная площадь, что в условиях толпы фатально. 
- Вспомнив о возможности аврала - стена из стекла уничтожит возможную проходимость по смотровой.
- Столы в "общей" части - хорошо, но зачем на них общедоступные аптечки? Помести их как раз в "рабочую" зону

Идея классная - регулировать как-то поток людей, чтобы они были более систематизированы. Но тут нужно сильно додумывать нюансы самой работы

**Comment by Bolmorr** [comment]
1) Рукава для быстрого прохода без толкучки в внутреннюю зону, и собирания  народа ближе к центру.
2) При такой раскладке есть место для 6 человек с полным доступом к слиперу\сканеру\дефибу\раздатчику меда во внутренней зоне при этом для всех есть проход в остальные части меда.
3) Не понял про стекло, но оно же роняет только тех кого тащат?
4) Эти аптечки есть и сейчас в общем доступе, правда на полках возле химии.

**Comment by hnappinn** [comment]
Слишком много сканеров. 2 более чем достаточно. Лучше убрать 2 лишних сканера и поставить вместо них капельница с каталкой

**Comment by Bolmorr** [comment]
Ну да, можно вместо 2-х правых сканеров столы как раз влезут каталки/с коробками капельниц

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184358966-cf563060-4c77-4923-b91f-7f97097cf6e6.png)
