### ISSUE TITLE
Bug: Из красного граба никак нельзя освободиться самостоятельно.

### ISSUE THREAD

**Issue by HolyGunCheck** [ss220-space/Paradise#275]
### Ckey

XyJluraH

### Описание бага

Если тебя схватили в красный граб, то Resist уже работать не будет. Единственное, что можно сделать, так это взаимодействовать через Interact с тем, кто тебя схватил. (Можно, конечно, попытаться забить противника подзатыльниками, но это вряд ли сработает до того, как он придушит тебя окончательно.)

### Шаги воспроизведения

Просто быть схваченным в красный граб. При этом неважно застанен/лежишь ты или нет.

### Ожидаемое поведение

Используя "resist" выбраться из красного граба. Конечно, для этого придется прожать его неоднократно, в отличии от желтого и синего граба.

### Дополнительная информация

Первый раз баг случился со мной на Мейне. Повторил его уже на локальном сервере, дабы убедиться, что это точно баг. (Версия билда свежая)

### Операционная система

Windows 7 - Максимальная

### Версия клиента

5.0 Public. Version 513.1542

### Название сервера

MAIN

### Примерное время и дата

Начало августа этого года, точнее сказать не могу.

**Comment by Bolmorr** [comment]
Так в этом же и смысл, если уже до красного дошло то "текать с городу уже поздно"

**Comment by Jordanstolethepreciousslam** [comment]
Это не баг. При переходе в красный граб на схваченного накладывается стан в 3 тика.(4.5 секунды). Во время стана прожимать резист нельзя. Если переждать стан то из красного граба можно выбратся. Хотя в игре захватывающий обычно за это время дождется удушающего и апгрейднет в мигающий граб.

**Comment by Honker9999999** [comment]
Там 5% шанс на то что сбежит. Вполне себе логично, нет?

**Comment by Sykybekk** [comment]
Это фича вообще-то

**Comment by Honker9999999** [comment]
Вырезка из гита оффов: 
			if(GRAB_NECK)
				if(prob(5))
					visible_message("<span class='danger'>[src] has broken free of [G.assailant]'s headlock!</span>")
					qdel(G)
При этом у нас такой-же код, и его не меняли. Так что либо у ОПа что-то сломалось и он был в стане, либо поломка состоит где-то хуй знает где в караганде. Так что нет,



> Это фича вообще-то

Не фича.

**Comment by Danefalt** [comment]
Это не является багом, а механикой игры. Так что увы, но предложка уходит в небытие.

**Comment by Danefalt** [comment]
Или у меня шиза... Пофиг короче KEKW

**Comment by Danefalt** [comment]
Ага... Всё-таки не баг:

> if(prob(5))

Эта строка - шанс того, что выйти всё-таки выйдет, т.е. - 5% на выход, а это очень мало, как вы понимаете. Так что не баг, а механика игры.

**Comment by Honker9999999** [comment]
> Ага... Всё-таки не баг:
> 
> > if(prob(5))
> 
> Эта строка - шанс того, что выйти всё-таки выйдет, т.е. - 5% на выход, а это очень мало, как вы понимаете. Так что не баг, а механика игры.

Внимательно прочитай блять. У него ВООБЩЕ не было резиста в красном. Если бы не прокнуло - оно бы написало. Там свое сообщение, а по словам ОПа там пусто. Таблетки прими.

**Comment by Danefalt** [comment]
Вообщем, посмотрим как там.

**Comment by valldemar2017** [comment]
Уже исправлено, закрывайте
