### ISSUE TITLE
Bug: Сломанный РПЕД

### ISSUE THREAD

**Issue by Frozored** [ss220-space/Paradise#276]
### Ckey

Ditzy Shuudan

### Описание бага

После того как батарейки добавили в перечень компонентов для РПЕДА(обновление от 06.08.2021), он перестал заменять запчасти машин с первого раза (многие, наверно, заметили, что учёные стали по кучу раз стрелять лучом по одному и тому же условному пылесосу)  

### Шаги воспроизведения

1. Заправить БРПЕД компонентами разных тиров (micro-manipulator/femto-manipulator, advanced matter bin/bluespace matter bin)
2. Попытаться улучшить химический раздатчик или любую другую машину

### Ожидаемое поведение

Все компоненты заменяются с первого раза

### Операционная система

Windows 10

### Версия клиента

Version 513.1542

### Название сервера

MAIN

### Примерное время и дата

Начиная с  06.08.2021

**Comment by Den109G** [comment]
Я добавлю скрин, что это и вправду мешает.
![image](https://user-images.githubusercontent.com/87372121/129464466-f9c8481e-2d23-4277-9bd9-79d16f707d33.png)
В РПЕДе есть фемто манипуляторы, но из-за того, что также есть микро-манипулятор, РПЕД отказывается заменять детали ниже по рангу, заменяя теми же.

**Comment by Frozored** [comment]
Закрываю сабж, баг исправили
