### ISSUE TITLE
 ПИИ и модели СБшных ботов.

### ISSUE THREAD

**Issue by Zombara** [ss220-space/Paradise#278]
### Ckey

Zombara

### Описание бага

Нельзя засунуть ПИИ в СБшных Ботов. Таких как Бипкси, ED-209.

### Шаги воспроизведения

Пытаться запихнуть ПИИ В сбшные модели Бота.

### Ожидаемое поведение

Оно должно было засунутся в ПИИ

### Операционная система

10Ка.

### Версия клиента

5.0 Public. Version 513.1542

### Название сервера

MAIN

### Примерное время и дата

17:30

**Comment by Zigamus** [comment]
Не баг, поставлено специальное ограничение для пии, потому что пии верны своему хозяину, а дроны - станции.

**Comment by Zombara** [comment]
Тогда почему можность стать Мед ботом или уборочным ботом и даже Генералом Гифкси?

**Comment by MarshallPulse** [comment]
Было бы логично, если бы ПИИ можно было вставить, но только после открытия СБшным доступом. И чтобы это в панельке хоть отображалось.

**Comment by Zigamus** [comment]
> Тогда почему можность стать Мед ботом или уборочным ботом и даже Генералом Гифкси?

Потому что медбот и уборочный бот не могут бить дубинкой.

**Comment by Zigamus** [comment]
А Грифски вообще мем.

**Comment by Den109G** [comment]
> пии верны своему хозяину, а дроны - станции.

Так после того, как ставишь пИИшку в ботов, то у пИИ появляются законы, которые зависят от бота. Конечно же, дополнительные директивы переносятся вместе с этим, но там после основных законов, как с фриформом.

**Comment by Zombara** [comment]
Ну так: Что там решают по поводу этого бага?

**Comment by Den109G** [comment]
Это не баг.

**Comment by Zigamus** [comment]
Ладно, я повторю еще раз, это не баг.
![image](https://user-images.githubusercontent.com/59314481/129661842-420f451a-a857-4a18-a09a-dddf4806672a.png)
