### ISSUE TITLE
Feat: Реюзабл пушечек

### ISSUE THREAD

**Issue by Honker9999999** [ss220-space/Paradise#279]
### Проблема

На текущий момент есть дохрена оружия, автоматического и не очень, что просто не используется в игре, хоть и есть в билде. Почему бы и не исправить это? P.S. Ниже я разберу каждую из этих пушек и укажу где примерно они могут быть, НО: Я не беру откровенно грифозные и педальные пушки по типу Гироджета, а именно обычные пухи которые не используются, а могут.

### Решение

Начнем с лайтового:
**Kinetic speargun**(/obj/item/gun/projectile/automatic/speargun)
Гарпун. Использует свой тип боеприпаса под названием "Magnetic Spear". Урон за выстрел - 30. Само копье не пропадает и может быть использовано для дальнейших убийств. Урон в мили - 10 урона. У копья нет урона(планируется исправление).
Спрайты - 
![image](https://user-images.githubusercontent.com/74865061/129607370-98162d4e-9562-4f3d-8bbd-475c661dc562.png)
Известные проблемы: 
1. При поинт-бланк атаке стрела пропадает.
2. У самого копья(Spear) нет урона.

Вариант использования: Набор во взломанном/обычном карго "Carp Hunter Kit". Состоит из некоего скафандра, этот гарпун+2-3 запасных гарпуна. Цена - 80-100 кредитов.

**Nanotrasen Saber SMG**(/obj/item/gun/projectile/automatic/proto)
Знаменитый привет от старых билдов. Делался в протолате, сейчас не достать никак. Был заменен ВТшкой. В обойме - 21 патрон+1 в патроннике. Можно закрепить глушак. Два режима стрельбы - очередь по 3 и полу-автомат. Кулдаун между стрельбой очередями достаточно маленький. Урон за пулю - 20. По аналогии с ВТ имеет три доп. типа боеприпасов: 
1. Огненный. Урон понижен до 10, поджигает цель при попадании.
2. Токсины. Брут урон понижен до 0. Урон токсинами в 15. Можно изменить на 5 брута и 10 токсинов.
3. Бронебойки - 17 урон, 40% игнора брони(т.е. если броня на сто - защитит на 60, если броня на 10 - защитит как 6, и так далее)
Спрайты -
![image](https://user-images.githubusercontent.com/74865061/129608928-69251bda-2e36-4db4-a1fa-65cb25e5e22b.png)
Вариант использования: Нет, не протолат ибо имба. Либо протолат, но 7-8 боевые. Дать их амбер и/или ред ЕРТ с тремя-четырьмя запасными обоймами.
Известные проблемы: 
1. Описание обоймы является "A box of ammo? There are 13 shells left!"

**'Type U3' Uzi**(obj/item/gun/projectile/automatic/mini_uzi)
Тоже самое. Наследие вырезанного режима "Gangs". Не получить, очевидно говоря. В обойму вмещается до 32 патронв+патронник. Режимы стрельбы - полуавтомат и очередь по два патрона. 15 урона. 
Спрайты - 
![image](https://user-images.githubusercontent.com/74865061/129612101-73a43e99-c368-43f9-b44a-f2bf1384d032.png)

Вариант использования: То-же карго, либо добавить ассистентам в аплинк если триторы. Так-же создать новый набор синдикека "Банда", где будет форма для банды, два таких УЗИ, патроны для них и томмиган(о нем чуть ниже)
Известные проблемы: N/A

**APG**(/obj/item/gun/projectile/automatic/ar)
Одно из немногих оружий, которые можно получить без щитспавна(формально). Продаются в автомате "Свободы"(такой только на админ тестинг корабле). В обойме - 30 патронов+патронник. 2 режима стрельбы - полуавтомат и очередь по три выстрела. Урон за выстрел - 35. Перезарядка между стрельбой маленькая. Урон в мили 5.
Спрайты - 
![image](https://user-images.githubusercontent.com/74865061/129612853-b0ea38d7-ea46-4327-83e8-e204749a178f.png)
Вариант использование: Добавление в аплинк нюкеров. Некий аналог калаша или М90.
Известные проблемы:
1. Нет спрайта для магазина или он проебался.

**Thompson SMG**(/obj/item/gun/projectile/automatic/tommygun)
"Передаем привет от дона...". Известная пушка. 60 патронов в обойме+патронник. Калибр .45. 20 урона брутом+65 стамине за выстрел. Полуавтомат и стрельба очередями по 4 патрона. Орудие не борьбы, не битвы, а настоящей РЕЗНИ. 
Спрайты -
![image](https://user-images.githubusercontent.com/74865061/129613497-89b2fcaf-1c0f-4451-a9c4-830ebfa91655.png)

Вариант использование: Набор генга(см. выше), может нюка(но имба)
Известные проблемы:
1. Имба. Урон плюс стамина... Адское оружие

Не совсем уже пушка, но можно взять:
Mental Focus(/obj/item/gun/magic/staff/focus)
Магический посох, стреляющий гига-снаряди. При попадании в цель СИЛЬНО(очень) отталкивают её. Отталкивает очень много предметов и живых существ. 6 зарядов.
Спрайты - 
![image](https://user-images.githubusercontent.com/74865061/129614312-f5d95a68-4a2b-47c9-bff4-94fc2c1a7de8.png)

Вариант использование: Маг. За 2 или 3 спеллпоинта. 
Известные проблемы:
1. Магбутсы не защищают, но... А должны ли?

Это не все что можно было бы добавить, но пока что хватит. 
Голосуя за - вы голосуете за каждую пушку. Если вы против определенной - напишите об этом, т.е. "Ну я за все кроме ментал фокуса, он ебать имба" и так далее. Если у вас есть свои идеи где использовать, как нерфануть или баффнуть - пишите! Код написать могу я сам, но придется ебаться с гитом ибо я слишком тупой.

### Плюсы

ПУШЕЧКИ ПУШЕЧКИ ОБОЖЕ КАК ЖЕ Я ЛЮБЛЮ ПУШЕЧКИ

### Минусы

Больше способов убивать. Больше пушечек для антагов и не только. Больше.

**Comment by Danefalt** [comment]
Нужно сразу же брать все пушки с эриса, но мы не будем, за то что вы не уважаете вульп. Спасибо за запрос.

**Comment by Danefalt** [comment]
Для АРГ прийдётся рисовать магазин... Ага...

**Comment by Honker9999999** [comment]
> Нужно сразу же брать все пушки с эриса, но мы не будем, за то что вы не уважаете вульп. Спасибо за запрос.

Какой вопрос?... Энивей, вне "Э сука билд не пизди" по сути ничего не мешает действительно спиздить пушки с эриса. Ну, и разного кода, но это уже такое(ибо открытый код на то и открытый и код что открытый код.)

**Comment by OpsCoretango** [comment]
Если проще то все торговцу ТСФ

**Comment by OpsCoretango** [comment]
Также проработать аналог Револьвера Детектива 38. ого ввиде старого доброго Кольта и разработать резиновый боеприпас, MP7 калибра 4.7 на 9мм Пистолет Пулемет уровня кода Гамма в отношении нюк сквада.

**Comment by Honker9999999** [comment]
> Если проще то все торговцу ТСФ

Тогда смысла особо не будет. У них и так уже есть пушка, которая только у них и нигде больше(дробовик с двойной трубой по два патрона в каждой). А эти хотелось бы что бы хоть немного были в раундах, даже если ЕРТ или триторы с нюкерами или магами. Ну и на крайняк можно добавить эти пушки магу при призыве пушек, там и по имбовее будут, хули нет?(Там уже пулемет, снайперка, ракетница и пульсач. Это уж не разрушит баланс)

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
Сейчас бы говорить про мага и баланс...

**Comment by Gnatr** [comment]
За ибо убивать красиво

**Comment by hnappinn** [comment]
Главное что я хочу, так это ВЕРНИТЕ СМГ!!!!

**Comment by VictorSocks** [comment]
1. ЗА
2. О БОЖЕ ДА, БОЛЬШЕ ПУШЕК, УБИВАТЬ УБИВАТЬ УБИВАТЬ УБИВАТЬ
Взять оружие с других билдов это хорошая идея тоже, хотябы как щитспавн
Чувствуешь запах? Это оружие, сынок. Больше ничто в мире не пахнет так.
Я люблю запах пороха поутру. Однажды мы атаковали одну станцию, двенадцать часов подряд. И когда всё закончилось, я поднялся на мостик. Там уже никого не было, даже ни одного вонючего трупа. Но запах! Вся станция была им пропитана. Это был запах… победы!

**Comment by VictorSocks** [comment]
> Нужно сразу же брать все пушки с эриса, но мы не будем, за то что вы не уважаете вульп. Спасибо за запрос.

Это хоть какая-то память о покинувшем Хаб билде, пусть память о нем будет хоть у нас в виде оружия с него, вульпы, не вульпы будут им пользоваться это неважно, главное что оно будет.

**Comment by terribaum** [comment]
Исключительное, максимальное за. Арсенал расширить всегда любо.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184357949-2fca29d3-46fb-4368-a43f-2cfd945128a9.png)
