### ISSUE TITLE
Бипкси и ED-209 для контроля ПИИ.

### ISSUE THREAD

**Issue by Zombara** [ss220-space/Paradise#281]
### Проблема

Если захочешь стать Бипкси или за ED-209 ТО Ты должен просить об этом админа.

### Решение

Сделать возможность для роботехов чтобы те могли засунуть в Бипкси или ED-209 или СБ.

### Плюсы

Новое тело с делом, бипкси будут умнее чем без контроля игрока как и ED-209, они могут легко эксплаутироваться.

### Минусы

Врагам НТ не понравится когда на них бежит Бипкси. А с далека с тайзера шмаляет по тебе ED-209.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184358002-06fd051a-5b82-465a-a6a6-97ff9703731a.png)
