### ISSUE TITLE
Feat:Текстурочка егана

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#282]
### Проблема

Стандратный еган выглядит как бревно, Учитывая что на дворе 26-ой век дизайн можно было и получше сделать. Считаю дизайн полной жизненеспособной хренью, ставшей результатом невыспавшегося спрайтера. 

### Решение

Заменить текстуру нынешнего Е-гана на текстуру с официального вики парашиза. (http://imgur.com/a/HMCrNgj) 

### Плюсы

Обычный Е-ган начнёт выглядеть так, как он, мать твою так, должно выглядеть у службы безопасности, особенно в чёрт вашу маму дери 26-ом веке. Эстетическое удовольствие от использования намного, согласитесь. 

### Минусы

Заменить одну текстурку? А, ну ещё текстурку в руке. И заменять придётся кому-то другому, потому что я не у компа до понедельника.

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
1. За
2. Выглядит православно, футуристично, таким и робаститься классно, и просто дулом вертеть. Однозначно классная идея. Надеюсь, кто-то ее воплотит

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184358820-dcdd96aa-35be-43c4-867e-34fff077bb78.png)
