### ISSUE TITLE
Feat: Козёл

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#283]
### Проблема

Козёл повара, Петя, мягко говоря не лучший питомец на станции. Этот пидрила так и норовит слететь с катушек и пойти разносить все, что видит, за что и отправляется на крюки у 95% поваров.

### Решение

Заменить козла на кота-тортика, Keeki, назвав Пирожок/Тортик.

### Плюсы

1. У повара будет нормальный питомец, а не рогатая пидрила
2. Повар всегда сможет перекусить кусочком своего котика
3. Все пончики от повара будут с посыпкой!

### Минусы

1. Меньше козлятины в рационе станции

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
1. Против
2. Мы тут общество прогрессивное, пидарасов защищаем
@администрация SS220
Пит хоть и пидрила, но родной. А Куки тогда немного обесценится. Куки есть в меню крафта и его может сделать любой пчел, которому дадут юнит теслиума и доступ к кухне

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184359183-873b6118-c5f1-4ef1-ade7-b3a4cf1977d7.png)
