### ISSUE TITLE
Bug:  Неправильные доступы на дверях в суд

### ISSUE THREAD

**Issue by Kirozet** [ss220-space/Paradise#2832]
### Ckey

Kirozet

### Описание бага

боковые двери в суд имеют требуемый доступ 63(доступ к бригу), а не 42(доступ к суду), из-за чего доступ конкретно в зал суда не позволяет попасть внутрь.
![image](https://github.com/ss220-space/Paradise/assets/96671463/38723c6e-e680-47a0-bee3-0d191c89dd90)
![image](https://github.com/ss220-space/Paradise/assets/96671463/a92bb42c-57b0-4b33-b915-aca25cb3f1c2)

### Шаги воспроизведения

Запустить дельту, открыть VV двери и посмотреть в req access.
выдать себе карту только с доступом в courtroom, чтобы точно убедиться, что она не откроет эти двери.

### Ожидаемое поведение

Дверь должна была открыться с доступом в Courtroom на id карте

### Операционная система

Windows 10

### Версия клиента

514.1589

### Название сервера

MAIN

### Примерное время и дата

11.05.2023 1:52 по МСК

**Comment by Vladisvell** [comment]
https://github.com/ss220-space/Paradise/pull/4631
