### ISSUE TITLE
Feat: HEV Suit reports

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#287]
### Проблема

На нашем билде есть такое прекрасное оружие, как доминатор с сибилом и голосовым оповещением. Круто? Круто.
Почему бы не прикрутить ко всем хардсьютам голосовую систему оповещения об уроне?

### Решение

Прилепить к хардсьютам голосовое оповещение об уровне здоровья и получении урона. Звуковые файлы можно стащить из уведомлений HEV костюма из Half-Life:
"Minor fracture detected" - 1-2 перелома
"Major fracture detected" - 3+ переломов
"Blood loss detected" - уровень крови ниже 70%
"Minor lacerations detected" - средний брут урон
"Major lacerations detected" - высокий брут урон
"Internal bleeding detected" - внутреннее кровотечение
"Warning: hazardous radiation levels detected" - урон от радиации
"Warning: hazardous chemicals detected" - урон от токсинов
"Warning: extreme heat damage detected" - урон от огня
"Warning: vital signs critical" - софт крит
"Emergency: user death imminent" - крит
Слышимость их соответственно либо только пользователю, либо в радиусе 1 тайла

### Плюсы

Позволит несколько проще отслеживать свое здоровье. Да и черт возьми, эти уведомления звучат ахуенно

### Минусы

Это надо кодить :с

**Comment by Slisenz** [comment]
Да, действительно звучит пиздато, осталось бы ещё найти кто бы это сделал :(

**Comment by botka4aet** [comment]
1. За
2. Хорошая идея. Правда кому-то(предложившему) желательно предоставить звуковые файлы, выполненные в одном стиле

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
1. За
2. Цистерну чая автору.
Если еще и найдутся энтузиаст, что это сделает - будет вообще огонь

**Comment by Racer396** [comment]
1. За
2. Атмосферно, полезно, круто. С учетом того что я фанат халфы, подобное в ССке было бы прекрасно, и в стиль вписывается, и олдскулы сводить будет.

**Comment by Racer396** [comment]
По поводу звуков, прошу - https://tcrf.net/Half-Life_(Windows)/Sounds

**Comment by AugustBebel** [comment]
Можно взять звуки из Black Mesa или второй халвы, там качество получше.

**Comment by VictorSocks** [comment]
За
"Гордону не нужно слышать это - он высококвалифицированный профессионал"

**Comment by hnappinn** [comment]
1. не совсем согласен, но идея неплохая.
2. На маринах есть такая штука ACID Harness. Я предлагаю сделать HEV Suit похожим на него, тоесть чтобы программу для костюма можно было бы настроить, и озвучку тоже (но были бы звуки с халфы). И чтобы костюм мог вводить реагенты как ACID Harness или иметь заряд брони, который будет снижать или полностью блокировать урон как в халфе, тогда от него будет хотябы какая-то польза. Плюс интересный контент для учёных.

**Comment by hnappinn** [comment]
Фишка доминатора не только в голосовом оповещении, а разных режимах и система сибил. Если сделать костюм так как ты указал, то он будет совершенно бесполезный

**Comment by VasilevAY** [comment]
![Uploading image.png…]()
