### ISSUE TITLE
Bug: нет необходимого предмета для успешной аугментации хвоста

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#288]
### Ckey

Sykybekk

### Описание бага

Мы можем провести операцию augment limb на хвост. Но мы не можем успешно завершить, так как нет предмета, который нужно вставить в хвост. Так, для аугментации груди нужен торс борга, для аугментации головы нужна голова борга и т.д. То для хвоста подобного нет, из-за чего операцию невозможно завершить успешно.

### Шаги воспроизведения

1)начать операцию на хвост augment limb
2)дойти до этапа, когда нужно вставить предмет в хвост
3)обнаружить, что подобного предмета нет

### Ожидаемое поведение

Появиться предмет для вставления в тело при аугментации хвоста; появится спрайт аугментированного хвоста.

### Операционная система

Windows 7

### Версия клиента

153.1542

### Название сервера

MAIN

### Примерное время и дата

До сих пор

**Comment by mahdias0yaebaltvoumertvuymat** [comment]
Как ты себе видишь аугментированный хвост, фуррилюб?

**Comment by pahanya** [comment]
Ну я примерно такое писал тут - https://github.com/ss220-space/Paradise/issues/273
Механических хвостов в игре нету - вот нету и аугмента.

**Comment by Honker9999999** [comment]
Для успешной - и не должно быть. Операцию закончить прижигателем+скальпелем ведь можно, так что где баг?

**Comment by Sykybekk** [comment]
> Для успешной - и не должно быть. Операцию закончить прижигателем+скальпелем ведь можно, так что где баг?

Успешной будет считаться, если истинная цель операции будет выполнена. Сейчас она выполняется?

**Comment by Honker9999999** [comment]
> Успешной будет считаться, если истинная цель операции будет выполнена. Сейчас она выполняется?
Ахуенная логика. Теперь если есть операция "Кавити имплант ремувал" - она ОБЯЗАТЕЛЬНО должна иметь возможность вытащить имплант, если его там НЕТ? Ну а фигли.
