### ISSUE TITLE
Вернуть импланты лояльности

### ISSUE THREAD

**Issue by Danefalt** [ss220-space/Paradise#290]
### Проблема

Что же, как мы все знаем, в этой игре есть всего один святой Грааль, к которому все должны стремится. Речь конечно же идёт об импланте защиты сознания. Но не кажется ли вам, что в условиях тоталитарной корпорации зла и форона, слишком мягко ставить только защиту сознания? И на такие случаи к нам приходит давно позабытое старое...

### Решение

Давным давно, когда небо было голубее, трава зеленее, а игроки сски робастнее, такого понятия как защита сознания не было, а было лишь одно простое словосочетание - имплант лояльности. Как нам всем известно, имплант защиты сознания просто не даёт искусственно перезаписывать твой мозг, личные взгляды и убеждения. Но имплант лояльности делает ровно наоборот, делая из тебя личного пёсика на поводке, принадлежащего огромной корпорации на букву "N". Он буквально стирал твоё понятие воли, заставляя тебя во всём слушаться людей, чьи погоны в корпорации более красивые. Ты забывал что есть ты, ведь есть великая корпорация, чьи идеалы ты обязан преследовать. Эдакий имплант рабского сознания, от мира голубого конгломерата. Но в те времена, имплант лояльности был у всех, кто нынче носит импланты защиты сознания. И это слегка убивает простор для РП и ситуаций, да и не логично с точки зрения атмосферы, в конце концов мало кто пойдёт в место, где любое твоё повышение могло значить для тебя обращение в рабство.

Но теперь, пришло время вернуть его к жизни, однако, уже в несколько ином виде.
Получить его можно только двумя путями - сделать в протолате и щитспавном.
Для его разработки в протолате требуется: 8 уровень био-исследований, 7-ые уровни инженерии и информации, а так же 5 боевой. Цена в ресурсах у него будет чуть больше, чем у защиты сознания.
Так же он будет сразу же со спавна у представителя корпорации, и всего ЦК. Так же под вопросом капитан и ГСБ. Простые смертные, у кого во флаге профы указано не СБ/ЦК/Главы, не смогут атаковать левее перечисленных, и обязаны во всём им подчиняться.

Касательно знаний:
* Простой экипаж - считает существование импланта простыми байками.
* Главы и СБ - уведомлены о существовании импланта, но должны хранить это в тайне.
* Учёные - считают это возможным, но в ввиду своей неосведомлённости, считают что галактика не имеет необходимых для этого технологий.

Что по поводу взаимодействия с антагами:
* Глава ревы позабудет что пару минут назад ненавидел это место и всех этих людей, и вместе пошагает в строй развивать продажи NT.
* Синдикат (агенты) так же поймут что это всё не правильно, и вообще, так нельзя, и переобуются с красного в синий. Оперативники и офицеры будут иметь перк, который поможет им сбросить эффект импланта, но об этом чуточку позже.
* Маги смогут использовать свою магическую магию чтобы защитить свой мозг от внешнего вмешательства импланта.
* Вампиры не смогут сосать кровь у игроков, а только из мартышек или других подобных животных. Так же перестанут идти против корпорации. Эффект может быть снят.
* Генокрады потеряют какой-либо интерес в выполнении своих целей, и даже могут присоединится к СБшному строю. Эффект может быть снят.
* Культисты - "Что значит "Это должно нас подчинить вам"?".
* Абдукторы - какого-либо эффекта не будет вообще, потому что у них слишком глобальный разум.
* Тенелинг - без эффекта.

А теперь по поводу сброса эффекта:
Определённые антаги смогут самостоятельно заблочить эффект импланта, и будет происходить это так:
Появляется определённая кнопка, что-то вроде специального резиста. Её нужно использовать три раза. Каждое использование занимает минуту, а кулдаун между использованиями - две. Во время использования резиста, игрок не сможет говорить, ходить или использовать что-либо (однако повторное нажатие останавливает процесс). Во время процесса игрок будет трестись, кричать и плакать, а так же игра будет спамить что у тебя болит голова (При этом успешный резист будет наносить урон мозгу). Все удачные использования могут быть сброшены обычными наркотиками, к примеру ЛСД (Но регулировать приём без резких причин всё-таки придётся).

Дополнительно:
* Имплант вкалывается как и трекер/химический/защита сознания.
* На ИЛС СБ он будет отображаться так же, как и защита сознания, но не зелёным, а светло-голубым цветом.

### Плюсы

* Больший простор для РП.
* Тоталитарность.
* Атмосферность.
* Несколько более особенные отношения с корпорацией, у имплантированных.
* Больше механа относительно антагов.

### Минусы

* ыыы антагав душат((9(

**Comment by Zombara** [comment]
Я за. Пусть какую нибудь идею уже реализуют да и плюс. Я несколько раз был с такой имплантом когда только зашел на парадайз.

**Comment by DoctorSkullka** [comment]
Куда вернуть? У нас их не было никогда.

**Comment by jtmiad** [comment]
Мне кажется небольшая несостыковка есть по поводу ученых. 

У нас не утверждено знают ли ученые о том что "можно" будет создать на протолате после изучения технологий, но обычно, ученые заранее знают весь список того что будет исследовано в будущем, т.е. они заранее будут знать об импланте лояльности. 

Тут надо либо момент с учеными поменять (они знают но подписали бумажку о неразглашении), либо система авторизации/взлом протолата для доступа к ним (второй вариант легче, ибо функционал уже есть).

**Comment by Zigamus** [comment]
Иногда происходит такое, что ты не можешь прокомментировать ситуацию не из-за отсутствия мыслей, а из-за их переполнения, настолько много чего не так, что легче для всех написать не полную отрицательную рецензию, а просто сказать "ну и хуйню же ты придумал".

**Comment by 1heShogun** [comment]
ыыы антагав душат((9(

**Comment by Danefalt** [comment]
> Куда вернуть? У нас их не было никогда.

Ну так добавим до принятия предложки, удалим, а потом вернём KEKW

**Comment by zombie288** [comment]
Против
Раньше было лучше, но импланты лояльности это не та вещь, которую нужно вернуть. Как раз таки отсутствие имплантов лояльности даёт больший простор для отыгрыша главам и СБ.

**Comment by Danefalt** [comment]
> Против
> Раньше было лучше, но импланты лояльности это не та вещь, которую нужно вернуть. Как раз таки отсутствие имплантов лояльности даёт больший простор для отыгрыша главам и СБ.

Я не предлагаю поставить его вместо защиты сознания, а на станции он фактически будет только в 1 экземпляре. В РНД же сделать его будет трудно, ибо требуется исследование 8 уровня.

**Comment by DoctorSkullka** [comment]
> Против
> Раньше было лучше, но импланты лояльности это не та вещь, которую нужно вернуть. Как раз таки отсутствие имплантов лояльности даёт больший простор для отыгрыша главам и СБ.

Не было никакого раньше, у автора шиза

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184359246-fc92edf9-4904-4fbd-8e1e-69eda443481c.png)
