### ISSUE TITLE
Feat: улучшение и доработка пАИ

### ISSUE THREAD

**Issue by NotInkHuman** [ss220-space/Paradise#292]
### **Недоработки:**
- При вытаскивании кабеля Door Jack, пАИ не может его поднять либо другой игрок с руками не может его засунуть обратно.
- Мессенджер не идёт в комплекте с системой, но есть возможность отправлять сообщения на ПДА через вкладку AI IM.

### **Решение недоработок:**
- Убрать опцию слать сообщения через AI IM и выдать мессенджер со старта
- Дать возможность втянуть кабель обратно, либо автоматически втягивать его если паи дальше от кабеля на 1 тайл

### **Идеи для функционала:**
- Возможность вставлять картриджи для ПДА в пАИ (до 2 картриджей, их нельзя вытащить, если программа с картриджа уже установлена через меню пАИ, картирдж можно будет вытащить, картриджные аналоги программ пАИ требуют меньше памяти)
- Расширения памяти пАИ за счёт 5 блюспейс кристаллов в обмен на шасси (вес паи значительно больше, шасси его уже не потянут, в карманы не влезет)
- Синтезатор за 10 памяти
- Возможность встроить аплинк с 0 телекристалами за 10 памяти (Использовать устройство с открытым аплинком на пАИ для того что бы установить аплинк, если не достаточно памяти, аплинк не установится)
- Возможность выдачи доступа к дополнительным каналам связи если наушник/и хоста имеет/ют доступ к каналу/ам
- Доступ к камерам за 55 памяти
- пАИ теперь можно прикреплять к девайсам (Отвёрткой перевести в attach), пАИ так же может изменять их конфигурацию (вкл/выкл, радиус действия проксимити сенсора и т.д.)

### Плюсы

- За пАИ теперь интереснее играть
- У антагов появилась причина брать пАИ
- У неантагов появилось больше причин брать пАИ

### Минусы

- За пАИ теперь немного сложнее играть, ну, прям самую малость

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184359325-d6535b57-569b-4344-bcd5-cc890dd2cbc2.png)
