### ISSUE TITLE
Bug: Ловушка Floor Painter'а.

### ISSUE THREAD

**Issue by Den109G** [ss220-space/Paradise#298]
### Ckey

Den10901

### Описание бага

При активации Floor Painter'а игра фризится, а после в выборе открывается ВСЕ полы, что доступны. Не следует радоваться, поскольку через секунду другую у игрока умирает клиент.
_Скорее всего, лом слишком полезен для боргов, что ломает игру, но это не точно._

### Шаги воспроизведения

1.1: Стать боргом и выбрать инженерный модуль.
1.2: Найти Floor Painter за человека.
2: Взять в руки Floor Painter и активировать его в руке.
3: Наслаждаться этой картиной:
![image](https://user-images.githubusercontent.com/87372121/130806047-845bbe6f-a9d4-444f-b879-e536e807815c.png)

### Ожидаемое поведение

Как минимум - не должно вылетать.
Как максимум - там будет ограниченный список покрасок.

### Дополнительная информация

Первая информация насчёт этого бага сказали тут: https://discord.com/channels/617003227182792704/756409070721957918/880084398551220315
На локалке тоже самое происходит.

### Операционная система

Windows 10

### Версия клиента

513.1542

### Название сервера

WL

### Примерное время и дата

17:00 25.08.2021 (Примерно в это время, была скачена, поставлена локалка и проверен этот баг)

**Comment by DayBreakerBrony** [comment]
полностью согласен, вчера пытался покрасить пол вокруг шлюза,который закрывал портал на базу синдиката, но выдало все текстуры а потом вылетало.

**Comment by Den109G** [comment]
Так, файл с полами откатили и пеинтер починился, закрываю баг.
