### ISSUE TITLE
Сделать фритюр великим снова

### ISSUE THREAD

**Issue by AugustBebel** [ss220-space/Paradise#301]
### Проблема

На многих серверах обжаривать во фритюре можно практически что угодно, но на парашизе почему-то нельзя. 

### Решение

Дать возможность обжаривать во фритюре практически все предметы в игре. Чтобы не кидали вещи случайно сделать окошко «Да/Нет», перетаскивание или другую форму подтверждения что хотите по факту уничтожить предмет.

### Плюсы

Больше веселья поварам. Спиздил палку абдуктора и на его глазах кинул во фритюр.

### Минусы

Возможно это сложно закодить, особенно если на парашизе код просто не отключён или его тяжело спиз… скопировать с других серверов.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184359883-f81ea14d-956f-4c67-b0d9-161edeae3ed0.png)
