### ISSUE TITLE
Bug: КПБ боевой модуль - изменение работы дефибриллятора.

### ISSUE THREAD

**Issue by Kozaku072** [ss220-space/Paradise#302]
### Ckey

Kozaku072

### Описание бага

Не работает дефибриллятор, а именно третья комбинация боевого модуля IPC, при условии его загруженности или даже отсутствия.
![image](https://user-images.githubusercontent.com/87883057/131209041-d964f3ff-02f5-4f6e-9050-95c1ebf97b1d.png)

### Шаги воспроизведения

1. Загрузить IPC combat upgrade.
2. Попытаться провести третью комбинацию боевого искусства.
3. Ничего не происходит при последнем интенте хелпа.

### Ожидаемое поведение

1. Загрузить IPC combat upgrade.
2. Провести рабочий метод дефибрилляции.
3. Существо живо.

### Дополнительная информация

В общее, чтобы механика лучше работала, мне кажется лучше сделать доступ к дефибриллятору по другому.
Когда загружается модуль, во вкладке левого верхнего угла появляется дефибриллятор. Чтобы он лучше работал, сделать его уже подготовленным, как будто он взят в две руки. То есть взять код от обычного дефибриллятора и сделать его доставаемым из рук КПБ. Поместить все это в левую руку, так-как правая же занята под зарядку из АПЦ. Если это все может работать, было бы удобно и балансно использовать.

### Операционная система

Win10

### Версия клиента

514.1564

### Название сервера

MAIN

### Примерное время и дата

2021.08.28 9:00

**Comment by Den109G** [comment]
Вы проверяете это комбо на мёртвом? Тогда у меня есть новости. Дефиб у КПБ - это аналог жёлтого дефиба у меда, то есть этого:
![image](https://user-images.githubusercontent.com/87372121/131209494-3f52e42a-2bc2-4599-b7cc-13a052bec247.png)

Это лишь модуль самообороны (СБ) и/или для защиты кого-то (Блющилд). Он и не предназначался для мед персонала/для тех, кто занимается трупами.

**Comment by pahanya** [comment]
Да, как уже написали сверху - у КПБ дефиб это аналог жёлтого, а не белого. Так что если ты пытался таким образом оживить труп - оно и не должно было оживить.

**Comment by Kozaku072** [comment]
Тогда получается сбивает описание, что запустить сердце = оживить.
В общее дефибриллятор, часто может теряться и быть недоступен при той же потери станции от чего либо.
Это тогда уже предложение по улучшению, получается.
Возможно я в балансе мало чего понимаю, но повысить эффективность дефибриллятора, было бы самое то для разнообразия исхода игры.

**Comment by AnywayFarus** [comment]
ну оформи в предложку тада.
а так, желтый круче.

**Comment by Kozaku072** [comment]
Переоформлено на предложку:
https://github.com/ss220-space/Paradise/issues/302

Это сообщение о баге можно закрыть/удалить.
