### ISSUE TITLE
Feat: КПБ боевой модуль - изменение работы дефибриллятора.

### ISSUE THREAD

**Issue by Kozaku072** [ss220-space/Paradise#305]
### Проблема

На данный момент, дефибриллятор позволяет поддерживать раненное существо, как это часто удается исполнить ? В моем опыте в общее никогда. Дефибриллятор приходит от КПБ на дело только тогда, когда существо уже мертво, и в итоге получается что функция дефибриллятора бесполезна, скорее всего будет во многих случаях. В моем опыте, часто бывает подключен модуль, но реализовать его для помощи не получается. Самая частая ситуация когда нужен дефибриллятор от КПБ, это когда потерян медицинский отдел или даже станция целиком. Есть жертвы, есть медицина, даже медик за углом найдется для дальнейшего лечения, но дефибриллятора нигде не найти. Так и получается, что третья комбинация бесполезна в итоге.
![image](https://user-images.githubusercontent.com/87883057/131214688-2e00270e-b188-4d9b-b215-00ad8f6e4aa7.png)

### Решение

Улучшить функцию дефибрилляции, как у полноценной версии, для полноценного оживления мертвого существа.

Пример реализации:
Когда загружается модуль, во вкладке левого верхнего угла появляется дефибриллятор. Чтобы он лучше работал, сделать его уже подготовленным, как будто он взят в две руки. То есть взять код от обычного дефибриллятора и сделать его доставаемым из рук КПБ. Поместить все это в левую руку, так-как правая же занята под зарядку из АПЦ. Если это все может работать, было бы удобно и балансно использовать.

### Плюсы

Возвращает игроков обратно в игру.
Появляется разнообразие исхода ситуации.

### Минусы

Если убийство было намеренное, сознанием что не будет возможности вернуть из-за тяжелой ситуации, КПБ может нарушить планы антагониста и подпортить ему игру.

**Comment by AnywayFarus** [comment]
если и реализовывать, то просто через выдачу борговского дефиба по нажатию, а так, не особо круто, для лечения есть лекари, а для боевого.. ну не то.

**Comment by Kozaku072** [comment]
Стороны, если менять, все же значительные и положительные. А вот если оставлять какой есть сейчас, это получается нужно справляться с боевой угрозой и еще таскать за собой раненного и периодично его бахать разрядами, и еще если повезет не будет кровотечения (подбегать в безопасное место и давать разряды, уже теряется смысл боевого действия). Тем более, это может повлиять и на заинтересованность в получении этого модуля, не только там щитом или СБшником, а кем угодно на самом деле, улучшенная самооборона и дефибриллятор на случай для существа, чем не хорошо ? 

Тут скорее как положительная сторона КПБ, что они могут от себя разряд дать в ущерб своего заряда. Когда бой закончен и начались обстоятельства с убитыми которых могут вылечить и отсутствием дефибриллятора, можно менять печальный исход для них. В нынешний момент получается, что используется только две комбинации вместо трех задуманных (и то быстрые захваты, сильно ситуативны, что сводится к использованию одной комбинации).

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184359594-6603273f-7dd2-4faa-963f-3337c5593092.png)
