### ISSUE TITLE
Хирурги смеются во время операций

### ISSUE THREAD

**Issue by MorgoWizard** [ss220-space/Paradise#31]
Хирурги смеются во время операций, предположительно из-за наркоза, а точнее его утечки

**Comment by DetectiveEnotsky** [comment]
А где баг? Позови атмостехов в свой отдел, дабы они настроили скрабберы и откачку токсинных газов, в том числе и закиси азота. Не будешь смеяться.

**Comment by MorgoWizard** [comment]
Концентрация газа, который выходит в следствие утечки не должна быть такой большой. Хирурги на постоянной основе смеются, несмотря на то, что у нас анестезия закрытого типа. То есть газ не должен вообще выходить, поидее.

**Comment by MorgoWizard** [comment]
Не актуально
