### ISSUE TITLE
Feat: Обновление игры, включающее в себя роль/работу "эксты" | Experimental Station №009

### ISSUE THREAD

**Issue by Kozaku072** [ss220-space/Paradise#310]
### Проблема

Это не проблема, а предложение для обновления мода.
Простое объяснение моей идеи, это добавление на текущие активные сервера (main + wl), возможность получить занятость и место для игры в extended. Именно, при любом игровом режиме, игроку доступна специальная роль для эксты. Создать это можно с помощью специальной игровой зоны и её необходимой обработкой. Обновление несет в себе много хороших сторон для разнообразия игры.

### Решение

По текущему шаблону, мне не очень удобно описывать идею для обновления мода, поэтому пока идея потихоньку собиралась в мыслях, оно записывалась в отдельный документ. Подробно изучить возможную реализацию идеи в моем стиле, можно по этой ссылке:
https://docs.google.com/document/d/1CjSTJEUsjfPrHixbB0N6H3BzSaL-n5NeQSRKrqpHxnk/edit?usp=sharing

"Подключение в игру дополнительной самостоятельной станции с небольшим населением 10-20 существ. Станция построена корпорацией Taina Technology, для изучения самостоятельного взаимодействия различных существ в условиях ограниченного действия. Учитывая этот момент, у каждого будет свободный доступ и каждый может заниматься чем захочет. Любая деятельность должна приносить пользу для населения, что даст продолжать жизнь на станции. Статус эксперимента, только с документальной стороны, фактически станция является своеобразным съемным жильем, что означает, станция для существ будет является их временным домом."

Это вырезка из документа по основной задумке.
Если подобное интересно, то обязательно ознакомление с документом ^_^
В случае развития, могу со своей стороны предложить написание целого лора связанного с Taina Technology, и конечно же этой новой станцией для РП эксты. Еще можно с маппингом помочь, только для начала нужно будет научиться...

### Плюсы

Много, очень много, основная отдача указана в документе, но можно вспомнить про самые основные:
1. Улучшение игрового мода и создание разнообразия для игроков.
2. РП Направление, расклад построения роли, приводит персонажа к более объемному отыгрышу.
3. Многообразие занятости персонажа, возможность обучаться или проверять/изучать для себя отдельные механики.

### Минусы

Хм-м, в данной идеи все идет к РП игре, с правилами проблем не должно возникать, единственное что может стать проблемой:
1. Сложность реализации подобной идеи.
2. Такая прекрасная станция может пострадать от набегаторов.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184359649-bd56f886-05fc-46d0-a52f-b46e57c75f32.png)
