### ISSUE TITLE
Bug: Нельзя починить киборга

### ISSUE THREAD

**Issue by Frozored** [ss220-space/Paradise#313]
### Ckey

Ditzy Shuudan

### Описание бага

Если раунд длится дольше часа, то со сломанными боргами начинает происходить пиздец. Натуральный пиздец.
Часто в роботехнику приносят сломанных киборгов, у которых в описании горит красная надпись о необходимости рестарта. (До 25.08.2021 раньше такое было очень редко)
Ты чинишь сломанного робота и с помощью худа диагностики видишь, что у него горит жёлтый крестик. В examine сказано, что нужен рестарт. Ты вставляешь плату рестарта и киборг оживает, начиная разговаривать с тобой.
НО ПРИ ЭТОМ ЖЁЛТЫЙ КРЕСТИК НИКУДА НЕ ПРОПАДАЕТ, А У РОБОТА ВКЛЮЧАЕТСЯ LOCKDOWN ( И ЭТОТ LOCKDOWN НЕ ОТОБРАЖАЕТСЯ НИ НА КОНСОЛИ, НИ В ПРОВОДАХ)
Дальше три варианта развития:
1. Ты открываешь панель с проводами, включаешь/выключаешь lockdown, но киборг снова уходит в рестарт и тебе снова нужна плата, а цикл становится бесконечным (Я не знаю как это, блять, работает!)
2. Ты включаешь/выключаешь lockdown с консоли РД и киборг может двигаться. При этом жёлтый крестик над его головой никуда не делся, а извлечение батарейки приведёт снова к тому, что потребуется рестарт.
3. Ты полностью разбираешь киборга и вставляешь его в мозг в другое тело. Здесь всё хорошо, но только до следующей серьёзной поломки. А ещё нужно по новой вставлять все улучшения, которые стоят крайне дорого.

В итоге играть на синте в течении длительного раунда становится невыносимо тяжело. Ровно как и робототехнику, у которого ТО киборга из 15 секунд превращается в 15 минут, 
Если кто-то сталкивался с этим или я что-то делаю не так и у меня руки из жопы, то налетайте в комментарии.  

P.S. Не уверена влияет ли на это время раунда, так как в начале смены киборгам просто негде получить столько урона, чтобы выйти из строя.

### Шаги воспроизведения

1. Дождаться, когда вам принесут сломанного киборга с красной надписью о рестарте и жёлтым крестиком(diagnostic HUD) над головой.
2. Починить его и вставить плату restart.
3. Услышать от киборга, что он с какого-то хуя не может двигаться.
4. Включить режим разумиста и делать то, что описано выше.

### Ожидаемое поведение

1. Дождаться, когда вам принесут сломанного киборга с красной надписью о рестарте и жёлтым крестиком(diagnostic HUD) над головой.
2. Починить его и вставить плату restart.
3. Услышать от киборга "Юнит выражает благодарность"
4. Поцеловать его в животик на прощание.

### Операционная система

Windows 10

### Версия клиента

Build 514.1564

### Название сервера

MAIN

### Примерное время и дата

Несколько раз наблюдала и становилась заложником этого бага 28.08.2021 и 29.08.2021. Есть предположение, что это происходит с 25.08.2021 в связи с обновлением киборгов.

**Comment by AnywayFarus** [comment]
Ну кстати было пару раз мной замечено, шо борг зашел в зарядник, а по итогу сломан..

**Comment by AnywayFarus** [comment]
но все же это было и до 25.
