### ISSUE TITLE
Bug:  

### ISSUE THREAD

**Issue by Mustux** [ss220-space/Paradise#314]
### Ckey

mustux

### Описание бага

За генокрада при переходе в низшую форму альт перебинживается на смену ходьбы\бега и назад даже после смены формы не возвращается, невозможно перемещаться по вентиляции

### Шаги воспроизведения

Генокрад - низшая форма - прячешься в шкафчик - становишься низшей формой - пытаешься использовать альт чтобы залезть в вентиляцию , но это не получается 

### Ожидаемое поведение

возможность залезть в вентиляцию 

### Операционная система

Windows 10 

### Версия клиента

513.1542

### Название сервера

MAIN

### Примерное время и дата

31.08.2021 ; 1:00:00 по МСК

**Comment by AnywayFarus** [comment]
Я опробовал, в первый раз не лезло в вентиляцию, перезапустил локалку.. и начало лезть. Странный прикол, но насчет ходьбы а не бега - норма.
Надо выяснить саму причину того что user.ventrawler не меняет значение(мейби пролаг?), но а так пока только к админам что бы вариаблу тебе поменяли
