### ISSUE TITLE
Feat: QOL в GPS

### ISSUE THREAD

**Issue by antrophoss** [ss220-space/Paradise#315]
### Проблема

Так уж вышло, что на нашем билде GPS показывают одни лишь xyz координаты, что на мой взгляд недостаточно. 

### Решение

Предлагаю дополнить их стрелкой к направлению и тем, сколько метров осталось до цели, как это реализовано на /tg/
![image](https://user-images.githubusercontent.com/69713525/131432343-86336ac1-634c-4c31-af87-3d8e7c78ebe8.png)

### Плюсы

Quality of life

### Минусы

переносить код с /tg/?

**Comment by Bizzonium** [comment]
https://github.com/tgstation/tgstation/blob/4e2a36fe7e56fad93495adf01c697f4b5de04e90/tgui/packages/tgui/interfaces/Gps.js

**Comment by botka4aet** [comment]
Считаю, что эту возможность надо сделать открываемой. Покупаешь улучшение в раздатчике, используешь на GPS и получаешь уже расстояние.

**Comment by botka4aet** [comment]
Зачем тянуть с ТГ, если можно утянуть с парадиза!
![image](https://user-images.githubusercontent.com/11385249/131856664-7d918103-975e-4434-8dba-d8ca6cc0f2e3.png)

**Comment by botka4aet** [comment]
Ждем
