### ISSUE TITLE
Feat: Одежда из щитспавна в игру

### ISSUE THREAD

**Issue by VictorSocks** [ss220-space/Paradise#322]
### Проблема

Добавить немного красивой одежды, которая почему-то доступна только через щитспавн.

### Решение

Добавить в автомат с одеждой redcoat uniform, redcoat's hat, Lord Admiral's Hat, Lord Admiral's Coat. Я думаю для кодеров это пара пустяков. Такая красивая одежда просто существует и ее никто не видел, как так?

### Плюсы

Чуть больше красивой одежды в автомате с одеждой

### Минусы

Кому-то не понравится одежда? Ну не знаю, короче нет минусов

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184360040-b867c2ad-0cef-4aa3-8ce9-3438306542eb.png)
