### ISSUE TITLE
Feat:Ксеееноморфы

### ISSUE THREAD

**Issue by Zombara** [ss220-space/Paradise#326]
### Проблема

Захотел ты стать Ксеноморфов но вот проблема.  Истинным ксеноморфов с возможность размножение и vore возможно лишь при помощи мага и возможно даже еще и Админа.

### Решение

Починить ксеноморфов или же сделать так. Чтобы когда при зелье разума вливали в ксеноморфа. У него бы эти функций не убирались.

### Плюсы

Новый антаг для душниловка, для людей, фанатам vore и секасных ксеноморфов явно будет рады этому.

### Минусы

Минусов для меня нет.

**Comment by botka4aet** [comment]
Минусы в том, что они всех задушат?

**Comment by LoveTrapov** [comment]
Так то если у ксеноморфов убрать супер имбалансный дизарм, то их можно и в игру добавить, без него они прям очередняры.

**Comment by Whygil** [comment]
"Минусов для меня нет" особенно позабавило.
Для меня например минусы есть, это на текущий момент невероятно имбалансный антаг и вы предлагаете его запускать не только во время щитспавнов, не только случайным событием но и чёртовой ксенобиологией? Какая проработанная однако предложка.

**Comment by Zombara** [comment]
В чем он Имбалансный?

**Comment by zombie288** [comment]
1. За
2. Очень скучаю по ксеноморфам. Даже в текущих "имбалансных" реалиях они в 50% случаях сосут, если их щитспавнят. На самом деле, нытье по поводу имбаланса ну такое. Деды тоже имбалансные, давайте их нерфить? KekW

**Comment by Zombara** [comment]
Пусть главные услышут. Это было бы отлично.

**Comment by HMBGERDO** [comment]
Стоп, это что, просьба добавить игрокам возможность добавлять в раунд мажорного имбалансного антагониста просто так? Нет, спасибо.

**Comment by Honker9999999** [comment]
Нет, не отлично. Просто не надо...

**Comment by Zombara** [comment]
Ксеноморфы ожидают кодеров и решение овнера?

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184360087-1fbd723c-bf4b-4db7-ada8-72ebce20e941.png)
