### ISSUE TITLE
UFeat: Черешня инфинити

### ISSUE THREAD

**Issue by Mell22** [ss220-space/Paradise#328]
### Проблема

На сервере Sierra известный как "Инфинити" почти никто не играет, лишь по субботам онлайн иногда удовлетворительно поднимается. Сервер ест ресурсы, а толку ноль ведь сама сборка инфинити не так интересна как хотелось бы.

### Решение

Почему бы не заменить билд на TG Build? Классический TG это очень веселый билд с кучей разных мемных фишек, многие понимают что TG это будущее. Почему же просто не поставить TG на сервер WL Sierra? 

### Плюсы

Большинство билдов на базе TG, он должен многим понравится, на TG нету вульп это уж точно. На TG есть Моли и кошко-люди. На ТГ веселые предатели которые могут устраивать резню как при хиджаке.

### Минусы

В плане кода явно будет сложно оптимизировать билд под нас, а может и нет. Те кому понравился билд инфинити будут расстроены. На ТГ предатели могут устраивать резню?

**Comment by zombie288** [comment]
1. Против
2. У вас рот в казуальщине, вытрите :Starege:
А вот на мэйн было бы неплохо поставить. Шушовцы бы поиграли на нормальном билде, а не парадизе.

**Comment by antrophoss** [comment]
Дайте нам /tg/, бажожда.

**Comment by Shadugr** [comment]
Ну гений просто. Написать в репозиторий **парадайзовской** сборки, чтобы на сервере со сборкой **фиников** добавили **тгшную** сборку.

**Comment by VasilevAY** [comment]
На данный момент есть и TG, и Sierra
![image](https://user-images.githubusercontent.com/98010665/184360161-91722a59-b534-4a84-a57d-35ab315de27a.png)
