### ISSUE TITLE
Feat: Усиление безопасности ИИ

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#330]
### Проблема

Что не раунд, то строительство в подсобке консоли загрузки ИИ и установки своих законов. Я думаю, многих постоянных игроков на силиконах порядком заебала борьба капитана с антагом за изменение законов, когда ты 5 минут ломаешь станцию и пиздишь людей, а последующие 5 минут чинишь и лечишь. Повторять до вызова ЕРТ, ага.
И вообще, так подумать. Нюка может разъебать станцию в щепки, находится под замками и для запуска требует диск и коды. Грамотный ИИ может сделать то же самое путём плазмафлуда, выпуска сингуло/Теслы и тому подобного, но взломать ИИ куда проще, чем привести в действие ДД.

### Решение

Создать механизм доступа к консоли загрузки ИИ через код, раундстартом печатающийся у капитана и/или РД.
На возможности картирования это никак не скажется, только если коды не проебаны

### Плюсы

-Больше логики в защищенности ИИ
-Меньше горящих пердаков силиконов

### Минусы

-Больше сложности для антажек

**Comment by botka4aet** [comment]
Проблема в том, что ни что не мешает тому же кэпу или рд сжечь этот листочек.
Тогда антаг ничего не сможет сделать.
Более здраво разрешить строить аплоад только рядом с уже существующим аплоадом. Те или рядом с мостиком или в космосе у самого аи

**Comment by VictorSocks** [comment]
1. Против
2. Опять душат антагов, хватит

**Comment by Whygil** [comment]
1. За
2. 2. Впринципе идея интересная, глупо что у ИИ настолько низкая безопасность, хотя он буквально и есть сама станция, а коды можно запретить сжигать и уничтожать, чтобы предотвратить их полную потерю при смерти капитана/рд

**Comment by Honker9999999** [comment]
> Проблема в том, что ни что не мешает тому же кэпу или рд сжечь этот листочек.
> Тогда антаг ничего не сможет сделать.
> Более здраво разрешить строить аплоад только рядом с уже существующим аплоадом. Те или рядом с мостиком или в космосе у самого аи

Ничего не мешает сжечь капитану все хай-риск предметы, и после такого антаг, если есть хоть одна цель на предмет не сделает ничего. А так - назвать это ПГ и дело с концом. Ну или действительно только в определенной зоне разрешить строительство.

**Comment by AnywayFarus** [comment]
1. За
2. Была идея конкретно с этой проблемой, но с другим решением. Во истину поднадоело видеть 15 закон, что говорит что этот закон главный а другие сосо. 
https://discord.com/channels/617003227182792704/618952559607939072/876922197363531806

**Comment by LoveTrapov** [comment]
1. За
2. ИИ, имеет контроль над всей станцией, всё видит, чётко повинуется законам. И эти законы почему то поменять как два пальца об асфальт.

**Comment by zombie288** [comment]
1. Против
2. Опять антагов душат.

**Comment by Dimach** [comment]
1. Против
2. Взлом ИИ тогда станет практически невозможен если антаг не РД, хотите усложнить взлом ИИ рядовыми сотрудниками РНД - сделайте чтобы платы хай риск законов (one crew, antimov) и пержа печатались в кейсах как оружие

**Comment by MaliciousPancake** [comment]
> 1. Против
> 2. Взлом ИИ тогда станет практически невозможен если антаг не РД, хотите усложнить взлом ИИ рядовыми сотрудниками РНД - сделайте чтобы платы хай риск законов (one crew, antimov) и пержа печатались в кейсах как оружие

Смысл, если для взлома ИИ часто используют пурдж и фриформ?

**Comment by Dimach** [comment]
> > 1. Против
> > 2. Взлом ИИ тогда станет практически невозможен если антаг не РД, хотите усложнить взлом ИИ рядовыми сотрудниками РНД - сделайте чтобы платы хай риск законов (one crew, antimov) и пержа печатались в кейсах как оружие
> 
> Смысл, если для взлома ИИ часто используют пурдж и фриформ?

Плата пержа будет в локбоксе, и фриформом придется маневрировать между тем паком что уже стоит (что интересно), а на триторов что не скупятся и берут плату из аплинка это изменение не повлияет

**Comment by MarshallPulse** [comment]
1. За
2. Ну слишком уж просто
![image](https://user-images.githubusercontent.com/88078980/132137053-a790b614-a643-4c83-bb34-0758247a2f81.png)

**Comment by Den109G** [comment]
1. Против.
2. ИИшку как раз взламывают потому что это очень полезный инструмент за такую малую плату (пару ресов, один тайл в техах, плата законов). Конечно же, если что-то пойдёт не по плану, то трейтора поймают и он уже будет чиллить в перме, но так можно сказать о большинстве предметов в аплинке и в арсенале самого трейтора.
Если коды невозможно будет восстановить (бывает так, почти все бумаги не восстановить, если не подбирать коды/быть антагом).
Как по мне, эта предложка будет действовать в обратную сторону, вместо "антагов душат" будет "антагов усилили".
Конечно же, антаг будет чуть дольше взламывать ИИ, но для обычного персонала эти коды - большая проблема.
Если коды будут получатся через емаг (как и при взломе консоли мониторинга), то это глупо и лишь усилит антага (точнее его емаг) и МАКСИМАЛЬНО убьёт возможность персоналу перепрограммировать ИИ обратно.

С введением кодов для аплоуда, как мне кажется, ИИ не будут даже слушать, экипаж видит ионный закон "HONK" - "ИИ малф", "идём на спутник" и т.д. Так намного проще - убить ИИ, картрировать и пересобрать ядро, что бы новый и "надёжный" ИИ смог подключиться.
Со стороны экипажа - мне не нравится данное нововведение, ведь мы не сможем починить ИИ (при нормальном ИИ и при нормальном законе) и придётся его убить, чтобы выжить.
Со стороны ИИ - мне не нравится это, меня каждый раунд будут убивать, потому что появилась ионнка, а экипаж не может сменить законы, поэтому он идёт меня убивать, а если трейтор не купил емаг? Ну тут тоже, ГГ ВП, если он вспомнит про ИИ. Вместо взлома, трейтор пойдёт и убьёт единственного ИИ.
Со стороны антага - ИДЕАЛЬНО. Кидаем две зажигательных гранаты в комнату РД и кепа, идём строим аплоуд в техах, взламываем ИИ и смотрим, как самого сильного врага убивают свой же экипаж, пока под шумок мы делаем свои цели. А всего-то это стоило 18 ТК, а так ещё можно сделать оружие и импланты в РнД, разобрав плату.

Я понимаю, что это надоедает подчиняться разным 5 законам, которые ставят все кому не лень, но я также понимаю, что никто не хочет сидеть в гостоте ВЕСЬ раунд, из-за того что трейтор унёс емаг и коды вместе с собой.
**Против.**

**Comment by MaliciousPancake** [comment]
> 1. Против.
> 2. ИИшку как раз взламывают потому что это очень полезный инструмент за такую малую плату (пару ресов, один тайл в техах, плата законов). Конечно же, если что-то пойдёт не по плану, то трейтора поймают и он уже будет чиллить в перме, но так можно сказать о большинстве предметов в аплинке и в арсенале самого трейтора.
>    Если коды невозможно будет восстановить (бывает так, почти все бумаги не восстановить, если не подбирать коды/быть антагом), то тут ГГ ВП ИИшке.
>    Как по мне, эта предложка будет действовать в обратную сторону, вместо "антагов душат" будет "антагов усилили".
>    Конечно же, антаг будет чуть дольше взламывать ИИ, но для обычного персонала эти коды - большая проблема.
>    Если коды будут получатся через емаг (как и при взломе консоли мониторинга), то это глупо и лишь усилит антага (точнее его емаг) и МАКСИМАЛЬНО убьёт возможность персоналу перепрограммировать ИИ обратно.
> 
> С введением кодов для аплоуда, как мне кажется, ИИ не будут даже слушать, экипаж видит ионный закон "HONK" - "ИИ малф", "идём на спутник" и т.д. Так намного проще - убить ИИ, картрировать и пересобрать ядро, что бы новый и "надёжный" ИИ смог подключиться.
> Со стороны экипажа - мне не нравится данное нововведение, ведь мы не сможем починить ИИ (при нормальном ИИ и при нормальном взломанном законе) и придётся его убить, чтобы выжить.
> Со стороны ИИ - мне не нравится это, меня каждый раунд будут убивать, потому что появилась ионнка, а экипаж не может сменить законы, поэтому он идёт меня убивать, а если трейтор не купил емаг? Ну тут тоже, ГГ ВП, если он вспомнит про ИИ. Вместо взлома, трейтор пойдёт и убьёт единственного ИИ.
> Со стороны антага - ИДЕАЛЬНО. Кидаем две зажигательных гранаты в комнату РД и кепа, идём строим аплоуд в техах, взламываем ИИ и смотрим, как самого сильного врага убивают свой же экипаж, пока под шумок мы делаем свои цели. А всего-то это стоило 18 ТК, а так ещё можно сделать оружие и импланты в РнД, разобрав плату.
> 
> Я понимаю, что это надоедает подчиняться разным 5 законам, которые ставят все кому не лень, но я также понимаю, что никто не хочет сидеть в гостоте ВЕСЬ раунд, из-за того что трейтор унёс емаг и коды вместе с собой.
> **Против.**

Почему не выйдет починить ИИ при взломе? Никто не мешает кэпу и РД запомнить коды, записав в нотесы. В конце концов, если законы позволяют, никто не мешает сменить законы через интелкарту.

**Comment by xSmaiLx** [comment]
1. Против
2. Опять душат антагов. 
Да и бред с этими кодами, честно. Если Кэп или РД сжигает листик - ГГ для антага. Если никто не запомнил код, а листик сожгли - одна ионка и ГГ. Если кэп сжёг листик и ушел в крио - ГГ для всех.
Даже сейчас не так просто добыть плату аплоуда, а его ещё и построить нужно. Теперь ещё и листик с каюты воровать? Душка.

**Comment by Den109G** [comment]
> Почему не выйдет починить ИИ при взломе? Никто не мешает кэпу и РД запомнить коды, записав в нотесы. В конце концов, если законы позволяют, никто не мешает сменить законы через интелкарту.

Потому что
А) При нормальном трейторе (да-а, при хиджакере), эти листочки вместе с РД и кепом будут уничтожены в начале раунда.
Б) Через интелкарту никак нельзя сменить законы. Взял ИИ на карту - законы уже не поменяют.
В) Иногда (особенно на WL), нету ни кепа, ни РД, чтобы получить эти коды для аплоуда. А для одного лишь мейна вводить - странно.

Я не знаю как на мейне, но добавление этого предложение лишь на время шусстайда исправит проблему со сменой законов, а после шусстайда нужно опять откатывать изменения. _И, по моему мнению, это будет слишком необдуманное решение данной проблемы._

**Comment by MaliciousPancake** [comment]
> > Почему не выйдет починить ИИ при взломе? Никто не мешает кэпу и РД запомнить коды, записав в нотесы. В конце концов, если законы позволяют, никто не мешает сменить законы через интелкарту.
> 
> Потому что
> А) При нормальном трейторе (да-а, при хиджакере), эти листочки вместе с РД и кепом будут уничтожены в начале раунда.
> Б) Через интелкарту никак нельзя сменить законы. Взял ИИ на карту - законы уже не поменяют.
> В) Иногда (особенно на WL), нету ни кепа, ни РД, чтобы получить эти коды для аплоуда. А для одного лишь мейна вводить - странно.
> 
> Я не знаю как на мейне, но добавление этого предложение лишь на время шусстайда исправит проблему со сменой законов, а после шусстайда нужно опять откатывать изменения. _И, по моему мнению, это будет слишком необдуманное решение данной проблемы._

Как один из вариантов решения этой проблемы, можно сделать аутентификацию в консоли загрузки по карте капитана/РД.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184362016-e25eee2d-c427-4bcc-b0af-efd2da5b7013.png)
3/6
