### ISSUE TITLE
Перевод спама ПДА и лотереи

### ISSUE THREAD

**Issue by AugustBebel** [ss220-space/Paradise#331]
### Проблема

Англоязычный спам на ПДА выглядит убого и не вписывается в остальной поток чата.

### Решение

Перевел все спам сообщения и лотерейное тоже.

https://github.com/AugustBebel/ss13/blob/main/money_spam.dm
https://github.com/AugustBebel/ss13/blob/main/money_lotto.dm

Проверил на локалке. Просто заменить файлы. путь \code\modules\events
~~Ну или запруфридить и проверить а потом скопировать. Перевод почти идентичный. Если кому-то не похуй, потом можно добавить собственный спам со своими отсылками, смехуечками и ЕРП.~~
Добавлена куча ЕРП, отсылок и мемасов. Оригинальный спам слишком уж сухой и унылый.

Кто хочет спойлеры и заруинить себе весь фан — можете посмотреть все сообщения в файле по ссылке выше.

### Плюсы

Никому не нужный спам станет чуть веселее. чуть позже переведу все новости.

### Минусы

Админу нажать контрол c + контрол v.

**Comment by AnywayFarus** [comment]
пулл реквест бы оформил. 
а ну и мне кажется надо вставить и снг рекламные рофлы.

**Comment by 1heShogun** [comment]
можно даже не просто снг рофлы, а какие нибудь локальные мемы

**Comment by Shadugr** [comment]
Можно и снг рофлы, и локальные мемы

**Comment by xSmaiLx** [comment]
Да, было бы прикольно увидеть ещё и какие нибудь мемы из ИРЛ и локальные мемчики

**Comment by AugustBebel** [comment]
> 
> 
> Да, было бы прикольно увидеть ещё и какие нибудь мемы из ИРЛ и локальные мемчики

Уже. Оригинальный спам просто говно унылое.

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/336
