### ISSUE TITLE
Bug: Предметы в сейфе пропадают

### ISSUE THREAD

**Issue by AnatShmed** [ss220-space/Paradise#333]
### Ckey

AnatShmed

### Описание бага

Когда кладешь предмет в сейф, он пропадает и достать нельзя никак.

### Шаги воспроизведения

1. Ввести комбинацию из 5-ти цифр, (я вводил 12389) нажать е на панели сейфа
2. Закрыть сейф нажав на r на панели сейфа
3. Открыть сейф введя комбинацию
4. Положить предмет из руки. (например, одежду из прибытия или ид карты)
5. Закрыть сейф нажав на r на панели сейфа
6. Открыть сейф введя комбинацию
7. Понять что ты потерял карту НТР

### Ожидаемое поведение

При открытии сейфа можно забрать предметы в нём.

### Дополнительная информация

карты в сейф заносил вчера (03.09) был на трейторе, раунд ид не помню, закончился он где-то ближе к 23 00 по МСК; одежду заносил сегодня, время указано далее
На всякий случай напишу: я не сбросил пароль, когда отрывал сейф он был зеленым и статус UNLOCKED

### Операционная система

Windows 10

### Версия клиента

514.1563

### Название сервера

MAIN

### Примерное время и дата

13:30 04.09.2021

**Comment by AnatShmed** [comment]
Мой затуп, я не перетаскивал. Два раза писал менторам никто не сказал, что перетащить надо

**Comment by botka4aet** [comment]
Те одежда и карта остались у тебя?

**Comment by AnatShmed** [comment]
Это два разных давно прошедших раунда, я только что заходил проверил, всё работает. Просто я не перетаскивал на себя.
