### ISSUE TITLE
Feat: Бафф КПБ (В частности в ПВП)

### ISSUE THREAD

**Issue by LoveTrapov** [ss220-space/Paradise#347]
### Проблема

На данный момент КПБ самая слабая раса в стычках с игроками, они буквально умирают с пары тычек. Причина такой слабости крит равный смерти, то есть КПБ лежит, и умирает, всё. И это при на столько не существенных плюсах КПБ: не действуют газы - ни о чём, у всех есть баллон и маска раундстартом, отсутствие урона от токсинов - не особо то дельный бафф, к тому же не имеющий отношения к ПВП, отсутствие органов и урона по ним, тоже самое с костями - сильный плюс этой расы, но опять же, какая разница если ты и так дохнешь с пары тычков. В итоге КПБ очень легко убить, 100 урона = смерть, и это при том что КПБ ещё и от ЭМИ дохнут будь здоров.

### Решение

Ниже я перечислил несколько решений которые пришли мне в голову, подразумевая что разработчик который возьмётся за енто дело, выберет какое то одно.
1. Банально убрать у КПБ состояние крита, то есть условно с 0 по 199 урона ты живее всех живых, а на 200 бац и умер (Как по мне не плохое решение, теперь хотя бы способность КПБ работать без головы будет полезна). [В цифрах могу ошибаться, но суть я думаю всем и так ясна]
2. Дать КПБ бодрые резисты к урону (Логично, они же ну... Металлические типо, полагаю их должно быть не так легко повредить).
3. Сделать КПБ дефолтный крит, когда ты падаешь, снова встаёшь, теряешь сознание и т.д. (Буду рад даже этому, а так худший из вариантов, играет не в пользу того что КПБ это всё таки роботы, и равняет их по сути с теми же хуманами)

### Плюсы

- КПБ задышат в ПВП
- КПБ смогут существовать будучи антагами
- КПБ смогут что то противопоставить тем антагам стычки с которыми не подразумевают стана
- КПБ будут чаще терять голову и при том оставаться живыми, а не раз в миллион лет.

### Минусы

- КПБ задышат в ПВП
Не знаю, какие тут минусы, машинами убийцами они от этого не станут, их всё ещё можно будет забить, но теперь уже в честной схватке, а ЭМИ фонарик всё ещё будет снится игрокам на КПБ в кошмарах, как и ревенант кстати.

**Comment by DROZD-01** [comment]
Что это такое, рядовой Куча? Какой ещё бафф КПБ? Они и так лютая имба из-за отсутствия необходимости в кислороде (только давление важно), да ещё и лечатся/чинятся сами и бесконечно (сварка-провода и паста на случай повреждений, которые сварка-провода не починят) пока у тебя есть хотя бы одна целая рука.
Их реально убить только за один присест, отрубив им всё что можно, да и то их потом чинят почти моментально (если есть запасное тело - совсем моментально)

Может люди конечно и во время самого ПвП крепче, но вот автономность КПБ это люто.

**Comment by TrashDoxx** [comment]
Хорошее предложение, давайте сделаем КПБ людьми с уязвимостью к ЭМИ, но только лучше и крепче, я поддерживаю.

**Comment by LoveTrapov** [comment]
> Что это такое, рядовой Куча? Какой ещё бафф КПБ? Они и так лютая имба из-за отсутствия необходимости в кислороде (только давление важно), да ещё и лечатся/чинятся сами и бесконечно (сварка-провода и паста на случай повреждений, которые сварка-провода не починят) пока у тебя есть хотя бы одна целая рука.
> Их реально убить только за один присест, отрубив им всё что можно, да и то их потом чинят почти моментально (если есть запасное тело - совсем моментально)
> 
> Может люди конечно и во время самого ПвП крепче, но вот автономность КПБ это люто.

Дело в том что в стычке не на жизнь, до этой самой автономности не доходит, одна рука означает только то, что ты уже давно валяешься в крите, который медленно (быстро) тебя убивает. Поднять с того света да, легко, пока тебя не спрячут где то, не выкинут в космос, или ещё чего по хуже не придумают, ну и пока роботехи нормальные ребята. Про кислород фигня как есть, на станции полно баллонов и мест где их можно наполнить, ну и это по прежнему, никак не влияет в ПВП

**Comment by Whygil** [comment]
КПБ не нужно латать дырки в лёгких и других внутренних органах, провода+сварка и он как новый, они не дышат, они не болеют, у них резисты к огню и урону. Вы ёбнулись там самая слабая раса?

**Comment by DROZD-01** [comment]
То есть ты предлагаешь убрать у КПБ по сути единственный минус в ПВП? Алло, а слово "баланс" вы из методички варгейминга брали? Я как перманентный КПБвод заявляю - предложение чисто как "дайте вульпам резисты к огню, а то чо они горят?"

**Comment by LoveTrapov** [comment]
> КПБ не нужно латать дырки в лёгких и других внутренних органах, провода+сварка и он как новый, они не дышат, они не болеют, у них резисты к огню и урону. Вы ёбнулись там самая слабая раса?

Я говорю о стычках с игроками, условное антаг с СБ, в этой ситуации возможность быстро себя починить роли не играет, поскольку тебе банально не дадут.

**Comment by LoveTrapov** [comment]
> То есть ты предлагаешь убрать у КПБ по сути единственный минус в ПВП? Алло, а слово "баланс" вы из методички варгейминга брали? Я как перманентный КПБвод заявляю - предложение чисто как "дайте вульпам резисты к огню, а то чо они горят?"

"Единственный минус", а ЭМИ?

**Comment by DROZD-01** [comment]
> Я говорю о стычках с игроками, условное антаг с СБ, в этой ситуации возможность быстро себя починить роли не играет, поскольку тебе банально не дадут.

А с чего вдруг они должны тебе это давать? На кой хрен ввязываться в мощную зарубу, заведомо зная, что у тебя планка крита низкая? Это вот вы так сейчас баффните КПБ, а потом надо будет баффать СБ, чтоб хэборгов угомонить.

**Comment by Madmanap** [comment]
>Кпб
>Самая слабая раса
#Достаточно

**Comment by LoveTrapov** [comment]
> КПБ не нужно латать дырки в лёгких и других внутренних органах, провода+сварка и он как новый, они не дышат, они не болеют, у них резисты к огню и урону. Вы ёбнулись там самая слабая раса?

Кстати о резисте к огню, 20%, только вот умираешь ты в 2 раза быстрее, то есть, сгораешь тоже в два раза быстрее, но за счёт резиста получаем, что КПБ сгорают на 30% быстрее прочих рас

**Comment by DROZD-01** [comment]
> "Единственный минус", а ЭМИ?
Давно у всех подряд ты ЭМИ видел? Тебя быстрее просто из доминатора/другого летала расстреляют. Никто за ионной винтовкой ради КПБ не идёт. ЭМИ обычно - это какая-то бытовая проблема.

**Comment by Whygil** [comment]
> Против.
> УРА УРА, ещё одна раса рескин хуманов! Вот это здорово вы придумали, я даже сначало не понял, молодцы.

Не, это рескин хуманов, с 33% резистом к огню и порезам, без внутренних повреждений, имеющий возможность чинить себя БЕСКОНЕЧНО проводами и сваркой и ещё без не болеющие и не дышащие. Предлагаю тогда им ещё убрать учзвимость к ЭМИ, вот тогда баланс настанет :/

**Comment by LoveTrapov** [comment]
> > "Единственный минус", а ЭМИ?
> > Давно у всех подряд ты ЭМИ видел? Тебя быстрее просто из доминатора/другого летала расстреляют. Никто за ионной винтовкой ради КПБ не идёт. ЭМИ обычно - это какая-то бытовая проблема.

У СБ есть флеш, есть ионка. У антагов арсенал и того больше, да и просто затыкать не мешает

**Comment by DROZD-01** [comment]
> Не, это рескин хуманов, с 33% резистом к огню и порезам, без внутренних повреждений, имеющий возможность чинить себя БЕСКОНЕЧНО проводами и сваркой и ещё без не болеющие и не дышащие. Предлагаю тогда им ещё убрать уязвимость к ЭМИ, вот тогда баланс настанет :/

Ненуачо, сделаем себе наших "И ВАСССТАЛЕ ХЕБОРГИ ИЗ ПЕПЛА ЯДЕГНОЙ ВАЙНЫ, И ПАШЛА ВАЙНА НА УДИЧТОЖЕНИЕ ВСЕЙ СТАНЦИИ!"

Если у антажки возникают проблемы в борьбе с СБ - он явно что-то делает не так.

**Comment by LoveTrapov** [comment]
> > Не, это рескин хуманов, с 33% резистом к огню и порезам, без внутренних повреждений, имеющий возможность чинить себя БЕСКОНЕЧНО проводами и сваркой и ещё без не болеющие и не дышащие. Предлагаю тогда им ещё убрать уязвимость к ЭМИ, вот тогда баланс настанет :/
> 
> Ненуачо, сделаем себе наших "И ВАСССТАЛЕ ХЕБОРГИ ИЗ ПЕПЛА ЯДЕГНОЙ ВАЙНЫ, И ПАШЛА ВАЙНА НА УДИЧТОЖЕНИЕ ВСЕЙ СТАНЦИИ!"
> 
> Если у антажки возникают проблемы в борьбе с СБ - он явно что-то делает не так.

А если у СБ с антажкой?

**Comment by LoveTrapov** [comment]
> > Против.
> > УРА УРА, ещё одна раса рескин хуманов! Вот это здорово вы придумали, я даже сначало не понял, молодцы.
> 
> Не, это рескин хуманов, с 33% резистом к огню и порезам, без внутренних повреждений, имеющий возможность чинить себя БЕСКОНЕЧНО проводами и сваркой и ещё не болеющие и не дышащие. Предлагаю тогда им ещё убрать уязвимость к ЭМИ, вот тогда баланс настанет :/

Ладно, я ошибся, 33% резист, но ты всё ещё умираешь в 2 раза быстрее, то есть резист в 50% просто бы уровнял ситуацию.

**Comment by DROZD-01** [comment]
> А если у СБ с антажкой?

ВНЕЗАПНО - ответ тот же самый. Бафф очередной расы в очередной раз поломает и так кривой баланс между экипажем и антагами, который и так на ладан дышит из-за срочников с обоих сторон.

**Comment by DROZD-01** [comment]
> Ладно, я ошибся, 33% резист, но ты всё ещё умираешь в 2 раза быстрее, то есть резист в 50% просто бы уровнял ситуацию.

Чел, ты можешь прямо во время горения себя проводами лечить. А если страшна - маленький огнетуш и тебя тупо не сжечь. КПБ может даже в разгерме гулять почти спокойно, если запас проводов и сварки достаточный.

**Comment by DROZD-01** [comment]
Ну и если это ещё не ясно:

**Против.**
Предложка от и для тех, кто КПБ не понял и просто любит каэсочку.

**Comment by LoveTrapov** [comment]
> > Ладно, я ошибся, 33% резист, но ты всё ещё умираешь в 2 раза быстрее, то есть резист в 50% просто бы уровнял ситуацию.
> 
> Чел, ты можешь прямо во время горения себя проводами лечить. А если страшна - маленький огнетуш и тебя тупо не сжечь. КПБ может даже в разгерме гулять почти спокойно, если запас проводов и сварки достаточный.

Могу, если в этот момент мне не ломают лицо, но я опять же, говорю о стычках с игроками, то есть, отпускать тебя никто не станет, давать починиться тоже, и тут КПБ в проигрышном положении, даже банально тыкаясь по очереди друг в друга КПБ всегда будет проигрывать.

**Comment by DROZD-01** [comment]
> Могу, если в этот момент мне не ломают лицо, но я опять же, говорю о стычках с игроками, то есть, отпускать тебя никто не станет, давать починиться тоже, и тут КПБ в проигрышном положении, даже банально тыкаясь по очереди друг в друга КПБ всегда будет проигрывать.

А с чего вдруг они при таком количестве баффов (которые кста и для антажки с целями типа "украсть херню" полезны) должны ещё и ПвП на изи тащить?

**Comment by LoveTrapov** [comment]
> > Могу, если в этот момент мне не ломают лицо, но я опять же, говорю о стычках с игроками, то есть, отпускать тебя никто не станет, давать починиться тоже, и тут КПБ в проигрышном положении, даже банально тыкаясь по очереди друг в друга КПБ всегда будет проигрывать.
> 
> А с чего вдруг они при таком количестве баффов (которые кста и для антажки с целями типа "украсть херню" полезны) должны ещё и ПвП на изи тащить?

Речь идёт не о на изи, а о том что бы уровнять шансы.

**Comment by 1heShogun** [comment]
Пфф, этот человек видимо про нуклеацию не знает.

**Comment by LoveTrapov** [comment]
> Пфф, этот человек видимо про нуклеацию не знает.

Их можно в расчёт не брать, на них никто и не играет в здравом уме...Особенно за СБ или антагов

**Comment by 1heShogun** [comment]
> Их можно в расчёт не брать, на них никто и не играет в здравом уме...Особенно за СБ или антагов

Я играл только за нуклеацию весь 2020 год... И да, за антагов тоже...

**Comment by LoveTrapov** [comment]
> > Их можно в расчёт не брать, на них никто и не играет в здравом уме...Особенно за СБ или антагов
> 
> Я играл только за нуклеацию весь 2020 год... И да, за антагов тоже...

Интересно, нервы от такого крепнут, или наоборот?

**Comment by 1heShogun** [comment]
> Интересно, нервы от такого крепнут, или наоборот?

Крепнут. Когда у тебя x2 брута и **x4** берна и нет возможности воскрешения - ты крепчаешь. Хотя когда я перешёл на кидана (Потому-что это единственная раса которая имеет резист к бруту) привыкнуть было сложно. **Фу, дышать? Что это такое? Я боюсь радиации? Кровь?! БОЛЕЗНИ?!**

**Comment by Jordanstolethepreciousslam** [comment]
Что, зачем, и нахуя. КПБ и так наслаждаются нехилым удобством. Можно пожрать у любого АПЦ. Починиться можно той же сваркой которой только что сжег вульпу, а потом ей же воскресить товарища КПБ. Ебля с болоном тебя не касается как и мемные химикаты типа прионов. Да, яды говно и смешная хуета не опасная ни для кого, но тем не менее. 
Не все расы созданы для прямой конфронтации. Греи слегка пососные но их коммуникация ебучая имба которая не затыкаеться никак кроме потери сознания.

КПБ же занимают промежуточную позицию. Они не имеют имбовых абилок, но большинство проблем органиков их не касаются. Это выбор для ленивых. Хочешь быть сильным? Бери хумана, но за силу придется платить потребностями. Не хочешь тратить время на жрат, лечение и воздух? Ну тогда наслаждайся сниженным боевым потанцевалом без аугмента, вируса, генов и усилок из ДНК хранилища.

Да и вообще странно говорить о их слабости в ПВП.
Во первых - Они не настолько слабые. Сейчас у них вполне сносные 150 эффективного хп что всего на 50 ниже чем у хумана(+отваливаются конечности легко).
Во вторых - Ни одна раса не должна быть прямым апгрейдом человека. Это хуета.
В третьих - Основное ПВП станции это стрельба желтой мочей из доминаторов и прочие станы. Единственно когда крепость играет роль это всякие пауканы пососные да блобич. Но пауканы ебут ядами и яйцами а блоб ебет теми же химикатами. В обоих случаях КПБ похуй на яды но уязвимей к физической составляющей антагониста. Убери это и КПБ будет прямым апгрейдом.

**Comment by Slisenz** [comment]
Бафы кпб действительно внесут дисбаланс в игру , однако я сам не играю за кпб(а очень хочется) из за его беспомощности во время Крита, ведь упал в Крит = смерть. Хотелось бы предложить дать возможность "вернуться в сознание". Реализовать что то потипу ребута, который длится минуту(или больше) и после него у тебя есть 5 секунд чтобы починить себя или снова упадёшь в ребут. Вообщем механику до конца не продумал, но хочу лишь одного, чтобы после взрыва рядом с тобой у тебя ещё была Надежда выжить , а не просто с покерфейсом наблюдать за своим телом в ожидании пока тебя спасут
P.S. Ну да клоунская не продуманная идея, а что вы мне сделаете ?

**Comment by Elisei24** [comment]
> Бафы кпб действительно внесут дисбаланс в игру , однако я сам не играю за кпб(а очень хочется) из за его беспомощности во время Крита, ведь упал в Крит = смерть. Хотелось бы предложить дать возможность "вернуться в сознание". Реализовать что то потипу ребута, который длится минуту(или больше) и после него у тебя есть 5 секунд чтобы починить себя или снова упадёшь в ребут. Вообщем механику до конца не продумал, но хочу лишь одного, чтобы после взрыва рядом с тобой у тебя ещё была Надежда выжить , а не просто с покерфейсом наблюдать за своим телом в ожидании пока тебя спасут
> P.S. Ну да клоунская не продуманная идея, а что вы мне сделаете ?

Реально интересная идея. Дать возможность заребутиться после небольшого ожидания или через миниигру какую-нибудь, чтобы хотя бы на помощь позвать. Вполне в духе КПБ.

**Comment by OpsCoretango** [comment]
> > Могу, если в этот момент мне не ломают лицо, но я опять же, говорю о стычках с игроками, то есть, отпускать тебя никто не станет, давать починиться тоже, и тут КПБ в проигрышном положении, даже банально тыкаясь по очереди друг в друга КПБ всегда будет проигрывать.
> 
> Нанопаста лечит мгновенно и печатается за гроши. КПБ с 2-3 нанопастами и сейчас выигрывает Файт "я бью тебя, ты бьешь меня" против любой расы, выходя из него полностью здоровым (если, конечно, против него не химик-манчкин с полной сумкой синтплоти)

Опа, ну спасибо.

**Comment by girafe969** [comment]
> > Нанопаста лечит мгновенно и печатается за гроши. КПБ с 2-3 нанопастами и сейчас выигрывает Файт "я бью тебя, ты бьешь меня" против любой расы, выходя из него полностью здоровым (если, конечно, против него не химик-манчкин с полной сумкой синтплоти)
> 
> Шо за дичь? Я тебе как мейнер священника заявляю что хилка в нашем стан базед билде нихуя не решает. Удачи полечится в стане. У священника есть книжка которая ударом лечит круче нанопасты и бесконечна, но это не дает никаких особых преимуществ в ПВП потому что блять стан базед боевка. Единственное когда она полезна это против симплмобов. Но они просто отрывают ударами конечности КПБ. Удачи полечится без рук.

Я и не говорил про настоящее пвп, я про ситуацию, которую описывает чел в данной предложке

**Comment by Jordanstolethepreciousslam** [comment]
Окей я слегка спизданул, суть в том что хилка так не работает. Пытаться лечится прямо в бою это самоубийство. Если противник не отвлечен чем то другим и имеет стан оружие, или просто хороший дамаг, тебе ни нанопаста ни библия не поможет, а сделает только хуже.

**Comment by girafe969** [comment]
> Окей я слегка спизданул, суть в том что хилка так не работает. Пытаться лечится прямо в бою это самоубийство. Если противник не отвлечен чем то другим и имеет стан оружие, или просто хороший дамаг, тебе ни нанопаста ни библия не поможет, а сделает только хуже.

Не отрицаю. Но и большие резисты (о чем эта предложка) тебе так же не помогут. Поэтому я и написал 

> Если у тебя все драки сводятся к тому, кто кого быстрее отпинает/расстреляет, то ты просто не умеешь пвпшиться на нашем билде

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184360257-4d2446b3-691a-4ca1-bc11-28c5304fca46.png)
