### ISSUE TITLE
Прикрепление и открепление конечностей кпб

### ISSUE THREAD

**Issue by Isareluss** [ss220-space/Paradise#348]
### Проблема

Очередной баф на кпб. Это улучшение позволить откреплять и присоединять конечности и голову для кпб. В случае отсоединения головы, кпб потеряет зрение и слух. Такое уже есть на инфинити, так что исполнить это будет не сложно. Это в первую очередь логично, так как кпб не нужно присоединять сосуды, кости, мышцы и прочее. А во вторую просто прикольная механика, что будет отличать кпб ещё больше от хуманов.

### Решение

Добавить возможность кпб отсоединять и присоединять конечности, в том числе и голову, но с потерей зрения и слуха. Потребуется скомуниздить код с инфинити, так как там такая функция есть. Позволит вне робототехники приделывать себе конечности и голову. Как альтернативу, можно потребовать держать в руке кпб инструмент, например отвёртку, кусачки или гаечный ключ. Отсоединение и прикрепление можно разделить в несколько этапов: 
1 - отвёртка
2 - гаечный ключ
3 - кусачки
4 - отвёртка

### Плюсы

Усилит кпб.
Логично.
Позволит кпб в не очень приятных условиях латать себя.
Возможно разнообразит геймплей.

### Минусы

Усилит кпб
Возможно влияние робототехников по ремонту ипс немного снизится, из за чего робототехники со стажем будут недовольны.
Возможно покажется имбовым, но для присоединения и отсоединения конечностей потребуется инструмент/инструменты

**Comment by Den109G** [comment]
Можно же на каталке прикреплять голову/конечности.

**Comment by Whygil** [comment]
День усиления КПБ как "Самой слабой расы" как я понял. Робототехникам в теории стол хирургический нужен только для того, чтобы чинить КПБ и приделывать им конечности. Но нет, ведь КПБ, выживая при отстреле головы очень страдает.

**Comment by Isareluss** [comment]
Ну это же на каталке, а мой вариант предложит делать это на стуле, стоя

**Comment by botka4aet** [comment]
> Это в первую очередь логично, так как кпб не нужно присоединять сосуды, кости, мышцы и прочее. 
Вместо нервов и сосудов - провода
Так же конечность надо как-то фиксировать на месте.
Слишком имбово к тому же.

**Comment by LoveTrapov** [comment]
1. За
2. Если я правильно понял подразумевается то что КПБ самостоятельно сможет прикрепить себе потерянную конечность, действительно логично

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184360345-c24c2805-2020-4578-b47d-bee131220184.png)
