### ISSUE TITLE
Feat:Маннкономика боргам

### ISSUE THREAD

**Issue by Mell22** [ss220-space/Paradise#349]
### Проблема

Сейчас почти все расы экипажа могут носить шапки, ключевое слово почти, борги вот, обделены этим!

### Решение

Добавить возможность надевать на боргов шапки! Пусть они станут модными! Инженерный борг в инженерном берете это будет так круто! 

### Плюсы

Крутые и веселые внешности для боргов в шапках, и практическая сторона, например каски с встроенным фонарем

### Минусы

Кодить надо

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184360760-bc598896-1298-4866-8d35-4a56a733be61.png)
