### ISSUE TITLE
Feat: БоХ в БоХ

### ISSUE THREAD

**Issue by botka4aet** [ss220-space/Paradise#350]
### Проблема

Альтернативно одаренные пихают бох в бох для рофла

### Решение

Если не антаг это делает, то его просто разрывает на куски.

### Плюсы

Меньше раундов, завершенных слишком рано

### Минусы

Для рофлов останется лимитка и тесла.

**Comment by Whygil** [comment]
1. Против
2. Это одна из фишек ССки, которая присутствует почти на всех серверах. Нахуй такую предложку.

**Comment by normie5-cell** [comment]
Шуссоиды...

**Comment by botka4aet** [comment]
> Шуссоиды...
Очень интересен ваш аргументированный ответ.
> Это одна из фишек ССки, которая присутствует почти на всех серверах. Нахуй такую предложку.
Очень интересно. Оправдывать то, что это можно делать везде.
А еще вроде как самоантажить нельзя. Почти везде.
И соблюдать РП.
Так что "Нахуй такой ответ"

**Comment by Jordanstolethepreciousslam** [comment]
Вообще некоторые альетрнативно одаренные сервера уже выпилили эту возможность. Следовать этому идиотскому тренду мы конечно же не будем. В сосаке 1000 и 1 способ загрифонить кучу народа. Все способы не позакрывать, проще тогда уж 
во все сервера по приглашениям пускать.

**Comment by antrophoss** [comment]
Против. Иконические фичи убирать - не хорошо.

**Comment by zombie288** [comment]
Против.
Легендарная фича, такая же легендарная, как и возможность словить сингу БоХом. Если человек осознанно, не будучи антагом делает сингу, то нахуй такого человека в Бразилию на ПМЖ. 
Не будь ей 100500 лет, конечно стоило бы выпилить, но эта особенность присутствовала даже на старых Хай - РП финиках, и никто не думал её срезать.

**Comment by botka4aet** [comment]
> Не будь ей 100500 лет, конечно стоило бы выпилить, но эта особенность присутствовала даже на старых Хай - РП финиках, и никто не думал её срезать.

Точно? На том же парадайзе поднимался вопрос. Но не убрали по прчине
> Кроме того, как мы уже говорили ранее, **грифинг Singularity не является обычным явлением, на самом деле это невероятно редко.** 

> В сосаке 1000 и 1 способ загрифонить кучу народа.
И эти способы требуют от тебя хоть каких-то телодвижений. Для боха достаточно зайти за ученого и сидеть афк, ожидая ресурсов. Сделать 2 боха и все. И это единственный способ тотального грифа, который можно нормально прикрыть.

**Comment by MarshallPulse** [comment]
1. Частично за
2. набегаторы и новички надоели, но фича реально легендарная
3.  Предлагаю ввести емаг БоХа для того, что бы у хикекеров была возможность это провернуть, а остальные натыкались на защиту от дурачков.

**Comment by AugustBebel** [comment]
Можно сделать случайный эффект из списка а не сингу, если набигаторы совсем заели. И фича более-менее останется и грифить будет сложно.

**Comment by DROZD-01** [comment]
1. Частично **За**
2. Как вариант - облепить само действие кучей предупреждений о том, что "Не лезь блять, оно тебя забанит" и выдавать автобан серваком если это сделал пчел без роли тритора.

**Comment by DoctorSkullka** [comment]
> 1. Частично **За**
> 2. Как вариант - облепить само действие кучей предупреждений о том, что "Не лезь блять, оно тебя забанит" и выдавать автобан серваком если это сделал пчел без роли тритора.

Там и так предупреждение выдаёт.

**Comment by DROZD-01** [comment]
> Там и так предупреждение выдаёт.

Видимо, недостаточно убедительное.

**Comment by 1heShogun** [comment]
> > Там и так предупреждение выдаёт.
> 
> Видимо, недостаточно убедительное.

Дело в том, что если чувак уже хочет это сделать - он сделает. Предупреждение помогает только от случаев, когда человек не знает к чему это может привести.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184360849-0648b751-d2e9-4f34-a18f-8bc3d5ff3d8c.png)
