### ISSUE TITLE
Bug: Свет свармера+венты

### ISSUE THREAD

**Issue by AnatShmed** [ss220-space/Paradise#351]
### Ckey

anatshmed

### Описание бага

Если на свармере включить свет в вентиляции через его абилку, то свет останется на месте активации (на тайле) вне зависимости от перемещения свармера.

### Шаги воспроизведения

1. Будучи свармером войти вентиляцию с выключенной абилкой на свет.
2. Активировать абилку на свет (Toggle Light).
3. Переместиться по вентиляции.

### Ожидаемое поведение

Свет всегда остается на тайле со свармером.
Альтернативно:
Свармеры не могут включать свет в вентиляции.

### Дополнительная информация

Если выключить абилку, то свет пропадает.

### Операционная система

Windows 10

### Версия клиента

514.1563

### Название сервера

MAIN

### Примерное время и дата

02:00 08.09.2021

**Comment by Ohar** [comment]
Это не у свармера, а у любого вентовика с лампой (дрона, например).
Вот только это не настоящий свет, его видишь только ты, другие игроки - нет.

**Comment by AnatShmed** [comment]
Все ещё баг, то что вижу свет только я делает его в некотором смысле хуже: я вижу что творится в темной комнате, а те кто в ней находятся нет. 

Фикс вроде был, это до сих пор работает для дронов? Или его ещё не залили на сервер?

**Comment by LiSb331** [comment]
Фикс не залит судя по всему ещё
