### ISSUE TITLE
Bug: ММИ Синдиката не работает.

### ISSUE THREAD

**Issue by Dzhimax** [ss220-space/Paradise#355]
### Ckey

Dzhimax

### Описание бага

Купил из аплинка ММИ синдиката, вставил в него мозг человека, ММИ в киборга. Киборг привязался к ИИ и получил законы НТ дефолт. Модератор в переписке сказал, что заметил в коде ошибку после моего тикета. Раунд 3572

### Шаги воспроизведения

Купить ММИ синдиката, вставить в него мозг. Имея активный ии, к которому привязываются киборги автоматом, вставить этот самый ММИ в киборга. Проверить законы киборга.

### Ожидаемое поведение

Привязка к ИИ, наследование законов от ИИ.

### Операционная система

win10

### Версия клиента

514.1566

### Название сервера

MAIN

### Примерное время и дата

10.09.2021 Раунд 3572 первый час раунда.

**Comment by AnywayFarus** [comment]
модератор не нашел ошибку так то
но фикс уже готов
