### ISSUE TITLE
Feat: Добавить возможность ползать по полу, если лёг сам

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#356]
### Проблема

Сейчас это невозможно. Но думаю стоит добавить эту фичу. Можно добавить к этому, что если ты ползаёшь, то можешь заползать под предметы, например под стол

### Решение

кодить

### Плюсы

Новые механики

### Минусы

кодить

**Comment by LoveTrapov** [comment]
1. 50/50
2. Скорее даже против, нужно всю игру подгонять под это изменение, менять карту, что бы нигде не могли пролезть куда не надо, менять геймплей.

**Comment by Xoma-Sebas** [comment]
1. За
2. Будет больше возможностей проникнуть в разные места, и не обязательно искать перчатки и/или инструменты

**Comment by Whygil** [comment]
1. Против
2. Ползанье уже есть на сервере Extended, там оно мне не понрааилось.

**Comment by zombie288** [comment]
Давайте лучше сразу на ТГ перейдем Starage

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184360881-7360c546-e06a-46dc-90c3-4f5a747184bd.png)
