### ISSUE TITLE
Feat: Добавить агентов синдиката как гост-роли

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#362]
### Проблема

Сейчас из-за онлайна выше 100 тел, чаще всего такие роли как учёный, роботех, инженер заняты и на них не зайти. Стоять в очереди к ХоПу конечно вариант, но довольно таки неприятный процесс, особенно когда сами главы и усложняют его. Именно поэтому я и предлагаю добавить исследовательскую базу синдиката.

### Решение

- Что будет представлять из себя исследовательская база синдиката?
Эта база будет находиться либо в космосе либо на лаваленде. Она не будет особо большой, но будет включать всё необходимое для комфортной работы в роли учёного, инженера, шахтёра.

- Что надо будет делать за агентов синдиката в качестве гост-роли?
Работать в рнд, добывать ресурсы, поддерживать целостность базы и выполнять задания, которые будут со временем поступать.

- Что будет запрещено делать за эту роль?
Нападать на станцию/аванпост/шахтёров/исследователей без важной на то причины. То есть пока не поступит задание или приказ, нападать нельзя. Если уж какой-то там шахётр/исследователь забрёл на базу, то его можно убить, а можно захватить. Тут уж на усмотрение самих игроков, нападение на станцию/аванпост при этом не даётся

p.s: если эту предложку одобрят, то я самолично займусь её реализацией

### Плюсы

Больше рп ролей, чуть больше ролей для тех кто любит работку, немного разнообразия

### Минусы

Кодить, могут быть ситуации подобно как с эшами( то есть когда те нападают без должной причины)

**Comment by Frozored** [comment]
Ты же понимаешь, что кодить это будешь всё ты?
А так ЗА. В билде уже есть готовая база синдиката на лаве, но она вырезана на наших серверах.

**Comment by Sykybekk** [comment]
> Ты же понимаешь, что кодить это будешь всё ты?
> А так ЗА. В билде уже есть готовая база синдиката на лаве, но она вырезана на наших серверах.

Да, я понимаю это

**Comment by VictorSocks** [comment]
1. За
2. Пару месяцев назад я делал такую же предложку, никто ее не взял, проблема в кодерах, мапперах и атмосе наверно, никто не хочет это кодить, БОЖЕ ДАЙ НАМ КОДЕРА, ЧТОБ НАМ ДЕЛАЛ ВСЕ НАШИ ПРЕДЛОЖКИ, БОЖЕ ПОЖАЛУЙСТА!

**Comment by Danefalt** [comment]
> 1. За
> 2. Пару месяцев назад я делал такую же предложку, никто ее не взял, проблема в кодерах, мапперах и атмосе наверно, никто не хочет это кодить, БОЖЕ ДАЙ НАМ КОДЕРА, ЧТОБ НАМ ДЕЛАЛ ВСЕ НАШИ ПРЕДЛОЖКИ, БОЖЕ ПОЖАЛУЙСТА!

Мне лень. А так, у меня даже готовый код этой штуки где-то был.

**Comment by AttHawk** [comment]
1. За
2. С учетом того что готовая база есть в коде, особых проблем с реализацией возникнуть не должно, а идея здравая

**Comment by DoctorSkullka** [comment]
База синдиката на лаве была выпилена из за того что ломала атмос. Не знаю это ли имеет ввиду автор, но если её не починили то возвращать не будут - фиксить некому.

**Comment by Sykybekk** [comment]
> База синдиката на лаве была выпилена из за того что ломала атмос. Не знаю это ли имеет ввиду автор, но если её не починили то возвращать не будут - фиксить некому.

Насчёт проблемы с атмосом, я слышал  и буду её решать

**Comment by Sykybekk** [comment]
Ага, ну и за месяца два никто ничто не сдвинул, а ведь были кто делал, поперёк меня. Что ж

**Comment by dj-34** [comment]
> Ага, ну и за месяца два никто ничто не сдвинул, а ведь были кто делал, поперёк меня. Что ж

Так Furukai пилит Синди-станцию и она уже готова и ждет мерджа 🤔 
Там как раз то, что ты описал в своей предложке. Предложку можно закрывать. 🤷

**Comment by Sykybekk** [comment]
> > Ага, ну и за месяца два никто ничто не сдвинул, а ведь были кто делал, поперёк меня. Что ж
> 
> Так Furukai пилит Синди-станцию и она уже готова и ждет мерджа 🤔 Там как раз то, что ты описал в своей предложке. Предложку можно закрывать. 🤷

два месяца чот прошло, что там такого долгого можно было делать?

**Comment by dj-34** [comment]
> > > Ага, ну и за месяца два никто ничто не сдвинул, а ведь были кто делал, поперёк меня. Что ж
> > 
> > 
> > Так Furukai пилит Синди-станцию и она уже готова и ждет мерджа 🤔 Там как раз то, что ты описал в своей предложке. Предложку можно закрывать. 🤷
> 
> два месяца чот прошло, что там такого долгого можно было делать?

Можешь посмотреть в его ПРе.
https://github.com/ss220-space/Paradise/pull/409

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/409
