### ISSUE TITLE
Feat: Новый антаг: Контрабандист.

### ISSUE THREAD

**Issue by MiFaust** [ss220-space/Paradise#363]
### Проблема

Предложение:
Добавить нового антага. Контрабандист.

### Решение

Хотел бы немного порефлексировать над некоторыми механиками. (Возможно их не добавят, но все же) Можно сделать, что у него будет второй лицевой счет в банке, для переводов в синдикат. Так же он может принимать оплату телекристаллами, но их нужно будет передавать энд гемово, после прилета на ЦК. И как я думаю, ему нужно будет давать сумку кантробандиста раундстартом, а уже в ней будет рандомная кантробанда (ценовой диапозон вроде можно установить). Так же синдикат может напоминить, что использование довереных вещей в любых целях кроме продажи и показа возможностей товара запрещается.

### Плюсы

Один из немногих антагов который должен не убивать и насиловать пол сервера, а сдавать вещички синдиката по ценам и не спалиться.
Антаг направленный по большей части на РП (вы же знаете такое слово, мои маленькие щитокуры) составляющую.

### Минусы

Думаю ясно что нужен кодер.

**Comment by girafe969** [comment]
Здраствуйте. Хотел бы чтобы вы сделали игру, 3Д-экшон суть такова... Пользователь может играть лесными эльфами, охраной дворца и злодеем. И если пользователь играет эльфами то эльфы в лесу, домики деревяные набигают солдаты дворца и злодеи. Можно грабить корованы... И эльфу раз лесные то сделать так что там густой лес...

**Comment by MiFaust** [comment]
> Здраствуйте. Хотел бы чтобы вы сделали игру, 3Д-экшон суть такова... Пользователь может играть лесными эльфами, охраной дворца и злодеем. И если пользователь играет эльфами то эльфы в лесу, домики деревяные набигают солдаты дворца и злодеи. Можно грабить корованы... И эльфу раз лесные то сделать так что там густой лес...
