### ISSUE TITLE
Feat: Контрабандист

### ISSUE THREAD

**Issue by MiFaust** [ss220-space/Paradise#364]
### Проблема

Добавить нового антага. Контрабандист. (Заного делаю ветку т.к. я дебил и закрыл ветку)

### Решение

Хотел бы немного порефлексировать над некоторыми механиками. (Возможно их не добавят, но все же) Можно сделать, что у него будет второй лицевой счет в банке, для переводов в синдикат. Так же он может принимать оплату телекристаллами, но их нужно будет передавать энд гемово, после прилета на ЦК. И как я думаю, ему нужно будет давать сумку кантробандиста раундстартом, а уже в ней будет рандомная кантробанда (ценовой диапозон вроде можно установить). Так же синдикат может напоминить, что использование довереных вещей в любых целях кроме продажи и показа возможностей товара запрещается.

### Плюсы

Один из немногих антагов который должен не убивать и насиловать пол сервера, а сдавать вещички синдиката по ценам и не спалиться.
Антаг направленный по большей части на РП (вы же знаете такое слово, мои маленькие щитокуры) составляющую.

### Минусы

Я дибил и закрыл предложку (не привык к вашим интернетам)

**Comment by Dreemer556** [comment]
Очень интересная идея, которая способна разбавить РП или проявить навыки главного взломщика ворюги. Хоть кто-то будет пиздить зажигалки или вещи клоуна

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184361801-c554d6c9-a6e2-45c8-ac6f-1fcae9c8db65.png)
