### ISSUE TITLE
Сканер аутопсии не регистрирует нового пациента, если оба unknown

### ISSUE THREAD

**Issue by MarshallPulse** [ss220-space/Paradise#366]
### Ckey

ImPulseF 

### Описание бага

При сканировании сначала одного трупа unknown, сканер не регистрирует нового пациента на другое тело с статусом unknown. 

### Шаги воспроизведения

1. Просканировать первый труп unknown 
2.  Получить лист с результатами для него
2. Просканировать второй труп unknown 
3. Получить листок с совмещённым результатом для обоих 

### Ожидаемое поведение

При сканировании второго трупа получить отдельный лист результатов. 

### Дополнительная информация

Проблема временно решается костылем с постройкой второго стола в морге и помещением на него мартышки, как промежуточного объекта сканирования.
~~~~~~
Был открыт тикет, принятый СА HonkSquadLeader

### Операционная система

Windows 7

### Версия клиента

514.1566

### Название сервера

MAIN

### Примерное время и дата

~15:00

**Comment by Ohar** [comment]
Так вот почему у меня смерти были одинаковыми у них...

**Comment by Bolmorr** [comment]
Нужно скальпелем его порезать, тогда обновляет
