### ISSUE TITLE
Feat: Counter Space : Armed Assault

### ISSUE THREAD

**Issue by OpsCoretango** [ss220-space/Paradise#370]
### Проблема

Люди не умеют в "воевать" и действовать в боевой обстановке, надоедает стабильность игрового процесса. 

### Решение

В конкретный день скажем в вечер Воскресенья запускать на Эксте,WL  ввиде ивента побоище в Thunderdrome или разработать  "случайную встречу" Нюк-Сквада с морпехами ТСФ на Лаваленде.
(Как раз у Нюкеров есть аванпост окруженный лавой который вырезали из билда т. е это еще потенциальный штурм) 

### Плюсы

Грамотность в отношении оружия и борьбы а также тактики, ознакомление с редким вооружением и предметами для среднего игрока,  веселье и отдых от постоянных дней на станции перед работой ИРЛ.

### Минусы

где это проводить? 
Кодить спавн и вообще копировать+редактировать карту под другим названием или обойтись ивентом с обычной сменой на станции.

Возможно точка зрения "а зачем это нужно если мне не хочется воевать и просто под чай заняться для себя новым опытом в моей профе. "

**Comment by zombie288** [comment]
1. За.
2. Весело, задорно, интересно. Но кодить никто не будет :(

**Comment by Dreemer556** [comment]
1. За.
2. Устраивать КС в один день недели всегда весело. Некоторые люди получат возможность получить интересный им геймплей и меньше устраивать КС-ки на мейне. Да и потренироваться тоже хочется

**Comment by OpsCoretango** [comment]
удаляю, автор уверовал в TGMC

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184361871-8fbeb24e-647a-449a-8ba1-fe98432727f3.png)

**Comment by VasilevAY** [comment]
> удаляю, автор уверовал в TGMC но если бы мог...

Не удалил
