### ISSUE TITLE
Feat: Шахтерская Action/Body Видеокамера

### ISSUE THREAD

**Issue by OpsCoretango** [ss220-space/Paradise#371]
### Проблема

Есть ситуации когда нужно оперативно передать информацию, что то задокументировать а на станции это подтвердить к примеру : смерть напарника, различных обитателей Лаваленда как Диона, Големы, Пеплоходы.
![Drift_Head_Strap_Mount_3_650х581_EE](https://user-images.githubusercontent.com/55478690/133843905-0fa96695-e05b-47a5-b39a-5b3c7e491024.png)

### Решение

Данная механика уже реализована в виде видеокамер у Киборгов поэтому паразитировать код реальная задача а спрайт взять из обычной белой камеры с красным огоньком.
Механика выглядит следующим образом - вы купили камеру в вендоре где-то внизу списка или изучили в РнД, включили её и повесили на капюшон/комбинезон/скафандр ( то есть эта видеокамера она как Аксессуар )

### Плюсы

Оперативная передача информации коллегам, слежение за работой шахтера, Покупая вы подтверждаете свое добровольное согласие на передачу информации вторым и третьим лицам отчего мета/кооп- антагонисты/агенты синдиката могут тебя "подкараулить".
То же СБ отправляя в каторгу может на тебя эту камеру повесить и следить за тобой не давая шанса сбежать.

### Минусы

Есть вопросы по текстурам, как реализовать это типа Нательный видеорегистратор или Экшн-Видеокамера но тогда вопрос если ты убираешь капюшон или скафандр в костюм?

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/1172
