### ISSUE TITLE
Feat: Omegaдиссей

### ISSUE THREAD

**Issue by OpsCoretango** [ss220-space/Paradise#372]
### Проблема

Бесполезный в плане использования мехо-шприцемет и альтернатив ему нет.

При 5-ти выбранных лекарств с активным пользованием слиппера неиспользуемые вещества забивают полностью хранилище химикатов и это чертовски бесит(вводишь ДТПА, он кончается а Каломель весь бак заполняет) .

Кратко, стоит технологическая проблема(РнД) и Одиссей по данному факту в этом уникален, у него отсутствует вариативность оборудования в его сфере деятельности как оперативное мед. обеспечение. Поэтому я выкладываю свои наработки из иссуев и предложки  **но учтите что тут стоит подойти методом "что-то возможно а другое нельзя" ** как у кораблей схема бронирования "Все или ничего".

### Решение

Апгрейд увеличения хранилища химикатов Одиссея в категории Misc. у Exosuit Fabricator или увеличить его до 100 юнитов.

Редизайн интерфейса Exosuit Sleeper вместо обычного белого листа с именами и цифрами сделать как в обычном Слиппере и дать возможность игроку самому решать сколько вводить веществ.

Модуль дефибриллятор. Очень нужно как воздух, не вылезая из меха поднимать людей. 
(лично я вместо Шприцемета бы и брал)

Лечащий луч (Healing Beam) из арсенала вооружения полевых медиков ТСФ от корпорации Vey-med являющийся аналогом шприцемету. Передает пациенту лучем в тело выбранные вамивещества без брут урона (шприцемет при попадании делает около 10-ти брут урона).
Также умеет анализировать химикаты. 
Уже есть в билде Парадайза кстати.
 
Манипулятор с гипоспреем. 
Как обычная такая титановая рука с интегрированным Гипоспреем. Принцип работы с возможностью изменять колличество дозы. 

### Плюсы

Вторая жизнь Одиссея?

### Минусы

Честно, не знаю поскольку вот данный иссуй ему уже пару месяцев но я считаю тут сторона баланса и много шкодить плюс рисовать текстуры.

**Comment by OpsCoretango** [comment]
На сегодня, я все.

**Comment by girafe969** [comment]
Ничего не понял, но очень интересно

**Comment by OpsCoretango** [comment]
> Ничего не понял, но очень интересно 

в каком моменте?

**Comment by OpsCoretango** [comment]
Иссуй отредактирован.

**Comment by ZmeionishW** [comment]
Шприцемет наносит вроде как 5 уурона брутом. Но я за, ибо одиссей в моих глазах нужен для 2-х вещей. Одна это омнизина из шприца СМО превратить в тонну, и вторая, это накачивать углем челов при токсичном блобе. Все.

**Comment by Slisenz** [comment]
1.за
2.соглашусь, сейчас Одиссей из себя представляет как машина для Фарма омнизина и вливания пациентам. Расширение функционала вдохнёт вторую жизнь в него , и возможно он перестанет стоят в медбее 24/7.
Как всегда осталось найти человека который будет кодить.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184362630-4505a1fb-1e01-4975-8e58-ca268c9ff0d7.png)
