### ISSUE TITLE
Bug: Антидроп и даблсворд

### ISSUE THREAD

**Issue by Liionessa** [ss220-space/Paradise#374]
### Ckey

liionessa

### Описание бага

Даблсворд не убирался из руки. Его нельзя было: выкинуть, убрать в рюкзак, карман, выронить через падение на землю или банан, а так же работал в стяжках.

### Шаги воспроизведения

1. Оглушение бипски. Даблсворд **не** падает из руки, но вторая рука становится активной.
2. После оглушение ЭМИ от желтого экстракта. Даблсворд **падает** из рук.
3. Поднимаю даблсворд, активирую антидроп (в чате ещё пишется что антидроп работает).
4. Роняет халк и делает мою вторую руку активной. Даблсворд при этом **не** падает из рук.

### Ожидаемое поведение

Даблсворд должен был убираться из рук. Антидроп должен был работать. Рука не должна была забагаться.

### Дополнительная информация

Мейн. Раунд 3680
https://www.youtube.com/watch?v=jOqmOaex8ks
![image](https://user-images.githubusercontent.com/91167740/134269813-46ef400a-f10f-4b44-8386-1739e1d76b87.png)

### Операционная система

windows 10

### Версия клиента

514.1566

### Название сервера

MAIN

### Примерное время и дата

~20:47

**Comment by HMBGERDO** [comment]
После ЭМИ антидроп имплант роняет предметы. После того, как ты второй раз взял даблесворд и активировал антидроп, повторного ЭМИ не было, судя по тексту. Если антидроп не был отключен вручную - ты не выронишь даблсворд, кроме как отрезанием руки. То, что вторая рука становится активной - не влияет на работу предмета, если не ошибаюсь
