### ISSUE TITLE
Bug: автовыбор имени заключённого

### ISSUE THREAD

**Issue by MarshallPulse** [ss220-space/Paradise#375]
### Ckey

ImPulseF

### Описание бага

При выборе имени из выпадающего списка в формате xxx xxxx'ов (Prisoner xx-xx) система не распознает заключённого и не ставит статусы incarcerated/realised автоматически. 

### Шаги воспроизведения

1. Посадить заключённого в камеру
2. Выбрать имя из списка в панели камеры
3. Наслаждаться криками ГСБ "почему не сняли арест?" 

### Ожидаемое поведение

Соотнесение персонажа и имени из панели с автоматической установкой статусов. 

### Операционная система

Windows 7

### Версия клиента

514.1566

### Название сервера

MAIN

### Примерное время и дата

~2:30 23.09

**Comment by Honker9999999** [comment]
Не баг. Ты и должен оставлять карту человека, разве что у него доступ к бригу есть. И если настоящее имя в меню кто арестован написать то оно снимет арест, хоть и не с карты зека.

**Comment by HMBGERDO** [comment]
У Prisoner #1337 не существует записи в Security records, поэтому и установить-снять арест система не может. Указывать нужно реальное имя заключенного. При этом если записи не будет, статусы также установлены не будут.

**Comment by MarshallPulse** [comment]
> Не баг. Ты и должен оставлять карту человека, разве что у него доступ к бригу есть. И если настоящее имя в меню кто арестован написать то оно снимет арест, хоть и не с карты зека.

![IMG_20210923_223351](https://user-images.githubusercontent.com/88078980/134572162-29251a31-b065-49d9-854e-f032868d3943.jpg)
Ну срп похоже зря писали. Оставлю карту

**Comment by MarshallPulse** [comment]
> У Prisoner #XXXX не существует записи в Security records, поэтому и установить-снять арест система не может. Указывать нужно реальное имя заключенного. При этом если записи не будет, статусы также установлены не будут.

Я не совсем про это. Система находит имя человека добавляя дополнительную надпись. Из-за чего новички в СБ(и не только) оставляют уже отсидевших со статусом ареста/заключения, так как автоматически он не меняется.
