### ISSUE TITLE
Добавить возможность увеличения времени текущему заключённому в камерах брига

### ISSUE THREAD

**Issue by AugustBebel** [ss220-space/Paradise#380]
### Проблема

При побеге из обычной камеры заключения КЗ требует сбросить таймер и добавить 10 минут. Сбросить таймер можно одной кнопкой на дисплее камеры, а вот добавить 10 минут проблематично, ведь такой кнопки нет. В итоге для добавления срока выполняются танцы с бубном:
1. Нажать «Выпустить заключённого» — при этом открывается дверь и шкаф с вещами.
2. Заново провести процедуру помещения в камеру (флеш, на кровать и станбатон)
3. Заново ввести преступления, имя зэка и уже здесь добавить злополучные 10 минут.
Есть ещё альтернативная процедура с настройкой пустующей камеры и пересадки зэка туда, но это всё та же проблема.

Все эти танцы из-за отсутствия одной кнопки замедляет процедуру посадки в камеру, в процессе подвергая риску офицера. 

### Решение

Добавить кнопку «Увеличить срок на…» и если офицер ей пользуется и добавляет время, то появлятеся окошко с преступлениями заключённого чтобы он мог их отредактировать, добавив новое (побег из камеры).

### Плюсы

Удобство для офицеров СБ которые и так обычно заняты толпой ассистух.

### Минусы

Щиткурити сможет накручивать сроки по желанию левой пятки. Но они и так это могут. На то и щиткурити.

**Comment by AttHawk** [comment]
1. За
2. Звучит кайфово и удобно, почему бы и нет

**Comment by Ohar** [comment]
Полностью за

**Comment by VasilevAY** [comment]
https://discord.com/channels/617003227182792704/618952559607939072/1007642412451110993
предложка оживлена
это закрывается как протухшая
