### ISSUE TITLE
Feat: 

### ISSUE THREAD

**Issue by GQ0k** [ss220-space/Paradise#381]
### Проблема

Предложение:
чуть-чуть переделать операции на Киданах. А точнее убрать этап скальпель-гемостат-ретрактор для ремонта костей(потому что у них скелет вместо кожи и нет необходимости лезть внутрь для ремонта) и добавить в операцию по устранению внутреннего кровотечения необходимость использовать циркулярку и в конце боунгель
Дополню свою предложку: добавить на все инвазивные операции необходимость в циркулярке и боунгеле, а такие как пластика и стоматология и им подобные оставить как прежде. Как вариант нёрфа из-за простого восстановления костей повысить их хрупкость(а-ля воксы)

### Решение

кодинг операций для кидан

### Плюсы

-Новые фишки у расы киданов
-(хоть какое-то)разнообразие в игре за хирурга
-Реализм?

### Минусы

-Кодить, павучается
-"Ряяяя, ты плахой доктор, не откачал меня вовремя"
-проблемы в балансе?
-больше, по сравнению с людьми, времени на операцию

**Comment by VasilevAY** [comment]
![Uploading image.png…]()
