### ISSUE TITLE
Изменение кодовых слов у Агентов

### ISSUE THREAD

**Issue by WonShooter** [ss220-space/Paradise#382]
### Проблема

Заучивание кодовых слов агентов, типо когда в начале смены видишь в рации "чёрного русского" и так далее ты сразу понимаешь что он агент и что сб за ним будет следить.

### Решение

Добавить возможность агентам самим писать в начале раунда одно кодовое слово и одно слово ответа. Они будут отображаться всем агентам в Notes.

### Плюсы

1. Большая вариативность слов для нахождения агентам друг-друга и выполнения целей, тем самым будет меньше ситуацией с хантингом фраз от сб и персонала. 
2. Поимка агента и раскрытие фраз сб будет не предсказуемо, так как когда ты отыграл достаточно игр на антаге ты будешь знать большинство этих фраз, а когда люди сами выбирают их, сб точно не будет знать он сказал правду или нет. Тем самым если антаг сказал правду, то его информация будет полезна для сб.

### Минусы

1. Возможен вариант грифа со стороны агентов, они могут записывать абсурдные или редко используемые слова, а ещё есть вариант что кто-то напишет набор букв.
2. Получается нужно будет покодить, чтобы ввести данную механику.

**Comment by botka4aet** [comment]
Не понимаю первого минуса.
Допустим 4 агента.
Каждый предлагает по 2 слова(запрос и ответ).
В итоге получается 4 кодовых слова и 4 ответа.
Если 1 гений написал белиберду, то все равно остается 3 слова и 3 ответа.
И даже когда 2 агента, то проблем нет. 2ой агент сразу видит, что в напарниках человек, на которого рассчитывать не стоит.

**Comment by WonShooter** [comment]
Я имел ввиду то что это вычёркивает возможные используемые слова, а так же это фактически ещё одна запара для админов

**Comment by botka4aet** [comment]
Окей. Как работает сейчас:

1. Перед запуском раунда сервер генерирует число от 2 до 5. Это означает количество слов.
2. Затем генерируются слова.
Должно быть 1 имя или профессия.
Должен быть 1 коктейль или локация.
Остальное добирается из прилагательных, существительных и глаголов
3. Полученные слова записываются в глобальные переменные.
4. Когда заходить антаг - ему объявляются слова.

Как можно сделать(как у меня вышло)

1. После запуска сервера начинается 5минутный таймер
2. Каждый зашедший трейтор получает 2 диалога с вводом желаемых слов.
2.1. Введённые слова проходят проверку. Только на русском, 1 слово, от 4 до 12 букв. Проверка не прошла - записывается случайное слово.
3. Если слова еще не были сгенерированы, то появится сообщение "Синдикат сообщит слова позже, начинайте разведку обстановки"
3. Указанные слова добавляются с список и логи(вдруг какой-то шутник добавит что-то смешное)
4. По истечению таймера генерирует число от 2 до 5. Из списка кодовых слов выбираются слова. Если слов меньше нужного, то генерируются случайные.
5. *TODO* Запретить в ответах появляться словам из запросов.
6. *TODO* Сообщить всем предателям слова.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184640361-dfb759ca-b427-45e2-8ac5-7143eafb6707.png)
