### ISSUE TITLE
Feat: Джукбоксы, бумбоксы и кассеты!

### ISSUE THREAD

**Issue by HolyGunCheck** [ss220-space/Paradise#384]
### Проблема

(Лучше поздно, чем никогда)
У нас есть кривой, сломанный и неудобный дискошар, единственные функции которого противно пищать, включать один из четырех одноминутных треков интервалом в 9 секунд и ломаться каждый второй раунд.

### Решение

Выпилить нах%й дискошар и заменить его на портированные с бея джукбоксы и бумбоксы.

### Плюсы

+ В джукбоксе можно удобно настраивать громкость музыки и переключать её в любой момент. 
+ Бумбокс аналогичен джукбоксу, но, в отличии от него, он переносной, его можно носить в руках и для работы ему требуется маленькая батарейка.
+ С помощью блюспейс-кассет, которые можно вставить как в ждукбокс так и в бумбокс, можно будет включать СВОИ треки! Т.е. загруженный с вашего ПК аудио-файл (mp3, m4a и пр.) размером не более 10 МБ. Только представьте себе: вы и ваши коллеги воюют с ядерными оперативниками под песню Летова "Убивать".

### Минусы

- Механ дискошара заставляет всех игроков поблизости танцевать. В случае с джукбоксом этого не будет (Хотя, никто не отменял пляски через спам "Rest" и "Examine")
- В случае, если будет играть трек загруженный через чей-либо ПК, то, если джукбокс первый раз попадет в вашу зону слышимости, произойдет короткий пролаг длиной в 3-8 секунд, ибо кастомный трек загружается и вы не сможете услышать его не загрузив. (Тут уже можно отключить загрузку кастомной музыки по предпочтению игрока.)
- Портировать - значит кодить. МНОГО кодить.
- Через блюспейс-кассету кто-то может включить Моргенштерна.

**Comment by Ohar** [comment]
Чел, единственный смысл диско-шара - анимация танца. Его музыка никому не нужна.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184640410-5f74a062-278b-4991-aeae-c0203d90ceec.png)
