### ISSUE TITLE
Слаймомен умирает внутри халка

### ISSUE THREAD

**Issue by WonShooter** [ss220-space/Paradise#385]
### Ckey

WonShooter

### Описание бага

Вчера был хонк-халком, меня сделал им генетик, моя раса слаймомен и по итогу пока я бегал хокером, моё тело умирало из-за гена халка, потом моё тело окончательно сдохло, проходив ещё минут 15-20 мёртвым, моего халка убили, а моё тело уже было достаточно сгнившим. Не понимаю так и должно быть? Или это какой-то баг

### Шаги воспроизведения

1. Выбрать расу слаймомена.
2. Генетик должен попытаться вколоть ген халка (Я не силён в генетике, но он мне множество раз пытался вколоть, как выяснилось там процент срабатывания есть).
3. Пока мы бегаем халком тело умирает.

### Ожидаемое поведение

Не должно было смерти носителя или хотя бы должен умирать сам халк, а не оригинальное тело.

### Операционная система

Windows 10

### Версия клиента

513.1542

### Название сервера

MAIN

### Примерное время и дата

30.09.2021 14:00 - 15:00 по МСК

**Comment by Leck-Ti** [comment]
слаймомены тут не причем, когда игрок использует ген халка он берет под контроль симпл моба, а его прошлая кукла условно находится внутри моба, где нет атмосферы из-за чего кукла начинает умирать от гипоксии или от голода.
есть два способа избежать плохого исхода, простой и сложный: 
1. просто перед применением гена надеть кислородный болон и маску.
2. использовать гены: "хладостойкости" и "не дыхания", а также установить имплант помпа + (что подарит возможность не помереть от голода)
является ли это багом? да.
будут ли это фиксить? не в ближайшее время

**Comment by botka4aet** [comment]
Ну или не быть по долгу халком
Надо создать багрепорт на тау, дождаться решения, стянуть его себе

зы. Если кто-то в ближайшем будущем(~неделя) возьмется править - напишите. Взаимоуважение, все дела
