### ISSUE TITLE
Feat: Рофлостаны

### ISSUE THREAD

**Issue by Jordanstolethepreciousslam** [ss220-space/Paradise#388]
### Проблема

Текущие станы пары довольно... специфичны, и зачастую вызывают фрустрацию у игроков просто своей механикой. Многие бои заканчиваются при первом же попадании стан оружием, что сводит всю боевку к "кто первый попал летающей сверкающий мочой или электропогонялкой скота". Есть несколько исключений в которых необходимо другое оружие, и зачастую это редкие предметы тритора такие как Карп, Адренал, Стимуляторы и Двойные Мечи. Но Карп и Мечи вполне контряться теми же станами только в профиль(батоны, смазка), а стимуляторы и адренал просто скучные, и могут быть заменены смесью наркоты из РнД или химии. 

Текущие станы явно созданы для того чтобы играть одной рукой, ибо задержание любого опасного преступника живьем происходит в три клика - дубинка\тазер+смена руки+ клик наручниками. 
Станы также хотят понерфить и оффы, но они хотят это сделать это довольно давно и всё еще не сдвинулись с места.

### Решение

Замержить ПР с нерфом станов(https://github.com/ss220-space/Paradise/pull/161).
Может только в мейн, может только в ВЛ. Может сразу в оба. На усмотрение админов.

Вкратце - Изменения станов СБ, антагов, обычных источников стана, наркотиков, имплантов, пара изменений вампиру не касающиеся станов(что может вызвать проблемы ведь оффы вводят совершенно новых вампиров). Эти изменения в основном сводятся к тому что станы урезаны до почти нулевых значений, и добавлен стамина урон, который даст нормальный стан после нескольких попаданий. Также изменения урона некоторого летального оружия и улучшение бол.

### Плюсы

+Новая боевка. Я немного сменил баланс, но основное изменение это просто удлинение и усложнение боёв со станами.

### Минусы

-Этот ПР крайне неказист. Я не опытный разработчик, а потому я не могу предложить впечатляющего решения, как могут разработчики оффов.
-Этот ПР так и не прошел тестирование правильным образом. Несмотря на то что он был на тестовом сервере, всего лишь пара человек зашли опробовать их на пару минут и я так и не получил представление о том что рабоает/не работает.
-Этот ПР может содержать серьезные проблемы с балансом. Я пытаюсь сгладить возможные углы, но я просто не получаю обратную связь.
-Из-за природы этого ПРа, вероятно большое количество смертей в игре, так как летальное оружие становится гораздо предпочтительнее во многих ситуациях. Это может вызвать проблемы с правилами и тонны жалоб и нарушений.
-СБ будет сложнее. Несмотря на то что этот ПР ослабляет почти все источники станов, СБ будут иметь проблемы из-за того как у нас игроки отыгрывают взаимодействие с СБ. Любой ценой вырваться и сбежать даже если тебя посадили на 5 минут это за милую душу. Сейчас десяток сбегающих это не проблема из-за сильных станов, но когда все эти люди потребуют по 4-5 попаданий это приведет к неравноценной трате сил игроков на СБ.
-Этот ПР - Временное решение. Он будет заменен как только оффы сделают своё эффективное решение баланса станов. В конечном счёте привыкание к этим станам может быть пустой тратой времени ведь выйдет нормальное решение.

**Comment by Whygil** [comment]
1. За
2. Я чисто физически не понимаю почему это ещё не ввели, наконец-то будет разнообразие в боях и некоторая доля баланса.

**Comment by LoveTrapov** [comment]
Для тех кто не умеет читать и воняет про карпа, которого якобы не возможно будет поймать. https://github.com/ss220-space/Paradise/pull/161#issuecomment-884812723

**Comment by Jordanstolethepreciousslam** [comment]
Просто чела с карпом поймать будет так же просто как и раньше. А вот чела с карпом и под метом... Ну это будет реальный геморрой. Если конечно люди не вспомнят что самодельный арбалет и пневмопушка игнорят блок карпа. Хотя поощрение разумизма на СБ это не прям чтобы хорошее дело.

**Comment by LoveTrapov** [comment]
Если вдруг это будет проблемой, ну потому что я не думаю что много кто будет этим пользоваться, но даже если вдруг и будут, я думаю это можно будет быстро пофиксить. Типы то воняют просто на тему карпа, видимо не понимая что батон как и раньше будет с тычки сбивать с ног, просто не на долго.

**Comment by Jordanstolethepreciousslam** [comment]
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7487899/Changelog.txt)

**Comment by Jordanstolethepreciousslam** [comment]
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7532255/Changelog.txt)

**Comment by Gnatr** [comment]
Энерготопор станит сильнее чем все остальное, ладно

**Comment by Jordanstolethepreciousslam** [comment]
[Changelog.txt](https://github.com/ss220-space/Paradise/files/7546276/Changelog.txt)

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/161
merged
