### ISSUE TITLE
Feat: MONKI FLIP

### ISSUE THREAD

**Issue by internetclient** [ss220-space/Paradise#389]
### Проблема

Сейчас большинство взрывается ошмётками, если генетик устанавливает в тело S.E. блок 55 выше 800 или если неосторожный админ случайно жмёт кнопку monkeyize.

### Решение

Из-за этого предлагаю cделать почти для каждой расы свою низшую форму.

Уже есть в игре:
**Человек** - обезьяна;
**Скрелл** - неара;
**Таяран** - фарва;
**Вульпканин** - волпин;
**Унати** - сток;

Ещё нет в игре (взрываются при превращении):
**Вокс** - разумный попугай/сделать ещё одну версию обезьяны;
**Драск** - сделать ещё одну версию обезьяны;
**Плазмомен** - сделать S.E. блок 55 невозможным к модификации каким-либо образом;
**Слизнемен** - разумный светло-розовый слайм-ребёнок;
**Грей** - абдуктор;
**Абдуктор** - изначально начинают с S.E. блоком 55 >800 (т.е. фактически являются животными), перевод блока в состояние <800 превращает абдуктора в грея;
**Диона и диона Лаваленда (да, это два разных моба)** - нимфа;
**Врин** - сделать ещё одну версию обезьяны;
**Тенеморф** - тень;
**Тень** - изначально начинают с S.E. блоком 55 >800 (т.е. фактически являются животными), перевод блока в состояние <800 превращает тень в тенеморфа;
**Нуклеация** - больший взрыв, чем при обыкновенной смерти (0, 2, 4, 0);
**Свободный голем** - превращается в порабощенного голема, хозяином выбирается наиболее близко находящийся в момент порабощения гуманоид;
**Голем-раб** - изначально начинают с S.E. блоком 55 >800 (т.е. фактически являются животными), перевод блока в состояние <800 превращает порабощённого голема в полностью свободного голема;
**Скелет** - сделать страшную макаку-скелета;
**Кидан** - сделать ещё одну версию обезьяны;

**Чужие** - их почему-то можно запихнуть в камеру для генетического модифицирования, хотя если взаимодействовать с консолью, то игра выдаст ошибку. Нужно запретить запихивать их в аппарат.

Придётся также разрешить светло-розовым слизням, нимфам и попугаям (если выбор таки падёт на них, а не на свою макаку для воксов) иметь свои гены и влезать в аппарат генетика. Как - я не знаю.

P.S. КПБ уже не поддаются генетической модификации никак, поэтому их нет в списке.

### Плюсы

Разнообразие, круто, класс.

Генетиком играть немного интереснее.

Ходить к генетику тоже немного интереснее.

Никакие превращения не дают право на самоантагонизм.

Теперь свободным големам будет ещё одна причина не соваться на станцию - злой дядя-генетик подчинит своей воле.

### Минусы

Таинственные ритуалы написания программного кода.

Возможно шатание баланса, особенно для слизнеменов. Для них превращение в обычного слизня может стать опцией "минихалка", пока генетик не нашёл этот самый ген халка.

**Comment by Dreemer556** [comment]
1. За
2. Идея огонь, я всегда за углубление и так глубокой игры, но скорее всего предложка умэр. А жаль

**Comment by girafe969** [comment]
1. По большинству пунктов против
2. Воксы и греи/абдукторы - искусственно выведенные существа, у них нет низшей расы, потому что они не эволюционировали. 
Ну, про големов очевидно что ДНК вообще не причем. 
У слаймов вроде тоже нет ДНК (по идее их вообще должно быть невозможно пихать в машину).
Про тенеморфов то же самое что и про големов
Диона это как бы и есть нимфы... Из 50+ нимф делать одну путем изменения ДНК? Звучит логично (нет).
Разрывы плазмаменов при изменении блока это фича (ну рофельно же).
Скелет... Ну, можно сделать, чё, забавно. Особенно учитывая что про них нет никакого Лора и сама раса по сути фича.
А киданов, вринов и драсков да, согласен, стоит добавить

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184640592-1e7a60b1-0b1f-4713-adeb-388d93e8a876.png)
