### ISSUE TITLE
Feat: Маркировка проводов

### ISSUE THREAD

**Issue by MaliciousPancake** [ss220-space/Paradise#395]
### Проблема

Довольно странно, что инженеры, прибывая на космическую исследовательскую станцию, не знают устройства проводки шлюзов, а именно какой провод за что отвечает.

### Решение

Добавить в кабинет СЕ лист бумаги, аля "Инструкция по эксплуатации электроники на ИСН", в котором будет содержаться обозначение цветов проводов и их предназначение для шлюзов, торговых автоматов и автолатов. Этот листок СЕ может в дальнейшем копировать и распределить по инженерам.

### Плюсы

1. Больше логики в работе инженеров
2. Упрощение работы инженеров

### Минусы

1. Инженеров будут пиздить не только ради изолек, но и ради этого листа

**Comment by normie5-cell** [comment]
https://tgstation13.org/wiki/Skillchips

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184640641-93348015-d31b-471d-8a51-ebabb2ab15a2.png)
