### ISSUE TITLE
Feat: Добавить права механика Свободным големам и Чарли станции

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#401]
### Проблема

Что на Чарли станции, что у Свободных големов одна и та же беда - нет прав на фабрикатор подов. 

Големы сами по себе являются исследовательскими мобами, их шатл спокойно может летать в космос, и тот факт что они не могут делать поды расстраивает всех кто узнаёт о таком косяке с правами. Вместо подов делают костыльного Кларка чтобы летать как на поде используя трастеры и это совсем не круто, к тому же, ведь при выходе из меха с голема падает вся снаряга кроме рюкзака и шмоток надетых на голема.

Чарли станция так же не обладает доступом к фабрикатору подов, хотя их консоль, кажется, имеет общий доступ. Если игрокам совсем не повезет и они не найдут ресурсы для побега, а станция не ответит на запрос помощи - всё что остаётся это брать огнетушитель или ещё что, и улетать со станции автостопом, либо ждать отключения. Тоже хреново, при том что есть ресурсы чтобы сделать под и улететь, но из-за доступа нельзя. И да, на станции 100% кончится энергия ибо двигатель сингулярности и/или щиты сломаны и не сдерживают сингулярность внутри, она просто перешагивает их визуально работающие поля и гг всем на станции. Соляр не хватит так же.

### Решение

Прописать в карты Чарли и/или Големов права Механика. Но можно и иначе дать доступ...

Либо:
На Чарли станции в рнд добавить под фабрикатор открытого доступа. Или добавить фабрикатор в карту в рнд отдел или ещё куда-либо.

Големам добавить плату фабрикатора подов в кит Liberator's Legacy kit

### Плюсы

На Големах будет веселее. Получат настоящий статус "Свободных" големов - Свободных исследователей, какой им и положен по праву их существования в игре.

Чарли станция сможет свалить если на неё положат болт и не повезёт с рудой.

И другие плюсы можно вывести если подумать, но очевидные указаны выше.

### Минусы

[classified]

Кто хочет тот сам сможет придумать беды из этого улучшения, что, в принципе, есть у любой вещи в этой игре.

**Comment by VictorSocks** [comment]
1. За
Давно пора дать доступ големам и тетовцам к подам. Смысла не давать просто нет.

**Comment by Gnatr** [comment]
> 1. Против
> 2. Гост роли, лутающие весь космос? Нет спасибо.

Големы и без пода могут все прекрасно лутать, только вот бох нужен и рюкзаки

**Comment by snipersir** [comment]
> 2. Гост роли, лутающие весь космос? Нет спасибо.

Механ летает лутать весь космос в начале смены, разведчики летают лутать весь космос в начале смены. Големам ещё надо запасти ресурсы, построить поды, выгнать поды наружу (в одиночку это ещё веселее) и летать в космосе без магбутов на сраном спрее, без оружия дальнего боя (это если прям рваться и не накопить/сделать КА и купить модуль к нему). А ещё выходя из пода не проёбывать ключи карту пояс и прочую херь по дороге когда место в портфеле/бохе не резиновое. Ты о чём?

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184640718-d63377f9-be4f-49e7-b0d7-53921267a3a5.png)
