### ISSUE TITLE
Feat: Решение вопроса с боеприпасами дробовика

### ISSUE THREAD

**Issue by terribaum** [ss220-space/Paradise#403]
### Проблема

В данный момент кастомные боеприпасы на дробовик не используются от слова никак. Как по мне, пора уже решить вопрос с ними.

### Решение

Либо скинуть возможность их крафта в протолат РНД с последующими правками в СРП (В стиле "Печатать можно только в красный").Либо же удалить их совсем и навсегда ибо не используются.

### Плюсы

Расширение арсенала путем перекройки боеприпасов. Теперь будут кучи боеприпасов на дробовик под разные задачи.

### Минусы

Технически-баф СБ.А так же возможность бармену отстрелить клоуну ногу взрывными боеприпасами.

**Comment by Gnatr** [comment]
Либо оставить либо вырезать, ибо в протолате они выйдут на уровень имба ботаники из за самопал дробовиков

**Comment by terribaum** [comment]
> Очевидно что пункт "либо удалить их совсем навсегда" там сделан просто чтобы второй выбор казался предпочтительнее. Не нужно тут психологические трюки в предложке использовать

По факту решают кодеры. Это лишь предложение. Если им будет западло-то они удалят.

**Comment by VictorSocks** [comment]
А зачем добавлять их в протолат? Как бы все патроны кастомные крафтятся с помощью меню крафта. То что кто-то этим не пользуется их проблемы, мне на антаге или сб будет проще со станслагами и фраг12.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184640760-c43d7ba6-454c-40fd-874d-84a017340b87.png)
