### ISSUE TITLE
Feat: перенести систему навыков с инфинити на мейн

### ISSUE THREAD

**Issue by Sykybekk** [ss220-space/Paradise#406]
### Проблема

На данный момент, никаких ограничений в действиях не существует и это сильно снижает уровень взаимодействия между персоналом станции и тем самым само количество рп-ситуаций, а также в придачу частое нарушение правила 3.3 "Ограничения на профессиональные навыки". Именно поэтому и предлагаю такую систему перенести к нам. Чтобы больше не было учёных, которые самостоятельно перестраивают свои отделы с нуля; шахтёров, что шарят в рнд, лучше самих работников рнд и т.п

### Решение

Закодить самостоятельную версию данной системы, либо попробывать портировать с другого билда (инфинити, колониальный маринад)

### Плюсы

Повыситься количество рп-взаимодействий, реже будет нарушаться правило 3.3

### Минусы

Новые ограничения

**Comment by Whygil** [comment]
1. Против
2. Господи, может нам космос ещё с фиников взять? Это конечно очень круто, но вы понимаете СКОЛЬКО нужно будет кодить? Кто это будет делать? Вы?

**Comment by Sykybekk** [comment]
> 1. Против
> 2. Господи, может нам космос ещё с фиников взять? Это конечно очень круто, но вы понимаете СКОЛЬКО нужно будет кодить? Кто это будет делать? Вы?

если никакой гений, который взялся это делать за 2-3 дня до этой предложки не объявиться, то я

**Comment by DROZD-01** [comment]
1. Против.
2. Ёмаё, любители фиников, делали б уже сразу предложку вместо парадиза на мейн финики завести. Ограничения на проф. навыки это весело, модно и молодёжно, но у нас тупо не всегда нужные профы есть онлайн, а в случае мейна сервак будет выть от срочников на различных должностях без адекватно быстрого способа их заменять. Если хотите обосновать это по РП, то я уже предлагал сделать создаваемые библиотекарем и заверяемые главами (чтобы нельзя было их совсем уж бесконтрольно штамповать) книжки-"гайды", которые будут софт-локом на определённые знания (Активировал - официально имеешь знания. Не активировал - ну пеняй на себя при разборе очередной жалобы)

**Comment by DROZD-01** [comment]
> 100+ тел, нам нехвает должностей. Тогда давай предложи что-то, что решит повсеместную проблему с постоянным нарушением правила 3.3

Может быть тогда не только первую строчку прочитаешь, а?

**Comment by Sykybekk** [comment]
> > 100+ тел, нам нехвает должностей. Тогда давай предложи что-то, что решит повсеместную проблему с постоянным нарушением правила 3.3
> 
> Может быть тогда не только первую строчку прочитаешь, а?

ну так, ты мне дашь нормальное предложение, что решит повсеместную проблему с постоянным нарушением правила 3.3? Ммм, критикуешь предлагай

**Comment by DROZD-01** [comment]
> > > 100+ тел, нам нехвает должностей. Тогда давай предложи что-то, что решит повсеместную проблему с постоянным нарушением правила 3.3
> > 
> > 
> > Может быть тогда не только первую строчку прочитаешь, а?
> 
> ну так, ты мне дашь нормальное предложение, что решит повсеместную проблему с постоянным нарушением правила 3.3? Ммм, критикуешь предлагай

**Если хотите обосновать это по РП, то я уже предлагал сделать создаваемые библиотекарем и заверяемые главами (чтобы нельзя было их совсем уж бесконтрольно штамповать) книжки-"гайды", которые будут софт-локом на определённые знания (Активировал - официально имеешь знания. Не активировал - ну пеняй на себя при разборе очередной жалобы)**

Специально для тех, кто не читает дальше первой строки

**Comment by botka4aet** [comment]
Есть правила сервера.
Кто-то делает то, что не должен(при наличии того, кто это МОЖЕТ сделать) - бан.
Опять же теперь нельзя будет менять профу.

Идея говна.

**Comment by zombie288** [comment]
1. За
2. Народ ноет - значит предложка годная. 
"Рррряяяяя почему моя вульпочка 17(30) лет капитан не может запустить генератор сингулярности при наличии 10 инженеров, у неё же 8 высших образований"
Я обязательно доживу до момента, когда прекрасный билд парадайз дропнут и перейдут на нормальный, с нормальными правилами и механиками.
Рул 3.3 у нас впринципе не работает, btw.
Вот бы систему скилов с фиников :PepeChill:

**Comment by botka4aet** [comment]
> нормальными правилами и механиками.
Ну да, ну да. Я поиграл на оффе.
Там так же хуево с правилами и их соблюдением.
А механики...
Админу не нравятся взрывные томаты? Выпиливаем.
Админу не нравятся механики со спейсподами? Выпиливаем.

Гуд стори, бро.

**Comment by VictorSocks** [comment]
1. За
2. Меня нагибают и папки и казуалы, но навыки это круто. Больше не будет вульп которые умеют все подряд потому что им 30 лет.
