### ISSUE TITLE
Feat: Мини-апдейт радиопоста Синдиката(Дереликт).

### ISSUE THREAD

**Issue by RedLight912** [ss220-space/Paradise#408]
### Проблема

Мне...Ой...Нам нужна консоль мониторинга камер станции на Дереликт. Ибо топать в РНД за платой, немного подозрительно, да и лень.

### Решение

Просто воткните один обьект в редакторе, лол.

### Плюсы

+Немного разнообразит геймплей за механика/космо-шахтёра. Также можно потроллить ИИ/Глав/СБ/%insert_name%.

### Минусы

-Может быть, вышеперечисленным ролям не понравятся такие рофлы,впрочем, это разноообразит РП.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184362374-506df485-634f-4c99-804e-534f977c31ca.png)
