### ISSUE TITLE
Feat: Увеличить дальность и длительность T-ray Scanner'а

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#410]
### Проблема

Им сложно работать в текущем варианте. Подсвечиваются только тайлы вокруг себя, чего мало когда ищешь обрывы, поврежденные трубы вырванные из под плитки вихрем, да и в целом подсветка работает 1 секунду, еле хватает времени понять что ты видишь в этот промежуток.
![bad](https://user-images.githubusercontent.com/25121334/138218858-27854bb6-5cfe-4cca-be4d-bf0ce465836e.PNG)

### Решение

Увеличить дальность и длительность скана. На оф сборке уже увеличили дальность. Увеличение длительности на 0,5-1 секунду возможно тоже не помешает.
![good](https://user-images.githubusercontent.com/25121334/138218978-11e60012-bc40-4c89-8b6f-3f9c84f5eb65.PNG)

### Плюсы

Повреждения от аномалий, взрывов будет проще выявлять, скорость обработки "подпольных" проблем станет выше ибо их станет проще видеть

### Минусы

Асистухи будут выносить мозг ходя с этими сканерами?

**Comment by normie5-cell** [comment]
За
