### ISSUE TITLE
Feat: Выпилить лозу с Эксты

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#413]
### Проблема

Лоза в её текущем варианте ломает смену по кд из-за нулевого онлайна. Каждый день новая смена постоянно из-за лозы. Она выходит за сектор, она заходит на границу перехода сектора, иногда ломается так что даже админы не могут её выпилить. И она впринципе портит игру когда люди уходят в ссд на ночь или по делам задумывая что-то грандиозное или сложное, что за раз не сделать.

### Решение

Уменьшить рандомный спавн до нуля, либо установить на ноль. Никому она не нужна впринципе, её могут спецом вывести и исследовать. РВ сказал что фикс не сработал на защиту границы сектора от лозы.

### Плюсы

Люди будут чаще играть на Эксте не опасаясь что обычный микро эвент без игроков убьёт всю станцию за час и не заруинит смену "с большими планами".

### Минусы

???...
Разве, что гостанутые больше не вернутся в игру пока рак на горе не свистнет и сервер эксты не хватит с этого инфаркт.

**Comment by botka4aet** [comment]
За эксту отвечает РВ
Пиши ему в личку и проси
![image](https://user-images.githubusercontent.com/11385249/140635499-7a0c1817-5355-4854-bbe7-63f44469f839.png)

**Comment by VasilevAY** [comment]
![Uploading image.png…]()
