### ISSUE TITLE
Feat: Сделать всем боргам нормальный маяк GPS

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#414]
### Проблема

Некоторые борги теряются в космосе, на лаваленде в камнях или ещё где, стоя разбитые, без батареи, без питания, когда как получится. Консоль киборгов работает только в секторе, где она стоит. Недавно был случай когда СБшный борг улетел в камни лаваленда, почти в самый конец карты. Всё что оставалось ему - гостануться. Его искали 40 минут пока не кончился раунд на мейне.

### Решение

Всем боргам добавить нормальный GPS, чтобы их всегда могли найти если они пропадают с радаров. Сейчас можно включать и выключать GPS. Если борг будет синди или ломаный - может его сам выключить. На панельке или в инструментарии или в модулях. Где лучше будет, как лучше будет его сделать.

### Плюсы

Люди на разбитых и потеряных боргах не будут гостоваться из-за невозможности умереть до конца. Борги улетевшие в камни на лаваленде, почти мертвые в космосе и пропавшие как-либо ещё не будут безнадежно ждать чуда.

### Минусы

Возможно, придётся привыкать проверять GPS маячок, если он будет включаться по дефолту при старте на киборге или взломе.

**Comment by AgeofCreatons** [comment]
А это не будет палевом когда у тебя борг с радара пропадает?
