### ISSUE TITLE
Feat: Каторжники как работа раундстартом

### ISSUE THREAD

**Issue by XaycBC** [ss220-space/Paradise#418]
### Проблема

На данный момент каторга используется раз в никогда и мы имеем огромный онлайн цивилов-ассистух которые не занимаются ничем, кроме как доебыванием ГП по рации.

### Решение

Добавить в список профессий "каторжник" и "пермабриговец" со спавном в соответствующих местах и с соответствующей экипировкой. И та и другая роль отличная для новичков чтобы поиграться с основами игры никому ничем не мешая. Можно даже прикрутить N количество поинтов необходимых для освобождения. Благо автоматы для этого уже есть.

### Плюсы

+ новая и расслабленная роль для совсем новичков
+ интересная роль для хардкорщиков (по аналогу спавна на разьебанной станции, где криокамеры ещё)
+ и первые и вторые будут сидеть в своем мирке и не заебывать персонал

### Минусы

- нужно кодить (?)

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184640948-d54dc05e-b902-478b-8fd4-061f0d77a306.png)
