### ISSUE TITLE
Feat: Зажать рот кукле, закрыть глаза и другие плюшки

### ISSUE THREAD

**Issue by azorko9695** [ss220-space/Paradise#420]
### Проблема

Мало функционала в грабах

### Решение

![image](https://user-images.githubusercontent.com/45846852/139967631-e825c4e8-b569-4f54-9403-ca1dcdf3e3b5.png)

Взять да и позаимствовать все отсюда
Билд инфинити, вроде как

### Плюсы

Больший простор для отыгрыша 
Новые интересные ситуации
Новые возможности
Здравый смысл: почему так тяжело (невозможно) просто зажать кому-нибудь рот, к примеру

### Минусы

Кодить я не буду

**Comment by Jordanstolethepreciousslam** [comment]
Минусы - безбалансно. Слишком просто незаметно похитить цель. Сейчас антаги либо делают перфу, либо юзают ЕМП, либо мутстинг либо гарроту либо кидают в сон CQC. Если каждый бомж сможет голыми руками делать человека абсолютно беспомощным куском мяса который даже позвать на помощь не может, то это сильно ударит по эффективности СБ и глав. У нас уже давно есть этот готовый код, он просто отключен из-за проблем с балансом.
