### ISSUE TITLE
Bug: Сломан рендеринг карт с помощью dmm-tools

### ISSUE THREAD

**Issue by tizer7** [ss220-space/Paradise#421]
### Ckey

tizer7

### Описание бага

Коммит #289 сделал невозможным рендеринг карт дельты и кибериады. 
Начиная с него и по настоящее время невозможно зарендерить карты с помощью dmm-tools из [SpacemanDMM](https://github.com/SpaceManiac/SpacemanDMM). dmm-tools сообщает об ошибке.

### Шаги воспроизведения

Скачиваем билд из коммита 289 или используем текущий. Скачиваем [dmm-tools](https://github.com/SpaceManiac/SpacemanDMM/releases), копируем в корень билда с paradise.dme. Запускаем c параметрами: 
dmm-tools.exe minimap "путь к карте"
Получаем ошибку.
![image](https://user-images.githubusercontent.com/87470137/140010771-6e4e592a-b332-4a8b-8181-39731ad0970e.png)

### Ожидаемое поведение

Делаем всё выше с билдом на базе коммита #286 или ниже:
PS D:\Paradise-a717c9d1942333cdfecf1ab940a4410532915ebf> .\dmm-tools.exe minimap "D:\Paradise-a717c9d1942333cdfecf1ab940a4410532915ebf\_maps\map_files\Delta\delta.dmm"
parsing paradise.dme
D:\Paradise-a717c9d1942333cdfecf1ab940a4410532915ebf\_maps\map_files\Delta\delta.dmm
    rendering from 1,1,1 to 255,255,1
    generating z=1

...

saving data/minimaps/delta-1.png
Получаем изображение карты.

### Дополнительная информация

dmm-tools v. 1.3.1

### Операционная система

Windows 10 21H1

### Версия клиента

513.1542, 514.1569

### Название сервера

MAIN

### Примерное время и дата

**.09.21

**Comment by dj-34** [comment]
Подтверждаю, такая проблема есть и на моей стороне.
![image](https://user-images.githubusercontent.com/20109643/140079121-91e7e113-ae67-4beb-8e52-c9475a05e7dd.png)
