### ISSUE TITLE
Feat: Небольшое расширение КЗ и СРП для журналиста, библиотекаря и отдела сервиса.

### ISSUE THREAD

**Issue by VelhiorH** [ss220-space/Paradise#430]
### Проблема

Предложение: 
Дополнить КЗ и СРП для библиотекаря и журналиста положениями о журналистике как таковой.
На текущий моент библиотекарь и журналист - довольно бесправные создания, а первый так еще и скука смертная. Если попадется душный ГП то тут совсем печаль - не даст вообще ничего делать. 

### Решение

Предлагаю дополнить СРП следующим образом:
Журналист или библиотекарь в уведомительном порядке могут зарегистрироваться у ГП в качестве главного редактора издания. Для этого новоиспеченный главред должен предоставить следующие данные - тематику издания (информационное, рекреативное, литературное, кулинарное и пр.), название издания и его устав - внутренний распорядок и свод правил. ГП обязан оповестить персонал о создании редакции после того как главный редактор предоставит ГП устав редакции - внутренний распорядок и правила, действующие внутри редакции. Первый материал размещенный изданием - это всегда устав редакции. На станции может присутствовать только одна редакция одновременно.

Главный редактор в праве набирать себе до 3 корреспонедентов из состава отдела Сервиса или цивилов. Корреспонденты регистрируются у ГП и получают бумаги подтверждающие что они собственно являются корреспондентами - с подписью главреда и ГП. Служащие отдела сервиса при этом не должны забывать о своем СРП. Главред может запросить расширение доступа для корреспондента.

СБ и ГП не в праве препятствовать выполнению журналистской деятельности если та не противоречит КЗ. Если корреспондент нарушает какое-либо из уставных правил редакции - главред имеет право лишить его карточки корреспондента. Если устав нарушает главред - ГП в праве назначить нового главреда. 

Главред занимается проверкой и публикацией материалов которые ему приносят корреспонденты, консультируется с ГП если материалы касаются глав станции, а также занимается выдачей редакционных заданий - документов подтверждающих что тот или иной корреспондент действительно послан к тому-то и тому-то. По редакционному заданию корреспондент может быть направлен взять интервью, сопровождать патруль СБ (уведомительный порядок) или детектива (если тот даст согласие), присутствовать на судебных заседаниях или даже проводить независимое расследование какого-либо происшествия в рамках КЗ - опрашивать свидетелей и потерпевших, запрашивать результаты экспертиз и пр., посещать любые отделы станции предварительно уведомив персонал этих отделов.  

В зеленый код - журналист в праве свободно перемещаться по станции, вести журналистскую деятельность.

В синий код - журналист в праве перемещаться по станции исключая технические помещения, может запросить простейший бронежилет.

В красный код - журналист имеет право осуществлять журналистскую деятельность только при наличии редакционного задания. Журналист обязан использовать бронежилет если он сопровождает СБ. 

Соответственно придется дополнить КЗ статьей о препятствии работе журналиста по которой могут отлететь даже офицеры СБ. Разумеется легкое наказание вроде короткого заключения,  дисциплинарного взыскания и т.п. Если работе журналиста пытается препятствовать ГСБ - магистрат выносит вердикт о целесообразности решения ГСБ.

### Плюсы

Плюсы: 
+ Журналистам станет проще играть и понимать что они могут, а что нет. Чуть меньше хаоса, меньше бесправия.
+ СБ придется думать что они творят - любое превышение полномочий будет довольно быстро доходить до начальства.
+ Роли сервиса вроде барбера, психолога и пр получат дополнительные возможности для отыгрыша и занятий. Не придется творить совсем уж откровенную дичь чтобы развлечься.
+ У антагов будет больше пространства для действий.
+ Не надо кодить - всего-лишь добавить пару строк на вики.
+ Интересные РП взаимодействия.

### Минусы

Минусы:
- СБ придется думать что они творят
- Придется дописать несколько строк на вики
- У ГП будет чуть больше работы
- У антагов будет больше пространства для действий

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184641035-29ed7fcc-8cf4-41ff-927c-455f8ae64dee.png)
