### ISSUE TITLE
Bug: Не работает Электрогитара.

### ISSUE THREAD

**Issue by OrangeBirdx** [ss220-space/Paradise#435]
### Ckey

OrangeBird

### Описание бага

При воспроизведении не работает звук Электрогитары, когда остальные инструменты - работают.
На Официальной Сборке та же проблема, возможно ли исправить чужую ошибку, чтобы угодить своим игрокам?

### Шаги воспроизведения

1. Взять электрогитару
2. Вписать песню,ноты
3. Нажать произведение
4. Звук не идёт :(

### Ожидаемое поведение

Должны были проигрываться аккорды, ноты, но такового не случилось. Вместо этого бесконечное молчание от Музыкального инструмента.

### Дополнительная информация

Не работает ИМЕННО на Сервере WL, на локальном билде всё прекрасно работает, проблема встречается и на Кибериаде, и на Керберосе.

### Операционная система

Windows 10

### Версия клиента

514.1569

### Название сервера

WL

### Примерное время и дата

Всегда было

**Comment by tizer7** [comment]
На локалке с последним билдом работает.

https://user-images.githubusercontent.com/87470137/140845508-495307e9-4487-4dac-9c72-8e225a476e2c.mp4

.

**Comment by botka4aet** [comment]
А теперь зайди на WL и там попробуй

**Comment by tizer7** [comment]
хмм, Действительно на вл серваке не работает. На локалке с кибериадой все ок. Во дела.
