### ISSUE TITLE
Предложение: Увеличить количество сигарет с 6 до 20

### ISSUE THREAD

**Issue by terribaum** [ss220-space/Paradise#443]
### Проблема

При покупке любой пачки сигарет оная вмещает всего 6 штук. Предлагаю увеличить пачку до 20 сигарет. Особенно остро данная проблема ощущается если это сигареты купленные "с монет".

### Решение

Просто увеличить кол-во сигарет до 20 в пачке.

### Плюсы

-Меньше бегать за сигаретами.
-Покупка пачки сигарет не ощущается, как грязный обман.

### Минусы

-Кодить скорее всего?
-Минздрав будет недоволен.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184641076-6e40fdab-47d4-4892-8b4f-718871d3b88e.png)
