### ISSUE TITLE
Feat: Рескин и Ребаланс оружия

### ISSUE THREAD

**Issue by Vaderrrrrr** [ss220-space/Paradise#446]
### Проблема

Предложение:
Переделать скины на оружие, добавить новое оружие, ребаланс и добавление новых калибров. УРОН И ПРОЧЕЕ С НИМ СВЯЗАННОЕ ЭТО ВСЕГО ЛИШЬ ПОКАЗ БАЛАНСА, А НЕ УТВЕРЖДЕНИЕ ЧТО ТАК ДОЛЖНО БЫТЬ, Я ПРОСТО СЧИТАЮ ЧТО ПОРА БЫ ЧТО-ТО ИЗМЕНИТЬ.

### Решение

СБ:
1. Энфорсер так и оставить с 9 мм но увеличить магазин до 14 патронов
2. Добавить кольт с магазином на 7 патрон и калибром 45acp (урон 45 калибра - 20 + 35 стаминоурона)
3. Добавить полицейский револьвер на 6 патрон с калибром 38 special и уроном 35. Убрать сб доступ к 357 калибру.
4. Добавить 2 вида боевого щита. Это тупизм когда пластиковый щит имеет 50% блока пуль и лазера. Считаю что пластиковый щит должен давать 50% блок от всего кроме пуль и лазерного оружия. Добавить щит спецназа который можно заказать в карго, будет иметь блок от всего в 50%.
5. WT-550 Auto Rifle увеличить урон калибра 4.6x20mm до 25 (20 обычного урона и 5 бронепробивного). Это пистолет пулемет как бы и у него должно быть хоть чуточку больше урона.
6. Изменить цену спидлоадера для револьверов 30к слишком много.

Агенты и оперы синдикека:
1. Изменить обрыганый скин пистолета stechkin на красивый скин HK USP (глушитель будет наконец круто смотреться) также увеличить магазин до 12.
2. Изменить обрыганый скин револьвера синдиката, на что-то более крутое. Изменить коло-во патронов с 7 до 6 и сделать 357 калибр (50 урона) и добавить более дорогой патрон 44 магнум (60 урона).
3. Добавить AK-19 как новый автомат для синдикатовских оперов с магазином на 30 пуль и калибром 7.62 и уроном 40 + 5 бронепробивной.
4. С-20r автомат теперь будет с калибром 5.7 FN а не 45 acp. 5.7 FN будет наносить 25 + 5 бронепробивной. 45 acp это патрон сугубо останавливающие силы (лучшее применение в сб) и я не вижу смысла операм синдиката наносить не летальный урон противнику для их выживаемости.
5. L6 Squad automatic weapon переделать калибр с 5.56 до 7.62.

### Плюсы

Плюсы:
- Изменения которые добавят свежести и рациональности 

### Минусы

Минусы:
- Баланс и кодинг?

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184641109-e2ab189c-9eb0-4720-bb2f-3818e9f5fe08.png)
