### ISSUE TITLE
Bug: генокрад-макака не может превратиться в человека

### ISSUE THREAD

**Issue by DobrolyubovMaxim** [ss220-space/Paradise#458]
### Ckey

Liqud_Potroh

### Описание бага

При превращении генокрада в макаку с помощью изменения 55 гена он не может вернуться обратно способностью Lesser/Human form. Скилл Human form просто не появляется.

### Шаги воспроизведения

1) Быть генокрадом.
2) Вколоть 55 ген, превращающий в макаку.

### Ожидаемое поведение

При превращении в макаку с помощью изменения генов, скилл Human form должен появляться в списке скилов, если куплена способность Lesser form.

### Дополнительная информация

Проверял на локальном сервере, т.к. генетик-генокрад выпадает крайне редко.

### Операционная система

win 10

### Версия клиента

514.1569

### Название сервера

MAIN

### Примерное время и дата

16.11.2021 18:00

**Comment by ARZUMATA** [comment]
Посмотрел код
В общем да - для генокрада это не срабатывает.

Можно добавить проверку на генокрада при вызове метода превращении в макаку в /datum/dna/gene/monkey/activate для DNA инжектора.

Сама абилка как раз и вызывает monkeyize() и придется проверять, можно ли добавить абилку HumanForm (она будет добавляться дважды) или нет, и добавить проверку в /datum/action/changeling/lesserform/sting_action.

Как мне кажется это неправильно, поэтому, так как HumanForm в принципе копирует абилку Transform, предлагаю:
1. Упразднить HumanForm в принципе, т.к. при ее использовании так-же есть выбор ДНК как и при использовании Transform и ДНК не тратятся.

2. Перенести анимацию перехода в HumanForm в Transform (делается так-же коде).

3. Переосмыслить LesserForm и превращаться не только в макаку, а так-же в любое другое "низшее" животное, согласно текущей расе на генокраде.

Сделаю все самостоятельно.

**Comment by ARZUMATA** [comment]
Апдейт

Упразднить humanform в принципе можно, но это сильно бьет пока по трансформации и отсутствует анимация превращения. Плюс надо тронуть другую часть кода, что пока не очень желательно.
Если добавить анимацию через деактивацию гена как и должно быть, то нужно брать ДНК, менять ей 55й блок и доп. параметры иначе либо моб взорвется либо начнутся рантаймы.

И еще вопрос баланса, а нужно ли сразу из макаки в вульпу например?

Поэтому конкретный PR пока исправляет только баг.
