### ISSUE TITLE
Bug:  Опасный спрей в нагрудном кармане ) - Infinity

### ISSUE THREAD

**Issue by EvelinaMelloy** [ss220-space/Paradise#472]
### Ckey

evelinamelloy

### Описание бага

баг замечен на сервере Infinity - нет возможности указать это в соответствующей графе, по этому пишу здесь

В игре есть аксессуар, который одевается на джампсьют, "large webbing" разгрузка в общем, со множеством карманов. Так вот если в него положить спрей к примеру "space cleaner" то он 100% пшикнет на вас, я себе так голову расплавил кислотой 

### Шаги воспроизведения

- Одеваем на себя "large webbing"
- Наливаем любимую кислоту или можно просто воду в "space cleaner"
- Кликаем по своему джампсьюту рукой, в которой лежит спрей, и он в 100% случаев делает один пшик, прямиком на вас
- Если кликнуть по джампсьюту свободной рукой, и положить спрей в открывшееся окошечко инвентаря, такой ошибки нет
- Спрей не является оружием и правила "нескилованого" случайного выстрела на него не действую, если положить в карман, сумку, пояс, спрей никогда не делает произвольного распыления на вас

### Ожидаемое поведение

Всё просто, хочу что бы спрей перестал пшикать мне в лицо кислотой ) а то обидно так само выпиливаться 

### Операционная система

windows 10

### Версия клиента

514.1568

### Название сервера

WL

### Примерное время и дата

21.11.2021 время 3:45 по Москве

**Comment by dj-34** [comment]
https://github.com/ss220-space/Baystation12/issues

**Comment by LeadOnTaste** [comment]
Sounds more like...
**SKILL ISSUE**
