### ISSUE TITLE
Bug: Мед Борг спустя время не может использовать слиперы и мед сканы

### ISSUE THREAD

**Issue by 501D3N** [ss220-space/Paradise#478]
### Ckey

501D3N

### Описание бага

Спустя некоторое время или спустя некоторое количество использований слиперов и мед сканов, мед борг не может их использовать, они просто не открываются, либо могут мгновенно закрыться в то время как смотришь в них и больше не открыться, перезаход в игру и перезагрузка UI не помогает, после этого использовать можно лишь через пкм, что бы убрать человека изнутри. Вызывается баг каждый раунд

### Шаги воспроизведения

-Взять мед. борга
-Активно использовать слиперы и мед. сканы на сервере
-Получить баг

### Ожидаемое поведение

После получения бага невозможно открыть слиперы и мед. сканы, но все остальное все еще можно

### Операционная система

Windows 10

### Версия клиента

514.1569-514.1571

### Название сервера

MAIN

### Примерное время и дата

21.11.2021-24.11.2021

**Comment by NeonNik2245** [comment]
Такое возможно в случае, если в медблоке заканчивается энергия (проверить можно на АПЦ), при этом перестают работать слиперы и сканеры, а так же наномеды, при подаче энергии обратно всё вновь начинает работать, проблема возникает каждый раунд из-за инженеров

**Comment by 501D3N** [comment]
> Такое возможно в случае, если в медблоке заканчивается энергия (проверить можно на АПЦ), при этом перестают работать слиперы и сканеры, а так же наномеды, при подаче энергии обратно всё вновь начинает работать, проблема возникает каждый раунд из-за инженеров

Давненько я эту штуку оставлял. Я в последнее время очень мало играю, но вроде не замечал подобного бага больше. Проблема тогда точно не в апц была. Все медики спокойно использовали и слиперы и сканеры, а так же второй мед борг, если был. В апц я тоже смотрел, само собой. Проблема оставалась до самого конца раунда и вообще никак не правилась. Было даже пару раз так, что она возникала в первые 5-10 минут раунда, но обычно в мидраунде, когда ты уже достаточно накликался по слиперам. По итогу просишь медиков прокликивать слиперы и нужный реагент в них потому что у борга лапки и нет апдейта

Как уже написал, проблема, скорее всего, сама собой уже решилась давно, но проверить сейчас не могу особо. Даже если он и остался, то явно не на каждый раунд, по крайней мере у меня, уже хорошо

**Comment by dikers93** [comment]
а запиши видео данной с данной ситуацией с захватом клавиатуры и кнопок мыши
