### ISSUE TITLE
Предложение: добавить воксам карликовость и убрать способность негниения

### ISSUE THREAD

**Issue by Aanakh** [ss220-space/Paradise#492]
### Проблема

Воксы по лору около метра ростом, но их модели по размеру такие же, как у остальных рас, нормальный рост которых, как правило, составляет более 170см. Также есть проблемы со способностью негниения воксов. Во-первых, при общем существовании этой способности оторванные конечности разлагаются вне охлаждающего ящика (скриншот прилагается). Во-вторых, влияние этой способности на геймплей минимально: либо труп персонажа находят и доставляют в медбей в течение 3-5 минут при условии включённых датчиков, либо находят через 1-1,5 часа, ближе к концу раунда, когда, вероятно, игрок уже вышел из игры, и вернуть персонажа к жизни уже невозможно.
![1tO5WCtVRY8](https://user-images.githubusercontent.com/95498028/144741792-c8b4f7e8-d3e2-4bb4-9ed1-82595a86da9b.jpg)

### Решение

• Вписать воксам ген карликовости раундстартом
• Убрать способность негниения

### Плюсы

• Лорфрендли воксы, явное отличие от других рас, помимо одного постоянно занятого баллоном с азотом кармана
• Убираем сомнительной полезности способность

### Минусы

• Воксы станут расой номер один для любителей робаста, так как по маленькой модели сложнее попадать
• Отсутствие целых стеклянных столов на станции

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184641157-1775d7b0-0ffe-44b9-868d-3b5f60fb772c.png)
