### ISSUE TITLE
Feat: возможность разбирать display case

### ISSUE THREAD

**Issue by ARZUMATA** [ss220-space/Paradise#516]
### Проблема

Сейчас его можно только сломать, что тригерит алярму и красные лампы которые никак не убрать.

### Решение

Добавить возможность разбора.
Снятия алярм статуса (свайп картой глав на лампу) с разболтовкой дверей или иное.

### Плюсы

Делать ремонт легче

### Минусы

Нет

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184641211-5c1c4488-3c62-4e55-b4e7-6d143f11ac40.png)
