### ISSUE TITLE
Feat: TGMC огнемёты

### ISSUE THREAD

**Issue by Montaukek** [ss220-space/Paradise#529]
### Проблема

Огнемёты прошивают стенки и строения ксеносов насквозь.

### Решение

Сделать так, чтобы огонь ложился на первую стенку или дверь и дальше не шёл.

### Плюсы

+Все постройки ксеносов не будут сожжены за 10 секунд прибывания огнемётчика рядом
+Логика, реализм, физика - соблюдены
+В сложных строениях появиться смысл
+Маринам станет сложнее жить

### Минусы

-Маринам станет сложнее жить

**Comment by VasilevAY** [comment]
Предложка в ветке Пары
