### ISSUE TITLE
Feat: Снять кожуру банана кликом по нему.

### ISSUE THREAD

**Issue by BeebBeebBoob** [ss220-space/Paradise#530]
### Проблема

Ну немного бы логики. А то каждый банан сжирать ну как-то не очень.

### Решение

Клик по банану в руках превращает в кожуру.

### Плюсы

Инста кожура для клоуна.
Больше не надо сидеть и перепивать weight-loss shake.

### Минусы

Нету? Ну пропадает сам банан.

**Comment by m1rny1** [comment]
В теории можно при клике пустой рукой по банану разделять его на кожуру и мякоть, что было бы логичнее с точки зрения реализма, но схожей механики для других предметов я не помню.
