### ISSUE TITLE
Bug: Floorbot can’t be constructed from toolbox which was made at autolathe

### ISSUE THREAD

**Issue by Ohar** [ss220-space/Paradise#533]
### Ckey

ohar

### Описание бага

There are only 6 types of toolboxes available to construct a floorbot
```
/obj/item/storage/toolbox/emergency,    //which toolboxes can be made into floorbots
/obj/item/storage/toolbox/electrical,
/obj/item/storage/toolbox/mechanical,
/obj/item/storage/toolbox/green,
/obj/item/storage/toolbox/syndicate,
/obj/item/storage/toolbox/fakesyndi
```

But autolathe produces `/obj/item/storage/toolbox` which is not in the list.

The only way to made a floorbot from it is using craft menu

### Шаги воспроизведения

1. Print a toolbox at autolathe
2. Try to put 10 floor tiles into it

### Ожидаемое поведение

Tiles inserted

### Дополнительная информация

You could also read [mentor chat with discussion about it](https://discord.com/channels/617003227182792704/753557108737179658/923892763181867039)

### Операционная система

Windows 10

### Версия клиента

514.1572

### Название сервера

MAIN

### Примерное время и дата

2021-12-24 near 11:00 UTC+3

**Comment by KoJIT2009** [comment]
Закройте issue, фикс уже merged
