### ISSUE TITLE
Feat: МП на TGMC

### ISSUE THREAD

**Issue by Montaukek** [ss220-space/Paradise#540]
### Проблема

Слишком много унг нарушающие военные законы, не слушающих лидеров и ведущих себя как унг. Ввод МП позволит исправить это, приведёт новых игроков и расширит количество ролей для людей, не желающих играть в каэсочку.

### Решение

Ввести МП, добавить бриг на карту(если его нету), отредачить вики по закону пехоты.

### Плюсы

Повыситься уровень РП
Будет меньше унг и нарушений
Лидерам будет проще управлять своими отрядами, ибо их будут слушать

### Минусы

Унги будут не довольны 
Да НаМ и НаХоЙ Ни НуЖнЫ эТи Рп И мП мЫ жЕ фАнИцА пРиШлИ

**Comment by VasilevAY** [comment]
предложка в ветке пары
