### ISSUE TITLE
Bug: Неправильное отображение голода у вампира

### ISSUE THREAD

**Issue by Favelanky** [ss220-space/Paradise#559]
### Ckey

Favelanky

### Описание бага

Вампир будет постоянно падать и засыпать, не понимая почему, ведь его полоска голода не изменится.

### Шаги воспроизведения

1. Ты должен быть вампиром.
2. Заходишь в гейт Академия мага.
3. Кто-то должен юзнуть книгу из библиотеки с заклинание smoke. Не знаю все ли заклинания дают такой эффект после второго использования или только это.
4. Ты используешь второй раз книгу заклинания smoke.

### Ожидаемое поведение

Твоя полоска голода не меняется, а по факту ты начинаешь умирать от голода. (Если не вампир, то отображение, вроде, нормальное)

### Дополнительная информация

Собственно, как я обнаружил. Я зашёл в гейт на вампире (самое начало раунда). Но какой-то чел всё уже залутал. Я подумал, может он забыл про книгу в библиотеке, взял её, использовал, но оказалось, что она юзаная. Я смотрю на полоску голода, всё ок. Начинаю выходить из гейта, начинаю падать и задыхаться. В итоге вышел, меня отвезли в мед, накормили. В итоге пришёл дек, взял меня в бриг и дальше понятно. При этом моя полоска голода зелёная.... и прошло 15-20 мин раунда (вампир не успеет проголодаться). 
Так каточка на антаге закончилась, даже не начавшись. :/

### Операционная система

windows 10

### Версия клиента

514.1575

### Название сервера

MAIN

### Примерное время и дата

08.01.2022 17:30-17:50

**Comment by Favelanky** [comment]
Дополнение: если попробовать попить кого-нибудь, то полоска обновиться (станет красной).

**Comment by Kirozet** [comment]
Провел тесты, иконка не обновляется если от переменной значения насыщенности отнимается больше чем имеется в переменной
