### ISSUE TITLE
Bug: не могу зайти на сервер

### ISSUE THREAD

**Issue by TadeushFletch** [ss220-space/Paradise#560]
### Ckey

Tadeush_Fletch

### Описание бага

При попытке зайти на сервера Vega и Secondary вылетает ошибка 
Application error: a client-side exception has occurred (see the browser console for more information).
На секунду появляется новое меню выбора серверов, а потом вылетает ошибка.

### Шаги воспроизведения

1. Зайти в Byond
2. Зайти на сервер Vega/Secondary

### Ожидаемое поведение

Зашел на сервер и начал играть

### Операционная система

Windows 10

### Версия клиента

514.1571

### Название сервера

MAIN

### Примерное время и дата

09.01.2022

**Comment by semoro** [comment]
Привет! А напиши свой ник в Discord или напиши в мне в Discord (Semoro)

**Comment by Bizzonium** [comment]
fixed
