### ISSUE TITLE
Feat: а как покупать?

### ISSUE THREAD

**Issue by Chilipila** [ss220-space/Paradise#569]
### Проблема

Уже несколько раз встречал нюкеров "а как покупать"

### Решение

Добавить и положить нюкерам на стол книгу: guide how to not be bad as "S"
Там будет либо ссылка на вики по нюкерам, либо отдельный гайд

### Плюсы

Ньюфагов можно будет нормально послать читать вики

### Минусы

Челы могут слишком долго читать вики...

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
