### ISSUE TITLE
Bug: wrapping paper deletes items

### ISSUE THREAD

**Issue by Graybear98** [ss220-space/Paradise#5797]
### Ckey

graybear98

### Описание бага

Я решил сделать лутбоксы и продавать их по 100 кредитов, обернул разные предметы в обёрточную бумагу из карго и начал продавать, после распаковки, предметы внутри исчезли, затем товарищ, который это увидел совершил суицид, я его мозг тоже обернул и его мозг тоже исчез после распаковки, хотя предметы ровно как и мозг должны были распаковаться в руке

### Шаги воспроизведения

1. Найти обёрточную бумагу
2. Положить предмет на пол, который хочешь упаковать
3. Обернуть
4. Взять в руку упаковку
5. Разорвать упаковку
6. В результате у тебя нет ни предмета, ни бумаги

### Ожидаемое поведение

Ты должен был получить предмет, который обмотал

### Операционная система

Винда 10

### Версия клиента

15.1642

### Название сервера

MAIN

### Примерное время и дата

23 августа

**Comment by Den109G** [comment]
Починено в #5854.
