### ISSUE TITLE
Feat: Recreateable Tachyon-Doppler Array

### ISSUE THREAD

**Issue by firstghost** [ss220-space/Paradise#584]
### Проблема

If swarmers have eaten Tachyon-Doppler Array, you can't research Toxins anymore. Why this machine is so unique?

### Решение

Make a recipe for Tachyon-Doppler Array. Classical, with circuit, or make it orderable via Cargo.

### Плюсы

You can recreate Tachyon-Doppler Array if you need.

### Минусы

None

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/projects/2
