### ISSUE TITLE
Feat: Craftable racial clothes

### ISSUE THREAD

**Issue by firstghost** [ss220-space/Paradise#585]
### Проблема

You can get racial clothes via Loadout, but if something is destroyed, you can't craft it in-game.

### Решение

Add racial in Vend-o-mats or make it craftable.

### Плюсы

Craftable racial clothes

### Минусы

None

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
