### ISSUE TITLE
Bug: deep fryer endlessly fries

### ISSUE THREAD

**Issue by Graybear98** [ss220-space/Paradise#5888]
### Ckey

graybear98

### Описание бага

Если пищу засунуть в дип фраер, то он будет жарить пищу бесконечно

### Шаги воспроизведения

1.найти дипфраер
2. засунуть туда пищу
3. ждать вечность
4. недождаться

### Ожидаемое поведение

через пол минуты дипфраер выплюнет готовую пищу

### Операционная система

Винда 10

### Версия клиента

15.1642

### Название сервера

MAIN

### Примерное время и дата

9 сентября

**Comment by Den109G** [comment]
Починено в #5919
