### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by TossForce** [ss220-space/Paradise#595]
### Ckey

TossForce

### Описание бага

Плоды ботаников роняют сервер

### Шаги воспроизведения

1. Нужны плоды с такими чертами - Gaseous Decomposition и Liquid Contents, 100 потенции, и вероятно необходимо содержание каких-либо жидкостей, которые могут быть нанесены на пол, например вода, кровь, космическая смазка.
2. Выкинуть эти плоды в  мусорку, из-за того что когда они из трубы вылетают, они все сразу все детонируют, сервак начинает страдать, если плодов 70, то включается пошаговый режим, если как я понимаю больше 200 - сервак спасает уже только рестарт.

### Ожидаемое поведение

Раунд заканчивается перезагрузкой сервера.

### Дополнительная информация

Так же это вероятно будет работать, если что-то другое заставит плоды лопаться, например просто игрок будет накидывать их в одно место, или вероятно разгерма. Проблема в такой нагрузке на сервер мне кажется заключается в том, что вместо одной плоскости, возникают созданные жидкостями, и они накладываются одна на другую, и каждый последующий взорвашийся плод увеличивает нагрузку по арифметической прогрессии.

### Операционная система

Windows 10

### Версия клиента

514.1572

### Название сервера

MAIN

### Примерное время и дата

19.01.2022 13:40, сервер SECOND

**Comment by BeebBeebBoob** [comment]
Все парни. Удаляем ботанику. Fun is over.

**Comment by KasaAlex** [comment]
> 

Давно пора.
