### ISSUE TITLE
Feat: Учёт расы при выборе руководящей должности

### ISSUE THREAD

**Issue by firstghost** [ss220-space/Paradise#602]
### Проблема

Для командных ролей требуется персонаж минимум 30-ти лет. Однако, для таяран, например, это уже почти старики.

### Решение

Изменить требования к возрасту на должности для не-человеческих рас
Примерные пороги, лет: Вокс - 15; Вульпканин - 24; Дионея - 30?; Драск - 45; Кидан - 15; КПБ - 30?; Плазмамен - 45; Серый - 15; Скрелл - 45; Слаймомен - 39; Таяран - 12; Унатх - 14; Человек - 30

### Плюсы

Справедливость

### Минусы

Придётся решить также #626

**Comment by BeebBeebBoob** [comment]
Вульпа 18 ле- т.е. когда будет ограничение на расы? Думаю лучше сделать сперва предложу на сервере потом говорить что это баг. Да, мы знаем понятие "лор" но.......

**Comment by antrophoss** [comment]
Не бывает справедливости для ксеносов, делай предложку.

**Comment by firstghost** [comment]
> Вульпа 18 ле- т.е. когда будет ограничение на расы? Думаю лучше сделать сперва предложу на сервере потом говорить что это баг. Да, мы знаем понятие "лор" но.......

А я и не называл это багом.
Что такое предложка, и чего от меня хотят?

**Comment by BeebBeebBoob** [comment]
> > Вульпа 18 ле- т.е. когда будет ограничение на расы? Думаю лучше сделать сперва предложу на сервере потом говорить что это баг. Да, мы знаем понятие "лор" но.......
> 
> А я и не называл это багом. Что такое предложка, и чего от меня хотят?

У нас есть Discord сервер. Там есть спец-канал #книга-отложений. Там делаешь предложение что можно было бы ставить за разные расы разный возраст.

**Comment by firstghost** [comment]
> > > Вульпа 18 ле- т.е. когда будет ограничение на расы? Думаю лучше сделать сперва предложу на сервере потом говорить что это баг. Да, мы знаем понятие "лор" но.......
> > 
> > 
> > А я и не называл это багом. Что такое предложка, и чего от меня хотят?
> 
> У нас есть Discord сервер. Там есть спец-канал #книга-отложений. Там делаешь предложение что можно было бы ставить за разные расы разный возраст.

"Предложения включающие в себя кодинг должны быть оформлены на гитхабе." 
Поэтому эта заявка висит именно здесь, где и должна быть.

На чистом билде, скачанном с гитхаба, такое ограничение также присутствует. И отсутствует возможность настроить через конфиг. Вывод: менять надо что-то в коде.

**Comment by Pppfffttt** [comment]
> На чистом билде, скачанном с гитхаба, такое ограничение также присутствует. И отсутствует возможность настроить через конфиг. Вывод: менять надо что-то в коде.

_Могу сказать даже где нужно будет менять код:_ https://github.com/ss220-space/Paradise/commit/5757853425bd9f9ceb0687f484ed1e4993172b67

Но прежде чем кодить, нужно убедится, что это действительно будет востребовано. Сделайте всё-таки предложку в Дискорде.

**Comment by Pppfffttt** [comment]
Считаю, что это очередная победа кошкодевочек над человечеством. Завтра постараюсь уже изменить всем расам возраст на командные роли, и залить всё на гитхаб. 

![Рисунок5](https://user-images.githubusercontent.com/98468861/151880289-cd119084-3c47-4b45-87ed-6599f7f4d603.png)

**Comment by DayBreakerBrony** [comment]
А с какого черта у плазмаменов 45? Хотя я в лоре и написал, что они живут 150 лет, но в 4 года они уже полностью дееспособны и готовы ко взрослой жизни.
Непорядок согласовывать что-то без #lore-discussion в дискорде

**Comment by firstghost** [comment]
> А с какого черта у плазмаменов 45? Хотя я в лоре и написал, что они живут 150 лет, но в 4 года они уже полностью дееспособны и готовы ко взрослой жизни. Непорядок согласовывать что-то без #lore-discussion в дискорде

Где и что обсуждать и согласовывать я уже не знаю.
Я оставил предложение о том, что данный вопрос стоило бы проработать и прописать вики, но всё равно остался неугодным по 2.1
Я простой игрок, который заметил странность и несправедливость, несоотвествие кода и лора. Как это решить, не получая за каждое действие по голове от администрации я не знаю.

**Comment by firstghost** [comment]
> А с какого черта у плазмаменов 45? Хотя я в лоре и написал, что они живут 150 лет, но в 4 года они уже полностью дееспособны и готовы ко взрослой жизни. Непорядок согласовывать что-то без #lore-discussion в дискорде

Кстати, вчитавшись в параграф про образование у Плазмаменов, заметил несостыковку.
Человек считается полностью дееспособным в 18 (в среднем, или не беря в расчёт другие страны и эмансипацию)
Плазмамен считается таковым в 4
Однако, к моменту наступления полной дееспособности человек уже получил среднее образование, а плазмамен учиться только начинает.

**Comment by DayBreakerBrony** [comment]
> > А с какого черта у плазмаменов 45? Хотя я в лоре и написал, что они живут 150 лет, но в 4 года они уже полностью дееспособны и готовы ко взрослой жизни. Непорядок согласовывать что-то без #lore-discussion в дискорде
> 
> Кстати, вчитавшись в параграф про образование у Плазмаменов, заметил несостыковку. Человек считается полностью дееспособным в 18 (в среднем, или не беря в расчёт другие страны и эмансипацию) Плазмамен считается таковым в 4 Однако, к моменту наступления полной дееспособности человек уже получил среднее образование, а плазмамен учиться только начинает.

Плазмамены учатся всю жизнь.

**Comment by firstghost** [comment]
> > > А с какого черта у плазмаменов 45? Хотя я в лоре и написал, что они живут 150 лет, но в 4 года они уже полностью дееспособны и готовы ко взрослой жизни. Непорядок согласовывать что-то без #lore-discussion в дискорде
> > 
> > 
> > Кстати, вчитавшись в параграф про образование у Плазмаменов, заметил несостыковку. Человек считается полностью дееспособным в 18 (в среднем, или не беря в расчёт другие страны и эмансипацию) Плазмамен считается таковым в 4 Однако, к моменту наступления полной дееспособности человек уже получил среднее образование, а плазмамен учиться только начинает.
> 
> К тому же, какая разница? У всех своё устройство общества.

Все учатся всю жизнь

Разница как раз в том, что именно от этого и должны зависеть пороги возраста

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
