### ISSUE TITLE
Bug: Слышу голос из прекрасного далёка(хотя не должен)

### ISSUE THREAD

**Issue by 05126619z** [ss220-space/Paradise#603]
### Ckey

05126619z

### Описание бага

Слышу радио без наушника на лаве

### Шаги воспроизведения

Зайти за бармена на лаву

### Ожидаемое поведение

Не должен был слышать радио

### Операционная система

Win 10

### Версия клиента

514.1578

### Название сервера

MAIN

### Примерное время и дата

24.01.2022, 16:25

**Comment by snipersir** [comment]
Может ты слышишь common канал из-за настенного интеркома рядом с тобой?
