### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by KasaAlex** [ss220-space/Paradise#604]
### Ckey

Kasatto

### Описание бага

При крафте золотого гудка не удаляется обычный гудок. Получается, что после крафта у нас есть И обычный гудок, И золотой.

### Шаги воспроизведения

Через меню крафта сделать золотой гудок из 5 бананиума и 1 гудка.

### Ожидаемое поведение

Гудок будет использован в процессе крафта

### Операционная система

Win7 ultimate SP1

### Версия клиента

514.1575

### Название сервера

MAIN

### Примерное время и дата

2021 08 23

**Comment by Favelanky** [comment]
Где тут баг?) Гудок нужен, чтобы ты понял, как форму гудка сделать. Типо смотришь на него и делаешь
