### ISSUE TITLE
Bug: Дюп металла в автолате с помощью магазинов 9mm

### ISSUE THREAD

**Issue by larentoun** [ss220-space/Paradise#612]
### Ckey

larentoun

### Описание бага

Полный магазин на 8 патронов считается как полная коробка на 30 летальных патронов.
В итоге, когда сдаем магазин резины в автолат (7.2к металла), получаем возврат средств в целую коробку летальных патронов (30к металла)

### Шаги воспроизведения

1. Распечатать магазин 9мм
2. Вставить в автолат
3. Получаем возврат средств, равный 30000 единиц металла

### Ожидаемое поведение

1. Распечатать магазин 9мм
2. Вставить в автолат
3. Получаем возврат средств, равный себестоимости магазина.

### Дополнительная информация

30000 - это базовая цена любого хранилища боеприпасов. Судя по всему, отсутствует значения цены магазинов для 9мм.

### Операционная система

Windows 10

### Версия клиента

514.1578

### Название сервера

MAIN

### Примерное время и дата

24.01.2022

**Comment by Kirozet** [comment]
Шаги воспроизведения не вызывают бага при тестировании бага на локальном сервере
**версия BYOND** 514.1578
Билд парадиза актуальной для 29.01.2022 версии

https://user-images.githubusercontent.com/96671463/151645306-4280834a-df10-4904-8581-f36b9a51921d.mp4

**Comment by larentoun** [comment]
Пофикшено самим собой https://github.com/ss220-space/Paradise/pull/614
