### ISSUE TITLE
okay, i got info for ya.

### ISSUE THREAD

**Issue by OpsCoretango** [ss220-space/Paradise#613]
okay, i got info for ya.
its not dropped you just dupe texture but tank its self still in backpack slot.
Repeat your actions but now use shift+right mouse button on backpack slot. 

_Originally posted by @OpsCoretango in https://github.com/ss220-space/TerraGov-Marine-Corps/issues/16

**Comment by BeebBeebBoob** [comment]
Что
Что?
А?
Когда люди начали думать что Парадиз и тгмс одно и то же?
