### ISSUE TITLE
Bug: клонерка отказываеться работать

### ISSUE THREAD

**Issue by dikers93** [ss220-space/Paradise#615]
### Ckey

asaha

### Описание бага

клонерка в меде оказывалась клонировать. Активна была кнопка колонировать, но при нажатии на нее ничего не происходило. С АПЦ все в норме, консоль в норме, просто тупо не клонировала

### Шаги воспроизведения

не предсталяю

### Ожидаемое поведение

должно было сделать клона

### Операционная система

не требуеться

### Версия клиента

последняя

### Название сервера

MAIN

### Примерное время и дата

раунд 5914, время +- 2,40 когда засек время, и до конца раунда

**Comment by BeebBeebBoob** [comment]
Ну то есть тело было внутри, ты открыл окошко для клона и не отходя от кассы пытался клонировать? Боюсь просто интерфейс устарел поэтому там надо было в Special Verbs-> Reload UI res ну или закрыть и снова открыть терминал.

**Comment by dikers93** [comment]
> Ну то есть тело было внутри, ты открыл окошко для клона и не отходя от кассы пытался клонировать? Боюсь просто интерфейс устарел поэтому там надо было в Special Verbs-> Reload UI res ну или закрыть и снова открыть терминал.

если бы, это меня не могли воскресить, как и всех остальных отправленных на него, не один человек пытался запустить клонирование. Уже и на дискеты скопировали, но не помогало

**Comment by BeebBeebBoob** [comment]
> > Ну то есть тело было внутри, ты открыл окошко для клона и не отходя от кассы пытался клонировать? Боюсь просто интерфейс устарел поэтому там надо было в Special Verbs-> Reload UI res ну или закрыть и снова открыть терминал.
> 
> если бы, это меня не могли воскресить, как и всех остальных отправленных на него. Не только один человек пытался запустить клонирование а весь мед. Уже и на дискеты скопировали, но не помогало

Либо глюк (что очень вероятно ибо единственный такой случай), либо баг но не понятно на каком моменте либо игра работала как надо и там работа инженеров нужна была.

**Comment by Pppfffttt** [comment]
> Либо глюк (что очень вероятно ибо единственный такой случай), либо баг но не понятно на каком моменте либо игра работала как надо и там работа инженеров нужна была.

Это и правда глюк, который возникает, когда плоти в клонировалке нет, а кнопка клонировать горит. Лечится перезагрузкой интерфейса (Reload UI), или добавлением плоти.
