### ISSUE TITLE
Feat: Починка емагнутых шкафчиков

### ISSUE THREAD

**Issue by Honker9999999** [ss220-space/Paradise#619]
### Проблема

Сейчас починить шкафчики, которые попали под ЭМИ/емагнуты/сломаны с замком нельзя никак.

### Решение

Используя плату для шлюзов(или добавить новую плату, похожую на неё) можно будет починить такой шкафчик. В идеале добавить возможность изменять доступ, красить шкафчики и т.д, но такой еблей уже точно никто не займется.

### Плюсы

1. Можно чинить шкафчики

### Минусы

1. Можно чинить шкафчики.

**Comment by BeebBeebBoob** [comment]
На счёт того чтобы делать новые шкафчики это реальная идея но вот чинить шкафчики нет. сама сущность емага это полностью ломать что либо без возможности вернуть в прежнее состояние только если не разобрать(у шлюзов полностью сгорает плата и надо пересобиратьне чинить, БСХ только если построить новую, АПЦ навсегда синий пока не переустановить, киборга полностью пересобрать только и многие другие)
Это было специально сделано чтобы оставить ту специальную улику что этот предмет именно емагнули и никак по другому.

**Comment by firstghost** [comment]
> На счёт того чтобы делать новые шкафчики это реальная идея но вот чинить шкафчики нет. сама сущность емага это полностью ломать что либо без возможности вернуть в прежнее состояние только если не разобрать(у шлюзов полностью сгорает плата и надо пересобиратьне чинить, БСХ только если построить новую, АПЦ навсегда синий пока не переустановить, киборга полностью пересобрать только и многие другие) Это было специально сделано чтобы оставить ту специальную улику что этот предмет именно емагнули и никак по другому.

А что насчёт остальных методов взлома? ЭМИ и ручной взлом также непочиняемы. Что не добро

**Comment by BeebBeebBoob** [comment]
>А что насчёт остальных методов взлома? ЭМИ и ручной взлом также непочиняемы. Что не добро

Хорошо но как тогда будет ЭМИ влиять на ящик? Ручной взлом? С шлюзом легко так как там либо болты либо отключка либо ещё что-то. На другие вещи тоже также как емаг к примеру дефиб эми = емаг.

**Comment by firstghost** [comment]
> > А что насчёт остальных методов взлома? ЭМИ и ручной взлом также непочиняемы. Что не добро
> 
> Хорошо но как тогда будет ЭМИ влиять на ящик? Ручной взлом? С шлюзом легко так как там либо болты либо отключка либо ещё что-то. На другие вещи тоже также как емаг к примеру дефиб эми = емаг.

Может сделать шкафчику состояния замок включён/выключен (он же там, по идее, электронный). Мультитул бы (при отвинченной крышке) эти состояния переключал. И при втором состоянии нельзя было бы его залочить картой, он был бы просто как шкаф без замка. ЭМИ бы отключал замок в любом случае. А Емаг, как средство оператвного, но грубого взлома, да, сжигал бы плату замка.
Хотя, так шкафчик становится проще взломать незаметно, пусть он и бьёт иногда током.
Если делать классический взлом с проводами, то один провод отвечал бы за состояния открыт/закрыт, второй (или не только второй) вообще за питания замка, ещё пару били бы током, ну и пустой провод мог бы быть.
Но и это взлом не сильно усложняет, наверное.

**Comment by Honker9999999** [comment]
> у шлюзов полностью сгорает плата и надо пересобиратьне чинить, БСХ только если построить новую, АПЦ навсегда синий пока не переустановить, киборга полностью пересобрать только и многие другие

Тут тоже самое и выходит. Ты ведь не чинишь, а заменяешь плату, как в том-же шлюзе или ЛКП. Ну и ЭМИ и проводки, да.

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
