### ISSUE TITLE
Bug: Ошибка в меню выбора лобби, с невозможностью зайти на сервера.

### ISSUE THREAD

**Issue by Pivoman1234** [ss220-space/Paradise#620]
### Ckey

Pivoman

### Описание бага

Сегодня я поставил Windows 7 и пытался зайти на Main сервер SS220, но произошла ошибка из-за которой меню выбора просто отказывалась в принципе работать, спустя несколько часов разбирательства с обновлениями виндовса и интернет эксплорера, я смог открыть меню выбора лобби, но вот проблема, я не могу ни встать в очередь, не зайти даже на полу-заполненный сервер ( Kleo ), но могу зайти на сервера где нету лимита на кол-во людей как пример Marine Corps.

### Шаги воспроизведения

1. Установка BYOND с оф. сайта.
2. Ошибка меню выбора лобби.
3. Установка обновления Windows 7 и обновление до Internet Explorer 11 в результате чего ошибка исчезла.
4. Невозможность подключится/встать в очередь на сервера с лимитом играющих людей.

### Ожидаемое поведение

Я должен был или зайти на сервер или встать в очередь.

### Дополнительная информация

Попытка подключится через сайт или попытка подключится на конкретный сервер без забитых слотов ни к чему не привела.
( прикладываю скрин меню выбора лобби, просто что бы было ).
![image](https://user-images.githubusercontent.com/98662043/151674131-b1c70073-6c37-4050-8621-2b91024b5f0e.png)

### Операционная система

Windows 7 ( профессиональная )

### Версия клиента

5.0 public Version 514.1578

### Название сервера

MAIN

### Примерное время и дата

29.01.2022 примерно с 15;30 до 21:35

**Comment by Bizzonium** [comment]
Проблема с IE11 (отсутствует) в Windows 7

**Comment by Bizzonium** [comment]
Для Windows 7
1. Попробуйте удалить все internet explorer'ы
![image](https://user-images.githubusercontent.com/8555356/151676907-b4259480-b037-423c-ac8a-88e49525143e.png)
2. Перезагрузитесь
3. Установите все зависимости https://docs.microsoft.com/ru-ru/troubleshoot/developer/browsers/installation/prerequisite-updates-for-ie-11
4. Перезагрузитесь
3. Установите IE 11 https://www.microsoft.com/ru-RU/download/details.aspx?id=41628
