### ISSUE TITLE
Feat: Учёт расы при выборе возраста

### ISSUE THREAD

**Issue by firstghost** [ss220-space/Paradise#626]
### Проблема

Минимальный возраст в 17 лет и максимальный в 85 един для всех, хотя продолжительность жизни у всех рас разная.
Также, это является препятствием для реализации #602 
### Решение

Расширить диапазон возраста, который можно выбрать. Возможно, корректировать его в зависимости от выбранной расы.

### Плюсы

Восстановление ролевой справедливости и ликвидация расовой возрастной дискриминации

### Минусы

Нет

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
