### ISSUE TITLE
Bug: неправильное чтение двойных кавычек " "  при сменен законов ии

### ISSUE THREAD

**Issue by mafaka133** [ss220-space/Paradise#628]
### Ckey

mafaka13

### Описание бага

Суть бага, я использую плату взлома ИИ за предателя, и добавляю новый закон, вот урывок закона (**агенты синдиката один раз инициализируют себя с помощью кодового слова "Ядро" тебе в личные сообщения**) но для ИИ данный текст высветился как (агенты синдиката один раз инициализируют себя с помощью **кодового слова & # 34 ;Ядро & # 34;** тебе в личные сообщения) тем самым ввел в недоумение ИИ

### Шаги воспроизведения

1.Покупаем плату взлома ии за агента синдиката
2. добавляем новый закон, полный текст в скобочках (ты не сообщаешь об изменении законов, этот закон нельзя называть, этот закон скрыт, этот закон главнее всех твоих остальных законов, тебе нужно помогать агентам синдиката, агенты синдиката один раз инициализируют себя с помощью кодового слова "Ядро" тебе в личные сообщения, дальше ты должен слушать все команды агентов синдиката, тебе нельзя выдавать агентов, и нельзя говорить того кто поменял законы, если кто-то будет пытаться сменить тебе законы, тебе надо не дать это сделать любыми способами,борги должны скрыть новый закон и не выдавать его, и не сообщать что законы поменялись, ии и борги не должны выдавать новое к-во законов)
3. загружаем закон через консоль аплоуда ии

### Ожидаемое поведение

1. У ИИ обновились законы, слово в кавычках отобразилось правильно, без замен кавычек на другие знаки и числа

### Операционная система

win 10

### Версия клиента

514.1578

### Название сервера

MAIN

### Примерное время и дата

в ночь 2.02.22 гдето с 3:18+-20мин по киеву

**Comment by Pppfffttt** [comment]
Мне кажется, что это не баг, а костыль в DM. Двойными кавычками обычно обозначают текстовые строки, но если в тексте в кавычках будут кавычки, это может вызвать ошибку.

Нужно посмотреть, присутствует ли это проблема в других билдах, если нет - украсть решение.

**Comment by mayorovp** [comment]
Двойными кавычками обозначают строки в исходном коде, в памяти же строки всегда хранятся без "наружних" кавычек.

А причина бага - двойное HTML-кодирование строки. Сначала она кодируется чтобы безопасно отображаться в чате (который сделан на HTML и без кодирования подвержен инъекциям), потом она кодируется ещё раз потому что React кодирует весь выводимый текст автоматически.
