### ISSUE TITLE
Визуальный баг

### ISSUE THREAD

**Issue by He11Force** [ss220-space/Paradise#63]
Если надеть наушник на левое ухо, и на правое повесить ручку, наушник пропадает с персонажа.

**Comment by MorgoWizard** [comment]
@VasilevAY, добавь label "bug". Жук актуальный

![image](https://user-images.githubusercontent.com/84981163/185155996-59b15888-401c-4776-91ca-c379512a32be.png)
![image](https://user-images.githubusercontent.com/84981163/185156051-0f7fa2ff-094e-4c01-a8ce-96379b260421.png)
