### ISSUE TITLE
Feat: Включение спикер на позитронном мозге

### ISSUE THREAD

**Issue by L0st-S** [ss220-space/Paradise#635]
### Проблема

Бывает такое, что у КПБ выбивает мозг из тела. Взрыв, мегафауна, или просто вытащили из тела
Органическим мозгам нужно ММИ, и они могут через него говорить сразу
Робо мозг изначально имеет включенный спикер
А на позитронке он выключен, что уменьшает шансы на возвращение мозга обратно в тело, да и не факт что тебя вернуть в нормальное тело, а не посадят в киборга. Сказать то ты не можешь, а включать спикер люди забывают

### Решение

Изменить изначальное состояние спикера с выключено на включено

### Плюсы

Уменьшение вероятности что тебя посадят в борга, хотя ты таковым не был
Возможность поговорить с своим спасителем
Возможность докричаться до проходящих мимо игроков, которые не обращают внимание на мозг. К сожалению это происходит намного чаще чем хотелось-бы. Особенно на шахте... 
Уменьшение нужды писать админу/ментору, чтобы тот убил мозг. Зачем это? А затем что если выйдешь в госты, появится в робомозге, или за нового персонажа уже не даёт игра. 

### Минусы

Потратить немного времени на это

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
