### ISSUE TITLE
Feat: Добавить коронеру в ящик Анализатор ДНК и Консоль Мед записей

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#636]
### Проблема

Из слухов, у коронеров на работке ДО СМЕРТИ СКУШНО (бадум-тсс), а отчеты изобилуют постоянными "Unknown", ибо карты и пда всегда украдены, а говорить или предположить кто это был - никто не станет. Звать каждый раз дека - это абзац, он ливнет или сгорит от такого. Да и самим коронерам наверно интересно кого шлепнули, трупов обычно валом.

### Решение

ЧЕРЕЗ РЕДАКТОР КАРТ!!1! (проще некуда, yes!)
-добавить в шкафчик коронера тулзу из набора детектива: 2 Ручных детективных анализатора, из рассчета, один на активного коронера, второй запасной если первый ушел в крио с анализатором;
-добавить рядом с местом работы коронера Консоль Медицинских записей, чтобы наш товарищ в морге определял сразу на месте кем был тот или иной "пациент", не бегая через весь медбей в ресепшн за полной инфой о трупе.

### Плюсы

Коронерам в теории будет интереснее на своей роли(а эт самое главное), в каком-то смысле будут знать кто выигрывает на станции, в отчетиках появятся хоть какие-то данные;
Отчеты коронеров станут полезнее???;
Для Глав станции, тому же ХоПу, ХоСу, Кекпитану, например, будет к месту получать сводку кто откинулся, дабы открыть слоты или, в той же теории, перераспределить нагрузку между сотрудниками("ну-ну.."). Для хорошего ХоПа это будет приятной новостью.

### Минусы

Возможно морг станет очередной целью нашествия асистух и клоуна дабы украсть запасной анализатор и стать маминым кекективом на станции. Хотя морг и без того уже является целью нашествия всех кому не лень, того же сб.

**Comment by Ursosan** [comment]
Логичнее, наверное, просто добавить одному из анализаторов пункт где он говорит ДНК трупа и уже по ДНК искать инфу по базе данных.
А на счет терминала это точно отличная идея

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
