### ISSUE TITLE
Feat:  Беспомощность синего щита

### ISSUE THREAD

**Issue by Ursosan** [ss220-space/Paradise#643]
### Проблема

В случае если щит вступает в бой с больше чем двумя угрозами у него встают сразу две большие проблемы
1. У него по дефолту нет доступа в канал СБ, а значит он может просить поддержку только в общий канал или в канал командования.  Просить  помощи в общий канал не самая лучшая идея, ведь если условные агенты узнают о том что у синего щита проблемы они могут безнаказанно воровать шкафы и предметы для своей цели (иногда даже самих глав). Просить помощи через командный канал тоже не всегда эффективно, капитан или ГСБ не всегда смогут быстро передавать сообщения о проблеме в канал СБ, а иногда они просто не понимают что происходит (а тем временем щиту и условному РД уже смазывают жопу)
2. С изменением системы стана револьвер щита в этом режиме стал значительно хуже. У револьвера достаточно маленький заряд и для обезвреживания хотя бы одного агента с имплантом адреналина (или двух без импланта) у щита просто не хватит заряда. Можно решить проблему переключением на другой режим и нацеливанием в голову, но по СРП щит должен именно обезвреживать а потом передавать нарушителя к СБ (привет отсутствию канала СБ в хедсете щита). Если делать все по СРП то это трудно, а против опытного агента/агентов вовсе невозможно

### Решение

1. Добавить в хедсет щита канал СБ 
2. Увеличить количество заряда в револьвере или увеличить его останавливающую силу в стан режиме

### Плюсы

Играть за щита станет чуть проще и не надо будет бегать в бриг за хедсетом сб (что вообще админами может расцениваться как манчкинизм). В бою при защите главы щит будет чувствовать себя уверение 

### Минусы

Опять че та открывать, писать и делать

**Comment by EternalDrifter** [comment]
В качестве альтернативы можно добавить конкретно стан решим, как на доминаторе, который будет наносить повышенный урон стамине. Ну или пониженный, как с доминатором)

_**p.s.** если не знали, то в первом моде он наносит 33, а во втором - 20 стамина урона_

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
