### ISSUE TITLE
Bug: Хочу чтоб были бесконечные роллы!

### ISSUE THREAD

**Issue by MiFaust** [ss220-space/Paradise#659]
### Ckey

Microchel

### Описание бага

Когда ты съедаешь/режешь ролл/суши вываливается новая миска риса и ингредиент (икра либо филе), получается бесконечная еда из 2-х кусков ингредиентов.

### Шаги воспроизведения

1. Сделать ролл/сушину
2. Съесть.

### Ожидаемое поведение

Что бы ингредиенты не выходили после съедания.

### Дополнительная информация

-

### Операционная система

Windows 10

### Версия клиента

514.1578

### Название сервера

WL

### Примерное время и дата

00:00 16.02.22

**Comment by 05126619z** [comment]
НЕ НАДО ЧИНИТЬ!!

**Comment by MiFaust** [comment]
Надо
