### ISSUE TITLE
Feat:  Предлогаю дать шахтерам невосприимчивость к опьянению от Manly Dworf

### ISSUE THREAD

**Issue by DoctorFastoss** [ss220-space/Paradise#662]
### Проблема

Нельзя напиться и не попасть в больницу после тяжелой рабочей смены 

### Решение

Дать иммунитет к этому виду алкоголя

### Плюсы

Больше Rock and stone! и меньше шахтеров в больнице

### Минусы

мировые запасы Manly Dworf иссякнут после первой же смены.

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
