### ISSUE TITLE
Feat: Заменить енфорсер на электрошокер

### ISSUE THREAD

**Issue by EternalDrifter** [ss220-space/Paradise#664]
### Проблема

В данный момент энфорсером либо не пользуются совсем, либо используют по минимуму, когда доминатор уже не катит или разрядился. Ибо резиновые пули хоть и неплохи, но старый-добрый доминатор ведь всё равно лучше? Да и вообще, когда вы последний раз видели, как в игре енфорсер применяют другие? Давайте будем честны - давно, если вообще видели.
Я предлагаю сделать для него действительно используемую альтернативу с интересной _(нет)_ механикой

### Решение

Работать наш электрошокер будет как _почти_ настоящий.
При попадании в человека, находящегося в прямой видимости (без стёкол, других людей и т.п.), его застанит на ~1 секунду. Но чем же он тогда будет отличается от простого доминатора в первом режиме? 
А тем, что цель будет получать **постоянный** урон по стамине после попадания и при выполнении вышесказанных условий. Конечно, если стрелявший также будет находиться не дальше 5-6 тайлов от цели. По задумке нужно будет потратить 4-5 секунд (около 30-25 Стамина Урона в секунду, соответственно), чтобы повалить цель.
Кроме того, у оружия будет ограниченный **заряд**, который, после 10-15 (может меньше) секунд поддержания кончится, так что оружие придётся снова заряжать. 
И чем же наш новый "обычный" тазер будет отличаться от гибридного тазера? Вышеуказанными условиями. Тазер из оружейки стреляет разово и наносит разовый же урон по стамине, а этот - будет достаточно быстро наносить урон стамине, точно так же кладя стан, и не потребует постоянно попадать по цели, вместо этого требуя постоянно держать цель в _условных_ пределах экрана и не давать ей заходить за препятствия (включая, к примеру, других людей). 
Также предполагается, что «усики» тазера можно будет выдирать из цели **до** того, как истечёт заряд, используя предмета в руке (**Z**).

![Без имени-2](https://user-images.githubusercontent.com/97734691/154520110-697c23e9-535f-4cd1-b770-fb09e483640a.png)

**В качестве нерфанутой альтернативы**:  **0,5с** стана и **20** стамина урона в сек. Заряд на **5-7** секунд. **4-5** тайлов дальности.

### Плюсы

+ Новое альтернативное оружие для СБ, которым будут пользоваться потому что оно полезно

### Минусы

- Новое альтернативное оружие для СБ, которым будут пользоваться потому что оно полезно
- Частично откатывает нерф нелетального боя. **Примечание:** _решается изменением количества заряда до альтернативной версии, указанной выше или ниже_

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
