### ISSUE TITLE
Feat: Больше типов предметов для кошелька.

### ISSUE THREAD

**Issue by Blundir** [ss220-space/Paradise#666]
### Проблема

Добавить возможность хранения в кошельке большего количества типов предметов.

### Решение

Примеры возможных типов предметов: ключи для подов, спичечные коробки, тёмные очки, одиночные пули, ключи шифрования радио, картриджи для ПДА.  

### Плюсы

-Больше универсальности кошельку.
-Больше логики и здравого смысла.
-Не нужно будет забивать рюкзак всякой мелочью, она будет всегда в кошельке.
-Больше банального удобства.

### Минусы

-Манчеры будут в восторге, можно будет таскать почти всё что угодно в кошельке.
-Наверняка будут те кто будет бегать манчить ключи радио, бегая с практически капитанским радио, правда в менее удобном формате.

**Comment by VasilevAY** [comment]
0/0
В случае, если предложение актуально, рекомендуется его заново отправить в #книга-отложений
