### ISSUE TITLE
Bug: Не работает симптом

### ISSUE THREAD

**Issue by DreamingRebel** [ss220-space/Paradise#668]
### Ckey

DreamingRebel

### Описание бага

Несколько каток я замечаю одну старую особенность: Toxin Filter по какой-то причине не выводит из организма токсины. Я обратил на это внимание, когда меня агенты синдиката больше минуты ковыряли и у меня накопилось ~125 урона токсинами от компенсатора. Потом на это обратили внимание на станции на последней прошедшей игре. В итоге я сижу и не понимаю, в чём, собственно, причина.

### Шаги воспроизведения

Делаем полезный вирус с Toxin Filter и отрицательной скоростью (т.е)

### Ожидаемое поведение

Накопление токсичного урона без вывода из организма.

### Дополнительная информация

Для большей заметности стоит поставить в вирус ещё и Toxin Compensation

### Операционная система

Windows

### Версия клиента

514.1575

### Название сервера

MAIN

### Примерное время и дата

27.02.2022 20:46

**Comment by NeonNik2245** [comment]
Toxic compensation при лечении урона вводит в кровь вещество под названием toxin, которое при метаболизации наносит урон токсинами, при этом и выработка вещества, и его метаболизация проходят быстрее, чем toxic filter выводит эти самые токсины, проблема не в выводе, а в ускоренном входе токсинов в организм

**Comment by LiquidPotroh** [comment]
> Toxic compensation при лечении урона вводит в кровь вещество под названием toxin, которое при метаболизации наносит урон токсинами, при этом и выработка вещества, и его метаболизация проходят быстрее, чем toxic filter выводит эти самые токсины, проблема не в выводе, а в ускоренном входе токсинов в организм

Что то ты напутал. Никаких веществ он не вводит. Компенсация переводит урон для каждой конечности, головы, тела. Чем больше зон тела повреждено, тем быстрее переводит. Причём, если у расы есть модификатор на увеличение/уменьшение урона от токсинов, то он вполне себе влияет на этот урон (например +70% у кидан). 

А проблема тут скорее в другом. Очень умные вирусологи не обращают внимания, что скорость вывода токсинов зависит от скорости вируса, и напихивают маннитолов, кровотворения  и прочей ереси, снижающей эту самую скорость. Также у симптома каждый тик есть банальный шанс срабатывания, и может так повезти, что он не сработает  30 тиков подряд (что очень маловероятно, но вполне возможно). 

Вот. Аж 3 возможных объяснения. Кидан, вирус говна, просто не повезло)

**Comment by Jordanstolethepreciousslam** [comment]
> Делаем полезный вирус с Toxin Filter и отрицательной скоростью 

> В итоге я сижу и не понимаю, в чём, собственно, причина.

**Comment by LiquidPotroh** [comment]
Вот формула количества вывода токсинов: 
sqrtor0(20+A.totalStageSpeed())*(1+rand()) Её не сломать никакими значениями скорости. Если -20 и меньше, то просто 0 будет. Отрицательная скорость практически у всех полезных вирусов с 6 симптомами, в этом проблемы нет.
