### ISSUE TITLE
Feat: MAKE ENFORCER GREAT AGAIN! 

### ISSUE THREAD

**Issue by Sup-3000** [ss220-space/Paradise#672]
### Проблема

Ну, грустно смотреть на резину. Никто её вообще не использует, там будет хоть более юзабельна? Да, есть доминатор более удобный и ТД. Но, жалко просто пистолет.

### Решение

Апнуть с 30 до 35 урон по стамине. 

### Плюсы

Будет более логичней? Человек без брони упадет за 3 попадания, т.к больно. Человек с броней за 4, т.к броня уменьшит ударную силу  и в итоге боль, ну короче 

### Минусы

Вродебы нет. Резину хоть чуточку чаще будут использовать.

**Comment by Sup-3000** [comment]
> ### Проблема
> Ну, грустно смотреть на резину. Никто её вообще не использует, там будет хоть более юзабельна? Да, есть доминатор более удобный и ТД. Но, жалко просто пистолет.
> 
> ### Решение
> Апнуть с 30 до 35 урон по стамине.
> 
> ### Плюсы
> Будет более логичней? Человек без брони упадет за 3 попадания, т.к больно. Человек с броней за 4, т.к броня уменьшит ударную силу и в итоге боль, ну короче
> 
> ### Минусы
> Вродебы нет. Резину хоть чуточку чаще будут использовать.

https://github.com/ss220-space/Paradise/pull/671

**Comment by Mell22** [comment]
Почему бы и нет? Толк будет от резины хотя бы.

**Comment by Iranimakq** [comment]
Только от Энфорсера - ВО
Красивое число урона по стамине - ВО
Резина пойдёт в массы - ВО
Антаги смогут хоть как-то использовать трофейный энфорсер - ВО
Теперь можно будет отыгрывать онли баллистик мэна - ВО
В общем - ВО

**Comment by SlayVoo** [comment]
Энфорсер не будет лежать в кобуре или на спине мертвым грузом. Его вообще хотя бы начнут применять в бою, а не просто вот смотрите у меня красивый пестик. Щит будет чаще воровать его)

**Comment by dimaya22** [comment]
Я за

**Comment by SlimeOne** [comment]
Переделали боёвку. Играй - не хочу. Ну посмотрим что выйдет из этого. За, выходит.

**Comment by Harim860** [comment]
Беру энфорсер в каждом раунде, чаще всего он заряжен резиной. Бафф вызовет конкуренцию и спрос, может даже откажутся от заказов или перевооружения, хм... ЗА! Зачем нам целый арсенал и выбор, будем воевать стандартным набором, ХРП моментс - ВО!

**Comment by sanosit** [comment]
Энфорсер хорош только с леталом в текущей мете. Резину давно пора апать, виват баллистика!

**Comment by LiquidPotroh** [comment]
Ну, получается, за

**Comment by konungkhmel** [comment]
Получается За потому что оно нам нужно

*складывает пальцы в знак SOS*

**Comment by TovarischKrab** [comment]
энфорсер сейчас хорош только когда нужен летал, а кокпитан спит и не поднимает синий код (например хедкрабов пострелять или павуков)
резинки сейчас почти бесполезны
патронов тех же 7 штук всего что не дает возможности промахнуться
(да и риск нанести внутряк или перелом задерживаемому не стоит того)
так что с апом было бы круто. хоть какая то конкуренция доминатору

**Comment by Intellsus** [comment]
Лазеры - плохо
Баллистика - Во!

**Comment by 05126619z** [comment]
Я не понимаю. Что вы с этой резиной ебётесь. Берёшь летал - и дело с концом

**Comment by Dasadasbbf** [comment]
Идея супер, mooniNormas
Полностью поддерживаю

**Comment by Kirozet** [comment]
Полный бред. У вас дизейблер наносит 25 урона по стамине, а резина 30. К тому же резина наносит дополнительные 5 брута. Она и так достаточно хороша как запасной вариант если доминатор утерян, делать её основным средством поражения клоунов за поскальзывание на шкурках только порушит удовольствие от игры всем, кто не играет на СБ.

**Comment by Den109G** [comment]
> Полный бред. У вас дизейблер наносит 25 урона по стамине, а резина 30. К тому же резина наносит дополнительные 5 брута.

Не того берёшь в сравнение. Бери лучше Доминатор, потому что с ним чаще бегают.
Тот наносит или (в ЗК) 33 стамины, или 25 стамины, или (в СК) 20 ожогов, или (после минуты бега до ассистенсткой) 50 ожогов и 33 стамины.
Как понимаешь, 30 стамины и 5 брута энфорсера просто курят в сторонке.

**Comment by Kirozet** [comment]
> 
> Не того берёшь в сравнение. Бери лучше Доминатор, потому что с ним чаще бегают. Тот наносит или (в ЗК) 33 стамины, или 25 стамины, или (в СК) 20 ожогов, или (после минуты бега до ассистенсткой) 50 ожогов и 33 стамины. Как понимаешь, 30 стамины и 5 брута энфорсера просто курят в сторонке.

Урон от тревоги на станции не зависит никак. Не понимаю что у тебя за "бег до ассистентской" указан.

**Comment by Honker9999999** [comment]
> Урон от тревоги на станции не зависит никак. Не понимаю что у тебя за "бег до ассистентской" указан.
Режимы стрельбы сибулки(а следовательно доминатора) зависят от кода, раз.
Бег до ассистенсткой это бег за инструментами дабы снять сибулку.
