### ISSUE TITLE
Feat: Изменение ID консоли

### ISSUE THREAD

**Issue by Honker9999999** [ss220-space/Paradise#674]
### Проблема

Сейчас, по сути своей, НЕВОЗМОЖНО адекватно выдавать доступы. Легче повеситься, чем сделать это за ГП. Капитану за счет серебрянных карт легче, но не сильно.
Это не совсем уж простой ПР, и я, учитывая то что я даже ПРы делать не могу вряд ли его сделаю без костылей, но могу хотя-бы попробовать если никто не захочет с этим ебаться. 

### Решение

Изменить консоли таким образом, что бы: ГП мог выдавать профы и доступы базового и отдельного уровня(Общие доступы+доступы по отделам, кроме брига). Таким образом он сможет выдавать базовые профы: инженеры, медики, учёные и т.д.
Капитан(или карта с доступом капитана) смог выдавать доступ глав и СБ, за исключением капитанского доступа. 
Так-же добавить возможность заказать в карго за тысячу кредитов запасную карту капитана, ЕСЛИ она была уничтожена(дабы не было возможности потерять такую карту вообще навсегда, ибо тогда получить доступ капитанского уровня не будет возможно, кроме самого капитана)

### Плюсы

1. Нормальная, адекватная работа ИД консоли.
2. ГП не бесполезный
3. Карту кэпа нельзя будет проебать настолько просто.

### Минусы

1. Можно будет выдавать доступы.
2. В случае чего карго сможет получить кэпскую карту.
3. Этот ПР надо реализовать.

**Comment by Honker9999999** [comment]
(это, если кто не понял, для ТГ, ибо на гите ТГ это нельзя сделать, аы)

**Comment by BeebBeebBoob** [comment]
🐀 
https://github.com/ss220-space/tgstation

**Comment by Honker9999999** [comment]
> 🐀 https://github.com/ss220-space/tgstation

Видишь там возможность сделать иссуй?

**Comment by 05126619z** [comment]
В этом и смысл ТГ

**Comment by 05126619z** [comment]
Тут надо уметь

**Comment by VasilevAY** [comment]
issue в ветке пары
