### ISSUE TITLE
У меня есть спрайт, да не один, нужно его добавить.

### ISSUE THREAD

**Issue by El-Good** [ss220-space/Paradise#75]
1.Cap belt
2.Cap belt-sheath
3.Cap belt-sheath-rapier.
https://discord.com/channels/617003227182792704/859003461378113546/859004353813676072

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/185343756-4200b146-9da6-4f77-9b27-d5a12406369c.png)
