### ISSUE TITLE
Нормальное ПДА для боргов

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#78]
Умоляю, сделайте у боргов нормальный ПДА.

Текущий ПДА это катастрофа
-Отправка пм сообщений идёт без логов, без окна чата
-Нет вывода пм сообщений в игровой чат (ты даже не знаешь отправил ли ты за борга сообщение или нет)
-Crew Manifest в старой ущербной форме в виде таблицы Word

**Comment by KuzyXD** [comment]
Логирование доступно в другой функции в этом же разделе. Ты прав, это ужасно смотрится.

**Comment by VasilevAY** [comment]
Закрыто по причине не оформленной нормально предложки
