### ISSUE TITLE
Bug: STOP AMBER ERT MASTER RACE

### ISSUE THREAD

**Issue by Dydna** [ss220-space/Paradise#790]
### Ckey

DjSmail1

### Описание бага

При вызове ОБР через кейкард аунтификейшен девайс вне зависимости от того, какой код установлен на станции суммонится ОБР амбер кода, которые не являются боеспособной единицей, если им не открыть армори. Иногда оно просто не справнится. 

Обычно вызов ОБР через аунтефикатор используют, когда на сервере нет педалей или им всё-равно. Так пусть хоть нормальное ОБР спавнится, а не биба и боба. 

### Шаги воспроизведения

Подойти к аунтефикатору, ввести причину ЕРТ, провести двумя картами с разных девайсов. 

### Ожидаемое поведение

При красном коде должно было заспавнится ерт ред кода. При гамме соответствующее. 

### Операционная система

Шиндовс

### Версия клиента

514.1568

### Название сервера

MAIN

### Примерное время и дата

!?

**Comment by MorgoWizard** [comment]
@Bizzonium, тут баг — не баг. Так и задумано. Скорее всего, чтобы избежать абуза. Код то любой без причины можно ставить de facto. Закрой тогда Issue.
