### ISSUE TITLE
Не работает Show Alerts во вкладке Robot Commands

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#80]
Не обновляется список тревог в Show Alerts

Список тревог всё время показывает что тревог нет, когда в консолях они есть, и список ни за что не обновится, пока не откроешь какую-либо консоль и лишь потом обновишь свой список тревог в Show Alerts. Мало того, список тревог обновит записи о тревогах лишь той категории, консоль которой открыта. Т.е. открыл консоль атмоса - обновляется атмос, открыл питание - обновило питание, и т.д.

**Comment by Elisei24** [comment]
Плюсую. Камеры никогда не показывает, вообще.
Хоть два десятка переломано, всё-равно "All systems nominal"
