### ISSUE TITLE
Bug: Отображение модели персонажа с хардсьютом ГСБ

### ISSUE THREAD

**Issue by CarrotPuree** [ss220-space/Paradise#827]
### Ckey

MrCarrot

### Описание бага

Если одеть Вокса/Скрелла/Драска в РИГ ГСБ, то текстуры костюма не будет отображаться. Вследствие чего остальные игроки не будут знать о наличии на теле ГСБ его РИГа, если не осмотрят подробнее (examine).

### Шаги воспроизведения

1. В редакторе персонажа выбрать одну из рас: Вокс, Драск, Скрелл;
2. Надеть хардсьют ГСБ; 
3. Переключить режим шлема.

### Ожидаемое поведение

Корректное отображение костюма на кукле.

### Операционная система

Windows 10

### Версия клиента

514.1578

### Название сервера

MAIN

### Примерное время и дата

27/04/2022

**Comment by MorgoWizard** [comment]
@Bizzonium, тут всё просто — отсутствуют сами спрайты. Вывод: либо нарисовать их, либо криво копипастнуть с человеческих, что будет плохо смотреться; либо запретить пользоваться одеждой, которая не имеет спрайта х

**Comment by Suchinessa** [comment]
наконец то мы дождались "your species can't wear it" на паре
