### ISSUE TITLE
Bug: Взрывы снаружи отрывают конечности ВНУТРИ мехов

### ISSUE THREAD

**Issue by snipersir** [ss220-space/Paradise#876]
### Ckey

Connar369

### Описание бага

Взрыв снаружи меха оторвал руку когда я был внутри меха. Конкретный мех - Рипли. Место относительно взрыва - почти центр.

### Шаги воспроизведения

Сесть в Рипли
Быть подорваным в мехе будучи около бомбы
Потерять руку оставаясь внутри меха

### Ожидаемое поведение

Конечности не оторвёт при взрыве, мех всё таки защищает полностью от прямых попаданий оружия. Пенетрирующие снайперские пули не пробивают даже Рипли, даже с нескольких выстрелов - пилот остаётся полностью здоров. Как и выстрелы взрывными пулями - не причиняют урон пилоту внутри. По-скольку нет прямого попадания в тело разрывного вещества или осколков, чтобы оторвать конечность - всё что влияет от взрыва это резкое сдавливание тела давлением со всех сторон одновременно внутри. Максимум что из-за такого случится - переломы, как в случае с выходом в космос голым без рига и гена.

### Дополнительная информация

Противоположный пример - зарядник киборгов иногда защищает от взрывов тех кто на зарядке внутри на момент взрыва. Даже если сослаться на давление, то зарядник по своей структуре это даже не многослойный или бронированный мех... И тут нет никаких отмазок аля "очень нестабильные бс аномилии влияют на это" - отмазками такого рода можно перекрыть ВСЕ баги сборки, в таком случае... уже пытались втюхать такую хрень, как оправдание этого бага с мехом ...

### Операционная система

Win 7 x64 Pro SP1

### Версия клиента

514.1583

### Название сервера

MAIN

### Примерное время и дата

ИД смены: 9036, ~время: 14:20 МСК, Секонд

**Comment by MorgoWizard** [comment]
Чем взрывали? Я и бак взорвал, и синдибомбу, и чем только не взрывал. Максимум — получение урона, но никак не отрыв конечности
