### ISSUE TITLE
Ножи для шахтёров

### ISSUE THREAD

**Issue by zombie288** [ss220-space/Paradise#94]
### Проблема

Невозможность запихивать нож в ботинок для шахтера. Такая функция есть на ТГ/Bay/скорее всего где - то ещё.

### Решение

Дать возможность совать survival knife в work boots + jump boots, аки в кобуру.
Btw, предложка уже проходила, просто кодеров так и не нашлось :(
![IMG_20210708_193011](https://user-images.githubusercontent.com/27626053/124958581-fc387380-e022-11eb-9a54-fd53d84b48d8.jpg)

### Плюсы

Повысится выживаемость шахтеров, у которых выбили КА из рук.
На один почти бесполезный предмет меньше.
Это просто... Удобно .-.

### Минусы

Отсутствуют.

**Comment by MorgoWizard** [comment]
@Bizzonium, merge есть, а issue открыт. Работа более не ведётся, почему бы и не закрыть тогда?)

**Comment by VasilevAY** [comment]
https://github.com/ss220-space/Paradise/pull/308
