### ISSUE TITLE
Feat: Добавить инструменты абдукторов на abductor crash site на лаваленде

### ISSUE THREAD

**Issue by semoro** [ss220-space/Paradise#95]
### Проблема

В данный момент невозможно получить 4-ый уровень Alien исследований в РнД

### Решение

Добавить инструменты абдукторов в разбившийся корабль абдукторов на лаваленде
![image](https://user-images.githubusercontent.com/1918780/124974696-c650ba80-e035-11eb-83f3-9bd4926098c4.png)

### Плюсы

Возможность улучшения исследований Alien до 4-ого уровня, инструменты абдукторов на станции

### Минусы

Инструменты абдукторов на станции?

**Comment by Honker9999999** [comment]
А не слишком ли имбово выйдет? Тарелка появляется каждый второй раунд, и каждый второй раунд у инженеров и скорее всего у СБ будут самые имбовые инструменты? Ну, и 4 уровень получается исследованием батона/настоящих инструментов, абдукторы ведь тоже попадаются. 
Можно сказать что 4 левел это как 8 биотехнологии. Открывают крайне крутые штуки, но их не получить просто так.

**Comment by VasilevAY** [comment]
Нужна предложка
