### ISSUE TITLE
Feat: SOS-Sign

### ISSUE THREAD

**Issue by Jalesen** [ss220-space/Paradise#96]
### Проблема

Проблема в том, что СБ/И прочий персонал не  могут позвать на помощь ибо открытие чата и сам чаттинг процесс который делает игрока максимально уязвимым. И это к тому же выглядит нереалистично.

### Решение

Сделать хоткей для сигнала SOS, который при третьем режиме  костюма так же ретранслирует один раз при нажатии (возможно состояние здоровья) точно местоположение (UPD возможно нужно сделать КД в 30+ секунд и кд будет скейлиться от того насколько быстро игрок прожимает хоткей SOSа после кд).
Пример сообщения: "Я сотрудник <Имя> нахожусь в бедственном положении, требуется помощь в <местоположение при 3-ем режиме костюма (в другом случае отсутствует информация о местоположении)>" Если человек не сотрудник СБ, то это сообщение будет транслироваться в мед канал. Если человек сотрудник СБ/блюшилд, то сообщение будет транслироваться в каналы СБ и Мед.

### Плюсы

Плюсы: теперь сотрудники мед  отдела и сб не будут в незнании о том, что происходит с гражданскими/сб если они вообще не заходят в терминал мониторинга статуса команды, граждане станции будут менее уязвимыми ибо теперь не нужно будет нажимать T и писать, что вам нужна помощь (ибо на сообщение могут не откликнуться) (и вас могут убить пока вы будете писать).

### Минусы

Минусы: возможно антагонистам будет сложнее нападать на изолированную цель (легче будет если у цели будет режим у костюма ниже третьего).

**Comment by semoro** [comment]
Заполните название

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184348241-3828eeea-1fa5-4c1e-86b4-6dc9c0cf513e.png)
