### ISSUE TITLE
Feat: нью антаг, наверное 

### ISSUE THREAD

**Issue by DayBreakerBrony** [ss220-space/Paradise#98]
### Проблема

Добавление нового антага

### Решение

Предложение: накодить людям новых антагов! Да, очередная сложная идея, но всё же если пройдёт на ВЛе/Инфе то будет фишечка у билда. А фишки это огромный плюс, особенно учитывая стримерскую природу сервера (хотя я сильно сомневаюсь, что хоть где-то введут, но вдохновение есть вдохновение. Ненавижу парадизовский консерватизм. Так вот. 
Я бы хотел предложить некоторую альтернативу блобу, которая очень близка и одновременно далека от него. В основе моей идеи лежит Коллективный Разум. Рассказываю:

Коллективный разум - раундстарт/щитспавн антаг, который по лору является сбежавшим генномодифицированным экспериментом. Может быть лишь органическим. Сам разум - "сердце" находится в одном из техов и является 3х3 блоком, представляющим большой нарост. О его появлении в раунде известно только командованию, но рекомендуем от лица коллектоёбов делать предупреждение типа "Неопознанные формы жизни,", т. к. им нужно время на развитие во всех смыслах. Он, как правило, является НПС, а не игроком, и сам ничего не делает. На старте он получает себе 2-6 юнитов из любых возможных рас и профессий (кроме расы КПБ и майндшилд ролей)Все знания передаются по разуму, поэтому наличие глав в стартовой группе также запрещено, так как их мозги дают полные знания) . Боргов можно. Их задача: расширять и охранять с помощью навыков территорию сердца, маскировать его местонахождение до обретения силы, выращивать Дион и строить големов, а также боргов во славу Улья (чтобы получить набор законов Hivesimov, просто дайте кусок плоти "сердца" боргу. Такая фича, если хотите); Получать знания отделов для достижения цели (Это означает что со старта эти парни не знают и не умеют ничего, кроме своих стартовых ролей, если не цивилы, и получают инфу только из голов людей или построенных боргов. Из особенных возможностей: поглощение мозга личности (просто отхапать голову и скормить её сердцу, или боргифицировать существо и запросить знания) позволяет заполучить все её особые знания всему улью. Таким образом, сожрав главу вы получаете знания всего отдела.  Задача строится из 3 пунктов, в которых возможно:
1)Поглощение знаний определённого человека (То есть убийство с доставкой головы в улей, чаще всего НТР, РД и СМО, т. к. все они ведают самой большей информацией о сбежавшей угрозе коллективки) 
2)Боргификация (наличие робототехника надо, ага) 
3)Убийство группы
4)Побег на шаттле или поде хотя бы одного носителя разума.
5)Отсутвие задач, но необходимость любым способом дать сбежать разуму (телепортировать на шаттл, космировать в специальной обшивке)

### Плюсы

Новый интересный антаг, который должен действовать сразу, быстро и коллективно, словно нюкеры. Но зато не требующая особого доступа к капитану с его диском, более деликатная миссия с поглощением знаний, подпольной постройкой боргов, и т. д. 

### Минусы

много кода. много скриптов. многа букав. щитколлект каждые 2 спавна. затуп игроков после введения, сложность подпольного крафта боргов.

**Comment by PhantornRU** [comment]
Тогда можно сделать более расширенного антага. 
Например дионы как культисты могут строить подобие деревянных кузней, с которыми могут улучшать само ядро коллективного разума, получать семена лозы или апгрейды для себя и особенное снаряжение наподобие культистских.
Дионы также смогут получать нимф в самом ядре у которых будут сразу цели антагов повинующихся коллективному разуму, те же нимцы и дионы могут передать нимфам и дионам ботаникам и лаваленда свои цели с помощью предложения вступить в "союз" как революционеры.
Это будет ЛОРно, так как многие дионы только и мечтают стать сверх растениевой планетой и огромной сверх дионой.

А в конце достигания "свехразума" оно выпускает более опасную и прочную лозу чтобы пожрать станцию.
Для справки: Дионы могут свободны передвигаться по лозе.

В принципе если кто-то будет такое кодить, я готов даже порисовать спрайты
Дискорд: PhantomRU#1289

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184347797-5dca123e-66c7-4d5c-a6ae-a2654333befc.png)
