### ISSUE TITLE
Feat: Бореров в генокрадов

### ISSUE THREAD

**Issue by PhantornRU** [ss220-space/Paradise#99]
### Проблема

Бореры слишком не опасны и часто попадают. Почему бы им не добавить возможность стать опаснее, если они выпадут в раунде с генокрадами? Пускай бореры ищут генокрадов чтобы тоже стать генокрадами и соответственно поставить станцию под серьезную опасность, как пауки ужаса, ну или хотя бы свармеры.

### Решение

Для становления генокрадом, бореру предстоит в форме личинки с химикатами 150+ (или 250) встретиться с генокрадом в форме личинки(или нет) для того, чтобы генокрад мог передать бореру эволюционный геном и соответственно эволюционировать борера в генокрада.
Тоесть, сложность для борера в том, что ему предстоит найти человека, просидеть в нём определенное количество времени для накопления токсинов и при этом не умереть, после чего найти генокрада (а как известно генокрады крайне скрытые и хер ты их найдешь) и после этого умудриться вылезти из своего носителя и выжить в поисках самого генокрада, да еще и найти свободную открытую вентиляцию через которую в целом можно попасть к генокраду.

Т.е. вкратце что нужно сделать кодингом:
Генокрад с помощью способности "передача генома" может передать геном личинке борера и борер сменяется на генокрадского червя/трансформируется в генокрадскую бабизяну.

Пример генокрадского червя с ТГ (не знаю есть ли на парадизах):
![image](https://user-images.githubusercontent.com/41479614/125011528-fcc91c80-e0ab-11eb-805b-4b7c5b7283ee.png)

### Плюсы

Разнообразия геймплея.
Соответствие лору.
Оправдание почему бореры являются врагами НТ, хотя на деле ничего опасного не делают. Теперь будут.
Дополнительный отыгрыш бореров для становления генокрадом, появление цели у бореров, а не только выживание.

### Минусы

Усложнение геймплея в раунде в которых повезло заспавнить генокрадов и бореров и они даже все не повымирали.
Оправдание почему бореры являются врагами НТ, теперь их лучше тем более убивать.

**Comment by VasilevAY** [comment]
![image](https://user-images.githubusercontent.com/98010665/184348084-163715a9-dcc7-43e3-9855-7dbc20d58151.png)
